### ISSUE TITLE
SLB is enabled but not working

### ISSUE THREAD

**Issue by thatguy-za** [archetyped/simple-lightbox#1009]
## Description of Problem

I've recently installed and enabled the SLB plugin but it doesn't seem to be enabled on any of my images. I have tried the following:
- Disabling the following plugins: Akismet Anti-Spam, Hotjar, Koko Analytics & Site Kit by Google 
- Using Firefox and Chrome (in Windows 11)
- Incognito mode 
- Clearing cookies

My site uses the Blocksy theme version: 1.8.84 

## Details

* URL of Page exhibiting problem: https://tristam.ie - all pages
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox 112.0.2, Chrome 112.0.5615.138
* Version of SLB Installed: 2.9.3 (have reset it to standard settings)
* Other plugins installed: Akismet Anti-Spam, Blocksy Companion, Code Syntax Block, Hotjar, Koko Analytics, Site Kit by Google, Updraft Plus, WPS limit login. My site is running through a Cloudflare tunnel with Cloudflare analytics.

**Comment by thatguy-za** [comment]
Thanks to the team at Blocksy, I've managed to resolve this issue.

I hadn't linked the image to the media file - oops.

**Comment by archetyped** [comment]
Hi, glad to hear your issue was resolved.

Yes, without links, there is nothing for visitors to click on and display the lightbox.
