### ISSUE TITLE
[Request]: Fixed LightBox width

### ISSUE THREAD

**Issue by pedjas** [archetyped/simple-lightbox#1012]
## Description of feature

It is quite odd if there are several photos displaying and some are horizontal and other vertical, links to go to next/previous image moves depending on image width. User has to hunt the button on the screen.

I would like to have option to have LightBox with as constant width so next and previous buttons are always at the same place. User does not have to hunt them, just click mouse to switch to next image.

## This feature would be used to

This will improve user experience. It is quite annoying if you have to hunt for previous and Next buttons to see images.

## If you added this feature, I would:

Spread good word about this already good plugin.

**Comment by archetyped** [comment]
Navigation and other lightbox elements are fully customizable by the lightbox theme.  You didn't specify what theme you are using, but If you are using one of the built-in themes, then the navigation elements are always at the right and left edges of the lightbox-- no hunting required.

For full control over the navigation buttons and any other lightbox element, creating a custom theme is recommended.  Please refer to [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for all the details.

**Comment by pedjas** [comment]
I use OmniPress Magazine theme. Right and left edges of the lightbox are shifting to match image width. Navigation elements shift with them.
