### ISSUE TITLE
Regular Lightbox comes up first, then SLB behind it

### ISSUE THREAD

**Issue by babs4104** [archetyped/simple-lightbox#1016]
## Description of Problem

When we click "Open in Lightbox" in a Divi Image module image, we get both the original Lightbox and the SLB lightbox.

## Details

* URL of Page exhibiting problem: https://wtfcf.wisdomwebconsulting.com/episode-element/larrys-tree-redux-2  scroll down to last two images on the page at the very bottom.

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: 2.9.3
* Other plugins installed: 

Divi Theme...
Plugins:

Admin Columns Pro
ADS PRO – Multi-Purpose WordPress Ad Manager
Divi Booster
Divi Carousel
Divi Image Helper
Import and export users and customers
Monarch Plugin
Shortcodes for Divi
Simple Lightbox
SiteGround Optimizer
SiteGround Security
SVG SupportS
Toolset Access
Toolset Blocks 
Toolset Types
UpdraftPlus - Backup/Restore
WordPress Importer
WP Bulk Delete
WP Recipe Maker
WP Recipe Maker Premium
Yoast SEO

**Comment by babs4104** [comment]
Okay - I may have found the answer here:
https://divi.help/threads/disable-divi-lightbox-when-using-alternative-lightbox.4012/

I was able to turn off the CSS for the Divi lightbox.


.mfp-bg.mfp-fade.mfp-ready,
.mfp-wrap.mfp-close-btn-in.mfp-auto-cursor.mfp-fade.mfp-ready {
  display:none;
}

.mfp-zoom-out-cur {
  cursor:inherit;
}

**Comment by archetyped** [comment]
Glad to hear you were able to disable the other lightbox.
