### ISSUE TITLE
Link to an image that should be opened not in SLB

### ISSUE THREAD

**Issue by SuperBoss9** [archetyped/simple-lightbox#1017]
I use SBL at my WP-site for a very long time. It works perfectly. But I faced a problem: I don't know how to disable SLB for one single link to an image that is located at my server.
For example, I need to open a picture just in browser. But I can't do it because it opens in SBL.
What to do with that?

**Comment by archetyped** [comment]
Hi, you can use SLB's `[slb_exclude]` shortcode to selectively exclude links from being displayed in the lightbox.  Any links between the opening and closing shortcode will be excluded from SLB.

See [SLB's Shortcodes documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_exclude) for more details.
