### ISSUE TITLE
Dislaying custom taxonomy?

### ISSUE THREAD

**Issue by pedjas** [archetyped/simple-lightbox#1019]
## Description of Problem

I added custom taxonomy to indicate license for each image. I would like to display that within light-box. Cannot find any info on that. Is that possible?

## Details

* Version of SLB Installed: 
 2.9.3

**Comment by archetyped** [comment]
Hi, please refer to [SLB's Theme's documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for information regarding customizing lightbox themes, including [a tutorial providing all available lightbox template tags](https://archetyped.com/know/slb-theme-layout/).

Taxonomy data is not currently supported by template tags, but support for more template tags are planned for future updates.

Thanks.
