### ISSUE TITLE
Plugin installed, no lightbox on gallery

### ISSUE THREAD

**Issue by madriverweb** [archetyped/simple-lightbox#1020]
## Description

I have one native WordPress Gallery block in a page. All the images are linked to their media file. The larger images open when clicked but there is no lightbox, no controls.

## Details

* URL of Page exhibiting problem: https://darlenem9.sg-host.com/photo/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox
* Version of SLB Installed: 2.9.3
* Other plugins installed: Classic Editor | Version 1.6.3 by WordPress Contributors \| Auto-updates enabled
Contact Form 7 | Version 5.7.7 by Takayuki Miyoshi \| Auto-updates enabled
Disable Comments | Version 2.4.4 by WPDeveloper \| Auto-updates enabled
Easy Media Download | Version 1.1.9 by naa986 \| Auto-updates enabled
Protected Posts Logout Button | Version 1.4.6 by Nate Reist \| Auto-updates enabled
Really Simple CAPTCHA | Version 2.2 by Takayuki Miyoshi \| Auto-updates enabled
Simple History | Version 4.2.0 by Pär Thernström \| Auto-updates disabled
Simple Lightbox | Version 2.9.3 by Archetyped \| Auto-updates disabled
SiteGround Optimizer | Version 7.3.3 by SiteGround \| Auto-updates disabled
SiteGround Security | Version 1.4.5 by SiteGround \| Auto-updates disabled
WPFront Scroll Top | Version 2.0.7.08086 by Syam Mohan \| Auto-updates disabled
* Inactive plugins:
Easy PayPal Events | Version 1.1.8 by Scott Paterson \| Auto-updates enabled
Sidekick | Version 2.6.8 by Sidekick.pro \| Auto-updates enabled
Video Conferencing with Zoom | Version 4.2.1 by Deepen Bajracharya \| Auto-updates enabled

**Comment by archetyped** [comment]
Hi, the link you provided does not appear to be working.  Please provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to take another look.

Thanks.

**Comment by madriverweb** [comment]
I changed to another plugin the same day. I needed it to work. Two weeks is quite a long time to wait for a reply.
