### ISSUE TITLE
SLB not installing properly

### ISSUE THREAD

**Issue by thaibluesky** [archetyped/simple-lightbox#1021]
## Description of Problem

No js files are loaded - all plugins were disabled - still not working. 
In the head slb_core-css is called - 
visualorange.com/wp-content/plugins/simple-lightbox/client/css/app.css?ver=2.9.3. 
It's not the last css file which is being loaded. 
There is one lonely entry the footer of SLB - nothing else.
<script type="text/javascript" id="slb_context">/* <![CDATA[ */if ( !!window.jQuery ) {(function($){$(document).ready(function(){if ( !!window.SLB ) { {$.extend(SLB, {"context":["public","user_registered"]});} }})})(jQuery);}/* ]]> */</script>

I am developing the website based on TwentyTwentyTwo WP-Theme, Gutenberg Blocks.
Tried Firefox my standard browser, Chrome, Firefox, Opera - no success. 
Plugin "Under Construction" is installed and therefore the website is only accessible for admins (me). 
Logged out with Under Construction plugin disabled no Lightbox appears either - onclick the foto opens in the same Tab. 
Nav gone and I have to use the back button of the browser to return to the home page. 

SBL latest Version, downloaded - no errors on install (I temporary enabled Debugging in wp-config.php).
In fact the only plugin which worked was Responsive Lightbox & Gallery  it stores the gallery separately - which I dislike. I use Simple Lightbox since years and it would be really a pitty, if I could not use it anymore - I love simple plugins. 

Screenshots
![plugins](https://github.com/archetyped/simple-lightbox/assets/1756528/86b21174-db8c-4638-9839-0d54ddcdc08f)
![lightbox-settings](https://github.com/archetyped/simple-lightbox/assets/1756528/ce2f60b4-84c2-4e5a-b19f-eda05042489d)
![backend-home](https://github.com/archetyped/simple-lightbox/assets/1756528/0fe9ee51-e5cc-4c22-b900-3b0dd997574d)

![frontend-home](https://github.com/archetyped/simple-lightbox/assets/1756528/1f38878a-b847-40c1-ae0f-35438a5061b1)
![clicking-the-image-in-the-gallery](https://github.com/archetyped/simple-lightbox/assets/1756528/10dd1586-1fb8-47fe-98aa-0c2f6df6a464)

I tried to register on your website for the newsletter - did not get a confirmation so... and it hung at processing. 
Let me know if you need more material and if so what... 
Kind regards and keep the good work up.
Cheers,
Doris
I am based in Germany
E-Mail doris@visualorange.com 
and yes I am learning how to handle the wp-blocks - kind of restrictive in my opinion...

**Comment by archetyped** [comment]
Hi, the settings visible in the screenshot you provided appear to be fine.  Beyond that, without being able to evaluate the issue directly, I can only recommend following the steps listed in [SLB's documentation on evaluating your site for common issues](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support#self-serve-support).

When available, please update this ticket with a link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take a closer look.

Thanks.

**Comment by thaibluesky** [comment]
Hi, I appreciate your answer -and let you know the result.
Cheers,
Doris

On 2023-07-26 01:01, Archetyped wrote:

> Hi, the settings visible in the screenshot you provided appear to be 
> fine. Beyond that, without being able to evaluate the issue directly, I 
> can only recommend following the steps listed in SLB's documentation on 
> evaluating your site for common issues [1].
> 
> When available, please update this ticket with a link to a page that 
> exhibits the issue you are experiencing and I would be glad to reopen 
> this ticket and take a closer look.
> 
> Thanks.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/archetyped/simple-lightbox/wiki/Feedback-&amp;-Support#self-serve-support
[2] 
https://github.com/archetyped/simple-lightbox/issues/1021#issuecomment-1650679812
[3]

**Comment by thaibluesky** [comment]
Hi there,

You were right. WP-Blocks needs all content filled into the specific 
content-block. I built the layout using only groups and colums for the 
homepage. So sorry for my beginner mistake.
Could be a quick thing to put in FAQ, saves time to handle dummies... 
lol
I apologize for any trouble.
Cheers and thanks,

Doris

On 2023-07-26 01:01, Archetyped wrote:

> Hi, the settings visible in the screenshot you provided appear to be 
> fine. Beyond that, without being able to evaluate the issue directly, I 
> can only recommend following the steps listed in SLB's documentation on 
> evaluating your site for common issues [1].
> 
> When available, please update this ticket with a link to a page that 
> exhibits the issue you are experiencing and I would be glad to reopen 
> this ticket and take a closer look.
> 
> Thanks.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/archetyped/simple-lightbox/wiki/Feedback-&amp;-Support#self-serve-support
[2] 
https://github.com/archetyped/simple-lightbox/issues/1021#issuecomment-1650679812
[3]

**Comment by archetyped** [comment]
Hi, glad to hear your issue was resolved.  Supported content areas are listed in [SLB's documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation).

Support for WordPress' FSE template blocks are planned for a future update ([details](#1010)).  Click the 👍 on that ticket to upvote the functionality and add any comments/feedback you have there.

Thanks.
