### ISSUE TITLE
lightbox is active on some images and not on others, on the same page, without any logic

### ISSUE THREAD

**Issue by GizMo979** [archetyped/simple-lightbox#1022]
## Description of Problem

scrolling this page and trying to click on all the clickable images you will notice that on some in particular the lightbox is not activated, but the image opens directly in the window as a direct url, the affected images are always the same but not in the html code of the page I can't see any difference compared to the others that open without problems.

## Details

* URL of Page exhibiting problem: 
* a page of my site affected by this bug is this:
https://www.sb-lab.eu/come-nasce-un-trasformatore-audio-sb-lab/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
chrome
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB does not appear to be installed/activated at the link provided.

Please provide a link to a page with SLB activated that exhibits the issue you are experiencing, and I would be glad to take another look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
