### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by norbertk16** [archetyped/simple-lightbox#1024]
## Description of Problem

About every second time the lightbox is executed on our site an "Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name." appears.

## Details

In cases when the plugin doesn't work, the image link is executed once, after that also image links cannot be opened any more. 
* URL of Page exhibiting problem: https://www.spvgg-brandten.de/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): anyone, also on mobile devices
* Version of SLB Installed: 2.9.3
* Theme: Hueman

**Comment by archetyped** [comment]
Hi, I have been unable to reproduce the error on any of the 6 image links at the page provided, despite repeated attempts.

Please provide additional details:

* Where are you seeing the error message?
* Screenshot of error message.
* Any additional details of conditions that cause error message to be displayed.

Thank you.

**Comment by norbertk16** [comment]
Hi, and thanks for your response! I see the error message in the Chrome Dev Tools, see attached screenshot. Maybe network throttling helps when you try to reproduce the error. I generally think that the problem might have to do with the order of loading scripts/content.

![2023-08-11 19_39_37-Window](https://github.com/archetyped/simple-lightbox/assets/140969969/5d58368a-af0a-48df-9bc3-11a432926ddd)

**Comment by archetyped** [comment]
Thank you for the additional details.

You site appears to be loading 2 versions of jQuery, resulting in an outdated version of jQuery being loaded (v1.11.3).  It looks like it may related to a widget block called "fupa_livebox".

SLB supports the version of jQuery officially included with WordPress.  Multiple copies and outdated copies of jQuery can definitely result in unexpected behavior, so removing the outdated version of jQuery from the site is highly recommended.

See SLB's documentation on [jQuery support](https://github.com/archetyped/simple-lightbox/wiki/jQuery-Support) for more details.

If you are still experiencing an issue after removing the extra copy of jQuery, please provide the following information:

* Clarify "About every second time the lightbox is executed on our site".
    * Does this mean that the error is displayed when one image is correctly shown in the lightbox, but another image is not **on the same page load**, or something else?

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by norbertk16** [comment]
Hi! Your comment helped us to identify the problem, and we switched to a newer version of the JS-Widget from fupa.net that caused the issue. Now SLB seems to work without problems also on the start-page. Thanks a lot for your help!

Best regards,

**Comment by archetyped** [comment]
Glad to hear your issue was resolved 👍
