### ISSUE TITLE
so how do I make the picture bigger when I click on one of those images?

### ISSUE THREAD

**Issue by chrisgoh1** [archetyped/simple-lightbox#1028]
## Description of feature
so how do I make the picture bigger when I click on one of
those images?
(Describe your feature or idea here)

## This feature would be used to

(Describe usage here)

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Duplicate of #1029
