### ISSUE TITLE
how to make the picture bigger?

### ISSUE THREAD

**Issue by chrisgoh1** [archetyped/simple-lightbox#1029]
Hello,
On my site: https://guamguy.com/niagara-falls/ I am using the 
plugin, so how do I make the picture bigger when I click on one of
those images?

thanks
Chris
chrisgoh2017@gmail.com

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

If you are still experiencing an issue after adding valid links to the page, please provide an updated link and I would be glad to reopen this ticket and take another look.
