### ISSUE TITLE
Lightbox Not Working After Install (Cache Issue?)

### ISSUE THREAD

**Issue by azariosays** [archetyped/simple-lightbox#1030]
## Description of Problem

I installed your plug-in, but the images are not opening up. I had an issue where my images would open on a new page, even if I have Media File selected. However, after installing the plug-in, the images in a post gallery aren't opening when logged in as a user. If I navigate the site incognito, the images still open on a new page. I've tried to clear the cache of my browser and the website.

Any direction would be great. Thanks.

## Details

* URL of Page exhibiting problem: https://noisypixel.net/granblue-fantasy-relink-collectors-edition-gameplay-story/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  I tried, Chrome and Edge
* Version of SLB Installed: Newest
* Other plugins installed: Advanced Custom Fields, Autoshare for Twitter, Better Search, Child Theme Configurator, classic Editor, CodeBard's Patron Button and Widgets for Patreon, Disqus for WordPress, Ezoic, Guest Author, Health Check & Troubleshooting, Guest Author,  Health Check & Troubleshooting, Instant Indexing, Perfect Pullquotes, Posts Table with Search & Sort, 	
Rank Math SEO, Rank Math SEO PRO, Sassy Social Share, Simple Lightbox, Team Members, Temporary Login Without Password, ThirstyAffiliates, White Label CMS, BlogVault, WP Dark Mode

**Comment by archetyped** [comment]
Hi, "Newest" is not a valid version number.  Please update your post to include SLB's version number so that your issue can be fully evaluated.

If you are seeing this as the version for SLB on you site's plugins admin page, deleting and reinstalling SLB from WordPress official plugin directory is recommended.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
