### ISSUE TITLE
[Request]: Icon on thumbnails

### ISSUE THREAD

**Issue by LordKord** [archetyped/simple-lightbox#1033]
I would like to have a semi-transparent magnification icon displayed in the top right corner of a photo. If there is a gallery in the light box then with numbering. 

Like here: 
https://hypebeast.com/2023/9/nike-basketball-holiday-2023-showcase-info

It would be good if you could choose the position and an icon (arrows or magnifying glass) for zooming in in the backend, or you could integrate such an icon into the light box yourself via upload.

**Comment by archetyped** [comment]
Hi, Simple Lightbox does not affect the appearance of elements on the page (such as thumbnail images), it only controls what is displayed in the lightbox itself.

Gallery plugins or other plugins that control the display of thumbnails on the page may have settings for this, but that will depend on the plugin you use.
