### ISSUE TITLE
[Request]: Regrouper les éléments par galerie

### ISSUE THREAD

**Issue by Apemutam** [archetyped/simple-lightbox#1040]
## Description of feature

Hello, it could be interresting to group gallery by gallery

## This feature would be used to

When you have several galleries on a page, the lightbox successively displays all the images on the page.
I would like to be able to loop gallery by gallery.
For example, you can see this page in my Joomla site : http://www.sonnailles.net/index.php/traditions/region-france/cevenne/trans-cev
when you have finished to see the first gallery, it stops. You have to click on an image of the second gallery to display it.

And the same page in my wordpress site (I am migrating from joomla to wordpress) : 
http://dev.sonnailles.net/cevennes/transhumance-cevenole/
After the last image of the first gallery, the lightbox displays the first image of the second gallery. I would prefer it stops or it loops to the first image of the first gallery.

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, standard WordPress galleries (generated by the Classic editor or with the `[gallery]` shortcode) are grouped separately from other links on the page when grouping is turned on and the **"Group gallery items separately"** option is enabled in SLB's settings.

Support for grouping of galleries built using the Block editor/Gutenberg is planned for a future release.  You can vote for this feature and track its progress via the [existing ticket](802).

Thanks.
