### ISSUE TITLE
Simple Lightbox breaks font type's accent support outside of lightbox

### ISSUE THREAD

**Issue by kazerniel** [archetyped/simple-lightbox#1042]
## Description of Problem

I manage a site in Hungarian language. We use the font [Yanone Kaffeesatz](https://fonts.google.com/specimen/Yanone+Kaffeesatz) for headers, which does support all Hungarian characters, including "ő".

We use the Simple Lightbox plugin on a single page, and there it turns the "ő" characters in the headers into the sans-serif fallback.

Not sure if this is related to #1032, as we don't use text captions in the lightbox, instead the plugin breaks the font of headers on the page itself.

I tried deactivating plugins to find the cause, and when I deactivated Simple Lightbox, the problem was resolved.

## Details

* URL of Page exhibiting problem: https://aszex.hu/2023/04/21/aszex-pride-felvonulas-2023/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): both Firefox and Chrome
* Version of SLB Installed: 2.9.3
* Other plugins installed: 
    * Burst Statistics
    * Easy Table of Contents
    * Events Manager
    * Gallery Custom Links
    * Loco Translate
    * Molongui Authorship
    * Say What?
    * The SEO Framework
    * Wordfence
    * WP-Optimize

**Comment by archetyped** [comment]
Yes, same root cause as #1032
