### ISSUE TITLE
Add PHP image support

### ISSUE THREAD

**Issue by df1paw** [archetyped/simple-lightbox#1043]
## Description of Problem

I tried using it with .php files outputting JPGs. If you access the php file it is corectly displayed as an image by the browser. But it's unfortunately not handled by simple-lightbox.
I tried adding ?.jpg to both links : the <img ... and the <a href - it doesn't sove the issue.

Any idea?

## Details

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox 120.0.1
* Version of SLB Installed: 2.9.3

**Comment by archetyped** [comment]
There are currently no plans to support PHP files as images in the SLB core plugin, as this would require *all* php links in posts/pages/widgets/etc. to be scanned first to determine if any of them return image data.

Such functionality may be feasible as an extension.  Head on over to the [extensions request forum](https://github.com/archetyped/simple-lightbox-extensions/discussions/categories/extension-requests) to post your request.  Development is prioritized by demand, so if there is high demand for such functionality, an extension is more likely.
