### ISSUE TITLE
[Request]: Theme design

### ISSUE THREAD

**Issue by lomomir** [archetyped/simple-lightbox#1044]
## Description of feature

(Describe your feature or idea here)

## This feature would be used to

(Describe usage here)

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by lomomir** [comment]
Our customer is an artist. He have a page with gallery. We need to have a lightbox with image on left and description (title and  ...) on right. This is a very important things for us. Also we need the arrows for move to the next and previous image. Can you please help me with css?

This is an example from WIX: https://p3k620.wixsite.com/slavobrezina?pgid=lpkr6b0h-59da5cca-486b-4ed5-8d9e-91e685a27fc4

Thanks

**Comment by archetyped** [comment]
Hi, see SLB's [Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for full details on creating custom lightbox themes.   There is a full breakdown on CSS to use to control the layout of lightbox elements, as well as a starter theme to help you easily create your custom lightbox theme.
