### ISSUE TITLE
Plugin conflict with "WP VR"

### ISSUE THREAD

**Issue by wwwFrank** [archetyped/simple-lightbox#1045]
## Description of Problem

Works fine until last Week. Then SLB stopped working. Clicking a picture in an gallery opens the media-file.
Works again, after deaktivation of Plugin "WP VR".
Maybe a conflict?

## Details

WordPress 6.4.2
PHP 7
Theme "Blocksy"
Plugin "Simple Lightbox" 2.9.3
Plugin "WP VR" 8.3.15

**Comment by archetyped** [comment]
Hi, no issues were encountered with SLB and WP VR activated on the same site, so the issue may be specific to your site/configuration.  Please provide the following details, and I would be glad to take a closer look:

* Link to specific page that exhibits the issue you are experiencing.
* Screenshot of SLB's settings page.
* Screenshot of WP VR's settings page.

Thanks.

**Comment by wwwFrank** [comment]
**SLB**'s settings are all default accept the german language text in the last section.
**WP VR**'s settings are all default, while it is installed and activated but not configured and not used until now.
Page is: [fotodrachen.de](https://fotodrachen.de/naturgarten/einheimische-pflanzen/) but I try to configure not to show the error on the public site. 
Provider is: hetzner.com (Germany)

I did some additional testing:

Backup WP on the public server with WP-plugin "BackWPup". Installed this backup on my lokal system (Ubuntu-Linux, Apache, PHP). As a customer on the public server I have **no "php.log"**. I intended to get one localy. But the error did not happen on my local system.

Then I tried to debug the error. F12 / console in browser Firefox shows some HTTP-Errors 404 pointing to "mod_pagespeed". I configured the public server not to use "mod_pagespeed" (caching).
After this the plugins "_Simple Lightbox_" and "_WP VR_" work together.

An error in Lightbox only occurs when **both plugins** are installed and activated **AND "mod_pagespeed"** for the webserver is enabled.

**Comment by archetyped** [comment]
Hi, thank you for the additional information.

It sounds like there may be an issue with mod-pagespeed's configuration.  Can you please provide the full errors you are seeing and I'll see if there is anything that can be done from SLB's end.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by wwwFrank** [comment]
I switched OFF "mod_pagespeed" in my provider's configuration, after I recognised this error.
I wrote to the providers support, but they seems not to be interested because this combination is to "exotic".

Just switched **ON** "mod_pagespeed" again to get some detailed error-codes. But the error did not happen again.
Maybe the provider has changed the version or the configuration of "mod_pagespeed"?

"Simple Lightbox" Version 2.9.3 and "WP VR" Version 8.3.19 (_changed_!) now work together with "mod_pagespeed".

Please close this issue.

**Comment by archetyped** [comment]
Thanks for the updated details and glad to hear things are working well.
