### ISSUE TITLE
Simple Lightbox Add in not avaliable in LearnDash lesson page (wordpress)

### ISSUE THREAD

**Issue by jessicaatterton** [archetyped/simple-lightbox#1055]
## Description of Problem

Hi there I am creating a course, uploading storyline media file to a lesson page in LearnDash/Wordpress site. I am using Gutenberg editor. When I upload the storyline course as a lightbox, and then view the page, the lightbox it opens in is the same as the default wordpress one. no changes and not showing the customisation i added in settings after activating the plugin. please let me know how to fix this

## Details

* URL of Page exhibiting problem: https://learning.being.org.au/lessons/lesson-1/ 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Microsoft edge
* Version of SLB Installed: most recent as of 1-2-24
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

Note: the URL provided appears to redirect to a different page (https://learning.being.org.au/courses/introduction-to-journaling/).  Please provide an updated URL that contains image links and I would be glad to take another look. 

Please also provide:

* The actual version of SLB you are using (listed on your site's Plugin admin page).
* More details on what you mean when you say you "upload the storyline course as a lightbox".  Screenshots may be helpful.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
