### ISSUE TITLE
slide show displaying photos from all galleries'  

### ISSUE THREAD

**Issue by my-Event-Horizon** [archetyped/simple-lightbox#1057]
## Description of Problem

I have more than one gallery in a post.  When I look at the post and look at the first gallery it is showing all pictures from all the galleries not just the first one.  I looked at the documentation and wondered if I need to somehow add the shortcode exclude and group?

Sorry my knowledge is limited with WP. 

## Details

* URL of Page exhibiting problem: https://event-horizon.space/2024/02/08/great-horned-owl/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  using Chrome
* Version of SLB Installed: Version 2.9.3
* Other plugins installed: Backuply / Compact Audio Player/Conditional Menus/FileOrganizer/Loginizer/Max Mega Menu/SEO SIMPLE PACK/SpeedyCachePro/Universal Slider/YouTube WordPress Plugin by Embed Plus

**Comment by archetyped** [comment]
Hi, separate gallery grouping is supported when using WordPress' `[gallery]` shortcode.

Separate grouping for galleries added via WordPress' Block Editor is planned for a future update.
Vote on [the existing ticket for this feature](802), as development is prioritized by demand.

Thanks.
