### ISSUE TITLE
ACF Featured image lightbox

### ISSUE THREAD

**Issue by afidor** [archetyped/simple-lightbox#1058]
I have free ACF plugin and display only featured image, how can I show it in lighbox, is it possible?
http://szaliki.ssmwojt2.vot.pl/gks/
Thanks for your help

**Comment by archetyped** [comment]
That depends on how the linked featured image is added to the page.  If it is within the post/page's content, then SLB can display it in a lightbox automatically.

Content outside of supported content areas need to manually activated.

See [SLB's Activation documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation) for full details.

If you require further assistance, please provide specific details of how you are adding the link to the page, and I would be glad to reopen this ticket and take another look.

Thanks.
