### ISSUE TITLE
Disable lightbox for a specific http link

### ISSUE THREAD

**Issue by pescafab** [archetyped/simple-lightbox#1059]
Hi,
I would like to disable lightbox for a specific link because the link should redirect to a new page insted of showing the image on my website.
Since the image has a http url, I can not see the preview on my https website. So a solution could be to create a link with 

> target='_blank'

 that will open the image on a new tab with original http url.
But now instead of opening new browser tab, lightbox starts loading and it remains loading because of error with https.
How can I disable lightbox and allow browser opening new tab with original image url?

Thank you

**Comment by archetyped** [comment]
Hi, links can be excluded using the `[slb_exclude]` shortcode.

See [SLB's Shortcode documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_exclude) for full details.

Thanks.
