### ISSUE TITLE
Rapport erreur 

### ISSUE THREAD

**Issue by frederic14123** [archetyped/simple-lightbox#1062]
## Description of Problem
Rapport erreur hebergeur
/wp-includes/ads.txt : File should not exist
/wp-admin/install.2.old : File should not exist
/wp-admin/ads.txt : File should not exist
/wp-content/plugins/forum-wordpress-fr/forum_wordpress_fr.php : Checksum does not match
/wp-content/plugins/forum-wordpress-fr/css/fwf.css : Checksum does not match
/wp-content/plugins/forum-wordpress-fr/js/fwf.js : Checksum does not match
/wp-content/plugins/simple-lightbox/Gruntfile.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/jshint.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/sass.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/uglify.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/watch.js : File is missing
/wp-content/plugins/simple-lightbox/package-lock.json : File is missing
/wp-content/plugins/slideshow/slideshow.js : Checksum does not match
/wp-content/plugins/slideshow/slideshow.php : Checksum does not match
/wp-content/plugins/slideshow/readme.html : Checksum does not match
/wp-content/plugins/slideshow/slideshow.css : Checksum does not match
/wp-content/plugins/slideshow/license.txt : Checksum does not match

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem:   NON
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  NON
* Version of SLB Installed:  2.9.3
* Other plugins installed: 

Ma configuration WP actuelle :
- Version de WordPress : 6.4.3
- Version de PHP/MySQL : 8.1.27 / 10.11.4
- Thème utilisé : Hueman
- Thème URI : https://presscustomizr.com/hueman/
- Extensions en place : AddToAny Share Buttons (1.8.9), Advanced Ads (1.51.3), Advanced Ads – Google AdSense In-feed Placement (1.1.3), CAPTCHA 4WP (7.5.0), Complianz | GDPR/CCPA Cookie Consent (7.0.4), Contact Form 7 (5.9.3), Easy FancyBox - WordPress Lightbox Plugin (2.0.4), Facebook Chat Plugin - Live Chat Plugin for WordPress (2.5), FileBird Lite (5.6.3), Forum_wordpress_fr (4.2), Health Check & Troubleshooting (1.7.0), Icegram Express - Email Subscribers, Newsletters and Marketing Automation Plugin (5.7.14), LWSCache (2.8.2), PHP Compatibility Checker (1.6.3), Post Type Switcher (3.3.1), ProfilePress (4.15.4), Redirection (5.4.2), Secure Copy Content Protection (3.9.9), Simple Lightbox (2.9.3), Site Kit by Google (1.123.0), Slideshow (0.1), Smart Slider 3 (3.5.1.21), TablePress (2.2.5), TinyPNG - JPEG, PNG & WebP image compression (3.4.3), Travelers' Map (2.2.1), Wordfence Security (7.11.4), WP-UserOnline (2.88.3), WP Image Zoom (1.55), WP Statistics (14.5.2), WTI Like Post (1.4.6), Yoast SEO (22.3)
- Adresse du site : https://surfcastingclubdecaen.com
- Nom de l'hébergeur : Apache/2.4.56 (Debian)

**Comment by archetyped** [comment]
Hi, it looks like you have issues with files of several plugins.  In such cases, fully deleting the existing plugins and re-installing the plugins from the official source is recommended.
