### ISSUE TITLE
Lightbox settings not there

### ISSUE THREAD

**Issue by mchat05** [archetyped/simple-lightbox#1063]
I used to be able to set up lightbox on images, but since I updated the site, the settings to add on the image block when selected in edit mode on the sidebar in edit mode. I can no longer activate lightbox on new images since yesterday. I am sending a URL where some images have it since they were on the page earlier than today and then some new ones where I couldn't activate the lightbox due to the missing settings.

* URL of Page exhibiting problem:  https://underwater2stg.wpenginepowered.com/?p=2968
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Safari, Firefox, Chrome
* Version of SLB Installed: Version 2.9.3
* Other plugins installed: Akismet Anti-spam: Spam Protection, Content Aware Sidebars, Content Slider Block, Duplicate Page, Genesis Blocks, Simple Image Sizes, Simple Lightbox, Themezee Magazine Blocks, ThemeZee Toolkit, ThemeZee Widget Bundle, WP Featured Content and Slider, and Yoast SEO.

**Comment by archetyped** [comment]
Hi, SLB does not add any settings to the post editor.  Any settings you expect in the post editor are likely added by another plugin or WordPress itself.

Rather, SLB works automatically for image links in the post's content.  

The images at the URL you provided appear to be using WordPress' recently-introduced lightbox functionality, which does not use links.  If you instead add links to the images in the post, SLB can display them in a lightbox.

See [WordPress' documentation on adding links to images](https://wordpress.org/documentation/article/image-block/#link-settings) for more details.

Please provide an updated URL once links have been added to posts if you are still experiencing an issue with SLB.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
