### ISSUE TITLE
Lightbox no longer working for Link to: Custom URL

### ISSUE THREAD

**Issue by stevegallant** [archetyped/simple-lightbox#1064]
## Description of Problem

Great plugin! I've been using it for a while now and it recently (didn't notice exactly when) stopped activating the lightbox when clicking on an image link in posts. I use an external photo site (SmugMug) for photos and add URLs within post content to display the images. I use the Custom URL option to link the downsized image to the full size one on SmugMug. 

Simple Lightbox has been working fine until recently with this configuration. Before I go down the road of disabling themes/plugins I'm checking here first to see if this may have been caused by any recent updates on the SLB module. Thanks!

UPDATE: I just tried adding a test post with a locally stored image (stored on WP server) using Link to: Media File - that actually doesn't work either, it just links directly to the image rather than opening in SLB. So the problem doesn't appear to be related to the Custom URL choice after all.

## Details

* URL of Page exhibiting problem: https://swervenortheast.us/2023/06/ibr-2023-day-11-everything-all-at-once.html
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): tried Chrome and FF
* Version of SLB Installed: 2.9.3
* Other plugins installed: 
Akismet Anti-spam: Spam Protection
Blogger To WordPress
Categories to Tags Converter Importer	
Classic Editor
Clear Floats Button
Contact Form 7
Easy Google Fonts
Featured Image from URL (FIFU)
Google Analytics Dashboard for WP (GADWP)
Jetpack
Loginizer	
Open Graphite
Redirection	
Simple Lightbox
Transients Manager
UpdraftPlus - Backup/Restore
WP Mail SMTP

**Comment by stevegallant** [comment]
I have noted in other similar issues that cURL being disabled was a cause. My hosting provider recently moved the site to a new environment, so I've also opened a ticket there to check on cURL.

**Comment by archetyped** [comment]
Good sleuthing.  This does indeed to be a case where cURL is being prevented from retrieving some of SLB's files necessary to display the lightbox.

Hopefully your hosting provider is able to resolve it without too much trouble, though note that the support request frequently needs to be escalated to someone more knowledgeable of server's actual configuration to resolve the issue.

Please let me know if you are still experiencing an issue after your hosting provider enables cURL for local requests, and I would be glad to take another look.

**Comment by archetyped** [comment]
Hi, just following up to see if you have received any details from your hosting provider regarding properly configuring cURL for your site?

**Comment by stevegallant** [comment]
Thanks for the follow-up, I'm still waiting for the "server admins" to get back to me. Not very pleased with the lack of response from this hosting provider on this, but thanks for checking. I'll confirm when they finally get back to me. :(

**Comment by stevegallant** [comment]
Update: they have confirmed cURL is enabled but not specifically  if for local requests, so waiting for them to confirm that now, since SL is still not working. https://swervenortheast.us/curltest.php

Steve

**Comment by stevegallant** [comment]
Hello, the hosting support is asking for a sample cURL command they could test that requires the local requests enabled. Could you please provide a sample?

**Comment by stevegallant** [comment]
Hi Is there some place in the code I can point at for the hosting support to review the necessary commands used by the plugin? I've tried searching the repo but haven't spotted where this is configured. thank you!

**Comment by archetyped** [comment]
Hi, SLB does not interact with cURL directly, so I unfortunately have no commands to provide.  SLB uses WordPress' built-in functionality, which may use cURL (example: [`wp_safe_remote_get()`](https://developer.wordpress.org/reference/functions/wp_safe_remote_get/)).

Your hosting provider may be able to get the information they need by performing a test directly with `wp_safe_remote_get()`.

SLB's specific code that references this WP functionality is here: [`SLB_Base_Object::get_file()`](https://github.com/archetyped/simple-lightbox/blob/7a73dc7c7881b5baed20fa6a75824c706ac29b9d/includes/class.base_object.php#L229)

**Comment by stevegallant** [comment]
Hello, 
My hosting provider (MidPhase) support response is simply terrible. However, I luckily came across a solution unrelated to cURL. By adding the following to my functions.php file, the lightbox is now working.

`add_filter( 'https_ssl_verify', '__return_false' );`

I hope this helps someone else as well. Thank you for your help looking into this and thanks again for the great simple module.

**Comment by archetyped** [comment]
Glad to hear you were able to find a workaround for your hosting provider's server configuration.

If disabling SSL verification allows SLB to work, then the underlying cause may be related to the server's root certificate or non-standard configuration that the hosting provider implements, such as port forwarding for certain types of requests, etc.
