### ISSUE TITLE
[Request]: Make lightbox responsive design

### ISSUE THREAD

**Issue by BAProductions** [archetyped/simple-lightbox#1066]
## Description of feature

Make lightbox responsive design

## This feature would be used to

Making lightboxes design responsives witch would help thing render better on mobile devices once lightbox is open.

## If you added this feature, I would: d

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
SLB's built-in themes are responsive to different screen sizes.  If you are using one of SLB's built-in theme's please provide more details on the issue you are experiencing and include the following:

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed: 

Thanks.

**Comment by BAProductions** [comment]
Live resizing

**Comment by archetyped** [comment]
SLB's official themes prioritize responsive display for different screen sizes.  Dynamically adjusting to window resizing may be supported in a future update as a byproduct to screen size optimizations, but it is not the priority.

Note that lightbox themes are fully customizable to add any functionality you want.  See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for full details.
