### ISSUE TITLE
Plugin does not work gallery_shortcode

### ISSUE THREAD

**Issue by BAProductions** [archetyped/simple-lightbox#1067]
## Description of Problem

if I render a gallery using gallery_shortcode function in the custom i'm building ATM, it link to attachment page or the file & not the light box below is the code im using witch works with the previous lightbox plugin Responsive Lightbox granted  if im not using my own plugin to make the gallery render in a jetpack style slideshow.

```
<!-- Post Gallery -->
<div id="post-item-thumbnail-<?php the_ID(); ?>" class="post-thumbnail u-cf">
    <?php
    preg_match('/\[gallery.*ids=.(.*).\]/', $post->post_content, $ids);
    $gallery_args = array(
        'ids' => $ids[1],
        'type' => 'carousel',
        'columns' => is_single() ? '3' : '6',
        'link' => is_single() ? 'file' : 'attachment',
        'size' => is_single() ? 'medium' : 'universal-small',
    );
    echo gallery_shortcode($gallery_args);
    ?>
</div>

<?php if (is_single()) : ?>
    <span class="u-spacer-h u-spacer-light"></span>
<?php endif; ?>
```

## Details

* URL of Page exhibiting problem: NA as it's my local dev environment on my local server.
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  none
* Version of SLB Installed: lasted
* Other plugins installed: to many to list as it's my local dev environment on my local server.

**Comment by archetyped** [comment]
Unfortunately, `gallery_shortcode()` does not provide the necessary hooks automatically activate the image links it generates.

However, you can use `slb_activate()` to activate the output generated by that function.  See [SLB's Activation documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation) for full details.

**Comment by BAProductions** [comment]
Actually, it does cause I've done it before
