### ISSUE TITLE
[Request]: pop up for beat sale, artist roster, embedded media, etc I have some plugin I'm working on where your plugin would make sense to use

### ISSUE THREAD

**Issue by BAProductions** [archetyped/simple-lightbox#1068]
## Description of feature

pop up for beat sale, artist roster, embedded media, etc I have some plugin I'm working on where your plugin would make sense to use 

## This feature would be used to

(Describe usage here)

## If you added this feature, I would: d

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
I'm not sure what the request is here.  Can you please provide more details on the functionality you're requesting?

Thanks.

**Comment by BAProductions** [comment]
make plugin with more then just images make open a media player with button to download & pay  for beats, and display a artist bio in a record label type website

**Comment by archetyped** [comment]
Thank you for the additional details.

That functionality is very specific to a single site, and thus is not likely to be added to the core plugin.

The functionality may be possible via a custom extension.  You can discuss the functionality you're looking to add in [SLB's Extensions Forum](https://github.com/archetyped/simple-lightbox-extensions/discussions).
