### ISSUE TITLE
[Request]: Minor improvements

### ISSUE THREAD

**Issue by yuubin8** [archetyped/simple-lightbox#1071]
## Description of feature

-If slideshow is disabled, hide the play button in the top right.
-Please enable CSS to image captions.
-If you don't need navigation, it's nice to be able to add CSS to individual images to hide them.

## This feature would be used to

Reduces minor stress when viewing content.

## If you added this feature, I would:

b) Jump for joy
e) My dog ​​is happy

Thank you.

**Comment by archetyped** [comment]
> -If slideshow is disabled, hide the play button in the top right.

When SLB's grouping/slideshow functionality is disabled via the "**Group items (for displaying as a slideshow)**" option, all slideshow-related elements (play button, navigation arrows, etc.) are not displayed.

If you are experiencing different behavior, please provide a link to a page that exhibits the issue, and I would be glad to take a look.

-Please enable CSS to image captions.
-If you don't need navigation, it's nice to be able to add CSS to individual images to hide them.

Please provide more details on the functionality you are requesting here.

Thanks.

**Comment by yuubin8** [comment]
Thank you for your response. I'm glad you care.

       -If you don't need navigation, it's nice to be able to add CSS to
individual images to hide them.

I don't need the slideshow to autoplay.
But I would like to retain the ability to manually switch images.
So I just want to hide the autoplay icon that appears in the top right
corner.
Sorry for being so nitpicky.

[image: image.png]

       -Please enable CSS to image captions.

For example, the caption of my blog right now looks like this. Ah, don't
worry about what it says.
The font is big and the typeface is not cool. The spaceng with the image is
not smart either.
Since I speak Japanese, it may be difficult for me to convey the discomfort
I am feeling.
Anyway, if we can customize this part with CSS, everything will be solved.

[image: image.png]

Thank you.

2024年6月13日(木) 4:53 Archetyped ***@***.***>:

**Comment by archetyped** [comment]
Hi, thank you for the additional details.

SLB's lightbox can be fully customized (CSS, HTML, JavaScript, etc.) using a custom theme.  All of the customizations you referred to are possible with a custom theme.

See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for full details and tutorials.

**Comment by yuubin8** [comment]
I had overlooked the existence of such a feature.
I'll give it a try. Thank you for your prompt response.

2024年6月15日(土) 5:00 Archetyped ***@***.***>:

**Comment by archetyped** [comment]
Please feel free to post any theme-related questions in the [Themes forum](https://github.com/archetyped/simple-lightbox/discussions/categories/themes).
