### ISSUE TITLE
Issue with Font plugin

### ISSUE THREAD

**Issue by PiaBrix** [archetyped/simple-lightbox#1072]
Hi there
On my website: www.korat.dk I have a small issue. 
After some updates in several plugins my lightbox all of a sudden didn't work any more. I just noticed the error to day, last night it worked without any problem. 
The images on https://korat.dk/om-koraten/livet-med-korat-vol2/ simple do not open in lightbox, when clicked on.

Efter some troubleshooting, I found that the Font plugin makes some kind of issue with the Lightbox plugin
https://da.wordpress.org/plugins/olympus-google-fonts/
I have reinstalled both plugins, re-updated wordpress. Nothing works. 
If I go to the font-adaptions on the page it self, when I do one correction, the lightbox seems to work again. But when saved and I go to the page again, nothing changed and lightbox still does not work. 

So I'm not shure if it the Font Plugin og Lightbox plugin, that is making the problems ... but something is keeping the lightbox from appearing, when clicking on an image. 

Do You know if there is a good solution?
I like both plugins, so I would hate to drop one of them :)

**Comment by archetyped** [comment]
Hi, I tested with both plugins enabled, and no issues were found.  I also customized fonts using the Font Plugin's settings and SLB still worked normally.

If you are still experiencing this issue, please provide the following details:

* Link to page exhibiting issue (SLB works at the link you provided in your original post).
* Screenshot of SLB's settings page.
* Screenshot(s) of Font Plugin's settings.

Once I have these additional details, I would be glad to take another look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the previously-requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
