### ISSUE TITLE
PHP: Use of "parent" in callables is deprecated

### ISSUE THREAD

**Issue by padbrest** [archetyped/simple-lightbox#1074]
## Description of Problem

Recurring warning :
PHP Deprecated:  Use of "parent" in callables is deprecated in simple-lightbox/includes/class.options.php on line 501

## Details

* URL of Page exhibiting problem: any page: debug mode
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox
* Version of SLB Installed: 2.9.3
* Other plugins installed: checked with only SLB
* PHP 8.3.8

I've replaced 'parent' with parent::class on line 501. Everything is now OK.

**Comment by archetyped** [comment]
Duplicate #1038
