### ISSUE TITLE
Pdf not in a box

### ISSUE THREAD

**Issue by pietgolf** [archetyped/simple-lightbox#1076]
## Description of Problem

Opening a pdf it isn’t opened in a box but in full screen. A user has to hit the “goback” key in the browser but this is not very user friendly. I did expect a “X” or a button “Close”

https://test.residentiebeukenhof.nl/wp-content/uploads/2024/07/Elektra-juni-2024.pdf
Browser safari on ios 17.5.1

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, Simple Lightbox supports the display of media such as images in a lightbox.  PDFs are document files, not images, so what you are likely seeing is the browser loading the PDF directly.
