### ISSUE TITLE
Can't get it to work on CPT within Theme X Pro

### ISSUE THREAD

**Issue by Gitaarsnaar** [archetyped/simple-lightbox#1077]
## Description of Problem

First of all, I love the approach of your plug-in. Simple and easy, no unnecessary features. 
I encounter a problem on a CPT by using Theme X Pro. On all of the pages the lightbox works fine, however not on CPT when using the layout builder. I'm dynamically getting images from a gallery with ACF Pro, but even when I just add an image statically with a link attached to itself, it doesn't work. I have the idea it's just not activated on the CPT. 

Concerning the settings, I've enabled Simple Lightbox to apply on all page and post types. 

## Details

* URL of Page exhibiting problem: https://afaber.raap.media/projecten/3526-2/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Brave, Safari
* Version of SLB Installed: 2.9.3
* Other plugins installed: 
- Advanced Custom Fields PRO
- Classic Editor 
- Custom Post Type UI 
- Gravity Forms 
- Gravity Forms Google Analytics Add-On 
- Gravity SMTP 
- Members 
- Security Optimizer 
- Simple Lightbox 
- Speed Optimizer

**Comment by archetyped** [comment]
SLB does appear to be activated at the link you provided.  However, the theme template used for the CPT may not be set up properly to allow SLB to see the links in the post.

See [SLB's Theme Requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#theme) for more details on ensuring a theme template is compatible with SLB.

If you are still experiencing an issue after validating the theme template, please provide the full template code and I would be glad to take a look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
