### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by goranb** [archetyped/simple-lightbox#1081]
## Description of Problem

Unable to update plugin using WP Admin interface to resolve deprecation warnings introduced with PHP8. Alternative solutions exist, but would drastically change our approach, thus is a non-starter.

## Details

* latest release available is 2.9.3, which is stale (from 2022)
* update directly via trunk would add unnecessary overhead for otherwise fully automated process

**Comment by archetyped** [comment]
Hi, per [SLB's plugin details](https://wordpress.org/plugins/simple-lightbox/), v2.9.3 is currently the latest version.  If that's the version you have installed, then no further updates are necessary.

If you have an older version installed, WordPress' built-in plugin updater should allow updating to the latest version.  If it doesn't, deleting and re-installing the plugin from the Plugins admin page will always install the latest version.

**Comment by goranb** [comment]
I thought I saw this already applied in `develop` branch, but looks like I was wrong: https://github.com/archetyped/simple-lightbox/pull/1046.
