### ISSUE TITLE
When SLB avtivated "double taps" images in Essential Grid

### ISSUE THREAD

**Issue by DiBop** [archetyped/simple-lightbox#1088]
## Description of Problem

When I have SLB activated, when someone clicks on an [Essential Grid](https://www.essential-grid.com/) gallery, Essential Grid picks up the click and opens an image in a lightbox, SLB **_then_** picks up the click and makes the image take up the entire viewport with no way to get back (on a Mac) except for hitting ESC. Then SLB loads up the same image again and makes it fill the entire viewport until you hit ESC. Only happens with Essential Grid galleries. 
[
Link to video of issue in action: ](https://www.loom.com/share/668df43634fa428ca68f46f5ebac35f6?sid=efeb3d21-653d-4adb-a86a-dd455c5845b9)

Love the plugin but have to deactivate it for now :(

## Details

* URL of Page exhibiting problem:  https://360csg.com/gallery/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome, Edge, Safari
* Version of SLB Installed: 2.9.3
* Other plugins installed: Essential Grid

**Comment by archetyped** [comment]
Hi,

Depending on how the gallery is added to the page, you can exclude it from SLB using the `[slb_exclude]` shortcode ([documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_exclude)).

However, running multiple lightboxes on the same page is never recommended as they can cause conflicts and unexpected behavior.  Disabling other lightboxes is recommended.

> SLB then picks up the click and makes the image take up the entire viewport with no way to get back (on a Mac) except for hitting ESC. 

SLB resizes larger images to fit the browser window via the "Resize lightbox to fit in window" option.  This option is enabled by default, but it appears to be disabled on your site.  Enabling this option will prevent large images from extending beyond the browser window.

**Comment by DiBop** [comment]
Awesome! Thank you for taking the time!
