### ISSUE TITLE
Link to Attachment Page from Lightbox?

### ISSUE THREAD

**Issue by ghost** [archetyped/simple-lightbox#213]
I've created a custom template and would like to put a link to the photo's attachment page in the lightbox.  I've tried creating an a href link with {{item.permalink}}, but that tag seems to put some formatting options in the form of a <span>.  Is there a way to clean the data or a better way to link from the lightbox?

**Comment by webprese** [comment]
Hi archetyped, 

I would also really like (and need) a href link within the lightbox. Is there any way at all I can include the image as an attachment or create a link based on the selected image?

I will pay anyone who can come up with a solution for this quickly. I just want the visitor to be able to download the image, it cant be that difficult surely.
