### ISSUE TITLE
Issue: Not working with self-signed SSL

### ISSUE THREAD

**Issue by sdayman** [archetyped/simple-lightbox#280]
I have several sites, and I've switched to SSL. I'm using DreamHost's self-signed SSL certs and Cloudflare's Universal SSL certs. Now Simple Lightbox doesn't work.

Visitors to Cloudflare don't get certificate warnings, so that's encouraging. However, using curl on the Dreamhost server to hit the site, curl gives me the following error:
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Using 'curl -3k' works. Since I read that Simple Lightbox uses curl, I'm betting this is the issue.

Is there some code I can modify to get curl working? (I can't find 'curl' in any of the SLB files) Or is it some other issue?

URL of page exhibiting bug: https://4x4freelanders.org
Version of SLB installed: 2.3.1
Other plugins installed: Wordfence, Bruteprotect, Smushit, Cloudflare, 
Browser(s) with issue (Firefox, Chrome, etc.): Latest Safari, Chrome, Firefox, all on OSX 10.9.5

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
