### ISSUE TITLE
[slb_exclude] shows up in "Yet Another Related Post Plugin" excerpts

### ISSUE THREAD

**Issue by revmax** [archetyped/simple-lightbox#282]
## Description of Problem

[slb_exclude] shows up in "Yet Another Related Post Plugin" excerpts

added 

add_filter( 'the_excerpt', 'remove_slb_exclude_from_excerpt' );
function remove_slb_exclude_from_excerpt( $the_excerpt ) {
	return preg_replace ('/\[slb_exclude[^\]]*\](.*)\[\/slb_exclude\]/', '$1', $the_excerpt);
}

to functions but this did not fix

## Details

* URL of Page exhibiting problem: http://www.enemies.cc/illustrated-gnostic-myths/alien-god-aeons/the-barbelo/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Version 2.3.1 
* Other plugins installed: YARPP 4.2.4, Widget Logic 0.57, Exec-PHP 4.9

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
