### ISSUE TITLE
Feedback: Sanitizing URLs

### ISSUE THREAD

**Issue by sbstern** [archetyped/simple-lightbox#284]
Great plugin... My only question is why strip the URL parameters (or don't have an option to atleast leave them in). I am using the plugin with embedded pictures from Facebook, and the URL parameters are extremely important... simply put the images won't be pulled without the URL paremeters. Why not just take the link as is.

http://hotandfreshdeliveries.com/gallery/

**Comment by archetyped** [comment]
**Quick update:** This issue has been resolved and will be in the next update.

Thanks for the report :+1:
