### ISSUE TITLE
Simple lighbox lots of warnings while WP_DEBUG is enabled on PHP 5.4+

### ISSUE THREAD

**Issue by tometzky** [archetyped/simple-lightbox#285]
When WP_DEBUG and WP_DEBUG_DISPLAY are enabled then this plugin shows multiple warnings like this:

```
Strict Standards: Declaration of SLB_Lightbox::_options() should be compatible with SLB_Base::_options($options_config = NULL) in /wordpress/wp-content/plugins/simple-lightbox/controller.php on line 7
Strict Standards: Only variables should be assigned by reference in /wordpress/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 623
Strict Standards: Declaration of SLB_Themes::_options() should be compatible with SLB_Base::_options($options_config = NULL) in /wordpress/wp-content/plugins/simple-lightbox/includes/class.themes.php on line 9
```

This is because [from PHP 5.4.0 E_ALL includes E_STRICT](http://php.net/ChangeLog-5.php#5.4.0). And [Wordpress since 2.5 enables E_ALL when WP_DEBUG is enabled](http://codex.wordpress.org/WP_DEBUG). Also [Wordpress strongly recommends enabling `WP_DEBUG` while developing a plugin or theme](http://core.svn.wordpress.org/trunk/wp-config-sample.php).

When you go to `/wp-admin/` with this plugin enabled it prevents logging in with additional warning:

```
Warning: Cannot modify header information - headers already sent by (output started at /wordpress/wp-content/plugins/simple-lightbox/includes/class.options.php:445) in /wordpress/wp-includes/pluggable.php on line 1173
```

This is all bad. Some problems:
- You can only log in using `/wp-login.php`. And this link isn't always known.
- It makes debugging another plugin hard as there's a flood on warnings from Simple Lightbox.
- Its a bad practice to use non-strict code. It can break in any future PHP version.
- More and more sites use PHP 5.4+ as [PHP 5.3 reached end of life](http://php.net/eol.php).
- Correcting it shouldn't be a lot of work. But it would prevent a lot of future support requests.

I know this is a duplicate of #56. But I can't reopen that issue. Please correct this issue.

**Comment by eggmatters** [comment]
Is there a branch or commit with these updates? I noticed a reporter of a dupe of this issue offered to put in a fix. Did you take him up on that?
