### ISSUE TITLE
Issue: Images in Gallery do not show caption when set to link to "Media File"

### ISSUE THREAD

**Issue by wilflare** [archetyped/simple-lightbox#291]
## Description of Problem

When Post Format is set to "Gallery" and Gallery Link to is set to "Media File", captions do not show in Lightbox (In a Standard Format Post, captions show just fine when set to "Media File").

Captions only show in a Gallery Format when Gallery Link to is set to "Attachment Page"

Is this a bug?

## Details

* URL of Page exhibiting problem: http://www.wilflare.com/2014/11/07/week-one-photos/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.3.1
* Other plugins installed:

**Comment by archetyped** [comment]
Captions appear to be working in Gallery post formats with link set to "media file".  Perhaps this was resolved in an update.
