### ISSUE TITLE
Issue: Trouble with post that have a photo

### ISSUE THREAD

**Issue by mariafernandez** [archetyped/simple-lightbox#294]
Hi,

I've installed LightBox on my blog. It works well on pages that have no images. However, on posts with an image, the links open on a different window.

Is this a problem you're aware of?

Thanks

Maria

Details

* URL of Page exhibiting problem: site is in staging
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Safari, Chrome, Firefox
* Version of SLB Installed: 2.3.1
* Other plugins installed: 
Autoptimize 1.9.1 (active)
Disqus Comment System 2.83 (active)
Genesis Simple Edits 2.1.1 (active)
GeoTarget by Country Plugin Version 1.13 (active)
Gravity Forms 1.8.19 (active)
jQuery Pin It Button For Images 1.38 (active)
LeadPages connector 1.1.3.2 (active)
OptinMonster 2.1.1 (active)
OptinMonster - After Post Addon 2.0.1 (active)
OptinMonster - Sidebar Addon 2.0.0 (active)
Pretty Link Lite 1.6.5 (active)
Simple Lightbox 2.3.1 (active)
Simple Social Icons 1.0.6 (active)
Social Share Starter by KK 0.7.4 (active)
SpeakPipe - Voicemail for Websites 0.1 (active)
WordPress SEO 1.6.3 (active)
Wp-Insert 2.0.12 (active)
WP Smush.it 1.6.5.4 (active)
WP Ultimate Recipe Premium 2.1.1 (active)
WP User Avatar 1.9.13 (active)

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
