### ISSUE TITLE
Issue: Lightbox not working. 

### ISSUE THREAD

**Issue by stuartdn** [archetyped/simple-lightbox#295]
## Description of Problem

We have used your Simple Lightbox plugin in order to add Lightboxes to our website. It has worked fine until recently.However now, when clicked on its just opening the image in a new tab.

We are using this theme.
http://oboxthemes.com/theme/flatpack

## Details

* URL of Page exhibiting problem: http://www.interaction-lab.co.uk/facilities/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All of them
* Version of SLB Installed: V2.3.1
* Other plugins installed: WP Maintenance Mode, Jetpack, Hello Dolly, Duplicator, Akismet

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
