### ISSUE TITLE
Issue: it tooks five minutes after a publish article to work with the lightbox

### ISSUE THREAD

**Issue by azura404** [archetyped/simple-lightbox#308]
## Description of Problem
Hello,

When I publish a new article on my website, it tooks maybe 5/10 minutes for the lightbox to work? This is something normal? I use WP Super cache by the way.

Best

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
