### ISSUE TITLE
SLB doesn't work anymore

### ISSUE THREAD

**Issue by DBKenshin** [archetyped/simple-lightbox#315]
My site is here (with a bunch of pictures in the post):  http://wing-on-wing.com/?p=85

SLB had been working up until recently, but I just noticed today that it wasn't anymore. I've switched to default themes, I've disabled other plugins, with no luck. I've also tried both the released version of SLB and 2.4.0-b3.

The only other plugins installed are Akismet, Jetpack, and Social Profile Linking. All plugins, themes, and Wordpress itself are fully updated. What am I doing wrong?

Thanks!

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled for your site.  This can happen if you've moved to a different server or you (or your hosting provider) made changes to the server configuration.

Enabling cURL for local requests should allow SLB to function normally.  See here for more information on [SLB's minimum requirements](../wiki/Requirements).

**Comment by DBKenshin** [comment]
Turns out it is, but my web host no longer allows use of HTTP/1.0.

When I reconfigured Wordpress to use HTTP/1.1 in ./wp-includes/class-IXR.php and ./wp-includes/class-snoopy.php SLB began working again.

**Comment by archetyped** [comment]
Thanks for the update, glad to hear it's working again.
