### ISSUE TITLE
Hi, my blog has problems with lightbox in pages and home

### ISSUE THREAD

**Issue by novadehistoria** [archetyped/simple-lightbox#316]
My blog again cause problems.
The only thing working properly are the galleries as like this http://novadehistoria.com/el-siroco-del-olvido-2/
But lightbox does not work in other pages like this http://novadehistoria.com/la-utopia-de-mil-colinas/
And I think the following notice RESET https://dl-web.dropbox.com/get/Capturas/Captura%20de%20pantalla%202014-12-21%20a%20las%2013.20.06.png?_subject_uid=42251229&w=AAADkw_RuXYGc_Hin0vJYa9doGNRslSqIJW3wM1fmyKXcg
https://www.dropbox.com/s/xce0l4jm64qel67/Captura%20de%20pantalla%202014-12-21%20a%20las%2013.20.06.png?dl=0
Appreciate their review
Thank you so much.

**Comment by archetyped** [comment]
Hi, unfortunately the first image link you posted is returning an error, so I cannot see what the issue is.  Please provide a new link and I would be glad to take another look.

Also, make sure that SLB's "Enable on Pages" option is set to enable SLB for pages.

**Comment by novadehistoria** [comment]
Sorry, this image https://www.dropbox.com/s/xce0l4jm64qel67/Captura%20de%20pantalla%202014-12-21%20a%20las%2013.20.06.png?dl=0

**Comment by archetyped** [comment]
Hi, can you confirm that you have pages and posts enabled in SLB's settings?  If possible, please provide a screenshot of SLB's options page.

Also, here are [instruction for determining whether another plugin or theme is causing a conflict with SLB](../wiki/Troubleshooting-Plugin-Conflicts).

**Comment by novadehistoria** [comment]
Yes… https://www.dropbox.com/s/unxnxg3pclgitfe/Captura%20de%20pantalla%202015-01-07%20a%20las%2022.35.59.png?dl=0

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.

It looks like there may be a conflict with another plugin.  Please follow the instructions for identifying the conflicting plugin (see my previous reply).  Let me know what plugin is causing a conflict and I will be glad to take a closer look.

**Comment by archetyped** [comment]
Hi, Are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
