### ISSUE TITLE
Would love for there to be integration with ACF so that images get lightboxes in those custom fields

### ISSUE THREAD

**Issue by tigredanky** [archetyped/simple-lightbox#317]
## Description of feature/request
Provide documentation for how to hook into the plugin to extend it's functionality to custom fields.

## This feature would be used to
Allow images to be lightboxed when used or appearing outside of the_content();

## If you added this feature, I would:

d) All of the above and then some. :)

**Comment by archetyped** [comment]
Hi, you can use `slb_activate()` to activate non-native content with SLB.

* [More information on using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/)
* [Discussion on using `slb_activate()` with ACF](https://wordpress.org/support/topic/use-with-advanced-custom-fields-1?replies=16)
