### ISSUE TITLE
SLB not compatible with Wordpress 4.1

### ISSUE THREAD

**Issue by MrWordpress84** [archetyped/simple-lightbox#318]
After updating to Wordpress 4.1, SLB stopped to work. I already switched to various standard themes and deactivated all plugins except SLB - without success. Other Lightbox-Plugins, like fancybox, work like a charm... will there be an update to ensure compitability with Wordpress 4.1?

**Comment by archetyped** [comment]
Hi, SLB is indeed compatible with WordPress 4.1. Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a look.

**Comment by MrWordpress84** [comment]
Hi! Sorry for answerting that late, I just returned from vacation... The URL of the site is www.andyinusa.com. I deactivated all plugins except for the simple lightbox plugin. I found out, that this issue only occurs if the site is protected via htaccess. Deactivating the htaccess protection resolves this issue... Strangely, other lightbox plugins continue working if htaccess protection is enabled.
Maybe you could have a look at the site? Thank you very much for your help! May I send you the htaccess login data via e-mail?

**Comment by archetyped** [comment]
Hi, HTTP authentication stops SLB from being able to access the plugin files it needs to function properly.  As you noted, disabling authentication will allow SLB to function normally.
