### ISSUE TITLE
WP Engine Live w/ CDN vs. Staging server w/o CDN

### ISSUE THREAD

**Issue by tigredanky** [archetyped/simple-lightbox#319]
## Description of Problem
Not sure if having the CDN activated is what's breaking SLB, but on my live install of ecologyartisans.com SLB isn't working when it was on staging (see URLs below).

Thanks!

## Details

* URL of Page exhibiting problem: 
** Broken URL: http://ecologyartisans.com/kitchen-sink/
** Working URL: http://ecologyartisan.staging.wpengine.com/kitchen-sink/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: 2.3.1 on both live/staging
* Other plugins installed: http://ecologyartisans.com/i/plugins.png

**Comment by archetyped** [comment]
Hi, some CDNs break the link between images and SLB and must be supported via an add-on.  See here for [more information on the CDN add-on](33).

The link you provided on the production site is currently reporting a 404.  Please provide a working link and I would be glad to take another look.

**Comment by tigredanky** [comment]
Had it set to private, just put a password on it with "test". I'm hosting with WP Engine and looking at what their CDN is. Thanks!

**Comment by tigredanky** [comment]
They've got MaxCDN and the support team recommended that using relative URLs could work, or forcing it to grab the real URL (i.e. ecologyartisans.com vs. 24vm5qbm3vy38dhjx2vse3pi.wpengine.netdna-cdn.com).

**Comment by tigredanky** [comment]
New URL that should be showing the lightbox images, but isn't (just links to the default WP image only page) http://ecologyartisans.com/restoration-agriculture-workshop-march-10-14/

**Comment by archetyped** [comment]
Thanks @tigredanky, I can confirm that the CDN is changing the image's URL and breaking the connection between the image and SLB.  Your CDN provider/plugin may have settings to exclude image URLs from being modified or, as noted by their support, using relative URLs to the images in your links may allow the CDN to bypass these links.
