### ISSUE TITLE
SLB only works in certain places question?

### ISSUE THREAD

**Issue by PurpleApe007** [archetyped/simple-lightbox#320]
I have enabled all the options see screenshot. SLB seems to only work on content media actually placed in a post or page content via the editor or add media button in the back-end. It does not work on the "Featured Images" set on any page or post. Should it work on those? The workaround would be to put the featured image right in the post I guess.

Also, the theme I am using has a custom page post type called "projects" and SLB doesn't seem to recognize these pages content at all.

Visit the site here: http://www.paintingcoatingscontractors.com
These are the current settings:
![slbsettings](https://cloud.githubusercontent.com/assets/7967069/5653274/bd0cddfa-9686-11e4-8de9-59ab16a49905.png)

Is there a way to add unique post types like "projects" to SLB so the content is recognized (maybe a shortcode)?

Thanks for getting back to me.

**Comment by archetyped** [comment]
Hi, SLB automatically activates content inside post content.  External content may be activated via add-ons or manually using `slb_activate()`.  See here for [more information on using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/).

All custom post types are supported by SLB, but the theme may not be outputting the project's data according the WordPress' theme guidelines.  I would be glad to take a look if you can provide the template code used by the theme to display a project's content.

**Comment by PurpleApe007** [comment]
Hi Archetyped

Thanks for getting back to me so quick.  Thanks for the link to the additional SLB info and short codes those will be use full.

I attached the two php files that I think are suspect. They are both commented as “single post page” but the single-portfolio.php is different in that it doesn’t call the thumbnail (line 31) and it has a gallery (line 109) the gallery contains the images that do not work in SLB. The gallery input is in the backend and does not allow code but I am thinking the single-portfolio.php could be edited to allow SLB and be put in the child theme I think maybe. I am not good enough with php to know.

I appreciate you taking a look at it. If you could edit the code to make the gallery go into SLB that would be great. If you don’t think that would work let me know.

Thanks again for your help.

Barry Marciniak
Way Better Networks, LLC.
Cell:	727-415-7357
Email: barry3000@me.com

**Comment by archetyped** [comment]
Hi, I don't think attachments work when you reply to the forum notification emails.

Please click the "View it on GitHub" link in the email and paste your template's code into a new comment and I will take a look.

**Comment by PurpleApe007** [comment]
Hi Archetyped

Thanks for getting back to me. I have everything fixed now. I picked your plugin because I thought it was best. However the developers that made the theme I am using used a different plugin. They sent a link to the correct plugin that they used in their theme and everything works fine now.

So I’ll have to use your plugin on a future application.

I appreciate the response. Thank you.


Barry Marciniak
Way Better Networks, LLC.
Cell:	727-415-7357
Email: barry3000@me.com

**Comment by archetyped** [comment]
Glad to hear you found a solution for your needs.
