### ISSUE TITLE
Issue: Not working with Google Chrome

### ISSUE THREAD

**Issue by T-Co** [archetyped/simple-lightbox#322]
## Description of Problem

Not working with google chrome...

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your ticket to include the details of the issue you're experiencing and I would be glad to take a look.

Thanks.

**Comment by archetyped** [comment]
Are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
