### ISSUE TITLE
one thumbnail

### ISSUE THREAD

**Issue by jacksiejohn** [archetyped/simple-lightbox#323]
Is it possible to only have one thumbnail visible, which links to the lightbox of multiple gallery images? 

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 2.3.1
* Other plugins installed:

**Comment by archetyped** [comment]
Yessir, here's [a tutorial on launching slideshows from a single link](http://archetyped.com/know/slb-single-link-slideshows/ "a tutorial on launching slideshows from a single link").
