### ISSUE TITLE
Issue: won't pop up

### ISSUE THREAD

**Issue by scrappy587** [archetyped/simple-lightbox#326]
## Description of Problem

SLB doesn't pop up regular images. 

I PURCHASED Simple Lightbox: Video Handler and it works fine. Just images won't pop up in a Lightbox? Any tricks?

## Details

* URL of Page exhibiting problem: http://www.lawabidingbiker.com/live-to-ride
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Safari, others.......
* Version of SLB Installed: 2.3.1
* Other plugins installed: Video Handler works fine, so not a plugin problem.

**Comment by archetyped** [comment]
Looks like you might be using Jetpack's Photon module which currently modifies image URLs and breaks the connection between images and SLB.  Deactivating Photon will allow SLB to function properly.

**Comment by scrappy587** [comment]
Thanks so much. RESOLVED.

Love the plugin and the video handler add on I bought

-Ryan

**Comment by archetyped** [comment]
Glad to hear your issue was resolved :)
