### ISSUE TITLE
Issue: SLB Doesn't Work With W3 Total Cache in Google Chrome

### ISSUE THREAD

**Issue by sethmad** [archetyped/simple-lightbox#327]
## Description of Problem

When both SLB v. 2.3.1 and the plugin W3 Total Cache v. 0.9.4.1 are activated, SLB stops functioning entirely in Google Chrome 39.0.2171.95 for OS X 10.10.1.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please fill in the rest of the details of your ticket and I would be glad to take a look.

Thanks.

**Comment by archetyped** [comment]
Are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by transbetty** [comment]
I have the same problem. My guess W3TC minifying the JS/CSS resources messes up something. Event doesn't even trigger, the normal link opens with W3TC enabled.

I can post the URL but it's an adult site, so please aprove that  first.

**Comment by archetyped** [comment]
Hi @transbetty, SLB should be fully compatible with W3TC's minification, but if you send an email to support@archetyped.com with a link to a page that exhibits the issue you are experiencing, I can take a look.
