### ISSUE TITLE
Feedback: Horizontal Scrolling Issue

### ISSUE THREAD

**Issue by linseedstudio** [archetyped/simple-lightbox#328]
Hi there,

Just want to say that your plugin is great and thank you for taking the time to construct it.  I'm migrating my site to WP and for some reason very few lightbox plugins have been integrating w/ it (probably partially due to my limited WP skills) but yours seems to hit all the marks (knock on wood).  I have a few pages that use JQuery to horizontally scroll through thumbnail images and one problem I ran into was that when I would scroll to the right of the page and click on any thumbnail, the image would open all the way over to the left (this is Chrome btw).  When I inspected it, it looked like #slb_viewer_wrap .slb_theme_slb_baseline .slb_viewer_layout was centering where it should if I hadn't scrolled the page, so it was remembering the original centering positioning and using that instead of centering to the current browser window (sorry if I didn't explain that very well).  I found that changing the position from absolute to fixed remedied the problem, so you might want to check it out yourself.  Hopefully I don't realize that this causes other problems somewhere down the line.  

Thanks again,

_Mike

**Comment by archetyped** [comment]
Hi, thanks for the feedback.  Fixed positioning can be a problem when images are larger than the browser window as it would keep users from being able to view the entire image.  However, horizontal scrolling is uncommon, so it may be a good solution for your site.  If you can provide a link, I would be glad to take a closer look at improving compatibility.

**Comment by archetyped** [comment]
Are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
