### ISSUE TITLE
Issue: lightbox not working on pages with Divi 2.0 theme

### ISSUE THREAD

**Issue by rcorbari** [archetyped/simple-lightbox#329]
## Description of Problem

Hello, SLB works well in the posts pages, but does not in simple pages. I use WP 4.1 and Divi 2.0 theme. Do you know why?

Thank you, best regards.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please fill in the details of your issue and I would be glad to take a look.

Thanks.

**Comment by archetyped** [comment]
Are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
