### ISSUE TITLE
Issue: FloZo Theme/SLB Issues

### ISSUE THREAD

**Issue by adam-webb** [archetyped/simple-lightbox#331]
## Description of Problem
Lightbox not working - have tried all diagnosis I can find.
Theme is FloZo, but I have made some changes to it, however non that I think should effect SLB
SLB works with default theme, suggesting a theme issue not plug in
wp_header, wp_footer and content all being loaded
## Details

* URL of Page exhibiting problem: http://www.maddogcomposites.com.au/new_website/asw-20bl/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox & Chrome
* Version of SLB Installed:  2.3.1
* Other plugins installed: Theme issue not plug in

**Comment by archetyped** [comment]
Hi, it appears that something is stopping scripts from loading on the page (including SLB).  It may be related to the validation issues on the site.  I would recommend fixing these issues as that may allow SLB to function properly.

More information: [Validation results](http://validator.w3.org/check?verbose=1&uri=http%3A%2F%2Fwww.maddogcomposites.com.au%2Fnew_website%2Fasw-20bl%2F)

**Comment by adam-webb** [comment]
Thank you for your response - I have cleared all the validation issues on the site, but still having no luck. Is there anything else which could be interfering with the loading of the scripts?

**Comment by archetyped** [comment]
Hi, certain SLB files are still not being loaded.  I would recommend temporarily reverting to an unmodified version of the theme to determine whether the theme itself has a conflict with SLB or if it was the modifications that were made to the theme causing the conflict.

**Comment by adam-webb** [comment]
Thanks again.
I have installed a fresh install of WP, and installed only SLB and the theme and I'm still having the same issues. Is available on http://www.adam-webb.com/smellyleopard/ . Do you have any more suggestions?
Cheers
Adam

**Comment by archetyped** [comment]
Hi, an outdated version of jQuery is being loaded on that page.  If no other plugins are installed, then it's being loaded by the theme.

See here for more information: [jQuery Support](../wiki/jQuery-Support)

**Comment by adam-webb** [comment]
Thanks very much, while sorting that issue out (which I had resolved on the
original problem website) I found the line <?php
wp_deregister_script('jquery'); \> which I deleted and now it appears to be
working :).

Seems obvious now...

Thanks again for your help

AW

**Comment by archetyped** [comment]
Glad to hear your issue was resolved :)
