### ISSUE TITLE
Request: 

### ISSUE THREAD

**Issue by heikepander** [archetyped/simple-lightbox#332]
## Description of feature/request
feature with which I can automatically add water marks to photographs (maybe it is already there but I could not identify it... sorry)

## This feature would be used to

add water marks to photographs where necessary

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

b and thank you very much!!! :-)

**Comment by heikepander** [comment]
I love the lightbox plug-in and I would be very sad if I could not use it further - for some of my photographs I would love to add water marks and I was wondering if it would be possible to do that in lightbox...
Thanks for your response. 
Heike

**Comment by archetyped** [comment]
Hi, SLB does not modify images in any way.  I would recommend adding watermarks to images prior to uploading them for the best results.

**Comment by heikepander** [comment]
Thanks very much for your quick response - I'll find a solution.

Gesendet: Freitag, 23. Januar 2015 um 03:51 Uhr
Von: Archetyped <notifications@github.com>
An: archetyped/simple-lightbox <simple-lightbox@noreply.github.com>
Cc: heikepander <heike.pander@web.de>
Betreff: Re: [simple-lightbox] Request: (#332)


Hi, SLB does not modify images in any way. I would recommend adding watermarks to images prior to uploading them for the best results.
