### ISSUE TITLE
Request: Hovered mouse

### ISSUE THREAD

**Issue by kostaspa** [archetyped/simple-lightbox#333]
## Description of feature/request
When someone hovers over an image,It would be nice, to turn the pointer in to a magnifying glass.

## This feature would be used to
This feature would be used to be more clearly from the people/visitors, that this image can be viewed in a lightbox mode.

## If you added this feature, I would:
b
a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

thank you!

**Comment by archetyped** [comment]
Hi, SLB does not have any effect on the images on the page, only what is displayed in the lightbox.  However, you can edit your theme's CSS to change how the mouse cursor appears over links like so:

```css
a {
cursor:zoom-in;
}
```

You can control which links use this cursor by using a more specific CSS selector.

**Comment by kostaspa** [comment]
Thank you Very much !!!
