### ISSUE TITLE
Request: Activate content outside of post content

### ISSUE THREAD

**Issue by Beee4life** [archetyped/simple-lightbox#335]
## Description of feature/request

support for usage in template files

## This feature would be used to

create a lightbox outside the_content

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, links outside of native post content can be manually activated using `slb_activate()`.

See here for [more information on using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/).

**Comment by Beee4life** [comment]
not what i was looking for.... but thanks

**Comment by archetyped** [comment]
Please provide more details on what you are looking for SLB to do and I would be glad to look into it.

**Comment by Beee4life** [comment]
Now that I'm explaining it, I think I already expressed this wish a while ago...

I have some pages, which are generated purely out of templates, not through the_content(). I use Lightbox Plus Colorbox there because if I write an "a href" in a template it automatically gets lightboxed, without me putting shortcodes around it.

I like that but your lightbox looks better... So I hope you can achieve the same with this plugin.

**Comment by archetyped** [comment]
Thanks for the additional details.  This type of functionality is not currently planned, but I've added it to the list for a possible future update.

**Comment by Beee4life** [comment]
Thanks
