### ISSUE TITLE
Where are the demos?

### ISSUE THREAD

**Issue by paaljoachim** [archetyped/simple-lightbox#336]
Hey

I am looking at implementing a lightbox that I can easily customize.
Am I in the right place?
Downloading the JS adding the code snippet to use in WordPress.
Adding the information to this page for others to read about as well:
http://easywebdesigntutorials.com/adding-a-lightbox-to-wordpress-without-using-a-plugin/

**Comment by archetyped** [comment]
Hi, SLB has a simple options page for customizing several aspects of the lightbox's display and functionality.

SLB works automatically.  There is no JS to download or snippets to add.
