### ISSUE TITLE
Request: Support for (m)qtranslate

### ISSUE THREAD

**Issue by lambrassie** [archetyped/simple-lightbox#337]
## Description of feature/request
Add support for (m)qtranslate shortcodes in the multimedia-descriptions so the description that is displayed depends on the language.

## This feature would be used to
Have a correct description depending on the language the image is displayed on

## If you added this feature, I would:
Be very happy!

**Comment by archetyped** [comment]
Hi, please add your suggestions to [this existing ticket for the Multilingual add-on](205).

Thanks.
