### ISSUE TITLE
Issue: Round gallery thumbnails disappeared

### ISSUE THREAD

**Issue by knoxbronson** [archetyped/simple-lightbox#338]
## Description of Problem
I am using the "Nulis" WP theme, when I updated it, your beautiful round gallery thumbnails disappeared! :(
I think it could be a theme issue, but I don't know how to fix.
## Details

* URL of Page exhibiting problem: http://www.iphotographer-magazine.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed:  2.3.1
* Other plugins installed: social media feather, WP to Twitter

**Comment by archetyped** [comment]
Hi, SLB does not modify the display of gallery thumbnails on the page.  It only controls how content is displayed in the lightbox.

Perhaps it was a setting in your theme or with another plugin?

**Comment by knoxbronson** [comment]
thanks. I wrote a support ticket with the theme developers. Hopefully they will have an answer. Love how your lightbox works, BTW!
