### ISSUE TITLE
Issue: conflict with Bootstrap Basic theme

### ISSUE THREAD

**Issue by zoespring** [archetyped/simple-lightbox#340]
I'm working on a site using the bootstrap basic theme, and I can't figure out why SLB doesn't work on it. I changed the theme to twenty fifteen and the plugin worked perfectly, so I believe it's a bootstrap basic conflict. In the element inspector, I can see that the SLB parameters are being added to each image. I checked all the requirements and they're AOK. I understand you can't help much if the page isn't live. Sorry in advance if this issue is addressed elsewhere.
[screen shot 2015-02-15 at 9 47 02 pm](https://cloud.githubusercontent.com/assets/1789303/6206647/aab2cc38-b55c-11e4-835a-320a381cf4bc.png)

## Details

* URL of Page exhibiting problem: site is in local development
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: first tried 2.3.2, then 2.4.0-b3
* Other plugins installed: none

**Comment by archetyped** [comment]
Hi, unfortunately that screenshot doesn't give me a lot to go on.  If you've already confirmed that the theme meets [SLB's requirements](../wiki/Requirements), then I would need to take a closer look to see what is happening.

Let me know when you are able to get a dev server up and I would be glad to take a look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
