### ISSUE TITLE
Incompatible plugin

### ISSUE THREAD

**Issue by lemonadedesign** [archetyped/simple-lightbox#341]
## Description of Issue

Simple lightbox stops working with http://aspenthemeworks.com/atw-show-posts/

I narrowed it down to the following plugin: http://aspenthemeworks.com/atw-show-posts/

## Details

* URL of Page exhibiting problem: http://www.materialitytracker.net/results/djsi-industry-leaders-2013-2014-key-material-topics/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
* Version of SLB Installed: 2.3.1
* Other plugins installed: Akismet (v.3.0.4) from Automattic
	http://akismet.com/
ATW Show Posts (v.1.1) from wpweaver
	http://AspenThemeworks.com/atw-show-posts
BackWPup (v.3.1.4) from Inpsyde GmbH
	https://marketpress.com/product/backwpup-pro/
Hello Dolly (v.1.6) from Matt Mullenweg
	http://wordpress.org/plugins/hello-dolly/
Maintenance (v.2.4) from fruitfulcode
	http://wordpress.org/plugins/maintenance/
Slider WD (v.2.0.4) from WebDorado
	http://web-dorado.com/products/wordpress-slider-plugin.html
Weaver X Theme Support (v.0.97) from wpweaver
	http://weavertheme.com/plugins
Weaver Xtreme Plus (v.0.15) from Bruce Wampler
	http://plus.weavertheme.com
Wordfence Security (v.5.3.5) from Wordfence
	http://www.wordfence.com/
WYSIWYG Widgets / Widget Blocks (v.2.3.4) from Danny van Kooten
	http://DannyvanKooten.com/wordpress-plugins/wysiwyg-widgets/

**Comment by archetyped** [comment]
Thanks for the report.  I am looking into it and will update this ticket when I have more details.

**Comment by archetyped** [comment]
Hi, I've tested the Weaver Show Posts plugin with SLB and no issues were found.  Can you please provide some details on how you are using the Show Posts plugin when SLB stop working?

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
