### ISSUE TITLE
Protocol Relative URLs Supported?

### ISSUE THREAD

**Issue by kynetiv** [archetyped/simple-lightbox#342]
Hello,

I'm having issues with protocol relative urls for my images not displaying in the lightbox in WP 4.1.1 and SLB 2.3.1

For instance this
```<img src="//domain.com/wp-content/uploads/2015/02/logo.png">```

will give me an error of:

```http://domain.com/domain.com/wp-content/uploads/2015/02/logo.png Failed to load resource: the server responded with a status of 404 (Not Found)```

On the frontent, my html is generated like this:

```<a href="//domain.com/wp-content/uploads/2015/02/logo.jpg" data-slb-group="35" data-slb-active="1" data-slb-internal="0"><img class="aligncenter size-medium wp-image-20" src="//domain.com/wp-content/uploads/2015/02/logo-300x169.jpg" alt="logo" width="300" height="169"></a>```

Manually setting  ```data-slb-internal``` flag set to ```"1"``` didn't seem to help.

Any ideas? Thanks!

**Comment by archetyped** [comment]
Hi, relative and absolute URIs are currently supported.  Support for protocol-relative URIs has been added to the list for a future update.

**Comment by kynetiv** [comment]
Protocol relative URI support  appears to have been added in 2.4.1 release! Closing this out, thanks!
