### ISSUE TITLE
Issue: Simple Lightbox not displaying via HTTPS

### ISSUE THREAD

**Issue by mictho** [archetyped/simple-lightbox#343]
## Description of Problem
I have recently converted my site to default HTTPS, i.e. all pages are shown via HTTPS by default. No HTTP content. It works pretty well apart from images displayed via Lightbox. For some reason Lightbox is trying to load via HTTP, which causes a mixed content warning (HTTP and HTTPS on the same page, which is a security issue).

I'm also getting mixed content issues with my Theme, but I am not sure whether the two are related. 

## Details

My site is https://www.m-thomasius.co.uk. The main home page doesn't exhibit the issue, but some of the sub-pages do. For example https://www.m-thomasius.co.uk/wp/?p=2298

If you plug this URL into https://www.whynopadlock.com/check.php and run a test, it will list the various insecure items.

For example: 

http://www.m-thomasius.co.uk/wp/wp-content/plugins/simple-lightbox/client/js/dev/lib.core.js?ver=2.2.2
http://www.m-thomasius.co.uk/wp/wp-content/plugins/simple-lightbox/client/js/dev/lib.view.js?ver=2.2.2

and some others...

Do you have any idea what could be causing this? And what could I do to force the loading of the SLB assets via HTTPS? Can I edit one of the config files to force it?

* URL of Page exhibiting problem: See above
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: 2.3.1
* Other plugins installed: 
- Anti-spam by CleanTalk 4.18
- Force SSL URL Scheme 1.0.0
- Insert Headers and Footers 1.3.2
- SSL Insecure Content Fixer 1.8.0
- WordPress Simple Firewall 4.4.0

Many thanks and kind regards,

Michel

**Comment by mictho** [comment]
The issue is resolved! I have changed my theme to another one, and SLB now loads correctly via HTTPS.

**Comment by archetyped** [comment]
Hi, glad to hear your issue was resolved.  For reference, what theme were you using before that caused issues with SLB and HTTPS?
