### ISSUE TITLE
Captions sometimes not working

### ISSUE THREAD

**Issue by insightint** [archetyped/simple-lightbox#344]
## Description of Problem

It seems that sometimes when I add a photo to my homepage, the photo's caption doesn't show up when you click the image even though it is saved to the media file. I have formatted every image the same way so I am not sure why this is happening.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update the details of your issue so that I can take a closer look.

**Comment by insightint** [comment]
http://brightgreetings.com/ This is the site the error is occurring on. If you go to Blank Cards > Wisteria (not wisteria panel) when you click on the image, only the image number comes up, not the caption information as you will see if you click on any other card image. It seems to always happen with the most recent image added to the page but once you add another it sometimes acts fine and the caption does come up.
Brittney Dullin
Art Director

Visit us in person

3871 Harlem Road, Buffalo, NY 14215
brittney@insightinternationalusa.com
716.320.0501
Visit us online

   
Insight International USA, LLC is a Certified Women’s Business Enterprise in New York State.

This communication is from Insight International USA, LLC. is a registered company in New York, USA. Entire contents copyright Insight International USA, LLC © 2014. This communication and any attachments contain information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s).

**Comment by archetyped** [comment]
It appears that the Wisteria image is not recognized as part of WordPress' media library (where SLB pulls the image data from).  I would recommend confirming that this image is listed in WordPress' media library.  You may have to delete it from the media library, re-upload the image, and set the image's title so that WordPress can refresh the data in the media library.
