### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by Febz** [archetyped/simple-lightbox#346]
## Description of Problem
Hi, I would like to use the slb_group shortcode to group images linked in the woocommerce product short description, but it seems it doesn't even have the lightbox basic functions in it since it prints out the shortcode as text and when I click on the button that should trigger the lightbox it opens a new tab instead with just the image and nothing else. I've checked the options and lightbox was already enabled in woocommerce options, so I'm not getting why it works for the product image and not for the links in the product short description. 

## Details

* URL of Page exhibiting problem: http://www.testbusters.it/prodotto/teoriapraticarifinitura/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all of them
* Version of SLB Installed: Versione 2.3.1
* Other plugins installed: canvas theme, woocommerce

**Comment by archetyped** [comment]
Hi, the [WooCommerce add-on](http://archetyped.com/lab/slb-woocommerce-beta/ "WooCommerce add-on for SLB") is required for SLB to activate links in WooCommerce's content areas.
