### ISSUE TITLE
Lightbox makes Front End Editor problematic

### ISSUE THREAD

**Issue by Cuthulthor** [archetyped/simple-lightbox#347]
## Description of Problem

Hey,
I installed your Simple Lightbox Plugin for wordpress and are generally amazed about the usage und functionality.
But I'm sorry to tell, that I noticed an issues. Before I installed the WordPress Front-end Editor - but both work against each other now. 
Is it possible, to deactivate Simple Lightbox on Login mode?

Thank you very much!

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please fill in the details of the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
