### ISSUE TITLE
Request: customization of lightbox

### ISSUE THREAD

**Issue by civicsitedesign** [archetyped/simple-lightbox#348]
## Description of Problem
I have a client who wants some customization done to this plugin. He wants it to display a print button and an email or share button. Can you do this?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, unfortunately I am not currently available for custom development.  Add-ons may be available to provide the functionality you requested in the future, however.
