### ISSUE TITLE
Issue: ssl

### ISSUE THREAD

**Issue by Grimmwicht** [archetyped/simple-lightbox#349]
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by Grimmwicht** [comment]
Sorry, I opened this accidentally. But reading through the open cases, I was able to solve my problem. SLB did not work after changing the site to HTTPS. But after setting the site's url and wordpres url to HTTPS all worked well. Thank you.  :)

**Comment by archetyped** [comment]
Glad to hear you were able to find the solution to your issue :)
