### ISSUE TITLE
www.site.com/blog + <img src="/blog/img.jpg"> = "www.site.com/blog/blog/img.jpg"

### ISSUE THREAD

**Issue by whitetrefoil** [archetyped/simple-lightbox#351]
To reproduce:

1. set up a WP site at `www.site.com/blog`.
2. in the general options of WP, set both URL to `www.site.com/blog`.
3. upload an image.
4. post a blog with the linked image, use a site related path as the `src` & `href`.

```html
<a href="/blog/wp-content/uploads/img.jpg">
  <img src="/blog/wp-content/uploads/img.jpg" alt="alt" />
</a>
```

Then view that post, there should be a image displayed correctly, linked correctly (right-click -> open in new tab -> it works).  But if click that image, the lightbox will fail to load the image.  The dev tool shows a failed request to `www.site.com/blog/blog/wp-content/uploads/img.jpg`.

**/blog** is duplicated.

Here's one reproduction example: http://www.whitetrefoil.com/blog/?p=1670

**Comment by archetyped** [comment]
Hi, thank you for the report.  I am evaluating this now.
