### ISSUE TITLE
Issue: Clicking on image defaults to first image, closing opens last image

### ISSUE THREAD

**Issue by Richardfalconer** [archetyped/simple-lightbox#352]
## Description of Problem
Clicking on any image first image opens, closing image opens last image. 

## Details
Clicking on any image in the gallery on home page does the above. Creating other pages and same problems.

* URL of Page exhibiting problem: http://vineleafstandrews.co.uk/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Does the same in all browsers
* Version of SLB Installed: latest
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, thanks for the report.  I am taking a look at this now.

**Comment by archetyped** [comment]
The issue does not appear to be occurring any longer at the link provided.  If you are still experiencing this issue, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take another look.
