### ISSUE TITLE
Issue: qTranslate-X plugin problems

### ISSUE THREAD

**Issue by igoschia** [archetyped/simple-lightbox#354]
## Description of Problem
Hello simple-lightbox plugins does't works used with qTranslate-X plugin , doesnt works with other languages thai is not the default langiage.
qTranslate-X plugin is an update of the mqtranslate plugin ,with mqtranslate simple-lightbox works well but mqtranslate is out of date and does not support the latest versions of wordpress
 

## Details

* URL of Page exhibiting problem: http://www.romecentral.com/paranza-il-miracolo/?lang=en
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox
* Version of SLB Installed: last
* Other plugins installed:  qTranslate-X

**Comment by archetyped** [comment]
Hi, qTranslate X support has been suggested for a multilingual add-on to SLB.

Please see here for more information: [Add-on: Multilingual Support](205).
