### ISSUE TITLE
Issue: P3 Plugin

### ISSUE THREAD

**Issue by MrJoeG** [archetyped/simple-lightbox#359]
## Description of Problem: 

I am having issues and SLB seems to be seen as an issue using analyzing resources such as P3 Plugin Profile. My customer's site (http://beverleygolden.com) issue seems to be that the simple light box plugin take a few seconds to load up on the page and is taking up about 52% of runtime during a page load. Although, the plugin takes 1.2 to 2 seconds to fully load, I am getting notifications from my hosting server (via GoDaddy) that my resources are being utilized to almost 100% and I am encouraged to purchase additional hardware supplements like RAM or faster Processor speeds to accomodate for my resources. When the plug in is not running (disabled) my site uses about 240 MB out of 512MB and CPU usage ranges from 1-15%. 

Hopefully, there is some information you can provide me that will shed some light on my slow site load issues. Until then, I will continue to troubleshoot and see if I can provide additional details. 

## Details

* URL of Page exhibiting problem: http://beverleygolden.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome / Safari / IE (10/11)
* Version of SLB Installed: 2.3.1
* Other plugins installed: Various other plugins
* WP Version: 4.1.1
* jQuery version: 1.11.1 (used the archetype bookmarklet)

**Comment by archetyped** [comment]
Hi, improving SLB's performance is always a priority, so thank you for the feedback.  Unfortunately, P3 has never worked properly in our tests, so we cannot confirm your results.

SLB activates supported links on the current page, so the impact on a page's loading depends on how the number of links on a given page.  For example, a page with no image links (such as the home page) should barely be affected by SLB.  If you can provide a link to a specific page with links that are displayed in SLB, I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
