### ISSUE TITLE
Request: Disable SLB On-Demand

### ISSUE THREAD

**Issue by blompinnen** [archetyped/simple-lightbox#360]
## Description of feature/request
Hi.
I would like the possibility to temporarly disable simple-lightbox. If I use a gallery, two lightboxes will be used and that doesnt look to good. :(

Dont know if this function alredy exist, read all the documentation I could find. But it doenst look to hard to be able to create a shortcode (like [disable-slightbox] so we could temporarly disable the function for a single page/post?

Or do you know any other way to fix this "problem"

## This feature would be used to
when a post also uses a gallery which has lightbox or similar included, so it wouldnt be double

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, you can use SLB's `[slb_exclude]` shortcode to exclude specific parts of a page or post from being activated.

More details here: [SLB Shortcodes](../wiki/Shortcodes)
