### ISSUE TITLE
Following single image to gallery instructions.

### ISSUE THREAD

**Issue by jtc242** [archetyped/simple-lightbox#361]
## Description of Problem
Instructions work perfectly save for a wrench I am throwing into it. I want to use a completely different image than one that is in the gallery. Works but adds first gallery image twice. If you know how I can do this I would be forever grateful. End result would be to have page full of company logos that link to separate galleries of client work. I really appreciate your thoughts/opinions on this.

## Details

* URL of Page exhibiting problem: 
http://dev.beanedesign.com/?page_id=639
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 2.31
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, you can use SLB's `[slb_group]` shortcode to group the standalone link and the gallery into the same group.

See the documentation in the wiki for more information: [SLB Shortcodes](../wiki/Shortcodes)

**Comment by jtc242** [comment]
Thanks :-) Works perfect.
