### ISSUE TITLE
Request: theme support

### ISSUE THREAD

**Issue by ryplay** [archetyped/simple-lightbox#362]
## Description of feature/request
It would be great if SLB can utilize font from actual site theme

## This feature would be used to
It would be great if SLB can utilize font from actual site theme

## If you added this feature, I would:

c) Shave my cat

**Comment by archetyped** [comment]
Hi, most themes use different fonts, so it would be difficult for SLB to determine *which* font you would like it to use automatically.

Thankfully, SLB supports fully customized themes, allowing you to specify the font(s) the theme uses.   Here's [a guide on customizing SLB themes](http://archetyped.com/know/slb-theme-anatomy/).  The guide also contains a downloadable starter theme that you can use to create your own custom theme.
