### ISSUE TITLE
Request: Display data above image and select data to display

### ISSUE THREAD

**Issue by geo2arc** [archetyped/simple-lightbox#363]
## Description of feature/request

a) Add option to select if data is displayed above or below image.
b) The data displayed now are caption and description. I would like to add title, and select which of the three data (title / caption / description) are visible in the lightbox.

## This feature would be used to

Improve user experience when viewing portrait images and lightbox size is not adjusted to screen (so that portrait images are viewed full size and not shrunk). Now, viewer has to scroll down the image to see its data. Placing them above the image will be easier to view.

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, SLB supports fully-customizable themes so you can design a theme for your specific needs.

To get you started, here's [a guide on customizing SLB theme layouts](http://archetyped.com/know/slb-theme-layout/).
