### ISSUE TITLE
Issue: Using SLB

### ISSUE THREAD

**Issue by igrafiq** [archetyped/simple-lightbox#364]
## Description of Problem

Hi, 

I do not know why but the pluging does not work. I test it with and without other plugins with the same effects.

I would like yo hace the name in portfolio as hover option. I would like to have nex/revius buttons.
I check the settins and they look ok, so........

Any suggestion?

## Details

* URL of Page exhibiting problem: ahdesign.es
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.3.1
* Other plugins installed: no,

**Comment by archetyped** [comment]
Hi, please fill in the details of your support request (URL, browser, etc.) and i would be glad to take a closer look.

**Comment by archetyped** [comment]
Hi, SLB appears to be functioning properly at the site you provided.

If you are still experiencing an issue, please provide more details and I will reopen this ticket and take another look.
