### ISSUE TITLE
Help on strict standards warnings

### ISSUE THREAD

**Issue by szepeviktor** [archetyped/simple-lightbox#365]
Good morning!

I see you are getting more report about this on WP.org and here.
Could I you help in the development? I can provide you PHP 5.6 test evironment.
I think we should face that code must change with modern PHP decisions.
How can I help you?

**Comment by szepeviktor** [comment]
E.g. to temprarly silence a warning:
class.field_base.php / format()
`if ($context === array()) $context='';`

**Comment by archetyped** [comment]
Hi, you can [download SLB 2.4.0 RC1](../releases/tag/2.4.0-rc1), which should resolve these issues.

The official release will follow soon, so please add your feedback and report any issues in [SLB's official support forum](../wiki/Feedback-&-Support).

Thanks.

**Comment by szepeviktor** [comment]
Thank you.
