### ISSUE TITLE
WP script handling

### ISSUE THREAD

**Issue by szepeviktor** [archetyped/simple-lightbox#366]
Script printing (echoing) may stop users optimizing your output.
Please consider separating your Javascripts:

- code - `wp_enqueue_script()`
- data - `wp_localize_script()`

I would be gladly to help in this.

**Comment by szepeviktor** [comment]
This way WP will *know* about your scripts, and can handle merging and minifying your output.

**Comment by archetyped** [comment]
Hi, SLB does indeed use WP's API for loading scripts.

**Comment by szepeviktor** [comment]
@archetyped I am thinking about this script printing:
https://github.com/archetyped/simple-lightbox/blob/29a9cc55fda3a9475ba1bdf573a07f9fa0f05fba/includes/class.utilities.php#L504
It could be `wp_localize_script` if you develop full data-code separation.

**Comment by archetyped** [comment]
That code is used to load dynamically-generated output in the client.  When SLB needs to output localized strings to the client, `wp_localize_script()` will be used, but currently, there are no localized strings sent to the client.

**Comment by szepeviktor** [comment]
I suggest to use `wp_localize_script()` for *all* your plugin's data needs. As this function - I think - is mainly not for localization:

> Though localization is the primary use, it can be used to make any data available to your script that you can normally only get from the server side of WordPress.

**Comment by szepeviktor** [comment]
That would raise the plugin's WordPress comformance.
