### ISSUE TITLE
Lightbox not working

### ISSUE THREAD

**Issue by igrafiq** [archetyped/simple-lightbox#367]
http://www.ahdesign.es/packaging-3/

I would like to see snext and previous narows but i do not why i can see them. The same with portfolio item name.

Versión 2.3.1
plugings: EWWW Image Optimizer, Final Tiles Grid Gallery Lite. Instagram Feed, Polylang, Under Construction

**Comment by archetyped** [comment]
Hi, navigation arrows are displayed in the lightbox when there are multiple images on the page.

Example: http://www.ahdesign.es/187/

The portfolio items titles should be displayed, but it appears that SLB's CSS styling has been modified and thus the titles are being hidden.  Did you download SLB from [WordPress' official plugin repository](https://wordpress.org/plugins/simple-lightbox/)?

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please let me know what you found regarding the notes in my previous post and I would be glad to take another look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
