### ISSUE TITLE
Issue: Lightbox fails to open when images clicked

### ISSUE THREAD

**Issue by joshnya89** [archetyped/simple-lightbox#368]
## Description of Problem

Hi, awesome little plugin. However, I recently tried activating Wordpress's Jetpack feature called "Photon" and it completely prevented the lightbox from performing at all. I just wanted to mention it in the hopes that it will get on a list of future update fixes. 

Thanks and keep up the good work!

Regards,
Josh

## Details

* URL of Page exhibiting problem: http://whistlehillnursery.com/black-eyed-susan/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.3.1
* Other plugins installed: a lot

**Comment by archetyped** [comment]
Hi, please see [this existing ticket](33) for more information on support for Jetpack Photon and other CDNs.

Thanks.

**Comment by joshnya89** [comment]
Thanks!

Josh
