### ISSUE TITLE
Lightbox only works on subpages

### ISSUE THREAD

**Issue by andreas83** [archetyped/simple-lightbox#369]
jQuery version: 1.11.2
Template: emulate
Wordpress: 4.2.2

Demo: http://linearis.moving-bytes.at

Working subpage example:
http://linearis.moving-bytes.at/testseite/

Not a browser related issue.

Tried slb_activate() on the_content() in page.php

**Comment by andreas83** [comment]
I fiigured out, it works when i change the priority in _hooks_init() to 9

add_filter('the_content', $this->m('activate_links'), 1);

**Comment by archetyped** [comment]
Hi, editing SLB's code should not be necessary (and will also be overwritten with any future updates).

Can you please provide a bit more detail on what you're trying to do?  Using `slb_activate()` on `the_content()` is not necessary.

**Comment by andreas83** [comment]
The problem was, slb only worked on subpages, but not on frontpage, changing the priority solved this issue for me. 

iam pretty sure its a template issue, if you need further details, i could provide a test installation.

**Comment by archetyped** [comment]
Hi, if you can provide the template markup you're using in `page.php`, I would be glad to take a closer look for any issues.

**Comment by andreas83** [comment]
Hope this helps:
http://pastebin.com/2Ngb12FE

**Comment by archetyped** [comment]
Thanks.  Nothing seems amiss with the template markup, but I'll let you know if I find anything in the future.

BTW, is this a custom template file or the default markup from a specific theme?
