### ISSUE TITLE
Issue: SLB not working on WP 4.2.2

### ISSUE THREAD

**Issue by Verticalx** [archetyped/simple-lightbox#370]
## Description of Problem

SLB is not working with Wordpress 4.2.2 with no plugins installed with default theme.
Check this out: http://verticalx.url.ph. On this site only plugin is loaded is SLB.

I also tried switching on plugins and with my other websites. Plugin is not working at all.

I also checked jQuery and seems no problems with that. My version is 1.11.2

## Details

* URL of Page exhibiting problem: squadmag.ru, verticalx.url.ph
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Checked in Safari, Firefox, Chrome
* Version of SLB Installed: 2.3.1
* Other plugins installed: None

**Comment by archetyped** [comment]
Hi, SLB appears to be working properly at the link you provided.  If you are still experiencing this issue, please provide some details on when SLB is not working and I would be glad to take another look.
