### ISSUE TITLE
Issue: SLB not working after Duplicator move to another address

### ISSUE THREAD

**Issue by obgc** [archetyped/simple-lightbox#371]
Hi,

I hope I have checked everything possible before writing here. I had prepared a properly working website with SLB (sample page: http://wp.complit-solution.de/loesungen/business-intelligence/wirtschaftsplan/). [Wordpress 4.2.2, spyropress porto commercial theme, SLB version 2.3.1)

For production I was supposed to move it to another address: http://www.complit-solution.de/loesungen/business-intelligence/wirtschaftsplan/
I used Duplicator pluging for that and after the movement I noticed that SLB stopped working. Please check images shown under "Einblicke" on the pages mentioned above.

I tried switching theme to 2015 and turning off other plugins. The development site (wp.complit-....) works fine (also with theme 2015) but the production one - does not.

Any ideas what happened and why it stopped working?

Thanks
Greg

* URL of Page exhibiting problem: http://www.complit-solution.de/loesungen/business-intelligence/wirtschaftsplan/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all (FF, Chrome, IE)
* Version of SLB Installed: 2.3.1
* Other plugins installed: Duplicator, Breadcrumb NavXT, Contact Form 7, Custom Sidebars, Google Analytics by Yoast, WordPress SEO, WP Maintenance Mode (but after switching them off it still doesn't work).

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled or properly configured for PHP on the production server.  Please see [SLB's minimum requirements](../wiki/Requirements) for more information regarding cURL support.

**Comment by obgc** [comment]
It's on the same server. Is it possible that one site one the same server works properly and the other casuses problems? Can cURL be configured differently on the same server?

**Comment by archetyped** [comment]
Hi, I would recommend contacting your host to check on these things as it can depend on how they've set things up.

**Comment by obgc** [comment]
Thanks! Restore on another hosting platform shown that everything is fine so you're right - probably there is something wrong with the server configuration itself.
Thanks

**Comment by archetyped** [comment]
Glad to hear you've narrowed down the issue!
