### ISSUE TITLE
Issue: Featured images

### ISSUE THREAD

**Issue by auzhost** [archetyped/simple-lightbox#372]
Why is this plugin not putting Featured images in to a lightbox.?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your ticket with the requested details (url, browser, etc.) and I would be glad to take a look.

Thanks.

**Comment by auzhost** [comment]
This page here has a FI Image. http://ctry.biz/services/web-site-building/
The problem is not browser dependant, consistant on all.
Current version of SLB asd you can see from attached image

![ashampoo_snap_2015 05 15_12h02m23s_001_plugins - jch computers - wordpress - mozilla firefox](https://cloud.githubusercontent.com/assets/12439289/7645584/63f5ff0c-fafa-11e4-8046-80d5b0282992.png)

**Comment by archetyped** [comment]
Thank you.  SLB automatically activates post content output by `the_content()`.  Other links can be activated manually using `slb_activate()`.

More information: [Using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/).

**Comment by auzhost** [comment]
I have no idea what this is supposed to mean. Please explain.
![ashampoo_snap_2015 05 16_09h45m47s_001_lightbox settings - jch computers - wordpress - mozilla firefox](https://cloud.githubusercontent.com/assets/12439289/7663623/8f6acf80-fbb0-11e4-8e59-943bd0a0dce0.png)

**Comment by archetyped** [comment]
Hi, you will need to edit your theme and use the `slb_activate()` template tag to manually activate the featured image link.  Instructions for using `slb_activate()` are in my previous comment.
