### ISSUE TITLE
SLB core files not included in the page source

### ISSUE THREAD

**Issue by obgc** [archetyped/simple-lightbox#375]
Hi,

What can be the cause of not including SLB core files on my pages?
I mean the files shown below and further inline scripts:

```
type='text/javascript' src='/wp-content/plugins/simple-lightbox/client/js/prod/lib.core.js?ver=2.3.1
type='text/javascript' src='/wp-content/plugins/simple-lightbox/client/js/prod/lib.view.js?ver=2.3.1
type='text/javascript' src='/wp-content/plugins/simple-lightbox/themes/baseline/js/prod/client.js?ver=2.3.1
type='text/javascript' src='/wp-content/plugins/simple-lightbox/themes/default/js/prod/client.js?ver=2.3.1
type='text/javascript' src='/wp-content/plugins/simple-lightbox/template-tags/item/js/prod/tag.item.js?ver=2.3.1
type='text/javascript' src='/wp-content/plugins/simple-lightbox/template-tags/ui/js/prod/tag.ui.js?ver=2.3.1
type='text/javascript' src='/wp-content/plugins/simple-lightbox/content-handlers/image/js/prod/handler.image.js?ver=2.3.1
```

## Details

http://www.complit-solution.de/loesungen/business-intelligence/mis-management-informationssystem/
All browsers
SLB v2.3.1
Spyropress Porto commercial theme.

It worked some minutes ago and then ... stopped. Suddenly.

**Comment by obgc** [comment]
I noticed one more issue. On another page the core files are being included but SLB still doesn't work. What I found that there is this one difference in the generated online js:

                    "layout_raw": "<div class=\"slb_container\"><div class=\"slb_content\">{{item.content}}<div class=\"slb_nav\"><span class=\"slb_prev\">{{ui.nav_prev}}<\/span><span class=\"slb_next\">{{ui.nav_next}}<\/span><\/div><div class=\"slb_controls\"><span class=\"slb_close\">{{ui.close}}<\/span><span class=\"slb_slideshow\">{{ui.slideshow_control}}<\/span><\/div><div class=\"slb_loading\">{{ui.loading}}<\/div><\/div><div class=\"slb_details\"><div class=\"inner\"><div class=\"slb_data\"><div class=\"slb_data_content\"><span class=\"slb_data_title\">{{item.title}}<\/span><span class=\"slb_group_status\">{{ui.group_status}}<\/span><div class=\"slb_data_desc\">{{item.description}}<\/div><\/div><\/div><div class=\"slb_nav\"><span class=\"slb_prev\">{{ui.nav_prev}}<\/span><span class=\"slb_next\">{{ui.nav_next}}<\/span><\/div><\/div><\/div><\/div>"

This part is absent on the site where it doesn't work. Is that information helpful?

**Comment by archetyped** [comment]
Hi, that link is returning a 404 error (page not found).  Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by obgc** [comment]
Hi,
We switched DNS addresses two days ago. Maybe flushing DNS will help? Or we need to wait some more hours for the DNS to spread all around the world. Please check now.

**Comment by archetyped** [comment]
Hi, I was able to get a look at the page after a couple days.  The issue may be caused by the way the theme is loading the content.  Can you please post the page template from your theme that is used to display this page, so that I can see if there are any issues?

Thanks.

**Comment by obgc** [comment]
I hope this will be enough. http://www.complit-solution.de/theme.zip
Please let me know.
Thx.

**Comment by archetyped** [comment]
Hi, unfortunately the download does not appear to contain the entire theme.  The template calls a function called `spyropress_the_content()`.  Does your theme use a parent theme or separate plugin?  If so, I'll need to take a look at it to investigate further.

Alternatively, you can contact the theme's developers to inquire whether the theme meets [SLB's minimum requirements](../wiki/Requirements).

**Comment by obgc** [comment]
Hi,

That's a commercial theme and I do not want it to be published fully with the source code. Is there a place where I can send the theme only for you and only for the purposes of analyzing the problem?

Thx

**Comment by archetyped** [comment]
Hi, as I am unable to access commercial themes, I would recommend contacting the theme's developer to check if the theme meets [SLB's minimum requirements](../wiki/Requirements).
