### ISSUE TITLE
Issue: updating wordpress made plugin inactive

### ISSUE THREAD

**Issue by mijavera** [archetyped/simple-lightbox#377]
## Description of Problem

Just updated wordpress database and all of my plugins. Now Simple Light Box is inactive.

## Details

* http://malice.honey-vanity.net 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Safari
* Version of SLB Installed:  2.3.1
* Other plugins installed: Akismet, Contact Form 7, Easy Gravatars, Gravatar Signup, Limit Login Attempts, LiveJournal Crossposter, Subscribe2, Subscribe to comments, Symple Shortcodes, Wordpress Thread Comment and WP Post Signature

**Comment by archetyped** [comment]
Hi, SLB appears to be working properly at the link you provided.  If you are still experiencing this issue, I would recommend checking your site on a different computer to ensure that the issue is not being caused by your computer.  Clearing your browser's cache may help as well.
