### ISSUE TITLE
Reposition the close button

### ISSUE THREAD

**Issue by fduraibi** [archetyped/simple-lightbox#379]
Can you make an option to allow us to reposition the close button? I would like to move it down to the white area outside the image since it kinda interfere with the content of some images (see attached image)
Also i would love to have another option to hide/not show the slideshow button

![lightbox](https://cloud.githubusercontent.com/assets/432460/7786535/a6c14aa8-01a3-11e5-8ed8-8f7f057f191e.png)

**Comment by archetyped** [comment]
Hi, SLB's appearance is completely customizable using themes.  You can even create child themes from existing themes and just modify the features you want to.

Here are some resources to get you started on working with themes in SLB:

* [Anatomy of a theme](http://archetyped.com/know/slb-theme-anatomy/) - a quick breakdown of a theme's components, including how to create a child theme.
* [Customizing theme layouts](http://archetyped.com/know/slb-theme-layout/) - details on theme layouts and template tags
