### ISSUE TITLE
How to disable the title in lightbox

### ISSUE THREAD

**Issue by Norm4u** [archetyped/simple-lightbox#380]
## I am not able to disable the title in the lightbox.
The setting says "Enable default title (Default: Disabled)". If I check or uncheck nothing happens.

I only want to display item 1 of 40

What can I do?

## Details

* http://www.equicaption.nl/stal-groenendaal-knhs-pony-springen-9-mei-2015/

**Comment by archetyped** [comment]
Hi, the default title option tells SLB whether to display the titles automatically-generated by WordPress when a custom title has not been set.

All features of the lightbox are controlled via themes.  You can create your own lightbox theme to show or hide information.

See this tutorial for more information on themes: [Simple Lightbox: Anatomy of a Theme](http://archetyped.com/know/slb-theme-anatomy/ "Simple Lightbox: Anatomy of a Theme")
