### ISSUE TITLE
Issue: SLB works locally, but not on dev site

### ISSUE THREAD

**Issue by mysticalone** [archetyped/simple-lightbox#381]
## SLB not working on Dev site, works fine locally

Simple Lightbox works locally, but does not work on the development website. Plugins are all the same, files are all the same. The only difference is PHP on the development site is 5.4.39

On the dev site, the image links have an extra data attribute, data-slb-internal="0"

## Details

* URL of Page exhibiting problem: http://www2.uspalm.com/cynology-war-labs-photoshoot-outtakes/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All 
* Version of SLB Installed: 2.3.1
* Other plugins installed: WooCommerce, Advanced Custom Fields, Constant Contact by Katz, Simple Page Sidebars, Synchi, updraft, WonderPlugin Slider

**Comment by archetyped** [comment]
Hi, Simple Lightbox does not appear to be installed or activated at the link you provided.

Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by mysticalone** [comment]
I have re-enabled the plugin on the reported page.

**Comment by archetyped** [comment]
Hi, it appears that cURL may not be enabled on your Dev site, which WordPress needs for functions that SLB uses.

See here for more information [SLB's minimum requirements](../wiki/Requirements), including cURL support.
