### ISSUE TITLE
Goes directly to image rather than opening lightbox

### ISSUE THREAD

**Issue by superghostmaster** [archetyped/simple-lightbox#382]
ONLY if I have an image link IN a post does this plugin do anything. 

I've tested with multiple/default themes.

I don't expect to get an actual response other than "theme conflict" or "plugin conflict" like Mr. Archetype has posted to every fucking response on WP.org, so I'm just letting you know your plugin doesn't load jQuery at the proper time in the head in the latest version of WP.

It's pretty worthless if it only works on default WP themes, anyway.

Don't bother responding, just fix this shit and quit denying your plugin is broken.

**Comment by archetyped** [comment]
Hi, SLB works specifically on links within post/page/widget content.  You can also use `slb_activate()` to manually activate links outside of these content areas ([more information on using `slb_content()`](http://archetyped.com/lab/slb-2-3-0/)).

It sounds like you're wanting a different type of functionality, so I hope you find a plugin that meets your needs.  Have a nice day :)
