### ISSUE TITLE
Issue: Simple Lightbox does not work in Advanced Custom Fields

### ISSUE THREAD

**Issue by sunni77** [archetyped/simple-lightbox#383]
## Description of Problem:

Images placed in advanced custom fields (such as tabs) do not open in Lightbox.  Simple Lightbox applies attributes to images but those same attributes are for some reason not applied when an image is added to an advanced custom field. 

## Details

* http://www.traveloffthebeatenpath.com/provence-tour-itinerary
* All browsers
* current most up-to-date version 
* Other plugins installed:  Advanced Custom Fields

**Comment by archetyped** [comment]
Hi, SLB automatically activates links in post/page/widget content.  Links outside of these content areas can be manually activated using `slb_activate()` ([more information on using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/)).

**Comment by sunni77** [comment]
Thank you for the very helpful link however, forgive me, but where exactly do I PUT this code you are referring to??



On Jun 2, 2015, at 4:11 PM, Archetyped <notifications@github.com> wrote:

Hi, SLB automatically activates links in post/page/widget content. Links outside of these content areas can be manually activated using slb_activate() (more information on using slb_activate()).

**Comment by archetyped** [comment]
Hi, you would most likely edit your theme's template files where you've added the ACF code to also use `slb_activate()`.
