### ISSUE TITLE
Abs pos images rearrange in Chrome on slb close or open

### ISSUE THREAD

**Issue by webconstructor** [archetyped/simple-lightbox#384]
## Description of Problem
When opening or closing the lightbox in Chrome on http://sampost.nl/products/ the lightbox opens but disturbs the absolute vertical positioning of the image just clicked on. 
Sometimes it's on opening: upper right. 
Sometimes on closing i.e. second row left.
You can actually see it happen if you concentrate on the background behind the opening screen.
I'ld love to hear the cause.

## Details

* URL: http://sampost.nl/products/
* Browser: Chrome only
* Version of SLB Installed: 2.4.0 
* Other plugins installed: WP super cache

**Comment by archetyped** [comment]
Hi, it appears that your theme may not meet [SLB's minimum requirements](../wiki/Requirements).  Let me know if you are still having issues after you have reviewed the requirements and updated the theme if necessary.

**Comment by webconstructor** [comment]
Minimum requirements were perfectly met. I found the issue: https://twitter.com/inigogrimbergen/status/606114592666882048 and fixed it.
