### ISSUE TITLE
Issue: SLB not working

### ISSUE THREAD

**Issue by starfox221** [archetyped/simple-lightbox#385]
## Description of Problem
Lightbox isn't loading correctly. I've dropped image files in but each time it just goes to the image file link, not the lightbox. I've disabled all non-necessary plugins, even switched themes. Not sure what else to do. 

## Details

* URL of Page exhibiting problem: http://spagfinder.com/?s=fleece  
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: Latest
* Other plugins installed: Search Everything, Hupso Share Buttons, Excerpts

**Comment by archetyped** [comment]
Hi, please check to ensure that your theme meets [SLB's minimum requirements](../wiki/Requirements).  If SLB is not working with a default WP theme, please enable a default theme (e.g. Twenty-Fourteen), and I would be glad to take another look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
