### ISSUE TITLE
Spare one HTTP request

### ISSUE THREAD

**Issue by szepeviktor** [archetyped/simple-lightbox#387]
Is it possible to avoid this HTTP request?
`wp_safe_remote_get()` at https://github.com/archetyped/simple-lightbox/blob/master/includes/class.base_object.php#L254

I think one HTTP request is very expensive for a local file:
```
1.2.3.4 - - [13/Jun/2015:13:53:02 +0200] "GET /wp-content/plugins/simple-lightbox/themes/baseline/layout.html HTTP/1.0" 200 1028 "-" "WordPress/4.2.2; http://site.hu" "-"

```

**Comment by archetyped** [comment]
Hi, not all WordPress installations store plugin files locally, so `wp_safe_remote_get()` provides the necessary compatibility for all installations.

Performance is constantly being optimized though, so if performance can be improved for local files without affecting compatibility, it will be added to a future update.

**Comment by szepeviktor** [comment]
Could you clarify what does "not-local" mean for plugins?
