### ISSUE TITLE
Issue: When on CDN, the lightbox stops working.

### ISSUE THREAD

**Issue by Geobusteni** [archetyped/simple-lightbox#388]
## Description of Problem

Activating CDn causes the lightbox to stop working

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it looks like you found the [existing ticket for the CDN add-on](33).  Please refer to that ticket for future updates.

Thanks.
