### ISSUE TITLE
Updating simple-lightbox from 2.3.1 causes white screen of death

### ISSUE THREAD

**Issue by lppdev** [archetyped/simple-lightbox#389]
## Clicking 'update now' for simple-lightbox 2.3.1 in list of plugins causes white screen of death with WordPress version 4.2.2

I'm using PixelPress theme (theme forest) with paidmembershippro and woocommerce standard plugins.

## Details

* URL of Page exhibiting problem: https://gritsgobang.org
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome/IE/Safari/etc...
* Version of SLB Installed: 2.3.1
* Other plugins installed: 
paid-memberships-pro | 
pmpro-bbpress | 
pmpro-customizations | 
pmpro-email-confirmation-master | 
pmpro-email-templates-addon | 
pmpro-mailchimp | 
pmpro-register-helper | 
pmpro-roles-master | 
pmpro-woocommerce | 
s3bubble-amazon-s3-audio-streaming | 
save-with-keyboard | 
simple-lightbox | 
spider-event-calendar | 
stripe-for-woocommerce | 
the-events-calendar | 
theme-my-login | 
vanilla-pdf-embed | 
whats-new | 
woocommerce | 
woosidebars
woothemes-updater | 
wp-bouncer | 
wp-force-https | 
wp-smushit | 
index.php | 
accordions | 
agreeable | 
bbpress | 
bbpress-notify-nospam | 
bnfw | 
css-javascript-toolbox | 
custom-functions | 
custom-menu-wizard | 
dynamic-dates | 
dynamic-widgets | 
gd-bbpress-tools
google-analytics-dashboard-for-wp | 
hide-admin-bar-from-non-admins | 
insert-pages | 
jquery-ui-widgets | 
notify-users-e-mail | 
oa-social-login | 
page-links-to

**Comment by archetyped** [comment]
Hi, as there appear to be some paid plugins, I am unable to fully replicate and test your issue.  If you are still having an issue updating SLB, I would recommending removing and re-installing the latest version of SLB: https://wordpress.org/plugins/simple-lightbox/
