### ISSUE TITLE
Issue: SLB 2.4.0 not working with IE8

### ISSUE THREAD

**Issue by sfranzis** [archetyped/simple-lightbox#390]
## Description of Problem
SLB 2.4.0 does not work with IE8, Image is shown in a new page instead of the lightbox.
I deactivated all other plugins, changed to a default design, no change.
In Developer tools it shows an error "object doesn't support this property or method" in client/js/prod/lib.view.js?ver=2.4.0

## Details
* URL of Page exhibiting problem: http://www.medica-natura.de/?page_id=7
* Browser(s) exhibiting problem: IE8 
* Version of SLB Installed: 2.4.0
* WP Version 4.2.2
* Other plugins installed: Contact Form 7

**Comment by archetyped** [comment]
Thanks for the report.  I am looking into this.

**Comment by archetyped** [comment]
This bug has been fixed an will be included in the next update.  Thanks again @sfranzis :)
