### ISSUE TITLE
Request: HTML content

### ISSUE THREAD

**Issue by grem001** [archetyped/simple-lightbox#393]
## Description of feature/request
Can I have a website in lightbox ? I would like to have a google map opened in lightbox

## This feature would be used to
Open an url in lghtbox like googlemap

## If you added this feature, I would:
e) kiss your ass

**Comment by archetyped** [comment]
Hi, thanks for the request.  Support for additional types of content are provided via add-ons.  Please add your vote and comments to the [HTML add-on ticket](394).

Thanks.
