### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by pudDesign** [archetyped/simple-lightbox#395]
hi I'm using cloudfront CDN but this has stopped the lighbox working, is there as fix for this?

http://donquixote.co.uk/project/welsh-elements-3-watercolour-68-x-50cm/

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please add your vote for the CDN you would like supported by SLB at the [existing ticket for the CDN add-on](33).

Thanks.
