### ISSUE TITLE
Issue: Videos in widgets 

### ISSUE THREAD

**Issue by ksadityan** [archetyped/simple-lightbox#396]
Videos in widgets do not open in lightbox. I have enabled for widgets in the activation section of settings.

## Details

* URL of Page exhibiting problem: http://smartweldingmanager.com/contact-us/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Both
* Version of SLB Installed: Latest
* Other plugins installed: No other lightbox plug-in

![image](https://cloud.githubusercontent.com/assets/8672443/8492455/a275274c-2167-11e5-8ce0-3eb2e56d4d59.png)

**Comment by ksadityan** [comment]
I have HB Highend theme installed

**Comment by archetyped** [comment]
Hi, I see embedded video players in the sidebar at the link you provided, but no links to videos.  SLB is activated when a link is clicked.  See [the quick-start guide](http://archetyped.com/know/simple-lightbox-for-noobs/) for more information on using SLB.

Also, SLB requires the [video add-on](http://archetyped.com/lab/slb-video-addon-beta/ "video add-on") to display videos in the lightbox.
