### ISSUE TITLE
Scrolling while lightbox is open

### ISSUE THREAD

**Issue by franga2000** [archetyped/simple-lightbox#397]
## Description of Problem
When a lightbox is open, you can still scroll the page.

## Details

* URL of Page exhibiting problem: http://dev.franga2000.com/mirko/2015/07/07/vlc/#pretvorba-videa
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All of them. (Tested in Chrome and Firefox)
* Version of SLB Installed: 2.4.0
* Other plugins installed: TinyMCE Advanced (not the cause)

## Fix
Add the CSS property `overflow: hidden;` to `html` while the lightbox is open.

**Comment by archetyped** [comment]
Hi, scrolling is enabled to allow the entire lightbox to be viewed when the content is larger than the browser window (e.g. large images, long captions/descriptions, etc.).

**Comment by franga2000** [comment]
Well couldn't you do a check like this? I'd make a PR, but I don't have the time to find where in the code to put this.
```js
if ($(".slb_viewer_layout").height() < $(window).height()) {
    $("html").css("overflow", "hidden"));
}
```

**Comment by rubymused** [comment]
I'm also looking to disable scrolling when the lightbox is open. I see this request has duplicates, but as far as I can tell no change in implementation (or intention to do so?) I'm wondering if the original poster's question has been answered as to how one would solve this oneself: "could I achieve this by adding similar code [here](https://github.com/archetyped/simple-lightbox/blob/5c24a692081c6f9a936f975150d50f45294512ce/themes/default/js/dev/client.js#L13) and [here](https://github.com/archetyped/simple-lightbox/blob/5c24a692081c6f9a936f975150d50f45294512ce/themes/default/js/dev/client.js#L53)?If you don't decide to implement this, could I achieve this by adding similar code [here](https://github.com/archetyped/simple-lightbox/blob/5c24a692081c6f9a936f975150d50f45294512ce/themes/default/js/dev/client.js#L13) and [here](https://github.com/archetyped/simple-lightbox/blob/5c24a692081c6f9a936f975150d50f45294512ce/themes/default/js/dev/client.js#L53)?If you don't decide to implement this, could I achieve this by adding similar code [here](https://github.com/archetyped/simple-lightbox/blob/5c24a692081c6f9a936f975150d50f45294512ce/themes/default/js/dev/client.js#L13) and [here](https://github.com/archetyped/simple-lightbox/blob/5c24a692081c6f9a936f975150d50f45294512ce/themes/default/js/dev/client.js#L53)?"
