### ISSUE TITLE
Issue: Disable 'next' and 'back' links in opened lightbox

### ISSUE THREAD

**Issue by ATappman** [archetyped/simple-lightbox#398]
## Description of Problem

I would like to remove the 'back' link from the left side of the lightbox display window, and the 'next' link from the right side. How can I accomplish this?

* Version of SLB Installed: 2.4.0

**Comment by archetyped** [comment]
Hi, SLB's themes are fully customizable using HTML and CSS.   Here are a few tutorials to get you started:

* [Anatomy of a SLB theme](http://archetyped.com/know/slb-theme-anatomy/ "Anatomy of a SLB theme")
* [Customizing SLB theme layouts](http://archetyped.com/know/slb-theme-layout/ "Customizing SLB theme layouts")
* [Customizing SLB theme styles](http://archetyped.com/know/slb-theme-styles/ "Customizing SLB theme styles")
