### ISSUE TITLE
Simple Lightbox dont working on theme Falcon Magazine ver.1.5

### ISSUE THREAD

**Issue by Anderor** [archetyped/simple-lightbox#399]
Error is in template "Falcon Magazine". Under TwentyThirteen everything goes right.

## Details

* http://lcinfo.sk/test/
* Chrome v.43.0.2357.134, Firefox 38.0
* Version of SLB Installed:  2.4.1
* Other plugins installed: theme Falcon Magazine ver.1.5, Awesome Weather Widget 1.5.2, Easy MailChimp Forms 5.4.3, Google Analytics Dashboard for WP 4.8.1.2, Google Tag Manager for Wordpress 1.1.1,

**Comment by archetyped** [comment]
Hi, as noted on [WordPress' forums](https://wordpress.org/support/topic/slb-is-broken), I would recommend contacting the theme's developers regarding the error, as they would have the best knowledge on resolving it.

Thanks.
