### ISSUE TITLE
Breaks when port number is specified in the URL

### ISSUE THREAD

**Issue by rkeplin** [archetyped/simple-lightbox#400]
This plugin does not work when hosting on port 8080.  This is an issue whenever any port is specified in the URL.  I assume it has something to do with the colon being in the url.

I don't have a website hosted anywhere under port 8080 in production, but locally it is very easy to reproduce the issue.

Plugin works:
 http://127.0.0.1/2015/07/21/hello-world/

Plugin does not work under same exact setup, except different port number:
 http://127.0.0.1:8080/2015/07/21/hello-world/

**Version of Wordpress Installed:** 4.2.2
**Version of SLB Installed:** 2.4.1
**Other plugins installed:** none
**Theme:** twentyfifteen
**Browser:** Chrome Version 43.0.2357.134 m (64-bit)

**Comment by archetyped** [comment]
Thanks for the report.  I will look into this.

**Comment by Emulator000** [comment]
Hi archetyped,
I have a similar issue about this.

In my local environment all is working fine.
I cloned the site in a DEV space and all is working fine exept for your Plugin.

For some reason, all is loading (I mean, script is loading and DOM is modified []) but when I click on one Image, the Lightbox doesn't show up and the JPG is loaded directly in the Browser.

Very annoying thing, did you have some idea about this issue?

**Version of Wordpress Installed:** 4.4.2
**Version of SLB Installed:** 2.5.2
**Other plugins installed:** yes
**Theme:** custom
**Browser:** Chrome Version 48.0.2564.116 m (64-bit)

**Comment by archetyped** [comment]
Hi @Emulator000 are you experiencing an issue when a port number is used in the URL?  If not, please [create a new ticket](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) so that your particular issue can be evaluated further.

Thanks.

**Comment by rkeplin** [comment]
I just tested this again, with updated versions, and the issue seems to be resolved.

**Version of Wordpress Installed:** 4.6.1
**Version of SLB Installed:** 2.5.3
**Other plugins installed:** none
**Theme:** Twenty Sixteen

**Comment by archetyped** [comment]
Awesome, thanks for the update :)

**Comment by Karionis** [comment]
I confirm the original issue that the plugin is not working when specifying a port like:
http://localhost:8081/
Although JavaScripts are properly loaded and event listener seems to be attached properly.

When using standard port 80 it works.
http://localhost/

fresh installation of WordPress 5.5.1
Simple Lightbox 2.8.1 
Theme Twenty Twenty Version 1.5
no other plugins active
