### ISSUE TITLE
Issue: Not working after update

### ISSUE THREAD

**Issue by dustinfife** [archetyped/simple-lightbox#401]
## Description of Problem
I just updated my lightbox and the images no longer work. (See, for example, http://www.dustinfife.net/blog/i-learned-to-love-exercise/). I'm not sure if it's because of the update, or something else that I did. It could possibly be that I optimized my images using WP Smush, but I've only done half of my images and they all seem to be affected. However, when I add a new image, it doesn't seem to be affected. So maybe it is WP Smush? 

Is there anything that can be done so I don't have to reinsert all those images?

## Details

* URL of Page exhibiting problem: www.dustinfife.net/blog/i-learned-to-love-exercise/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox
* Version of SLB Installed: 2.4.1
* Other plugins installed: WP Smush (and others)

**Comment by archetyped** [comment]
Hi, it appears that there may be some code from another plugin or the theme causing a JavaScript error on the page. An error will stop other JavaScript code (such as SLB) from running.

See here for [instructions on troubleshooting plugin/theme conflicts](../wiki/Troubleshooting-Plugin-Conflicts) to identify the code causing an issue.

It also appears that an outdated version of jQuery is being loaded on your site.  SLB requires the version of jQuery official included and supported by WordPress.  See here for more information: [jQuery Support](../wiki/jQuery-Support)

**Comment by dustinfife** [comment]
Makes sense. It seems the problem was with the plugin autoptimize. Do you
know of any way to make both work?

On Tue, Jul 21, 2015 at 6:40 PM, Archetyped <notifications@github.com>
wrote:

> Hi, it appears that there may be some code from another plugin or the
> theme causing a JavaScript error on the page. An error will stop other
> JavaScript code (such as SLB) from running.
>
> See here for instructions on troubleshooting plugin/theme conflicts
> <http://../wiki/Troubleshooting-Plugin-Conflicts> to identify the code
> causing an issue.
>
> It also appears that an outdated version of jQuery is being loaded on your
> site. SLB requires the version of jQuery official included and supported by
> WordPress. See here for more information: jQuery Support
> <http://../wiki/jQuery-Support>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archetyped/simple-lightbox/issues/401#issuecomment-123509973>
> .
>



-- 
Dustin Fife
www.dustinfife.net

**Comment by archetyped** [comment]
I would recommend reporting the JS error to the plugin developers.  Once it is fixed, other plugins that run JS code (such as SLB) will no longer be blocked from running.
