### ISSUE TITLE
Issue: Photos are out of order

### ISSUE THREAD

**Issue by ackern** [archetyped/simple-lightbox#403]
## Description of Problem
The photos cycle through in the opposite order of what they're supposed to:

1. Create a gallery with thumbnails and save the post
2. Go to the post -> click on any thumbnail -> the lightbox opens with the full-size photo
3. Click on that photo
4. You will get taken to the PREVIOUS photo, which is not supposed to happen. You should get taken to the next photo.

So in a gallery with 5 photos, if you start with #1 the sequence is now: 15432 and it should be 12345

Similarly, if you click on thumbnail #3 the sequence is:  32154

## Details

Please note, I am not having this problem does not occur with the plugin "Lightbox Plus Colorbox" v2.7.2. I am new to lightboxes and didn't know there are many choices of lightbox plug-ins. I first discovered this after I filed this Issue.

I updated Wordpress and Lightbox today, so they are the absolute latest versions.
Theme is Piedmont
Firefox 28

Plugins - 
Wordpress Importer
WP Super Cache
Akismet - not activated

**Comment by archetyped** [comment]
Hi, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
