### ISSUE TITLE
Issue: Not Working on Images in Code Loaded via jQuery.get()

### ISSUE THREAD

**Issue by rickgordon** [archetyped/simple-lightbox#404]
## Description of Problem
On http://theshelterblog.com , I've set up a system that when you click on the Zoom icon at the upper left of a post (on index, archive, or search pages), content from the full post is loaded into the zoomed div. Images that were initially on the page go into lightbox normally, but images pulled in from the $.get() call are handled in a default manner, going to the attachment page. 

For instance, if you go to this search page: http://www.theshelterblog.com/?s=More+Beautiful+Buildings+of+Kauai , and click the zoom icon, either of the first two images, which were initially loaded onto to the page, will lightbox normally, but the 3rd and successive images will link to the media attachment page.I note that the slb data attributes do show in the ajax-loaded images, though.

**Code of an initially loaded image:**
`<a href="http://www.theshelterblog.com/wp-content/uploads/2015/05/IMG_2231.jpg" class="local-link" data-slb-group="8329" data-slb-active="1" data-slb-internal="0" target=""><img class="wp-image-8332 size-large" src="http://www.theshelterblog.com/wp-content/uploads/2015/05/IMG_2231-728x546.jpg" alt="IMG_2231" width="728" height="546"></a>`

**Code of an ajax-loaded image:**
`<a href="http://www.theshelterblog.com/wp-content/uploads/2015/05/front.jpg" class="local-link" data-slb-group="8329" data-slb-active="1" data-slb-internal="0"><img class="wp-image-8335 size-large" src="http://www.theshelterblog.com/wp-content/uploads/2015/05/front-728x546.jpg" alt="front" width="728" height="546"></a>`

### URL of Page exhibiting problem: 
http://www.theshelterblog.com/?s=More+Beautiful+Buildings+of+Kauai
or any index, archive, or search page on http://theshelterblog.com, where a post fits the conditions. (Look for posts with a Read More button, though it will only occur if addition images are loaded.) There are a few posts, such as the post titled "Campervan Build," on this search page: http://www.theshelterblog.com/?s=camper+van+build , where there is only one image visible in the pre-zoomed state, but two more images exist classed to display none, except when they are in a featured context. So those images do go to lightbox as one might hope. The problem is where new images are ajax-loaded (at least via $.get(). )

### Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Tested in current versions of Chrome, Firefox, and Safari, in OS 10.10.4 (Mac)

### Version of SLB Installed: 2.4.1

* Other plugins installed: 
* A2 Optimized
* Admin Post Navigation
* Akismet
* Asset Queue Manager
* Async JS and CSS
* Auto Insert Title To Link
* Bad Behavior
* BAW Manual Related Posts
* Better WordPress External Links
* Broken Link Checker
* Categorized
* Default Image Settings
* Delete Expired Transients
* Dynamic Image Resizer
* Email Address Encoder
* Enable Media Replace
* EWWW Image Optimizer
* Facebook Auto Publish
* Fancy Excerpt
* Far Future Expiration Plugin
* Featured Image Reminder
* Featured Video Plus
* Fix WP Caption Shortcode Width
* Grab & Save
* HTML Special Characters Helper
* Image Cleanup
* Jetpack by WordPress.com
* Limit Login Attempts
* Media File Renamer
* Post Thumbnail Editor
* Quick Page/Post Redirect Plugin
* Resize At Upload Plus
* Rich Text Excerpts
* Safe Mode
* Search & Filter
* Search Regex
* ShareThis
* Show Dimensions in Library
* Simple Image Sizes
* Simple Lightbox
* Simple Lightbox: Video Handler
* Taxonomy List Widget
* Toggle wpautop
* Transients Manager
* UpdraftPlus - Backup/Restore
* User Role Editor
* WP-Optimize
* Yoast SEO

**Comment by rickgordon** [comment]
Looking more closely, it seems that the only difference between the image code on the single post page and the code as loaded into the zoomed area, is the existence of target="" in the `<a>` tag in the single post page context. But adding that with Chrome's Developer Tools did not solve the problem. I suspect, but am not sure, that that may be added by the **Better WordPress External Links** plugin.

**Comment by rickgordon** [comment]
I just added a small jQuery function to add target="_blank" to the newly imported images. At least they open into a new tab, so you don't have to refresh to get back to where you were. It doesn't change how the lightbox is working; it still works on the initially cached images, and the new images open into the attachment page. However, if I then click one of the early, lightbox-enabled images, it opens into the lightbox, but then after that, the target="_blank" doesn't seem to function on the late-loaded images; they load into the same tab. (A new wrinkle.)

One more clarification on the architecture: The lightbox-working images are the ones that are loaded onto the page (index, archive, or search); but when the `.entry-content` from the single post age are imported into the zoomed post, the **entire** `.entry-content` container div, including the previously loaded images are loaded into the zoomed post. So really they are loaded in the same way as the images that aren't working. (The post-loop `.postlistcontent` is there too; it's hidden `[display:none]` when zoomed, and the `.entry-content` is hidden when unzoomed.) So they difference may really be one involving local caching; the images in the `.entry-content` that were previously loaded into `.postlistcontent` work in lightbox, and the new ones don't.

**Comment by rickgordon** [comment]
A little more observation shows that some ajax-loaded images into some posts, such as http://www.theshelterblog.com/?s=Solar+Tiny+Container+House+Built+with+Cob **never** load into a new tab. Some, like the ones on the Kauai post mentioned earlier will open into a new tab **until** a lightbox is used. (I'm offering mostly search links because they can supply a post with known characteristics into the right context to demonstrate the issue.)

**Comment by archetyped** [comment]
Hi, SLB uses server-side functionality, so new content loaded via AJAX will be supported via an add-on.

See here for more information: [Add on: AJAX Content Loading](208).

Thanks.

**Comment by rickgordon** [comment]
Just getting back to this. Infinite Loading (as implemented by JetPack) also foils SLB's functionality on late-loaded posts. If I knew what SLB file to reload (using jQuery.getScript(), for instance), I could add it to my set of functions in the callback.
