### ISSUE TITLE
Feedback: 

### ISSUE THREAD

**Issue by michil5** [archetyped/simple-lightbox#405]
I wish you people would provide some kind of readable instructions for Simple-Lightbox. I know I have it downloaded, but where do I go to download photos to albums, etc. I have simple-lightbox under Appearance in the Dashboard, but when I click on it, it just brings up settings. Where do I go from here????
I downloaded the Free version and I wouldn't buy into any upgrades that cost money UNTIL I find out that it will work for us. I have been told that your plugin is a good Photo plugin. We are currently using WP Photo Album Plus 4.9.7 and we are not happy with it at all and I put this on every website I make, which is about a dozen. They are large websites. A lot of pages and a lot of photos. I still have not been lucky to find a demo version of your plugin. Do you have a demo on Youtube or something? My name on the repository is Michil5. I hope I'm making sense to you, as I'm really lost in here. my email is: thechiefwawatam@yahoo.com. Regards, Doug Taylor (616) 784-3200 Office (616) 784-0000 Cell.

**Comment by michil5** [comment]
We also have used NextGEN Gallery by Photocrati 2.1.2 and we wasn't happy with that plugin either. I've used Cincopa version 1.136 and it just seems to difficult to use, as they don't want to call a photo album what it is a photo album. They got to put a fancy name to it, which I can't recall right now, but if it was called a photo album, I would remember that. I don't want to learn another language, do you understand? Regards, Doug Taylor

**Comment by archetyped** [comment]
Hi, as the **Usage** section on [SLB's home page](http://archetyped.com/tools/simple-lightbox/) notes, all you have to is insert links to images in posts as per normal and SLB automatically takes care of the rest.

With SLB activated, when a visitor clicks on an image link in your post, the image is now displayed in a lightbox rather than loading a new page.

SLB is so simple to use, people sometimes overthink it and look for complex settings, but there's none of that in SLB.  You can also check out [the beginner's guide to SLB](http://archetyped.com/know/simple-lightbox-for-noobs/) if you need more in-depth instructions.

**Comment by michil5** [comment]
One of my big websites has 2300 pages and it's going to grow to about 6000 pages, will your plugin work for us, or do you have a limit on the storage, etc. Like I said, I want to see a demo of your product, Please. Regards, Doug Taylor  
RE; www.WestMichMusicHystericalSociety.com
The website that I want to test this on is: www.MichilimackinacHistoricalSociety.com

**Comment by michil5** [comment]
Thanks for getting back to me so quick, I didn't even notice you had already. Thanks so much for a quick response. Doug Taylor

**Comment by archetyped** [comment]
Hi, SLB does not impose any limits.  You can see the lightbox by clicking the links on SLB's aforementioned home page and beginner's guide.

**Comment by michil5** [comment]
Thanks again for getting back to me promptly. I will check it out we I get some time and will get back to you. Is there any simple way of transferring all those photos that we have from WP Photo Album Plus 4.9.7 to SLB?

**Comment by archetyped** [comment]
SLB works with WordPress' native media library and gallery functionality.  As such, you may need to transfer your images to WordPress' media library if the plugin adds a separate management layer on top of WordPress.  I would recommend contacting that plugin's developers to determine what (if anything) may need to be done.

**Comment by michil5** [comment]
Most of the photos are on WP Photo Album Plus 4.9.7, which I believe is what your talking about (media library). I have been looking for a long time for a good photo album, I hope yours will work for us, so far I'm impressed with your support. Cincopa support is terrible.
