### ISSUE TITLE
Request: suppression of "# of X" in the lightbox.

### ISSUE THREAD

**Issue by newuser327** [archetyped/simple-lightbox#406]
## Description of feature/request
 suppression of "# of X" in the lightbox.
I just downloaded the plugin and like it.  There may be a way to do this already but I could not find a FAQ to try and look it up.  It goes away if I disable "grouping" but then I lose the slideshow. 
Thanks in advance
## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, you can customize this with the "Slideshow status format" option in SLB's admin settings.  By deleting the text for this option entirely, it will no longer be displayed in the lightbox.
