### ISSUE TITLE
Issue: Lightbox not working

### ISSUE THREAD

**Issue by mattmccabe1984** [archetyped/simple-lightbox#407]
## Description of Problem

Hi, 

I've checked my jquery version, set the standard theme, disabled all plugins. But still lightbox isn't working. Looks like a great plugin but no joy for me...

http://79.170.44.126/riverconservation.org.uk/

Thanks,
Matt

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB does not appear to be activated at the link you provided. Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
