### ISSUE TITLE
Request: Remove the play/pause and close buttons at the right top of the lightbox

### ISSUE THREAD

**Issue by newuser327** [archetyped/simple-lightbox#408]
## Description of feature/request
Remove/Move the play/pause and close buttons from the right top of the lightbox.  

## This feature would be used to

They are intrusive to the gallery images I want to display

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, the lightbox is completely customizable via themes.  Here is a [tutorial for creating a custom lightbox theme for SLB](http://archetyped.com/know/slb-theme-anatomy/) so that you can customize the layout for your needs.
