### ISSUE TITLE
Issue: Back and Next button intrude on the displayed item frame

### ISSUE THREAD

**Issue by newuser327** [archetyped/simple-lightbox#409]
## Description of Problem
Back and Next button intrude on the displayed item frame.  

## Details
It looks like the Back and Next arrows are fixed.  If they are can you move them outward a bit?  I think 3-5 mm each would likely do it. Thanks 

BTW...I REALLY like your product.  Simple like the name but is very clean and stable. 

* URL of Page exhibiting problem: Firefox
* Version of SLB Installed: 2.4.1
* Other plugins installed: 
In the picture below the arrow is well inside the gray frame and actually on my image.  The Gray frame is is part of my image.
![back arrow](https://cloud.githubusercontent.com/assets/13605206/9041729/b2cf4928-39d7-11e5-9dd4-3c3f1b3a9a77.JPG)

**Comment by archetyped** [comment]
Hi, the lightbox is completely customizable via themes.  Here is a [tutorial for creating a custom lightbox theme for SLB](http://archetyped.com/know/slb-theme-anatomy/) so that you can customize the layout for your needs.
