### ISSUE TITLE
Issue: I deployed your plugin. It seems to do nothing.

### ISSUE THREAD

**Issue by toddlohenry** [archetyped/simple-lightbox#410]
## Description of Problem

I deployed your plugin. It seems to do nothing. When I click on an image, no lightbox appears.

## Details

* URL of Page exhibiting problem: http://toddlohenry.com/2015/08/04/how-i-use-twitter-google-and-inoreader-to-build-my-online-reputation/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Current version of Chrome.
* Version of SLB Installed: Current version. Just downloaded.
* Other plugins installed: 
![image](https://cloud.githubusercontent.com/assets/1030264/9064570/cc878446-3a92-11e5-85cc-64b6536cd832.png)

**Comment by archetyped** [comment]
Hi, it looks there is some other code that is causing the following JavaScript error:
```
TypeError: flipboard is null
```

A JS error can stop other JS (such as SLB) from running.  Resolving the error will allow SLB and other scripts on the page to function properly.

See here for [instructions on troubleshooting plugin/theme conflicts](../wiki/Troubleshooting-Plugin-Conflicts).

Let me know if you are still experiencing problems with SLB once the error has been resolved and I would be glad to reopen the ticket and take another look.

**Comment by toddlohenry** [comment]
I have no plugins or code that have anything to do with flipboard...

On Tue, Aug 4, 2015 at 2:21 PM, Archetyped <notifications@github.com> wrote:

> Hi, it looks there is some other code that is causing the following
> JavaScript error:
>
> TypeError: flipboard is null
>
> A JS error can stop other JS (such as SLB) from running. Resolving the
> error will allow SLB and other scripts on the page to function properly.
>
> See here for instructions on troubleshooting plugin/theme conflicts
> <http://../wiki/Troubleshooting-Plugin-Conflicts>.
>
> Let me know if you are still experiencing problems with SLB once the error
> has been resolved and I would be glad to reopen the ticket and take another
> look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archetyped/simple-lightbox/issues/410#issuecomment-127727519>
> .
>



-- 

Todd Lohenry
+19202651614
https://www.freelancer.com/hireme/toddlohenry

**Comment by archetyped** [comment]
Hi, if you view your page's source, you'll see a script is being loaded from flipboard.com.  Unfortunately, I cannot see whether that is being loaded by the theme or a plugin.  You can use the instructions linked to in my previous message to determine what is loading that code.

**Comment by toddlohenry** [comment]
Found the script. It is removed. Lightbox still not working.

On Wed, Aug 5, 2015 at 1:08 PM, Archetyped <notifications@github.com> wrote:

> Hi, if you view your page's source, you'll see a script is being loaded
> from flipboard.com. Unfortunately, I cannot see whether that is being
> loaded by the theme or a plugin. You can use the instructions linked to in
> my previous message to determine what is loading that code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archetyped/simple-lightbox/issues/410#issuecomment-128094676>
> .
>



-- 

Todd Lohenry
+19202651614
https://www.freelancer.com/hireme/toddlohenry

**Comment by archetyped** [comment]
Ah, looks like you may be using Jetpack Photon.  CDNs like Photon will be supported in SLB via add-ons.  You can [add your vote for Photon here](33).

In the interim, disabling Photon will allow SLB to display your images.

**Comment by toddlohenry** [comment]
That did the trick. Is there any way to make the lightbox larger?

On Wed, Aug 5, 2015 at 1:55 PM, Archetyped <notifications@github.com> wrote:

> Ah, looks like you may be using Jetpack Photon. CDNs like Photon will be
> supported in SLB via add-ons. You can add your vote for Photon here
> <http://33>.
>
> In the interim, disabling Photon will allow SLB to display your images.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archetyped/simple-lightbox/issues/410#issuecomment-128108920>
> .
>



-- 

Todd Lohenry
+19202651614
https://www.freelancer.com/hireme/toddlohenry

**Comment by archetyped** [comment]
You can disable the "Resize lightbox to fit in window" option in SLB's admin settings to tell SLB not to automatically resize large images to fit in the browser window.

**Comment by toddlohenry** [comment]
OK, I did that and it still doesn't make the image large enough:

[image: Inline image 1]

On Thu, Aug 6, 2015 at 2:46 AM, Archetyped <notifications@github.com> wrote:

> You can disable the "Resize lightbox to fit in window" option in SLB's
> admin settings to tell SLB not to automatically resize large images to fit
> in the browser window.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archetyped/simple-lightbox/issues/410#issuecomment-128280567>
> .
>



-- 

Todd Lohenry
+19202651614
https://www.freelancer.com/hireme/toddlohenry

**Comment by archetyped** [comment]
SLB will not make your images larger than their original size, so you may have to upload larger images.
