### ISSUE TITLE
Undefined index: host

### ISSUE THREAD

**Issue by Findus23** [archetyped/simple-lightbox#411]
I am getting the following Notice on every page, that uses lightboxes. The lightboxes are working fine.
```Notice: Undefined index: host in .../wp-content/plugins/simple-lightbox/controller.php on line 554```

So it seems that following line is causing the error:
https://github.com/archetyped/simple-lightbox/blob/master/controller.php#L554
Example page:
http://www.noe-schultennis.at/index.php/ausschreibung-2/

**Comment by archetyped** [comment]
Hi, thanks for the report.  You may have `WP_DEBUG` enabled on your site, which is not recommended for live sites.  Disabling `WP_DEBUG` will remove the notice.

Here are [details on disabling `WP_DEBUG`](https://codex.wordpress.org/WP_DEBUG).
