### ISSUE TITLE
Issue: Migrating to new server

### ISSUE THREAD

**Issue by jszuslik** [archetyped/simple-lightbox#412]
Hello,

I migrated my site from a dev server onto our production server and the lightbox plugin does not function now. Our server meets all the requirements and have no where else to look for support.

We are updating our DNS for the site to load hopefully soon. Details of the site are below.
## Details

* URL of Page exhibiting problem: www.centuryfence.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: Latest
* Other plugins installed: ACF

**Comment by archetyped** [comment]
Hi, I don't see any image links on the page you provided.  Please provide a link to a specific page that exhibits the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by jszuslik** [comment]
Thanks for the response. I figured out the issue. Before the DNS was resolved the local host file on my  pc was pointing to the site but the server would have no way of doing this. Once the DNS was resolved the issue fixed itself.
