### ISSUE TITLE
Can't Disable Lightbox from Homepage

### ISSUE THREAD

**Issue by lmadding** [archetyped/simple-lightbox#415]
## Description of Problem

Hello,

Although I uncheck the box to disable the lightbox on the homepage, it still enabled on the homepage. Because it's enabled, it's conflicting with another functionality on that page and is causing it to break. As you see in the image attached, it is supposed to say "more info" and "view larger" on the right, instead of the "by Carlos..."

I have this plugin installed on Wordpress and am using a theme.

Thank you,
Lyra

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed: 

 ![issue](https://cloud.githubusercontent.com/assets/13802971/9284519/53d38c46-4291-11e5-97ba-076a72e14ac8.png)

**Comment by archetyped** [comment]
Hi, SLB should not affect the display of any content on the page.  Please completely fill in the details of your support request and I would be glad to take a closer look.

**Comment by lmadding** [comment]
Hi,

Thanks for your response. Here are more details:

I am using a wordpress theme and have enabled a certain page (not a post) to be my homepage. On the homepage, there is a project portfolio section where if you hover over the thumbnail, you should see two buttons: “more info” and “view larger,” as shown:

[cid:image001.jpg@01D0D8C7.A4E3FA00]
Once I installed the simple lightbox plugin, it now appears like this:

[cid:image003.jpg@01D0D8C7.A4E3FA00]

So I think the plugin may have broke the buttons. To test, I uninstalled the lightbox plugin, and it reverted back to displaying properly with the “more info” and “view larger” button.

This same portfolio section can also be viewed on Our Work of the website’s navigation but that is displaying just fine. I have also went to the Settings’ module of the plugin and disabled that this functionality show on the homepage, but that didn’t work for me.

Website: dev.osbusinessinteriors.com

Thank you!
Lyra

**Comment by archetyped** [comment]
Hi, thanks for the info.  I'm taking a closer look now and will update this ticket when I have more details.

**Comment by lmadding** [comment]
Hello,
Was just checking in to see if you have found a solution for this issue?

Thanks,
Lyra

**Comment by archetyped** [comment]
You found a bug!  When a static page is used as the home page, SLB adheres to the "Enable on Pages" option.

The issue has been resolved and will be included in the next update.

Thanks!
