### ISSUE TITLE
Issue: simple-lightbox dont work any more after update

### ISSUE THREAD

**Issue by tokar86a** [archetyped/simple-lightbox#416]
## Description of Problem

After i updated to the newest version of simple-lightbox the plugin dont seems to work any more on my blog. 

## Details

* URL of Page exhibiting problem: http://www.myabdllife.com/2015/08/15/argi-and-the-bullies-part-1-and-2/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox
* Version of SLB Installed: 2.5.0
* Other plugins installed:

**Comment by tokar86a** [comment]
It seems like the new version have create a conflict whit WP-Rocket

**Comment by archetyped** [comment]
Hi, the link you provided has several JavaScript errors, which can stop other JS code (such as SLB) from loading and functioning.  Resolving these JS errors should allow SLB to function properly.

If you are using a caching plugin, it is recommended that the plugin is disabled to avoid any stale page data from affecting your troubleshooting.
