### ISSUE TITLE
Issue: Error message

### ISSUE THREAD

**Issue by shademount** [archetyped/simple-lightbox#417]
Receiving an error message on my site's backend. 

QUERY_STRING in /hermes/bosoraweb075/b2182/ipg.shademountcom/live/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 936

I have changed themes and deactivated/reactivated plugins but could not identify the cause.

Using Google Chrome
SLB version 2.5.0

All In One SEO Pack
Contact Form Maker
Follow-Up Emails
Google Map Lightbox
Google Universal Analytics
Google XML Sitemaps
iThemes Security
Simple Lightbox
WooCommerce
WooCommerce Accepted Payment Methods
WooCommerce Admin Bar Addition
WooCommerce Customizer
WooThemes Helper
WP Fastest Cache

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Thanks for the report.  I am looking into this.
