### ISSUE TITLE
Issue: Using with Justified Image Grid plug-in

### ISSUE THREAD

**Issue by katili** [archetyped/simple-lightbox#418]
## Description of Problem

Hi,

I am trying to use Simple Lightbox with [Justified Image Grid](http://codecanyon.net/item/justified-image-grid-premium-wordpress-gallery/2594251) but I can't get them to play nicely together. Galleries for JIG are generated via a shortcode, and the Simple Lightbox tags aren't being included in the image links. 

JIG has options to define a custom lightbox, but I can't find any class or rel to add to it to make this one work. A screenshot of the options I can select is attached. Any ideas?

<img width="1266" alt="screen shot 2015-08-16 at 7 13 08 pm" src="https://cloud.githubusercontent.com/assets/7275971/9296929/cbdf4fc0-444b-11e5-88f5-8ea70aad980b.png">

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please completely fill out the details of your support request so that I can take a closer look at the issue you are experiencing.

**Comment by katili** [comment]
I hope this is what you need, please let me know if I missed anything. I appreciate your looking into it :)

    URL of page exhibiting bug: http://www.katiewagner.photography/wordpress/2011/09/14/evie/
    Version of SLB installed 2.5.0
    Other plugins installed: 
Askimet
CryptX
Default Media Uploader View
Google XML Sitemaps
Justified Image Grid
Widget Logic
WordPress Hashcash
WOW Slider
WP-Optimize
WP Smush
    Browser(s) with issue (Firefox, Chrome, etc.): All browsers

**Comment by archetyped** [comment]
Hi, thanks for the details.  I'm looking into this now.

**Comment by archetyped** [comment]
Hi, it looks like the Justified Image Grid regenerates the gallery links directly in the browser when the page loads (removing the SLB-activated links).

Unfortunately, as a paid plugin, I cannot evaluate Justified Image Grid further to see if anything can be done on SLB's side.  I would recommend contacting the other plugin's developer to see if they have any suggestions.
