### ISSUE TITLE
Issue: SLB doesn't work if gallery shortcode is added to the page from a custom field

### ISSUE THREAD

**Issue by xarazar** [archetyped/simple-lightbox#420]
## Description of Problem
I have a fresh local installation of WP with a basic vanilla theme. I use Types for custom post type management. One of my post types has a bunch of additional fields including a WYSIWYG field for a gallery. 
If I add a gallery through the custom field - SLB doesn't work (doesn't append 'data-slb-...' vars at all).
If however the gallery is added in to the standard post content field - SLB works just fine.
I tested it on one page - included one gallery in the standard content field and another in the custom field. On the front end the gallery within the_content() works fine but the gallery from the custom field doesn't.
I include the custom field gallery with do_shortcode([gallery ids="1,2,3,4"])

## Details

* URL of Page exhibiting problem: local server, sorry
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Safari, Chrome - I don't think it's browser specific
* Version of SLB Installed: 2.5.0
* Other plugins installed: Types by OnTheGoSystems
![slb-issue-in-custom-field](https://cloud.githubusercontent.com/assets/203420/9504310/d337566a-4c33-11e5-8033-412a272ba0ac.jpg)

**Comment by archetyped** [comment]
SLB automatically activates the standard content in posts, pages, etc.  Other content areas can be activated using `slb_activate()`.  See here for [more information on using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/).

**Comment by xarazar** [comment]
Thanks a lot. 
I took a closer look at your plugin and it turns out that if I run the custom field output via the_content filter I get the same result as slb_activate().
<?php echo apply_filters("the_content", gallery_shortcode_goes_here) ?>
Many thanks for your help.

**Comment by archetyped** [comment]
The result may be similar in many cases, but using `apply_filters('the_content', $content)` will run *all* filters hooked into `the_content`.  If all you want to do is have SLB activate the links in the content, `slb_activate()` is the faster option.
