### ISSUE TITLE
How to enable "Save As" Option when image is clicked on and showing in LightBox?

### ISSUE THREAD

**Issue by jtrd333** [archetyped/simple-lightbox#421]
Hi, Since I do not see an option to download the image the next best thing is to have the user click on the image, which enlarges it to original size, right click and choose save as.

As of now they do not have the "save as" option when right clicking. Can you show me how to get this enabled?

The page in question is:  http://doorworksenclosures.com/dealer-marketing-material/

![capture](https://cloud.githubusercontent.com/assets/13988334/9507002/01fc3e52-4c11-11e5-8624-84c158e55c90.PNG)

**Comment by archetyped** [comment]
Hi, SLB does not block the right-click menu in the lightbox.  However, you may have been right-clicking over the click area for the navigation buttons, which is why the "save as" option is not in the context menu.  Clicking in the middle of the image should display the menu for the image itself.

**Comment by jtrd333** [comment]
It was actually because I had group images on page as slideshow. Once disabled the save as option came up.

Thanks,

Jeff Raymon
636.795.5812
