### ISSUE TITLE
Issue: Doesn't work with Jetpack's Photon images?

### ISSUE THREAD

**Issue by FiddlerStudios** [archetyped/simple-lightbox#422]
## Description of Problem

I apologize. I simply don't have time to do full testing on this. So I'm not certain my site meets the requirements. But I'm about 99% sure I had this plugin's lightbox working just great previously. However, after activating JetPack's Photon feature, it's not working. Has it been tested with Photon?

EDIT: Looking around more I found a gallery on my site that's still loading the images locally (not sure why) and they load in the lightbox just fine. But other images, loaded from Photon URL's do not. So it does look like it's possibly a Photon issue, perhaps because the plugin thinks they're external links, and so should be ignored?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed:  2.4.1
* Other plugins installed: many

**Comment by archetyped** [comment]
Hi, please see this existing ticket for information on [support for Photon and other CDNs](33).

Thanks.

**Comment by FiddlerStudios** [comment]
Okay. Thanks. I voted there. I did search this repository for both "jetpack" and "photon" before posting this, and nothing came up.
