### ISSUE TITLE
See pics of gallery when change or add gallery pictures

### ISSUE THREAD

**Issue by corvandongen** [archetyped/simple-lightbox#423]
Since recent update I can no longer see the pics in the gallery on the screen when I want to add or change a picture of gallery.
I can link to the library to add a picture, that's fine, but I cannot see the pic I just added, only text 
Can anyone explain how to make this text visual as a small pic again?

[gallery link="file" ids="1286,1211,1016,1043,542,393,391,366"]<span style="font-family: Tahoma;"><span style="font-size: small;">Click on a Thumbnail to open a full size image.</span></span>

**Comment by archetyped** [comment]
Hi, I would love to help.  Can you please clarify what screen you're referring to when you say *"I can no longer see the pics in the gallery on the screen when I want to add or change a picture of gallery."*

**Comment by corvandongen** [comment]
Thank you so much for your assistance:

I do following steps:

1. enable 3 languages in WPGLOBUS (Dutch, English and French)
2. Language selector mode: Two letter code with flag
3. All pages menu selector : enable

Than I choose Appearance -  "customize"
The front page appears with the tool menu on the left side
4. I choose WIDGETS
5. Choose SIDEBAR
6. ADD A WIDGET
7. choose "ADD WPGLOBUS WIDGET"
8. choose 'Drop down with flags' -
Now I can see the 3 language flags

[image: Inline afbeelding 1]

Next I press "SAVE & Publish" - and the page ask me to leave and warns me
to loose all data
I have no other option and the changes are not saved


[image: Inline afbeelding 2]

Hope above explains my problem




2015-09-08 1:15 GMT+02:00 Archetyped <notifications@github.com>:

**Comment by archetyped** [comment]
Hi, it looks like you included some images/screenshots of the issue, but you may have to upload them directly (rather than replying via email).

Aside from that, your description of setting up widgets does not seem to be related to your original message about working with galleries.  Perhaps your screenshots will help me understand the issue you're having with SLB though and I'll gladly look into the issue for you.

**Comment by corvandongen** [comment]
thanks for your assistance
I have resolved the issue, it appeared to be a conflict with the theme I am
using (Fotogram) and a language plugin/widget.This was the reason that my
lightbox was not showing the gallery correctly.

thanks again

Best regards
Cor


2015-09-10 1:42 GMT+02:00 Archetyped <notifications@github.com>:

**Comment by archetyped** [comment]
Great!  Glad to hear your issue was resolve :)
