### ISSUE TITLE
Request: Reposition UI buttons

### ISSUE THREAD

**Issue by dompans** [archetyped/simple-lightbox#426]
## Description of feature/request
1) My idea is to add an option to "move" all the buttons so they are outside of the image. I mean "next/previous item", "start/stop slideshow".
I really like the plugin with the effects etc, but I really prefer the image being clear from any buttons (or text).
2) And also, maybe even more imortant, to have an option to hide the image-title.

Is this maybe possible to solve through changing the css-code?

## This feature would be used to
Show images more "purely".

## If you added this feature, I would:

a) Eat my socks
b) Jump to the moon
c) Shave my wife (whaat?)
d) Learn english better

**Comment by archetyped** [comment]
Hi, you can fully control the layout of the lightbox (including buttons) for your needs using a custom theme.

Here are some [resources on creating and customizing SLB themes](http://archetyped.com/tag/simple-lightbox+theme+tutorial/).
