### ISSUE TITLE
Request: Vimeo Pro videos

### ISSUE THREAD

**Issue by syntexsk** [archetyped/simple-lightbox#427]
## Description of feature/request
Hello, I am not a user yet but I would like to buy your product. I am not sure if it supports Vimeo Pro files. I've tried several lightboxes but all of them have problems with Vimeo Pro videos (not publicly visible on vimeo.com and locked under one domain). If this works, I will buy the video add-on

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above
e) buy the plugin :-)

Thanks!

**Comment by archetyped** [comment]
Hi, the video needs to be embeddable on external sites to be displayed in the lightbox, but it should otherwise work.  If you can provide a link to a Vimeo Pro video, I would be glad to take a closer look at support for such videos.

**Comment by syntexsk** [comment]
Hello,

thanks for info. I can set the domain, where it can be embedded - only
domains which I select can work. So if you plugin uses any domain, I can
specify it and test it. I can send you a link to video but you will not be
able to see it, check below:
http://vimeo.com/120092696

If you can send me a domain, I can set up this video to be embeddable on
this domain and you can test it. If it will work, bingo!

Btw, I've tested 6-7 wordpress lightboxes  (free and paid) and none was
working for Vimeo Pro files. Classic vimeo.com files worked fluently, but
Vimeo Pro not thus for me all plugins were unusable.

Thanks and waiting for your feedback!

S pozdravom,







*Tomas SIPOS [image: Syntex] <http://www.syntex.sk>Syntex Bratislava s.r.o.
Zeleznicna 23 82107 Bratislava Slovakia T: +421 2 4552 5471* |
*+421 2 3214 4496 *E:
*tomas.sipos@syntex.sk <tomas.sipos@syntex.sk> www.syntex.sk
<http://www.syntex.sk>*

**Comment by archetyped** [comment]
Hi, you can set the domain to archetyped.com.  Let me know when you've enabled that domain and I'll do some testing.

**Comment by archetyped** [comment]
SLB should be able to display the video as long as the domain is authorized.  I've confirmed that the necessary data can be retrieved for Pro videos, such as the title ("#04.01 | Round-Trip in Adobe Premiere CC")

**Comment by syntexsk** [comment]
Hello, the domain archetyped.com is authorized. I will test it in few
moments.

S pozdravom,







*Tomas SIPOS [image: Syntex] <http://www.syntex.sk>Syntex Bratislava s.r.o.
Zeleznicna 23 82107 Bratislava Slovakia T: +421 2 4552 5471* |
*+421 2 3214 4496 *E:
*tomas.sipos@syntex.sk <tomas.sipos@syntex.sk> www.syntex.sk
<http://www.syntex.sk>*

**Comment by syntexsk** [comment]
It seems it is not working... but I don't have the video add-on, is it ok?
Will it work also without this video add-on?

S pozdravom,







*Tomas SIPOS [image: Syntex] <http://www.syntex.sk>Syntex Bratislava s.r.o.
Zeleznicna 23 82107 Bratislava Slovakia T: +421 2 4552 5471* |
*+421 2 3214 4496 *E:
*tomas.sipos@syntex.sk <tomas.sipos@syntex.sk> www.syntex.sk
<http://www.syntex.sk>*

**Comment by syntexsk** [comment]
Images are displayed, videos not.

S pozdravom,







*Tomas SIPOS [image: Syntex] <http://www.syntex.sk>Syntex Bratislava s.r.o.
Zeleznicna 23 82107 Bratislava Slovakia T: +421 2 4552 5471* |
*+421 2 3214 4496 *E:
*tomas.sipos@syntex.sk <tomas.sipos@syntex.sk> www.syntex.sk
<http://www.syntex.sk>*

**Comment by archetyped** [comment]
Yes, the [video add-on](http://archetyped.com/lab/slb-video-addon-beta/) is required to display videos in SLB.

I have tested the Vimeo Pro video you provided and it is displayed in SLB without any issues.
