### ISSUE TITLE
Issue: Having just updated the Simple Lightbox plugin, the site's home page now reports a redirect loop

### ISSUE THREAD

**Issue by PaulCutcliffe** [archetyped/simple-lightbox#429]
## Description of Problem
Having just updated the Simple Lightbox plugin, the site's home page now reports a redirect loop

## Details

* URL of Page exhibiting problem: http://www.gembuilderssussex.co.uk/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Version 2.5.2
* Other plugins installed: 
Akismet | Version 3.1.4 | By Automattic
Clef | Version 2.3.0 | By Clef
Easing Slider | Version 2.2.1.1 | By Matthew Ruddy
Flexi Quote Rotator | Version 0.9.4 | By Aidan Curran
Google Analyticator | Version 6.4.9.6 | By SumoMe
Gravity Forms | Version 1.9.13 | By rocketgenius
Jetpack by WordPress.com | Version 3.7 | By Automattic
Limit Login Attempts | Version 1.7.1 | By Johan Eenfeldt
Simple Lightbox | Version 2.5.2 | By Archetyped
Sucuri Security - Auditing, Malware Scanner and Hardening | Version 1.7.13 | By Sucuri, INC
UPDATE NOTIFICATIONS | Version 0.3.4 | By Mario Spinaci
WordPress Importer | Version 0.6.1 | By wordpressdotorg
WP-chgFontSize | Version 1.8 | By Ferran Rodenas
Yoast SEO | Version 2.3.5 | By Team Yoast

Please note the home page works just fine right now, since I've deactivated the plugin. With it activated, the home page reports a redirect loop, but only the home page. If you add something to the URL, like a page or the admin dashboard, then the site works fine.

Has anyone else reported something similar?

Thanks.

**Comment by archetyped** [comment]
Hi, thanks for the report.  SLB doesn't do any redirection itself, so there may be a conflict with another plugin/theme.  Here are a couple things you can try:

* Disable SLB on the home page (via SLB's admin settings)
* Check for plugin/theme conflicts: Here are instructions for [identifying plugin/theme conflicts](../wiki/Troubleshooting-Plugin-Conflicts).

Also, make sure to clear your browser cache and your site's cache (if you use a caching or CDN plugin) whenever you make any changes (settings, plugin updates, etc.) to ensure that there are no conflicts with stale data.

Let me know what you find and I'll be glad to take another look.

**Comment by PaulCutcliffe** [comment]
Thanks for coming back to me.

I have followed your suggestions, and can confirm that the home page still generates infinite redirect loops even when using the 2015 Theme with no other plugins activated, and with your plugin not enabled on the home page.

**Comment by archetyped** [comment]
Thanks for the update.

Does the browser report a redirect loop for any specific file?

Here are a few other options:

**Reset SLB's Settings**

1. Go to the plugin admin page and click the "Reset" link under Simple Lightbox (note: SLB must be activated for the reset link to appear)
2. Test your home page

**Clean installation**

1. Reset SLB's settings as above
2. Deactive and Delete SLB
3. Reinstall SLB
4. Test your home page

**Test previous version of SLB**

You noted that the issue began after updating SLB, so a previous version may resolve your issue.

1. Reset and uninstall SLB as above
2. Download a previous version from [SLB's releases archive](https://github.com/archetyped/simple-lightbox/releases)
3. Install SLB (here are [instructions on installing a plugin from a zip file](https://codex.wordpress.org/Managing_Plugins#Manual_Plugin_Installation))
4. Test your home page.

Let me know whether one of these options was able to resolve your issue, or which version of SLB worked without issue.

Thanks.
