### ISSUE TITLE
Issue: [Woocommerce] Lightbox not displaying on bundled product thumbnails

### ISSUE THREAD

**Issue by phases-design** [archetyped/simple-lightbox#432]
## Description of Problem
I have a bundled product, displaying thumbnails. Is there anyway to get their image to show up in the lightbox?

## Details

* http://dev.bitsibi.com/shop/knitted-goodies/spa-set/
* chrome
* Version of SLB Installed: current
* Other plugins installed: Woocommerce Product Bundles

**Comment by archetyped** [comment]
Hi, link you provided does not currently appear to be working ("Server not found"), but SLB's WooCommerce add-on is designed to support WooCommerce's core functionality.  Support for third-party extensions depends on how that extension is integrated with WooCommerce itself.

If you would like to create a user account and send the details to support@archetyped.com, I would be glad to look into what it would take to support the Product Bundles extension.

Also, note that this is the support forum for SLB itself.  Please use the [Add-ons Support Forum](https://github.com/archetyped/slb-addons/issues "Add-ons Support Forum") for add-on support.  Thanks.
