### ISSUE TITLE
Question: load external URL in lightbox

### ISSUE THREAD

**Issue by pixelaid** [archetyped/simple-lightbox#433]
## Description of Problem
This is not really a problem, but a pre-sales question. Can I use Simple Lightbox to load an external URL or will it work with your Add-on?

Thanks,
Darryl

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Yes, SLB supports external links as well as links to your site's media attachments.
