### ISSUE TITLE
Issue: 2.5.2: error 301 Moved permanently on page/2/

### ISSUE THREAD

**Issue by jjur** [archetyped/simple-lightbox#434]
## Description of Problem

After update SLB causes error 301 and redirects from /page/2 (2,3,4,5,6+) to home. Everything works on older version 2.5.1.
![12047376_1202869073062304_1022098250_n](https://cloud.githubusercontent.com/assets/13292381/10559266/043c227c-74ed-11e5-930c-bc756e9572e3.jpg)
## Details
- URL of Page exhibiting problem: http://www.fonyzciny.sk/page/2/
- Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Firefox Nightly, Google Chrome, Microsoft Edge
- Version of SLB Installed: 2.5.2 (now downgraded to 2.5.1)
- Other plugins installed: ![12168761_991419574213849_201598914_o](https://cloud.githubusercontent.com/assets/13292381/10559360/54abeeb6-74ef-11e5-85d3-124127750459.jpg)

**Comment by archetyped** [comment]
Thank you for the report.  I will look into this and update this ticket when I have more info regarding this issue.

**Comment by archetyped** [comment]
This issue could not be reproduced.  If you are still experiencing this issue after updating the [the latest version of SLB](https://wordpress.org/plugins/simple-lightbox/), please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.
