### ISSUE TITLE
Question: PDF in Lightbox

### ISSUE THREAD

**Issue by aarcadio** [archetyped/simple-lightbox#435]
## Description of Problem
Hello,
this is not an issue report but only a question. Does SLB support the view of PDF file in lightbox? if yes, could you tell me how to proceed?

Thank you

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, PDF files are currently not supported in the lightbox.
