### ISSUE TITLE
Feature Request: Disable SLB on mobile

### ISSUE THREAD

**Issue by dentaoman** [archetyped/simple-lightbox#437]
## Description of Problem
Hello archetyped

it's not a bug but a request if it is possible ?
I'd like to disable SLB on smartphone, so no link pointer on image

see in explanation

Thanks for you answer

Best regards

Den

## Details

* URL of Page exhibiting problem: local installation
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: last version
* Other plugins installed: meta  slider last version

Explanation :
In portrait mode, not much difference and less easy
In landscape mode, the size is smaller
see attached screenshot

![slb 1](https://cloud.githubusercontent.com/assets/15379390/10819454/73210ef0-7e48-11e5-9b9c-ec0704ef4627.jpg)

**Comment by archetyped** [comment]
Hi, thanks for the feedback.  Mobile-specific disabling is not currently in the plans.  You can disable automatic resizing in SLB's settings if you prefer to display images at their full size in the lightbox.

**Comment by dentaoman** [comment]
Hello Archetyped,

Thanks for your answer


Regards

Den
