### ISSUE TITLE
Issue: Black screen and no photos

### ISSUE THREAD

**Issue by floriandeboer** [archetyped/simple-lightbox#438]
## Description of Problem
I have updated Wordpress to the latest version and updated the Simple Lightbox too. But now I don't see any images, but the screen keeps black... Resetting the plugin doesn't help.

## Details

* URL of Page exhibiting problem: http://www.huurdersverenigingfraneker.nl/busreis-14-september-2015/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Google Chrome
* Version of SLB Installed: Wat is LSB?
* Other plugins installed: Yes

**Comment by archetyped** [comment]
Hi, it looks like there may be other plugins loading code that is not compatible with the version of jQuery currently used by WordPress.

Here are instructions for [identifying plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) to determine which plugin is loading the outdated code.

Let me know what you find and I would be glad to take another look if necessary.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please let me know what you found regarding conflicting plugins/themes and I would be glad to take another look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by floriandeboer** [comment]
Hi,

Thanks for your advice, a plugin was the problem.

Have a nive day.

Greetings, Florian

2015-11-24 1:33 GMT+01:00 Archetyped <notifications@github.com>:

**Comment by archetyped** [comment]
Ah, thank you for the update.
