### ISSUE TITLE
Shortcode [slb_exclude] showing up in widget

### ISSUE THREAD

**Issue by LeahGrrl** [archetyped/simple-lightbox#440]
I placed a video link and image on the front page so the video would pop out in a lightbox. But there is a new problem: the Featured Page widget is displaying the shortcode [slb_exclude] at the top of  the featured pages in the widget.

## Details
* URL of Page exhibiting problem: www.focustestdrive.net
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.5.2 plus Video beta pro add-in
* Other plugins installed: 
![pluginsnov10](https://cloud.githubusercontent.com/assets/15637372/11074006/44215f3e-87bb-11e5-8a3e-8551f575d055.png)

To get it to work, I had to implement SLB for home page and for widgets. It is not enabled for pages or posts--I only want this effect for this video on the homepage. thank you

**Comment by archetyped** [comment]
Hi, can you please provide a link to the specific featured page widget you are experiencing this issue with?

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by LeahGrrl** [comment]
I apologize for not responding. Since I only wanted this lightbox effect for one video image on one page, I have gone with a different solution. I think SLB will work better on another site I'm involved with because the client will want all the videos to pop out. Thank you for your responsiveness!
