### ISSUE TITLE
Issue: WPML compatibility?

### ISSUE THREAD

**Issue by Nossfloda62** [archetyped/simple-lightbox#442]
## Description of Problem
Hi
I have uploaded a very simple testsite to show you a problem with WPML Multilingual CMS and WPML Media. 3 plugins total and Twenty Fifteen.

See images below (and home page)
1 Swedish post with Swedish text for Image 1
2 LB with English texts
3 English post with English text for Image 1
4 LB with English texts, as it should be.

I can't upload po/mo files in Swedish for some reason (I think i promised you those like a year ago!!!).

Mail me at kristian@adolfsson.photo and I'll send them and login.

![1](https://cloud.githubusercontent.com/assets/8499529/11179680/604244e6-8c55-11e5-8e65-784ba9fc5da1.png)
![2](https://cloud.githubusercontent.com/assets/8499529/11179683/60485f7a-8c55-11e5-8637-e4f69c775d01.png)
![3](https://cloud.githubusercontent.com/assets/8499529/11179681/6042f1de-8c55-11e5-96e7-b100bb88e9f1.png)
![4](https://cloud.githubusercontent.com/assets/8499529/11179682/60448364-8c55-11e5-87de-ad19410897bb.png)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Both
* Version of SLB Installed: 
Latest
* Other plugins installed: 
See above, Latest

**Comment by archetyped** [comment]
Hi, you can vote on an add-on for WPML here: [Add-on: Multilingual Support](https://github.com/archetyped/simple-lightbox/issues/205 "Add-on: Multilingual Support")
