### ISSUE TITLE
Request: Video Autoplay

### ISSUE THREAD

**Issue by ipcode** [archetyped/simple-lightbox#446]
## Description of feature/request
Provide option to enable video to play instantly upon display of video lightbox

## This feature would be used to
Skip additional step of clicking play button 

## If you added this feature, I would:
d)

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, autoplay is supported by adding the URI query parameter to the link's URI.

For example, a Vimeo or YouTube link with `&autoplay=1` added to the URI's query string will automatically start playing when it is displayed in the lightbox.

Full URI example:

```
https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
```

This gives you full control over which videos start playing automatically when loaded in the lightbox.

**Comment by m2008** [comment]
That's great. Thanks
