### ISSUE TITLE
Issue: Overlay sizing

### ISSUE THREAD

**Issue by nmbr13** [archetyped/simple-lightbox#448]
## Description of Problem

Hi!

I am trying to display an image from an iframe link. The lightbox isn't scaling to my content though. How can I achieve this? I really enjoy the plug-in.  Thank you for your work

Alex

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please fill in the details of your support request (including a link to a page that exhibits the issue you are experiencing) and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
