### ISSUE TITLE
Request: Automatic resizing

### ISSUE THREAD

**Issue by merlinemrys** [archetyped/simple-lightbox#449]
## Description of feature/request

images are resized to be fullscreen

## This feature would be used to

allow images to be displayed fullscreen, and resized automatically to fit the browser window, with navigation arrows

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, enabling the "Resize lightbox to fit in window" option in SLB's settings will automatically resize any images that are larger than the browser window.
