### ISSUE TITLE
Lightbox fatal error

### ISSUE THREAD

**Issue by MikkiBlaes** [archetyped/simple-lightbox#450]
## Details

* URL of Page exhibiting problem: http://thechattanoogaauctionhouse.com/auction_date/2015-12/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Simple Lightbox
* Error Message: Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 902673 bytes) in /home/content/m/i/k/mikes88/html/wp-content/plugins/simple-lightbox/controller.php on line 646

**Comment by archetyped** [comment]
Hi, the page appears to load properly without any message about a fatal error.  However, this type of message is can usually be resolved by increasing PHP's memory limit for your site.

Here are instructions on [increasing PHP's memory limit in WordPress](https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP).

If you are still experiencing this issue, you may want to clear your browser's cache to ensure that you're viewing the current version of the site.
