### ISSUE TITLE
Issue: Simple Lightbox troubles on wordpress 4.4

### ISSUE THREAD

**Issue by n01d3a** [archetyped/simple-lightbox#453]
I am not able to get Simple Lightbox to work. [Here](http://josephcravotta.com/2015/12/test-post/) is a test post I created to show what is happening. When I click on the image, a new page is loaded instead of the lightbox with an image in it. I had disabled all other plugins and tried using the 2016 and 2015 theme. Unfortunately this did not resolve the issue.

**Details**
Wordpress Version: 4.4
SMB Version: 2.5.2
Browser: Chrome and IE 11.

**Comment by archetyped** [comment]
Hi, it appears that cURL may not be enabled for your site.  See here for [more information on SLB's requirements, including cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements).

**Comment by n01d3a** [comment]
Thank you for pointing me in the correct direction. I did not realize CURL was a requirement. Although curl was installed and enabled, it was not working properly when using my domain name. I have resolved the main cause and everything is working properly.
