### ISSUE TITLE
Issue: Slider dont working

### ISSUE THREAD

**Issue by boka003** [archetyped/simple-lightbox#454]
## Description of Problem
Hello,

After install lite box plugin i was update my gallery at posts, but nothing change.
Its look like plugin dont work.
Here is one post:  http://verdiment.com/zagreb-protesti-pred-stanom-kolinde-grabar-kitarovic-okupljeni-trazili-nove-izbore/

## Details

* URL of Page exhibiting problem: http://verdiment.com/zagreb-protesti-pred-stanom-kolinde-grabar-kitarovic-okupljeni-trazili-nove-izbore/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB appears to be working properly at the link you provided.  However, there also appears to be another lightbox activated on your site which is also activated when clicking on an image link.

This lightbox may be added by your site's current theme or another plugin.  Here are [instructions on identifying the theme/plugin that is loading the other lightbox](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

Once you have identified the theme/plugin, you can check if it provides an option for disabling the additional lightbox, or you can contact the theme's/plugin's developer for instructions on disabling it.
