### ISSUE TITLE
Issue: Launching Slideshows from a Single Link

### ISSUE THREAD

**Issue by bobbio** [archetyped/simple-lightbox#455]
## Description of Problem
Hello, wonderful plugin thank you very much! I am wondering if there is a fix for this issue. I have two Launching Slideshows from a Single Link set up here http://www.reeleminn.com/accommodations-test/ for Cabin 1 and Cabin 2. It works great except when cycling through the slideshow lightbox the images from both Slideshows seem to all connect together. i.e. at the end of the Cabin 1 images the Cabin 2 images start to display. Is there a way to limit the images to those of just the one slideshow. 

## Details

* URL of Page exhibiting problem: http://www.reeleminn.com/accommodations-test/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 2.5.2
* Other plugins installed: Photo Gallery, iThemes Slideshow,

**Comment by archetyped** [comment]
Hi, you can create separate groups of links on a page using the `[slb_group]` shortcode.

See this post for [instructions on using `[slb_group]`](http://archetyped.com/lab/slb-2-3-0/).
