### ISSUE TITLE
Issue: Plugin is not working

### ISSUE THREAD

**Issue by linasslepikas** [archetyped/simple-lightbox#456]
HI, well the plugin does nothing and I can not see why, no errors, no nothing, Checked the source, and when I add link it is just link. Any help would be much appreciated.

* URL of Page exhibiting problem: http://dev.solosystems.eu/salytis/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
* Version of SLB Installed: 2.5.2
* Other plugins installed: Advanced Custom Fields Pro, Admin Color Schemer, Custom Favicon, Customize Login Image, and I have this lightbox library added to my theme: http://lokeshdhakar.com/projects/lightbox2/, but I removed it and your plugin did not worked anyway.

**Comment by linasslepikas** [comment]
Now I see that plugin is not loading JS files, but CSS file is added. Makes no sense.

**Comment by archetyped** [comment]
Hi, are the image links inserted into the post's content or added via ACF fields?

SLB automatically activates links in post content, but other content can be activated using `slb_activate()`.

See here for [more information on using `slb_activate()`](http://archetyped.com/lab/slb-2-3-0/).

**Comment by linasslepikas** [comment]
Thank you, that was all I needed, work like a charm now.

**Comment by archetyped** [comment]
Glad to hear it :)
