### ISSUE TITLE
Issue: opt in pop up

### ISSUE THREAD

**Issue by montero7** [archetyped/simple-lightbox#457]
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by montero7** [comment]
I'd like to know if Simple Lightbox would allow me to create an opt-in pop up that will automatically appear when the home page is opened, in order to invite visitors to sign up for newsletter or updates.

**Comment by archetyped** [comment]
Hi, SLB displays a lightbox when a valid element on the page is clicked.  Support for displaying HTML content such as a form is planned.
