### ISSUE TITLE
Doesn't work with some pictures (was working well for any kind of pictures).

### ISSUE THREAD

**Issue by kvv213** [archetyped/simple-lightbox#458]
Hello All!

I found out recently that SImple LB stopped to open for some pictures. It worked recently but now it doesn't. Some pictures work but some don't.
For example:
Non working http://blog.kvv213.com/2016/01/ne-idet-dy-m-v-trube-ili-kak-zazhech-pechku-v-holodnoe-vremya-goda/

Working http://blog.kvv213.com/2016/01/atlant-raspravil-plechi-chast-iii-atlas-shrugged-part-iii-who-is-john-galt-2014/

**Comment by archetyped** [comment]
Hi, it appears that image in the non-working post is not linked to anything.  Without links, there is nothing for visitors to click on.

Once a link is added to the image, SLB will display the linked image in the lightbox when clicked.  Here are [instructions for inserting image links](http://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link) from WordPress' official documentation.

**Comment by kvv213** [comment]
Hi!

Yes, you are right!
