### ISSUE TITLE
Right click and save: 

### ISSUE THREAD

**Issue by JurgenDoe** [archetyped/simple-lightbox#459]
thank you first for the nice plugin .. it's working very well but I think there should be an option not to right click and save the image ... people can steal the image .. I saw on the net many galleries with a popup but you can't right click on it.

Can you please fix this problem .. Thank you

Jurgen

**Comment by archetyped** [comment]
Hi, SLB displays images from direct links in posts, meaning visitors could just as easily download the file from the link itself.

As such, SLB does not block right-clicking in the lightbox.  However, if you use a plugin that blocks right-clicking on the page, it should also be applied to the content in the lightbox.

**Comment by JurgenDoe** [comment]
Hi, do you know a plugin that blocks right-clicking ??? Thanks for the help

**Comment by JurgenDoe** [comment]
Never mind ... found the plugin ... thanks for the tip
