### ISSUE TITLE
Issue: file path

### ISSUE THREAD

**Issue by gumwp** [archetyped/simple-lightbox#460]
## Description of Problem

Loading the plugin, script paths are broken where theres a back slash being inserted before the hyphen. Should be `src='http://site.com/wp-content-staging/` but renders as `src='http://dev.boldearth.com/wp/-content-staging/`

`<script type='text/javascript' src='http://site.com/wp/-content-staging/plugins/simple-lightbox/client/js/prod/lib.core.js'></script>`

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by gumwp** [comment]
Loading the plugin, script paths are broken where theres a back slash being inserted before the hyphen. Should be src='http://site.com/wp-content-staging/ but renders as src='http://dev.boldearth.com/wp/-content-staging/
<script type='text/javascript' src='http://site.com/wp/-content-staging/plugins/simple-lightbox/client/js/prod/lib.core.js'></script>

**Comment by gumwp** [comment]
I have latest version installed, WP up to date, using Chrome, Safari, FF, same result

**Comment by archetyped** [comment]
Hi, I have not been able to reproduce this issue.  Custom paths set for WP's content and/or plugin directories appear to be handled without any issues.

If you can provide a link to a page that exhibits the issue you are experiencing, I would be glad to reopen the ticket and take a look.
