### ISSUE TITLE
Request: PDF support

### ISSUE THREAD

**Issue by mmjaeger** [archetyped/simple-lightbox#463]
Hello
I was wondering whether there's an easy way to load a PDF file into lightbox?

Thanks

**Comment by archetyped** [comment]
Hi, it may be possible to add support for PDFs via an add-on.  I've created a ticket for the add-on to keep track of the add-on's status and where you and others can add your comments.

See here: [Add-on: PDF Support](https://github.com/archetyped/simple-lightbox/issues/465)
