### ISSUE TITLE
Problem with span around item.source / item.permalink

### ISSUE THREAD

**Issue by ericantonio85** [archetyped/simple-lightbox#464]
## Description of Problem

HTML tag around `item.source` tag

## Details

I use `item.source` and `item.permalink` on `themes/baseline/layout.php` so in html lighbox on front, there is a span arround source or premalink like this:
```
<span class="slb_template_tag slb_template_tag_item slb_template_tag_item_permalink" style="display: inline;">http://sibelcomedia.s3-ap-southeast-2.amazonaws.com/20160128151138/sibelco_home_slider.png</span>
```
But i don't need this span, i just need absolute url to put in 

```
<a link a href="{{item.source}}">Download</a>
```

**Comment by archetyped** [comment]
Hi, template tags are "live" and updated when a new item is displayed in the lightbox.  As such, template tags are rendered as HTML elements, not raw text values.

A future update will allow for using item data in links though.

**Comment by ericantonio85** [comment]
Thank you, i'm waiting for it.

**Comment by philippemellenger** [comment]
As it been implemented? Same issue here.
