### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by gsallman** [archetyped/simple-lightbox#466]
Since the update to WP 4.4.2 The plugin has just stopped working. It seems to work the first time you visit the site and then stops and the linked image is displayed instead.

Example page: http://www.paisleylizard.com/2016/01/buried-treasure-aje-jewelry-challenge/

To reproduce the fault you may have to click around a bit.

I tried turning off all the plugins except Simple Lightbox and it still wouldn't work. All plugins are at their latest releases.

SLB 2.5.2

Other plugins:

Bad Behavior 2.2.18
jetpack 3.9.1
VaultPress 1.7.8
Yoast SEO 3.0.7

and my own shortcodes plugin (which just creates css text wrappers and has been working for several years, no changes have been made)

The Theme is a child Theme of Twenty-Twelve.

I have checked this and it failed on all browser / OS / Computer options I tried:

Chrome and Firefox on a PC running Windows 10, and Chrome and Safari on a MacBook running OSX

It doesn't work on Android lollipop either.

This is the page I checked: http://www.paisleylizard.com/2016/01/buried-treasure-aje-jewelry-challenge/

**Comment by archetyped** [comment]
Hi, it appears that cURL is not installed and/or enabled for your site.  You may have to contact your hosting provider to enable this.

More information: [SLB Requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements "SLB Requirements")

Once cURL is enabled, SLB should be able to function properly.  If you are still experiencing an issue after cURL has been enabled, please leave a comment with additional details and I would be glad to reopen the ticket and take another look.
