### ISSUE TITLE
Issue: video disappears

### ISSUE THREAD

**Issue by joshmrodg** [archetyped/simple-lightbox#467]
## Description of Problem

When you launch the lightbox, the YouTube video disappears...on a dev site (http://joshrodg.com/hallmark/star-wars/) I have disabled all plugins except for this one and activated the WordPress 2015 default theme with no modifications. There is a video on that page and an image almost directly below it (on the right side), if you click on the image, you'll see the video disappear.

## Details

* URL of Page exhibiting problem: http://joshrodg.com/hallmark/star-wars/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome, Safari
* Version of SLB Installed: 2.5.2
* Other plugins installed: None

**Comment by archetyped** [comment]
Hi, certain elements (such as flash objects) do not play well with overlaid elements like a lightbox and thus are hidden while the lightbox is active.  These elements are unhidden when the lightbox is closed.
