### ISSUE TITLE
hi Issue: 

### ISSUE THREAD

**Issue by nknandakishore74** [archetyped/simple-lightbox#468]
## Description of Problem

hi hello world , how can i reduce the speed of image gallery pop windows speed of carousel in in light box image gallery.

Thanking you
Nanda Kishor.S

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, you can customize the duration of each image in the lightbox by changing the **Slide Duration** setting in SLB's options.
