### ISSUE TITLE
Issue: SLB not working with the theme "Optimizer" (free version)

### ISSUE THREAD

**Issue by Bobbutterfly** [archetyped/simple-lightbox#469]
## Description of Problem
When using Optimizer, the SLB option panel is totally messed up as you can see in the image below.

Moreover, the plugin does not work at all when trying to see the images (use the default view of my system/wordpress).

The plugin works fine with other themes (like Twenty Fourteen or Evolve).

**Note as well that the problem appears on the dashboard when on desktop and mobile.
But, the lightbox effect works just a bit on mobile and not at all on desktop.**

![image](https://cloud.githubusercontent.com/assets/17457605/13553667/7d72c8f8-e388-11e5-9465-c40b059c4ac8.png)

## Details

* URL of Page exhibiting problem: an example with single pics or gallery pics: 
http://le-chemin-du-butterfly.fr/vie-dublin/manger/3-endroits-parfaits-devorer-burger 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Mozilla...
* Version of SLB Installed: 2.5.2
* Other plugins installed: Jetpack, Yoast, Imsanity...

**Comment by archetyped** [comment]
Hi, SLB appears to be working at the link you provided.  Please provide additional details if you are still experiencing an issue and I would be glad to reopen your ticket and take another look.

Thanks.

**Comment by Bobbutterfly** [comment]
Hi archetyped, thank you for your answer!

You're right. Though the plugin is now technically working (so far), the option panel remains the same as on the picture I gave.

What I did to make it works is that I switched to 2014 theme where the option panel is okay, then I change the settings (not that much this the plugin has been running for months) and switched back to the problematic theme (Optimizer!).

So far, so good but as I said, the option panel is still not working

**Comment by archetyped** [comment]
Hi, unfortunately, a plugin cannot prevent other plugins/themes from adding styles etc. to the page that can affect layout.  This is something that would need to be resolved by the theme's developer, which I see that you've contacted as well.  Hopefully they will update the theme so that it does not affect the layout of other admin pages.

**Comment by Bobbutterfly** [comment]
Hello again!

It seems not to work everytimes... I though it did but I just tried on 
http://le-chemin-du-butterfly.fr/vie-dublin/manger/3-endroits-parfaits-devorer-burger 
and pic are not responding everytimes > <.

But I'm in contact with the theme developer as well indeed this I think the issue is mostly on his side :)

**Comment by archetyped** [comment]
Hi, can you elaborate on when the lightbox is not working for you please?

Is there a specific image that doesn't work, or when you click on the same image, etc.?  I tested all of the links on that page and they all were displayed in the lightbox as expected.

**Comment by Bobbutterfly** [comment]
Hey!
Well, that's quiete strange actually... The effect mostly works but sometimes, rare times, it just doesn't...
The only thing I can tell is that the option panel is not working but otherwise, it's a mystery

**Comment by archetyped** [comment]
Hi, it may be that page loading has not completed on the occasions that it did not work.  If the page has not finished loading when a link is clicked, then it is possible that SLB has not been loaded yet, and thus it is unable to display the link in the lightbox.

**Comment by Bobbutterfly** [comment]
Alright; but what about the option panel?

**Comment by archetyped** [comment]
Hi, as previously-noted, while a theme should not be negatively affecting the layout and functionality of other admin pages, there is nothing we can do to prevent this on our end.

I would recommend requesting that the theme developer review their code to limit the effect they have on other admin pages.
