### ISSUE TITLE
Issue: divi

### ISSUE THREAD

**Issue by danilomlima** [archetyped/simple-lightbox#470]
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please fill in the details of the issue you are experiencing and I would be glad to take a look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the requested details and I would be glad to reopen the ticket and take a look.
