### ISSUE TITLE
Issue: Image linked to page - opening lightbox and not a page

### ISSUE THREAD

**Issue by aobrad** [archetyped/simple-lightbox#471]
## Description of Problem
So when it's clicked on a image which is linked to a proper page, it doesn't open up that page, instead image is opened in lightbox. URL of problem: http://www.format-fenster.at/turmodelle-pvc/

Dumped Firefox cache and cleaned up everything but problem is still there. Tried with Chrome it seems to be OK.

## Details

* URL of Page exhibiting problem: http://www.format-fenster.at/turmodelle-pvc/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox
* Version of SLB Installed: 2.5.2
* Other plugins installed: 
Advanced Custom Fields: Repeater Field
All In One SEO Pack
All In One WP Security
Black Studio TinyMCE Widget
Breadcrumb NavXT
Contact Form 7
Essential Grid
Newsletter
Photo Gallery
Tabby Responsive Tabs
WP Super Cache

**Comment by aobrad** [comment]
edit: tried with other computers and the problem appears there also

**Comment by archetyped** [comment]
Hi, WordPress itself determines whether a link is an image attachment, and it appears that you may have some attachment names that conflict with your page names.  You may need to rename the images in your media library to avoid such conflicts.
