### ISSUE TITLE
Simple Lightbox show up fine in the desktop version, but only will work on 3 images on a cellphone

### ISSUE THREAD

**Issue by RKK12** [archetyped/simple-lightbox#473]
Hi there -
I am putting together a portfolio of my work and am using the Themify Fullpane wordpress theme and the Simple Lightbox plugin on the galleries. It works fine in the desktop vewport, but when viewed on a cellphone, only 3 images work with the plugin. 

FYI, I have disabled all the other plugins and it doesn't seem to make a difference.

Details:
http://rhondakueffler.com/wp/folio/
The images that show up on the cell phone are: 
1. Photos Section - 1st row / 5th image (Name - Seeding)
2. Creative Section - 1st row / 3rd image (Name - Inspiration)
3. Creative Section - 1st row / 5th image (Name - Untitled)
I get the same results on my Droid Turbo and my sisters iPhone 6 and I have the most currently WP and SLB installed. I checked the latest version of jQuery and that is current too.

Any help would greatly be appreciated. Thank you for your time.
R!

**Comment by archetyped** [comment]
Hi, the site currently appears to be unreachable.  Please let me know when the site is back up and I would be glad to take another look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
