### ISSUE TITLE
Issue: lightbox stopped working - MIME type problem?

### ISSUE THREAD

**Issue by RikuRanta** [archetyped/simple-lightbox#474]
Hi!
Simple Lightbox has been working like a charm for ages but for some reason it stopped working a few weeks ago. I'm not entirely sure when this occurred. Might be because of a change web hosting provider made to the environment - just guessing here.

The problem is that pictures doesn't get showed in a lightbox window but open up in a blank window. I noticed that someone else was also having the same problem so I checked that curl is enabled.

I made a copy of the production, moved into default theme, disabled all the other plugins installed, updated Simple Lightbox to the newest version 2.5.2 (which I already was using) but still the outcome was same. I'm using version 4.4.2 of WP.

Issue can be verified here - **http://rm.ullatus.com/2015/10/10/thats-a-wrap/**. This is the test site that behaves same way as the prod.

I debugged it with Chrome but same happens also with other browsers.

Clicking one of the images produces this to the browsers console log:
**Resource interpreted as Document but transferred with MIME type image/jpeg: "http://rm.ullatus.com/wp-content/uploads/2015/10/Nosto-2015-09-01.jpg".
Navigated to http://rm.ullatus.com/wp-content/uploads/2015/10/Nosto-2015-09-01.jpg**

Googling around with that only suggested there might be an issue with the jQuery version in use (1.11.3), but according to Simple Lightbox documentation that should be supported.

A little help here would be greatly appreciated. Cheers!

**Comment by fduraibi** [comment]
I am having the same problem, it is not working at all, and the link opens the image directly.
I am also not sure when it happened, but I also migrated my installation to another server.
Not sure if it is caused by the migration or it could be related to the latest WP update?! (4.4.2)

**Comment by fduraibi** [comment]
I solved my problem, the plugin stopped working after enabling HTML, JS and CSS minification in "W3 Total cache". I think that missed up something.

**Comment by RikuRanta** [comment]
Good to know! Too bad I'm not using W3 Total cache or any other plugin at the moment. I actually deleted (not only disabled) all the other plugins so at the moment I have only SLB installed. And still the problem exists! I was also thinking that this has something to do with the latest WP update.

I tried another lightbox plugin "WP Lightbox 2" which works great so I switched to that on the production site. But the test site still remains the same.

**Comment by archetyped** [comment]
Hi, @RikuRanta it appears that cURL is not enabled or properly configured for PHP on your site.  You may have to contact your hosting provider to enable/configure cURL.

Here is [more information SLB's requirements, including cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements).

Please let me know if you are still experiencing an issue after enabling cURL and I would be glad reopen this ticket and take another look.
