### ISSUE TITLE
Not working in Wordpress 4.5

### ISSUE THREAD

**Issue by site-ox** [archetyped/simple-lightbox#475]
## Description of Problem
Simple Lightbox stopped working after upgrading to Wordpress 4.5

## Details
* URL of Page exhibiting problem: http://www.greystoneorl.com/projects/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  All browsers
* Version of SLB Installed:  2.5.2
* Other plugins installed: Disable Comments, Fast Secure Contact Form

**Comment by adnan-ismail** [comment]
I'm also facing the same issue. please help.

**Comment by archetyped** [comment]
Hi @site-ox, SLB has been tested to work properly with WP 4.5.  Please fill in the details of your request and I would be glad to take a look at your issue.

@adnan-ismail, please [create a separate ticket for your issue](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) so that it can be evaluated fully.

Thanks.

**Comment by site-ox** [comment]
I have tried uninstalling the plugin and reinstalling.  It does not appear to work at all, since upgrading to WP 4.5.

URL of Page exhibiting problem:  http://www.greystoneorl.com
Browser(s) exhibiting problem (Firefox, Chrome, etc.):  All browsers
Version of SLB Installed:  2.5.2
Other plugins installed:  Disable Comments, Fast Secure Contact Form

**Comment by archetyped** [comment]
Hi, it looks like there's an error in another script on the page.  Errors can stop other code on the page (e.g. SLB) from running.

You can use your browser's error console or developer tools to view the JS errors on the page.  Once the error is fixed, SLB will be able to function normally.

Let me know if you are still experiencing issues after fixing the error and I would be glad to reopen this issue and take another look.
