### ISSUE TITLE
Issue: Simple Lightbox not working after moving host

### ISSUE THREAD

**Issue by drooth** [archetyped/simple-lightbox#476]
Hi,

I can't get Simple Lightbox to work after migrating hosts. I've read various posts regarding cURL and suspect this may be the cause but the hosts (123-reg) have assured me that is enabled correctly.

I have tried disabling other plugins and switching themes but unfortunately this has made no difference.

Any help would be greatly appreciated.

http://preview.crsc.org.uk/return-queen-mary/

Thanks

**Comment by archetyped** [comment]
Yes, it appears that cURL is not properly configured for your site.  You can direct your host to [this page regarding cURL support for SLB](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

**Comment by drooth** [comment]
Ok, many thanks for the quick response.
