### ISSUE TITLE
Issue: Images showing twice

### ISSUE THREAD

**Issue by osmanppm** [archetyped/simple-lightbox#477]
## Description of Problem

Simple Lightbox shows every image/photo twice. I'm guessing the issue comes from the line breaks between <img> tags. When the line breaks/spaces are removed, it doesn't show the images twice, but that's a limitation to the layout of the post.

i.e. I have 9 images in the post, when I click first the image, it says "item 2 of 18" and shows every image twice.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.5.2
* Other plugins installed: Tried deactivating all the other plugins, but the issue is still there.

**Comment by archetyped** [comment]
Hi, line breaks should not have any effect on SLB's functionality.  Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
