### ISSUE TITLE
problem limiting images displayed in slideshow: 

### ISSUE THREAD

**Issue by bunkarma** [archetyped/simple-lightbox#478]
Hi, I am trying to get a group of specific images to display in a lightbox slideshow. It looks great but the slideshow displays additional images that are meant to open in a separate slideshow.
I've published a test page showing the problem and would be most grateful if you could offer
any help. I love this lightbox and would be very happy if I can use it on my site. Would be very
willing to upgrade to a pro version too if I can get it to do what I need.

I am building my site using Theme Grill Spacious Pro template btw.

Many thanks in advance

## Details

* http://heypixto.co.uk/test_images/
* Chrome browser
* SLB 2.5.3
* Other plugins installed:
Display Widgets 2.05 
Lightbox Gallery 0.8.3 (not activated) 
Page Builder 2.4.8
Simple Lightbox 2.5.3
SiteOrigin Widgets 1.5.11
TablePress 1.7
Theme Check 20151211.1
WooCommerce 2.5.5
WooCommerce Menu Cart 2.5.7
Wordfence Security 6.1.7
Wordpress File Upload Pro 3.6.1

**Comment by archetyped** [comment]
Hi, you can use the `[slb_group]` shortcode to create separate groups of links.  Please refer to [this page in SLB's documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes) for more details.

Thanks.
