### ISSUE TITLE
Issue: slb doesn't work after installation

### ISSUE THREAD

**Issue by marinalr** [archetyped/simple-lightbox#481]
I've just installed SLB on my website and nothing happens.
I'd just want to enlarge pictures on my articles, it'a a very simple website with zerif pro theme. 

for instance on this page:
* URL of Page exhibiting problem: 
http://www.soaudit.com/digitalisation-profession-comptable/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): chrome and firefox
* Version of SLB Installed: 2.5.3
* Other plugins installed: pirate forms, google maps widget, comet cache, simple custom css, share buttons

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without a link to an image, there is nothing for a visitor to click on, and thus no way for the lightbox to be displayed.

Once you add some Image links added to the post content, they will be displayed in the lightbox when clicked.

If you are still experiencing an issue after adding image links, please update this ticket and I would be glad to reopen it and take another look.

**Comment by marinalr** [comment]
There is a link to an image in the post:
http://www.soaudit.com/wp-content/uploads/expert-comptable-IFEC.jpg
that's why I don't understand  why the lightbox isn't displayed...

**Comment by archetyped** [comment]
Hi, there is only a standard image inserted in the post.  It is not linked to anything.

Please see [WordPress' documentation on inserting images with links](http://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link) for more details on adding the desired link to your post.  Once the link has been properly added, SLB should be able to display the image in the lightbox.

**Comment by frank6tg** [comment]
I've tested several lightboxes and since WP 4.5 they have issues... Not sure what the common problem is.

**Comment by archetyped** [comment]
Hi @frank6tg, SLB has been tested to work properly with the latest version of WordPress. If you are experiencing an issue with SLB, please [create a new ticket for your issue](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) and I would be glad to take a look.

**Comment by marinalr** [comment]
After inserting image link it's working fine now, thanks!

**Comment by frank6tg** [comment]
It is working on a test site that is stripped of other plugins.

Respectfully.

Frank Gomez
941-374-7711
Owner / Creative Director
Empowered Marketing, LLC dba Frank's Designs
Empowered Marketing™
<http://www.franksdesigns.com/>www.FranksDesigns.com
<http://www.franksdesigns.com/>

**Comment by archetyped** [comment]
Glad to hear it :)
