### ISSUE TITLE
Simple Lightbox is not working 

### ISSUE THREAD

**Issue by fnfcircles** [archetyped/simple-lightbox#482]
## Description of Problem

Hello, I am using Socially Viral Theme by my Theme shop on my wp site and this site also has lightbox but not working, I disable that lightbox and I installed Simple Lightbox on my wp website (http://www.gamingzones.info) but it also not working. I tried to edit post and change setting for Photo to Media File, Custom URL and Attachment File but simple Lightbox is still not working. I also cleared Cache from my site and chrome but same.

Kindly guide to solve this issue.

Regards
Abubakar Sattar

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled and/or activated for your site.  Please see SLB's documentation for [more information cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

It also appears that some code in your site's theme is triggering a JavaScript error. This error stops all other JS code on the page (including SLB's) from running.

You can confirm that the theme is causing a conflict by temporarily switching to one of WordPress' default themes and checking whether SLB works again. If there is still an issue, see here for [more details on troubleshooting theme and plugin conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

Once cURL has been enabled and the theme's JS error has been resolved, SLB should be able to function normally. If you are still experiencing an issue, please leave a comment and I would be glad to reopen this ticket and take another look.
