### ISSUE TITLE
Have to close pop up image lightbox twice

### ISSUE THREAD

**Issue by zoehoss** [archetyped/simple-lightbox#483]
Example of where it's happening: http://zoes.gallery/2016/05/22/photographing-kew-gardens/ 

You click on an image to view a lightbox of all the 8 images, - all works fine - but when you're closing it, you must close a further window of the first image that you clicked on 'behind' the lightbox. 

Not a major issue because functionality works fine. But a minor annoyance. 

Cannot close down all plug ins because I use Flothemes, a wordpress theme builder which relies on many plug ins for its functionality and I don't dare close it and have months of hard work undone for sake of remedying minor niggle

Thanks

**Comment by archetyped** [comment]
Hi, it appears that you have two lightboxes installed/activated on your site.  As lightboxes are designed to react to the same action, both lightboxes are displayed when an image link is clicked.

Disabling the theme's lightbox will stop the 2nd lightbox from being displayed when an image link is clicked.
