### ISSUE TITLE
Request: Add CSS class to page when lightbox is open

### ISSUE THREAD

**Issue by nbrummerstedt** [archetyped/simple-lightbox#484]
## Description of feature/request

Whenever a lightbox is open/activated, i would like to add "slb" as a class to the <body> element. This class should of course be removed when lightbox is closed.

## This feature would be used to

Add "filter: blur(8px);" to specific elements on page, thereby removing distractions from background, while keeping a "layered" feeling (semi-transparency).

## If you added this feature, I would:

Simply love you.

**Comment by archetyped** [comment]
Hi, the `slb_overlay` class is added to the page's `<html>` element whenever the lightbox is displayed.  You can use this class to selectively style elements on the page:

```css
/* Change paragraph text color when lightbox is open */
.slb_overlay p {
    color: red;
}
