### ISSUE TITLE
Issue: lightbox not working for all images

### ISSUE THREAD

**Issue by sickmint79** [archetyped/simple-lightbox#486]
## Description of Problem

lightbox works for the top locally hosted image but not for any others.  even if i copied its code and just changed the image url it didn't work actually.

## Details

* URL of Page exhibiting problem: 
http://www.igobyplane.com/2016/05/31/cats-of-istanbul-part-i/
http://www.igobyplane.com/2016/05/23/karting-across-thailand-part-13-bangkok-easykart-bangkok-rca/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
chrome v51

* Version of SLB Installed: 
2.5.3

* Other plugins installed: 
adsense explosion 1.1.4
akismet 3.1.11
cookies for comments 0.5.5
google analytics by monsterinsights 5.5
great circle mapper 0.0.2
insert php 1.3
recent posts widget extended 0.9.9.5
shareaholic 7.8.0.3
shortcode exec php 1.52
subscribe2 10.21 
tinymce advanced 4.3.10.1
wordfence security 6.1.8

**Comment by archetyped** [comment]
Hi, support for nonstandard image URIs can be added using the `slb_content_handlers_image_match filter`.

See [this previous discussion on this topic](https://github.com/archetyped/simple-lightbox/issues/55) for more details, including a sample plugin you can use as a starting point.

**Comment by sickmint79** [comment]
i don't understand what i am supposed to do?

i replaced the main.php in my wp-content/plugins/simple-lightbox but that just broke a lot of stuff.  so i tried opening it and adding the function definition and call in the github main.php to my existing main.php, which didn't break anything, but didn't appear to fix or change anything either.

how do i use this?

**Comment by archetyped** [comment]
Hi, as per the the [sample plugin's description](https://github.com/archetyped/slb-content-handler-image-match-example/), it is meant to be used as the basis of an add-on for SLB.  The code is not a replacement for SLB's core code.

You can modify the sample plugin's `slb_handler_image_match_extend()` function to add support for the nonstandard URI format of the images you would like to be displayed in the lightbox.

**Comment by archetyped** [comment]
Alternatively, you may be able to get the direct image URI (e.g. with the `.jpg` extension) to Google-hosted images by opening the image in Google+ and selecting "View Image" (or similar option) when right-clicking the image.

This direct image URI should work by default in SLB.

**Comment by sickmint79** [comment]
i'm not totally understanding that still... this is a code snippet for me to... write my own additional plugin... (?)

**Comment by archetyped** [comment]
Hi, SLB's functionality can be extended via add-ons, which are installed just like standard WordPress plugins.  The sample plugin linked to in my previous response is provided as a starting point for making your own custom add-on for matching nonstandard image URIs.

If you do not have development experience, then this approach may not be for you.  I am working on something that will make it easier to add custom URIs, or you can use the alternative image URI method I described in my previous response.

**Comment by sickmint79** [comment]
sill a future version of SLB incorporate the ability to handle these kinds of URLs itself?
