### ISSUE TITLE
Issue: lightbox notworking 

### ISSUE THREAD

**Issue by stridey** [archetyped/simple-lightbox#487]
## Description of Problem

content is no longer contained in a lightbox

## Details

* URL of Page exhibiting problem: ux-design.co.uk > portfolio > content is no longer contained in a lightbox
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  ALL
* Version of SLB Installed: 2.5.3
* Other plugins installed: Yes: -
Akismet
Select Brankic Social Media Widget	Brankic Social Media Widget
Select Envato WordPress Toolkit	Envato WordPress Toolkit
Select LayerSlider WP	LayerSlider WP
Select Login Page Styler	Login Page Styler
Select Newsletter	Newsletter
Select Simple Lightbox	Simple Lightbox
Select Velvet Blues Update URLs	Velvet Blues Update URLs
Select WP-Mail-SMTP	WP-Mail-SMTP
Select WPBakery Visual Composer	
WPBakery Visual Composer

**Comment by archetyped** [comment]
Hi, SLB displays image links in the lightbox, but the links in the portfolio section are set to open separate pages, not images.

If SLB previously worked in that section, then the links may have been changed from images to pages, which would explain why the links are no longer displayed in a lightbox.  Updating the portfolio links so that they point to images rather than separate web pages will allow SLB to display them in the lightbox.

**Comment by stridey** [comment]
Hi

Thanks for the quick response! 

Can you provide the steps on how to do that? 

Warm regards 
Mark

**Comment by archetyped** [comment]
Hi, here is WordPress' official documentation on adding image links for a post or page: [Inserting Images into Posts and Pages: Image Link](http://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link "Inserting Images into Posts and Pages")

**Comment by stridey** [comment]
Hi 

Thanks think there is some confusion still I'm afraid. 

When I setup this theme the portfolio displayed the content (text/images) in a light box so upon clicking the images from the home landing page a light box would open and display the content (formatted text/images) 

All of a sudden this no longer happens and upon clicking image open up a new content page diminishing the visual effect of the light box. 

I don't know how this has happened and was hoping for instructions on how to restore the light box. Has code changed in the light box functionality to have this affect? Or do you know how I can restore ? 

Many thanks and 

Warm regards 
Mark

**Comment by archetyped** [comment]
Hi, as noted in my previous reply, SLB displays image links in the lightbox.  If available, SLB also displays an image's caption and description, but it does not display formatted HTML content (e.g. the content's of a linked web page).

As such, if the portfolio links have not been changed and a lightbox was displaying the image/text content, then it sounds like you may have been using a different lightbox plugin.
