### ISSUE TITLE
Issue: Simple Lightbox Vertical Spacing

### ISSUE THREAD

**Issue by robertpath** [archetyped/simple-lightbox#488]
I am unable to create any vertical spacing between images using the Simple Lightbox. Please let me know how I can add some padding between images.

Thank you,

Robert Path

URL: http://thetotalaffiliate.com/gallery/

Browsers: Firefox & Chrome 

SLB Version 2.5.3

* Other plugins installed: 
Akismet
Black Studio TinyMCE Widget
Clef
Contact Form 7
Easy Facebook Likebox
Google Analytics by MonsterInsights
Page Builder by SiteOrigin
Recent Posts Widget Extended
SiteOrigin Widgets Bundle
SumoMe	
Sydney Toolbox
Title Remover
TJ Custom CSS
Toolset Types
WCK - Custom Fields and Custom Post Types Creator
WP Super Cache
Yoast SEO

**Comment by archetyped** [comment]
Hi, your site's theme is responsible for how galleries on the page are formatted/styled.  SLB only controls the display of content in the lightbox.
