### ISSUE TITLE
Doesn't work with widget

### ISSUE THREAD

**Issue by alat54** [archetyped/simple-lightbox#489]
## Description of Problem

Hi, 

If i had an image widget, the lightbox doesn't care of this :)
I activated the function in the plugin's backend.

I use the plugin in his last version and wordpress 4.5.2.

thanks

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by alat54** [comment]
Hi, it's on a local workspace :(
WP : Version 4.5.2
SLB : Version 2.5.3
Browser : firefox
Plugins installed : so many... :)

In fact, nothing appened when i checked the checkbox in the backend.
My image widget are still static so i can't click on them to enlarge the image.
It's equal to the checkbox unchecked...

Thanks

**Comment by archetyped** [comment]
Hi, whether it is compatible depends on the particular image widget plugin you're.  If you can provide a link to the plugin, I would be glad to take a look.

I also recommend making sure that the thumbnail image is linked to the image you want to be displayed in the lightbox, as without a link, there is nothing for visitors to click to launch the lightbox.

**Comment by alat54** [comment]
I use Image Widget Version 4.2.2

**Comment by archetyped** [comment]
Hi, as requested, please provide link to the specific widget plugin you are using, as there can be many with a common name like "Image Widget".  You can find a link to the plugin's home page directly below the plugin's name in your site's plugin listing page.

Thanks.

**Comment by alat54** [comment]
Hi, 

Ah ok 
https://github.com/moderntribe/image-widget
https://wordpress.org/plugins/image-widget/

Here the pages for it
Thanks a lot for the help

**Comment by archetyped** [comment]
Hi, it appears that this particular widget plugin does not link the image by default.  You need to manually add the URL to the desired image in the "Link" field in the widget's settings.  Once the widget has a valid link, SLB can display the image when clicked.

You can copy the selected attachment's URL via the "URL" field before you close the image selection dialog and paste it in the widget's "Link" field.  There may also be other image widget plugins that make it easier to add a link to the selected image.
