### ISSUE TITLE
Feedback: 

### ISSUE THREAD

**Issue by adir-gosh** [archetyped/simple-lightbox#490]
thks for this great plugin, simple, very simple and very efficient. avada self lightbox or ilightbox are such a pain in the ass : some options just don t work in some cases...
now, i wander, if simple lightbox could be launch from a slider such as revolution slider or layer slider ?
best.

**Comment by archetyped** [comment]
Hi, glad to hear you're enjoying SLB :)  SLB works with links, so if the slider (or any other plugin) generates valid links, then it is very possible for SLB to work with them out of the box.  If not, then it may still may be possible for them to be supported via an add-on.

Please provide a link to the slider you are interested in, along with a link to a page that uses the slider  and I would be glad to take a closer look.

**Comment by adir-gosh** [comment]
Hi,

actually i just wanted to have one single image featured on my standalone
page and be abble to launch the lightbox by a clic on it.

which is simply possible with your plugin by using "image carousel" element
in avada theme.

and again, which is obviously not possible with ilightbox or avada self
lightbox !

that why i though i d have to create a slider with a single image linked to
the lightbox. i guess it s possible with revolution slider and "fancy box"
:

https://www.themepunch.com/faq/using-fancybox-with-slider-revolution/

so it should be possible as well w your plugin.

anyway, bunch of thanks for your plugin that solves, for me, many issues...
very simply.

best,

lg



2016-06-08 23:38 GMT+03:00 Archetyped <notifications@github.com>:
