### ISSUE TITLE
Issue: Lightbox zoom mobile

### ISSUE THREAD

**Issue by jbworks2** [archetyped/simple-lightbox#491]
## Description of Problem

Hi Guys

On mobile there is something strange with the lightbox. in normal vertical stand, somethimes the pictures is not showing up. In horizontal stand it's working.. 

Also strange scales somethimes?
## Details
- URL of Page exhibiting problem: www.vrolixinterieur.be
- Browser(s) exhibiting problem (Firefox, Chrome, etc.): chrome, expl,
- Version of SLB Installed: latest
- Other plugins installed: no influence

**Comment by archetyped** [comment]
Hi, I couldn't find any image links on that page.  Can you please provide a link to a specific page that exhibits the issue you're experiencing?

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
