### ISSUE TITLE
Issue: Simple Lightbox stopped working

### ISSUE THREAD

**Issue by rota-rossi** [archetyped/simple-lightbox#492]
## Description of Problem

Today, I globally updated my wordpress installation, and simple lightbox stopped working. I tried disabling all other plugins, and changing to default theme, with no success.
## Details
- URL of Page exhibiting problem:  http://www.castellirossi.com/karyme/
- Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Safari, Firefox
- Version of SLB Installed: latest
- Other plugins installed: all other plugins are currently disabled.

**Comment by archetyped** [comment]
Hi, it looks like the theme may not meet [SLB's minimum requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements).  If possible, please activate one of WordPress' default themes (e.g. Twenty-Twelve) and let me know and I would be glad to take a closer look.

Thanks.

**Comment by rota-rossi** [comment]
Done. Changed theme to twenty-fourteen.

**Comment by archetyped** [comment]
Thanks!  SLB able to properly access the image links with Twenty-Fourteen, but it looks like cURL may not be enabled or properly configured for WordPress.

Please see here for [more details on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

Let me know if you're still experiencing an issue after enabling cURL and I would be glad to take another look.

**Comment by rota-rossi** [comment]
It appears that curl is working on my server. I just got back to old theme, and added the following line to it: 

echo 'Curl: ', function_exists('curl_version') ? 'Enabled' : 'Disabled';
echo '<br>';
$curl = curl_version();
foreach ($curl as $key => $value) {
	echo $key, ': ', $value, '<br>';
}

the return was: 

Curl: Enabled
version_number: 463623
age: 3
features: 1597
ssl_version_number: 0
version: 7.19.7
host: x86_64-redhat-linux-gnu
ssl_version: NSS/3.19.1 Basic ECC
libz_version: 1.2.3
protocols: Array
 

(it can be seen now at the end of: http://www.castellirossi.com/karyme/)

There's anything else missing?

**Comment by archetyped** [comment]
Hi, web hosts sometimes restrict cURL access to local requests, so you may have to check with your hosts to ensure that cURL is properly configured for your server.

Also, you may want to confirm that there are no `.htaccess` directives that may block access to SLB's files.

**Comment by rota-rossi** [comment]
I looked, and there are no block rules in .htaccess...
I just added a http://www.castellirossi.com/karyme/phpinfo.php file on that URL that does what the name suggests. 
I know that you are doing a lot more than what is expected, but can you take a look and tell me (or at least give me a hint) to what should I ask/request from my hosting service?

Thanks a lot!

**Comment by archetyped** [comment]
Hi, as previously noted, I would recommend asking your host about whether cURL is configured properly to allow local requests.

**Note:** Based on reports from other users, you may have to ask your host a few times about this because they might not be too thorough the first time.

**Comment by archetyped** [comment]
Hi, Hi, are you still experiencing an issue with SLB?  If so, please let me know what response you received from your site's hosting provider, and I would be glad to take a look if necessary.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.  If you are still experiencing this issue, please post an update and I would be glad to reopen this ticket and take another look.
