### ISSUE TITLE
video add-on: lightbox renders 100% wide, sometimes needs to be narrower

### ISSUE THREAD

**Issue by purplearth** [archetyped/simple-lightbox#493]
I just bought the video add-on to play videos in the lightbox, and it's working well except for one thing.

The lightbox styles that I designed for my client has a close button that extends slightly beyond the right side of the box. At 100% width, the button extends off-screen.

Is it possible to add a setting where the width is limited to something less than 100%?

**Comment by archetyped** [comment]
Hi, SLB's default themes should not extend off-screen, but if you are using a custom theme, you may need to set custom `margin` and `offset` values to tell SLB about the extra space your theme's UI needs.

You can use the baseline theme as a reference (in [`themes\baseline\js\dev\client.js`](https://github.com/archetyped/simple-lightbox/blob/master/themes/baseline/js/dev/client.js)).

If you are still having a problem once these properties have been set for your theme, please provide a link to page with your custom lightbox theme activated, and I would be glad to reopen this ticket and take a look.
