### ISSUE TITLE
Issue: Lightbox not working - probable conflict

### ISSUE THREAD

**Issue by davidellard** [archetyped/simple-lightbox#494]
## Description of Problem

Hello,

Following a recommendation I have installed your plug-in hoping that it would allow the static images on my site to be lightboxed.
I like the idea of the just install and it works, unfortunately it hasn't.  ;-)

I'm presuming that it is a conflict with something else that I have installed but I don't have the technical understanding to try to resolve that.

I would appreciate it if you could take a look and let me know if it something that is easy to resolve so I can use your plug-in.

As a test I also uninstalled you and tried a different lightbox plug-in - with the same result.
But you are the one recommended to me so I'm speaking to you to hope we can resolve it and I can use you.  :-)

Thank you so very much
David

## Details

* URL of Page exhibiting problem:   The whole site but an example page would be:  http://weddingsmk.com/team-view/david-ellard/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.):   All, but I'm mainly testing on Chrome and Vivaldi
* Version of SLB Installed:  New install 
* Other plugins installed:  Many!   I'm using the Cherry framework, and I do have other image related plug-ins installed such as SEO friendly images.  But nothing that I can work out that should be affecting all images on the site the way that you do.

**Comment by archetyped** [comment]
Hi, SLB works with image links.  Without a link, there's nothing for a visitor to click on, and thus nothing for SLB to display in the lightbox.

Once you've added image links to the page, SLB will be able to display them in a lightbox.  For more details on adding image links to your posts and pages, see [SLB's beginner's guide](http://archetyped.com/know/simple-lightbox-for-noobs/ "SLB's beginner's guide").
