### ISSUE TITLE
Issue: need to add "the_content" and the other tags in my template 

### ISSUE THREAD

**Issue by arkosoft** [archetyped/simple-lightbox#495]
## Description of Problem

i have a template that doesn't have "the_content" tag on the "functions.php", how could i add them ?

**Comment by archetyped** [comment]
Hi, the `the_content()` template tag is used in a theme's page/post templates such as `page.php`, `single.php`, etc., not in `functions.php`.

If the theme you are using is not using `the_content()`, I would recommend contacting the theme's developer to request that they update the theme to use WordPress' recommended best practices.
