### ISSUE TITLE
Issue: uBlock Origin Conflict

### ISSUE THREAD

**Issue by piestrzynski** [archetyped/simple-lightbox#500]
## Description of Problem
If you use ad blockers. Plug: uBlock Origin. Then the plug is not working. The photos do not show up in the popup'ie, but only as a file.

## Details

* URL of Page exhibiting problem:  http://piestrzynski.pl
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  FF, Chrome, Opera
* Version of SLB Installed:    Simple Lightbox  version 2.5.3
* Other plugins installed:  Google Captcha, Google Analytics by MonsterInsgihts, Formularze, ShortCodes, Aksimet, kk Star Rating

**Comment by archetyped** [comment]
Hi, it appears that uBlock Origin blocks some files loaded by the "Google Tag Manager for WordPress" plugin, and thus causes an error when these files are referenced in the plugin's JavaScript code on the page.

A JavaScript error can stop all other JS code (including SLB) on the page from running, which is what is happening in this case.  You can temporarily deactivate the Google Tag Manager for WordPress, which should stop the JS error and allow SLB to function normally.  However, it is possible that uBlock Origin could block files from other plugins as well.

My recommendation would be to report the issue to the developers of "Google Tag Manager for WordPress" and request that they update the plugin to check for the code before running it.  This will avoid any errors if an ad-blocker plugin blocks files used by their plugin.

**Comment by piestrzynski** [comment]
It's works. Thank you very much! :)




*Serdecznie pozdrawiam,*
Dominik Piestrzyński
piestrzynski.pl | piestrzynski.info | webarchitecto.pl




2016-07-14 21:47 GMT+02:00 Archetyped <notifications@github.com>:
