### ISSUE TITLE
Issue: Lightbox not working on sub content

### ISSUE THREAD

**Issue by jobouchard** [archetyped/simple-lightbox#501]
## Description of Problem

Hi, I am having a problem with this plugin. See https://bncsupport.lexop.com/doc/quick-start-guide/

The first tab (Installation) works properly, but when you go on the other ones (Sharing, Notification, etc...) the images won't open in lightbox.

Thanks!!

## Details

* URL of Page exhibiting problem: https://bncsupport.lexop.com/doc/quick-start-guide/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: 2.5.3
* Other plugins installed:

**Comment by jobouchard** [comment]
UP

**Comment by archetyped** [comment]
Hi, it appears that your site's theme or a plugin may be loading content for the additional tabs in a way that is not compatible with SLB.

Please fully fill in the details of your issue, such as theme and installed plugins and would be glad to take a closer look.

**Comment by jobouchard** [comment]
The theme is "Manual".

Here's the list of the plugins:

bbPress
Contact Form 7
Manual Framework (Post Type)
Slider Revolution
SSL Insecure Content Fixer
WordPress HTTPS
WPBakery Visual Composer
WPML Multilingual CMS
WPML String Translation
Zopim Widget

Thanks!

**Comment by archetyped** [comment]
Hi, is the tab functionality provided by the theme or one of the plugins?  Please provide a link to the specific theme/plugin, as there can be multiple with the same name.

Thanks.

**Comment by jobouchard** [comment]
It's not a plugin, it's built in the theme. (Manual)  https://themeforest.net/item/manual-multipurpose-online-documentation-creative-wordpress-theme/12997044

**Comment by archetyped** [comment]
Thank you.  It appears that the theme loads a tab's content in a way that prevents SLB from activating the links in the content.

Unfortunately, as a premium theme, I do not have access to it and am unable to look into it further.  [An add-on to support for AJAX-loaded content is planned](https://github.com/archetyped/simple-lightbox/issues/208), but the theme may still not be supported unless it retrieves the tab content using standard WordPress methods.  You may want to contact the theme's developers to request this.
