### ISSUE TITLE
Issue: Conflict with Lazy Load plugin

### ISSUE THREAD

**Issue by draconus** [archetyped/simple-lightbox#502]
## Description of Problem

SLB conflicts with "Lazy Load" plugin. The symptom is that it shows single image twice on the lightbox. Once Lazy Load plugin is disabled lightbox shows correctly single image.
## Details
- Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
- Version of SLB Installed: 2.5.3
- Other plugins installed: Lazy Load

**Comment by archetyped** [comment]
Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.  Also, please provide a link to the specific plugin you are using as there may be several plugins with the same name out there.

Thank you.

**Comment by draconus** [comment]
First goat on the list:
http://www.aw.gamescorner.pl/koza/

Plugin:
https://wordpress.org/plugins/lazy-load/

**Comment by archetyped** [comment]
Thanks.  Looks like that plugin inserts the image element a 2nd time into the page's source.  I'll take a look and see if there's anything that can be done from SLB's end.

**Comment by archetyped** [comment]
**Update:** Link text retrieval has been optimized in the next release and resolves this issue.
