### ISSUE TITLE
Issue: spinning wheel

### ISSUE THREAD

**Issue by raymondoh** [archetyped/simple-lightbox#503]
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please provide the details for the issue you are experiencing and I would be glad to look into it.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
