### ISSUE TITLE
Issue: Not Working

### ISSUE THREAD

**Issue by tferland** [archetyped/simple-lightbox#504]
## Description of Issue

after installing plug-in it I added an image.  The image just opens a new window and does not use lightbox .

## Details

* URL of Page exhibiting problem: http://dev.azurebiosystems.com/applications/customer-submitted-applications/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  all
* Version of SLB Installed: 2.5.3
* Other plugins installed: Woocommerce

**Comment by archetyped** [comment]
Hi, the lightbox appears to working properly at the link you provided.  You may need to clear your browser's cache to ensure you're viewing the version of the page with SLB activated.

If you are still experiencing an issue, please provide more details about your issue (such as the browser you are using) and I would be glad to take another look.

**Comment by tferland** [comment]
Strange it wasn't now all of the sudden it is.  Thanks!
