### ISSUE TITLE
Lightbox doesnt work on one page but does on another

### ISSUE THREAD

**Issue by CameronDutton** [archetyped/simple-lightbox#505]
## Description of Problem

Hello, I am completely new to Wordpress and everything to do with it. I created a website with the help of tutorials and I have found a problem where on one of my pages lightbox won't work, 'link to media' simply takes it to another page. 

The plug-in works on another page on the same website but I can't work out why. It doesn't work on [www.camerondutton.com/copper](http://www.camerondutton.com/copper) but works on [www.camerondutton/com/light](http://www.camerondutton/com/light). 

This happened for a minute or two on another page but randomly started working again but I can't get it to work on this specific page.

Can anyone help me out? 
**WARNING: Might be me being a noob**

## Details

* URL of Page exhibiting problem: http://www.camerondutton.com/copper
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, there may be another plugin causing a conflict with SLB.  Are you using a plugin's functionality on one page, but not the other?  If so, then you can temporarily disable that plugin to check if the lightbox works once again.

Otherwise, here's a [simple step by step guide on finding plugins/themes that are causing a conflict](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).

Let me know what you find and I'll be glad to take another look if you're still experiencing this issue.

**Comment by CameronDutton** [comment]
Sorry for late response, took a brake from website creating. But thanks for quick response. 

There are no different plugins active on either page. I haven't tested every plugin individually as I don't really understand how themes work and I'm really scared to lose any of my website. I might try recreating the page again, just copying and pasting stuff from before. Think it might just be a minor error in a plugin, as it works on most of the pages. 

Feel free to close this, I will open another if the problem persists as it is only minor and I love the plugin for the other pages. 
Thanks, keep up the good work.

**Comment by archetyped** [comment]
Hi, there are some validation issues with the HTML on that page ([see here](http://validator.w3.org/check?verbose=1&uri=http%3A%2F%2Fcamerondutton.com%2Flight%2F)), which may be preventing the browser (and by extension, SLB) from being able to properly access the links on that page.

If SLB is working properly on all of your other pages, then rebuilding the page from scratch may be the best course of action.  Let me know if you are still experiencing a problem after doing so, and I would be glad to reopen this ticket and take another look.
