### ISSUE TITLE
Issue: Lightbox opens within theme's lightbox

### ISSUE THREAD

**Issue by michaelezra** [archetyped/simple-lightbox#507]
Thanks for  a great plugin. I am using Photography theme by themeforest. That theme comes with its own lightbox. is there a way to disable SLB to be launched from the theme's lightbox?

e.g. I don't want it to launch when viewing portfolio & gallery pages, but DO want it to launch on blog pages.

Thanks!

**Comment by archetyped** [comment]
Hi, more granular controls are planned for SLB, but in the meantime, you can use `[slb_exclude]` to exclude content from being activated by SLB.

See SLB's shortcode documentation for [more information on using `[slb_exclude]`](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_exclude).

**Comment by michaelezra** [comment]
Thanks for a quick reply. Will I get a notification on a wp dashboard when new version is released?

**Comment by archetyped** [comment]
As long as you haven't disabled update notifications for your site, you should receive notifications for updates to all installed themes/plugins (including SLB) in your admin dashboard.
