### ISSUE TITLE
Compatibility with Visual Composer Grids

### ISSUE THREAD

**Issue by paula444** [archetyped/simple-lightbox#509]
Hello

My website is at www.paulamorison.com
I have used Visual Composer to create the image grids on the project pages.
I have downloaded Simple Lightbox but this is only working on images that I have added directly into the page and not any that I have added using a grid.
For example this image is working with the lightbox http://www.paulamorison.com/contact/
But these one aren't http://www.paulamorison.com/project-001/

Please could you advise as to how I might make this work on the other images too? I am not sure what I have done wrong...

Please excuse the face there are 2 lightboxes on the page that is working - I tried out another one to see if the problem worked with other plugin lightboxes (it does).

Many thanks and all best wishes

Paula

**Comment by archetyped** [comment]
Hi, SLB will work with links added by other plugins as long as that plugin follows WordPress standards.  I have contacted Visual Composer's developers to request access to the plugin to take a closer look into your issue, but as a paid plugin, I may not be able to investigate this further.

I will update this ticket when I have any news.

**Comment by paula444** [comment]
Thanks so much. I look forward to hearing from you.

**Comment by archetyped** [comment]
Hi, Visual Composer loads grid content separately via AJAX after the rest of the page has loaded.  Additionally, Visual Composer does not use standard WordPress hooks to allow other plugins to interact with content in grids.

As a result, the only way to activate links in Visual Composer's grids is via an add-on.  I've created a [ticket to track the development of this add-on](526).  Please post any comments you have for the add-on there.

Thanks.
