### ISSUE TITLE
Request: Show caption on the right side of image

### ISSUE THREAD

**Issue by vikktor** [archetyped/simple-lightbox#510]
## Description of feature/request
Add template that would show caption/description on right side of the image just like on facebook images instead of bottom like it is right now. Almost none of the current lightbox plugins for wordpress can do that so many people would download and use your plugin. 

## This feature would be used to
Show  caption/description on right side of image

## If you added this feature, I would:

a) Love you soo much!

**Comment by archetyped** [comment]
Howdy, thanks for the request!  SLB's themes can actually be fully customized by anyone to get exactly the look you want.

Here's a tutorial to help you get started: [Simple Lightbox: Anatomy of a Theme](https://archetyped.com/know/slb-theme-anatomy/ "Simple Lightbox: Anatomy of a Theme")
