### ISSUE TITLE
Issue: Will not function on custom page template

### ISSUE THREAD

**Issue by jlbworks** [archetyped/simple-lightbox#511]
## Description of Problem

The plugin works well on all other pages in the site but will not function within a custom template single-listing.php and all pages with that template.  Any ideas on how to integrate functionality to all pages and not just those available in general settings?

Thanks!

## Details

* URL of Page exhibiting problem: http://www.yourlandmark.com/our-listings/1829-b-11th-ave-n/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): I am using Chrome, client using Firefox
* Version of SLB Installed: Latest version: 2.5.3
* Other plugins installed: Plugin creating the custom page template is IMPress Listings

**Comment by archetyped** [comment]
Hi, I would recommend checking to see if the custom page templates use the necessary WordPress template tags [as noted on SLB's requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#theme).  Any well-made theme should use these tags, so I would recommend using a different theme or contacting the theme's developer if the theme doesn't use them.

If the theme uses the necessary template tags and you are still experiencing an issue with SLB, please fill in the rest of the details for your issue and I would be glad to take a closer look.

**Comment by jlbworks** [comment]
Hi,

Yes the theme works correctly with all the tags mentioned in the requirements, as well as the custom page template, everything is there.  Yet, the SLB still does not work as intended.

[http://www.yourlandmark.com/our-listings/1829-b-11th-ave-n/](url)
On the page linked above you will find three tabs, Details, Photos, and Floor Plan Gallery

The two latter tabs have images, when clicked the images are intended to open in SLB but do not - they open the media attachment page. 

Any ideas on how to resolve?  I appreciate your time and insight!

**Comment by jlbworks** [comment]
URL of Page exhibiting problem: provided in comment above
Browser(s) exhibiting problem (Firefox, Chrome, etc.): I am using Chrome, client using Firefox
Version of SLB Installed: Latest version: 2.5.3
Other plugins installed: Plugin creating the custom page template is IMPress Listings

**Comment by archetyped** [comment]
Hi, it appears that the IMPress Listings plugin is generating the output using `do_shortcode()`, which prevents any other plugin (including SLB) from processing the output any further.  As a result, the links photo gallery generated by the plugin cannot be activated by SLB.

I would recommend contacting IMPress Listings' developer and requesting that they enable its output to be filtered like standard post content.

Once the plugin's output is filtered in the same way as post content, SLB should be able to activate the photo links for displaying in the lightbox.  Please let me know if you are still experiencing an issue with SLB once IMPress Listings has added the necessary functionality and I would be glad to reopen this ticket and take another look.
