### ISSUE TITLE
Issue: Lightbox not vertically centering on mobile

### ISSUE THREAD

**Issue by janekkrause** [archetyped/simple-lightbox#512]
## Description of Problem

It seems the lightbox doesnt function properly on mobile and aligns to the top of the screen instead of the center.
## Details
- URL of Page exhibiting problem:  http://timandrabythesea.com.au/open-garden/
- Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Firefox, IE
- Version of SLB Installed: Latest
- Other plugins installed: Disable Comments, Display Widgets, Duplicate Post, Enable Media Replace, Genesis eNews Extended, Genesis Responsive Slider, Ninja Forms,  
  Regenerate Thumbnails, Simple Social Icons, SiteOrigin CSS, SiteOrigin Widgets Bundle, WP Edit

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  SLB's default themes are designed to align to the top of the screen on small-screen devices to make the most of the limited screen area.

Themes have full control over the layout and display of the lightbox though, so you can [create a custom lightbox theme](http://archetyped.com/know/slb-theme-anatomy/) that is tailored to your specific needs.
