### ISSUE TITLE
Problem Compiling with Sass

### ISSUE THREAD

**Issue by DocWhitaker** [archetyped/simple-lightbox#514]
I'm probably missing something obvious here, but I can't get the .scss files compiling into valid css. I've been trying to customize the baseline 'style.scss' but am getting errors because it is referencing an import and a mixin that aren't in the downloadable files (or so I think).

```
//Imports

@import "bourbon";

//Variables

//Mixins

%box-sizing-border-box {
	@include box-sizing(border-box);
}
```

I assume they are entirely necessary to compile the a working baseline 'style.css' file, so where can I get them? Or if I'm completely missing the point then I'm prepared for a riotous knowledge slap.

**Comment by archetyped** [comment]
Hi, Bourbon is a development dependency, which needs to be installed (along with other development dependencies) via NPM using the following command:

```
npm install
```

Once the dependencies are installed, Sass files should compile without issues and the rest of SLB's Grunt tasks can be used as well.

**Note:** Bourbon has already been removed from SLB's next update.
