### ISSUE TITLE
Request: Maximize button on picture view

### ISSUE THREAD

**Issue by Spiros94** [archetyped/simple-lightbox#518]
## Description of feature/request
When a user clicks on a picture, the picture (if selected) opens in a modal box that fits the browser's size. In the upper right there is a button for closing this modal window(an "x" button). Beside the close button could be added a button that maximizes the picture in the original size of the image if it's larger than the browser's window size.

## This feature would be used to
For a example pictures that have more detail, for example some text that has to be a greater size in order to view the text.

## If you added this feature, I would:

a) Eat my hat <--- and would be very happy!!!
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, please add any thoughts or comments you have to the existing request for this feature.

[Request: Full Size Image](288).
