### ISSUE TITLE
Lightbox not working 

### ISSUE THREAD

**Issue by slaaffrank** [archetyped/simple-lightbox#519]
## Description of Problem

The lightbox isn't working..

## Details

* URL of Page exhibiting problem: http://meesteresnatalie.nl/fotos-2/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
* Version of SLB Installed: latest (2.5.3)
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, that link does not appear to work.  Please provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to take a look.

**Comment by slaaffrank** [comment]
Good morning, tx for your email. The website is www.meesteresnatalie.nl.
.tx! Gr. Frank

Op dinsdag 6 september 2016 heeft Archetyped <notifications@github.com> het
volgende geschreven:
> Hi, that link does not appear to work. Please provide an updated link to
a page that exhibits the issue you are experiencing and I would be glad to
take a look.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/KgrfIEdyHMvGEnr1KGND52weth5KbjslyEGGzm9RcAGAUGgH3eVsd5NxveoYIIwgh6ajL0ilBMqe7hQkS0QjolJueFTuKf7GqeOeNBlnDdl_7Wl6htAnnZmx8VyObziB6G00x5PrHf3w23qO1bfOEJLiqGXbsA=s0-d-e1-ft#https://github.com/notifications/beacon/AU9qVTLZZFpS4KXncOPyMNNxPf_KHx0vks5qnNzxgaJpZM4J0eVt.gif>

**Comment by archetyped** [comment]
Hi, the images on that page are not linked.  Without links, there is nothing for visitors to click on, and nothing for SLB to know what you want to be displayed in the lightbox.

See this page for [help on adding links to images in WordPress](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts).
