### ISSUE TITLE
Issue: Plugin not compatible with Valenti Theme Galerie Post

### ISSUE THREAD

**Issue by alfonsberger** [archetyped/simple-lightbox#520]
## Description of Problem
I'm using the Valenti Theme (Version 5.4) but the SLB Plugin does not work on the themes custom gallery posts.

## Details

* URL of Page exhibiting problem: http://shoutkey.com/knee (link expires in 24h)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  All
* Version of SLB Installed:  2.5.3 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, are you referring to the large image in the slider/carousel widget?  That widget uses FlexSlider, which is currently not supported by SLB due to the way it loads images.  FlexSlider may be supported by SLB via an add-on in the future.
