### ISSUE TITLE
page slow to download

### ISSUE THREAD

**Issue by hilandrews** [archetyped/simple-lightbox#522]
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by hilandrews** [comment]
I have simple light installed in my website and for months it has been working well.  Over the last few weeks my site has been very slow to open and the slide show is acting up.  I upgraded the plugin but that has not helped but when I go to the plugin it does have a red "reset" link and I am wondering if I should click on it.

**Comment by archetyped** [comment]
Hi, it appears you also posted this in WordPress' support forums.  I've replied to that post, so I'm closing this ticket so that we can keep all further discussion in one place.

Thanks.
