### ISSUE TITLE
Fixed Position Lightbox

### ISSUE THREAD

**Issue by DocWhitaker** [archetyped/simple-lightbox#523]
I've been attempting to change the positioning of the lightbox from 'absolute' to 'fixed', but I can't seem to get it working just with CSS alone due to the code that positions the lightbox relative to the page scroll.

Is there a simple way to get rid of that calculated offset? I couldn't find it in the code myself.

**Comment by archetyped** [comment]
Yes, SLB themes have full control over layout.  For example, the default themes set the vertical position during the `open` transition event.

Take a look at `themes\default\js\dev\client.js` in SLB's folder for more details on what is done to the lightbox during lightbox state.

Though not ideal, you can always use `!important` in your custom CSS rules to override default styles (including dynamically-set inline rules).

Also note that using `position: fixed` prevents visitors from viewing the entire lightbox content when it is larger than the viewport.  This is why this property is not used in SLB's included themes, but if you're certain the lightbox on your site will never be larger than the viewport (including the title, description, etc.), then have at it.
