### ISSUE TITLE
Request: can this work with booking software

### ISSUE THREAD

**Issue by angelconcierge** [archetyped/simple-lightbox#525]
## Description of feature/request

I need to know like for AngelConcierge.com/destinations/hawaii/Oahu there's a book now button near the ohana circle island tour, I want that to open up in a lightbox 

## This feature would be used to

Book tours and activities 

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, SLB can be extended to support virtually any type of content via custom add-ons.  The most likely option would be an add-on for displaying web-pages in a lightbox, [which you can vote on here](394) if you would like to see it made.

**Comment by angelconcierge** [comment]
Well I would like to see it made ASAP, how much will it cost for you to do
it?

**Comment by angelconcierge** [comment]
When can we get this working?

**Comment by archetyped** [comment]
Hi, as noted in the add-on's ticket I linked to in my previous reply, add-ons are developed based on demand, so adding your comments to the ticket is the best way to cast your vote to for which add-ons should be prioritized.
