### ISSUE TITLE
Issue: Video Add-on not working

### ISSUE THREAD

**Issue by redressonline** [archetyped/simple-lightbox#531]
Hello,
I installed the simple video light box on my Wordpress site but some videos do not work properly on iPhone and iPad. For example, click on the "video" hyperlink on this page
http://www.redressonline.com/2016/09/south-african-man-held-hostage-and-left-begging-for-food-by-israels-merciless-system/

**Comment by archetyped** [comment]
Hi, please use the link in the Read-me.html included with the add-on to request support for the video handler so that you can get the most focused support for the issue you are experiencing.

Thank you.
