### ISSUE TITLE
Issue: Idiot using SLB for first time!

### ISSUE THREAD

**Issue by yougodo** [archetyped/simple-lightbox#532]
## Description of Problem
Hi - I'm trying to set up my first lightbox image galleries on a wordpress site.  I have installed the plugin and activated it.  

I then looked for what else I need to do (any coding, etc) and it looks like 'nothing?

But it does not seem to be working.

## Details

* URL of Page exhibiting problem: 

Website is marbellacomplex.com (pre release so password ferrari)

My simple test page with a few images - http://marbellacomplex.com/index.php/2016/10/06/test-lightbox-2/ 

The portfolio based images I would like to see with lightbox are on the Image Gallery page - see top menu.

Help!  Theme is Prodo and it is WordPress 4.6.1 running Prodo theme.

Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it does not look like there are any image links on that page.  Without links, there is nothing for a user to click on to launch the lightbox.

See SLB's documentation for [more details on adding image links to your posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts).  Let me know if you're still experiencing a problem once you've added some image links to the post and I would be glad to reopen this ticket and take another look.
