### ISSUE TITLE
AJAX Loading images

### ISSUE THREAD

**Issue by danyg790** [archetyped/simple-lightbox#534]
Hello, I am using AJAX to load more images to the screen, I am trying to use the function from the functions.php page and it looks like all the attributes are there for the light box, however when I click the link, it does not open the image in a lightbox. I am using slb_activate() to add the images to the lightbox, however they are not opening in the light box. 

Code: 

```php
$loop = new WP_Query($args);
    $out = '';
    if ($loop -> have_posts()) :  while ($loop -> have_posts()) : $loop -> the_post();		
		$post_id = get_the_ID();
		$url = get_the_post_thumbnail_url($post_id, 'full');
		$img = get_the_post_thumbnail_url($post_id, 'thumbnail');
		$title = get_the_title();
		
		$content = '<a href="'.$url.'" title="'.$title.'"><img src="'.$img.'" /></a>';
		//if ( function_exists('slb_activate') )
			$content = slb_activate($content);
		
		$out .= '<div class="auct_itm_img">'.$content.'</div>';

    endwhile;
    endif;
    wp_reset_postdata();
	die($out);
}
```

**Comment by archetyped** [comment]
Hi, AJAX-loaded content is not currently supported.  See [this existing ticket for more details and discussion on the add-on for AJAX support](https://github.com/archetyped/simple-lightbox/issues/208).
