### ISSUE TITLE
Feedback: great gallery plugin

### ISSUE THREAD

**Issue by TheBeatCorner** [archetyped/simple-lightbox#535]
I have been looking around for a good gallery plugin for my photo work. Most gallery plugins, very expensive ones included, are really bad. Bad cosmetics, horrible functioning, etc.
Simple Lightbox is for me the best. I do have some ideas about making it even better though.
I will put these thoughts into a feature request mail.

Thanks, Beat

**Comment by archetyped** [comment]
Thanks for the feedback!  Glad to hear SLB works well for you :)
