### ISSUE TITLE
Request: change font in gallery

### ISSUE THREAD

**Issue by TheBeatCorner** [archetyped/simple-lightbox#537]
## Description of feature/request

Add the choice for different fonts in the Lightbox settings.
## This feature would be used to

stylize my gallery better.
## If you added this feature, I would:

Shave myself.

Thanks, Beat

**Comment by archetyped** [comment]
Thanks for the request. Additional options for customization is indeed planned for the future.

**Comment by JayHoltslander** [comment]
+1
(But considering this has been planned since 2016...)

**Comment by senlin** [comment]
Not only should it be possible to change the font, I think it should also be possible to simply remove the font in favour of what the theme is using.

**Comment by brent-langdon** [comment]
Too bad this request has not been addressed as this is a pretty basic problem.  It would be one thing if the plug-in used a very basic font, but the baked in font (Yanone Kaffeesatz) stands out a bit too much.

I am not the best with CSS selectors, and the specific elements don't have an id, but the following worked for me (where Poppins is the font I have specified for my theme).  This changes the font on the Title and "Item X of Y" labels.

```
span.slb_template_tag_item_title,
span.slb_template_tag_ui_group_status
{
    font-family: 'Poppins';
}
```

**Comment by archetyped** [comment]
Apologies for not updating this thread sooner.  All visual aspects of the lightbox (including fonts) are now controlled by the selected lightbox theme.  Creating a custom theme with HTML and CSS (and custom JavaScript if you want to get fancy) allows the lightbox's appearance to be fully customized.

See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for tutorials on creating a custom theme.

Thanks.
