### ISSUE TITLE
Issue: Disable Looping

### ISSUE THREAD

**Issue by DavidManning** [archetyped/simple-lightbox#538]
## Description of Problem
Cannot disable looping of images as it it default enabled.
How to disable?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, looping can be disabled by unchecking the "Loop through items" option in SLB's settings.

**Comment by DavidManning** [comment]
I did that, but it still loops on woocommece single items, such as on this site: https://pinballmedics.ca/product/1979-williams-time-warp-pinball-machine/

**Comment by archetyped** [comment]
Hi, thanks for the link to an example page.  The lightbox being used on that page is the one included with WooCommerce, not SLB.

[SLB's WooCommerce Add-on](https://archetyped.com/lab/slb-woocommerce-beta/) allows you to use SLB on WooCommerce product pages instead of the default lightbox.

**Comment by DavidManning** [comment]
Okay, that clears it up. The link on the plugin's "Feedback & Support" sent me directly here so I thought it was a separate install. I'll contact Woocommerce about it.
Thanks for your time. :)
