### ISSUE TITLE
Request: Disable Scrolling when lightbox open

### ISSUE THREAD

**Issue by Netbytes-CMF** [archetyped/simple-lightbox#539]
## Description of feature/request
The lightbox should remain centered in the window/view.  When someone scrolls it's too easy to loose track of the lightbox's location.

## This feature would be used to
Enhance usability.

## If you added this feature, I would:
Where's 'e'?  ;-)
a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, scrolling is enabled to allow the entire lightbox to be viewed when the content is larger than the browser window (e.g. large images, long captions/descriptions, etc.).

See these previous tickets ([here](https://github.com/archetyped/simple-lightbox/issues/523) and [here](https://github.com/archetyped/simple-lightbox/issues/397)) for more details.
