### ISSUE TITLE
Request: Image Enlargement

### ISSUE THREAD

**Issue by sashakrasnov** [archetyped/simple-lightbox#540]
Hi there!
## Description of feature/request

On my personal site (skrasnov.com) all images become full width when on smartphones, but not on various pads. On most pads it is displayed as desktop version. So, on smartphones the images need no lightbox enlargement, because they do not get an actual enlargement. It will be very cool if you will add feature of "no enlargement" if image is allready full width. Full width -- from left side of mobile to right side of mobile.
## If you added this feature, I would:

c) Shave my cat

**Comment by archetyped** [comment]
Hi, images are never enlarged beyond their actual resolution in the lightbox on any device or screen size.  If you are experiencing different behavior than this, please post a screenshot and I would be glad to take a look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by sashakrasnov** [comment]
I do not. But the visitors do. It's not a problem of course. But there is a strange thing... I've added js-code from smartlook.com that registers any mouse actions on my site. So, you may watch them actions on the site like a movie. I've noticed that almost all visitor using smartphones vertically oriented clicks on images that is allready full width wanting them to enlarge. I don't understand their motivations. But why not to disable this feature on smartphones if image is allready full width displayed?

Anyway thank you very much for the plugin, it really helps me!

**Comment by archetyped** [comment]
Ah, if I understand correctly, you're saying that you don't want a lightbox to be displayed when the image displayed on the page is as wide as the screen?

SLB simply displays links when a link is clicked.  Opening the lightbox only when certain links are clicked (e.g. based on the thumbnail image's width) would create inconsistent behavior for visitors, where some links do something and other do nothing.  This is not something that SLB does.

If your request is for different behavior, please provide a bit more detail on what you would like to see and I would be glad to reopen this ticket and take another look.

Thanks.
