### ISSUE TITLE
Issue: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.

### ISSUE THREAD

**Issue by eminusII** [archetyped/simple-lightbox#541]
## Description of Problem

Clicking on the link still redirects to actual youtube page and throws error in client.

## Details

http://www.candis.io/homepage-2/

SLB version 2.5.1

Other plugins:

![image](https://cloud.githubusercontent.com/assets/12788491/19772208/c6e0a3ca-9c65-11e6-9acf-af75cd2090cd.png)

**Comment by archetyped** [comment]
Hi, your site is loading multiple versions jQuery, including an outdated version.  SLB only supports the version of jQuery officially supported by WordPress itself.  See here for more information: [jQuery Support](https://github.com/archetyped/simple-lightbox/wiki/jQuery-Support).
