### ISSUE TITLE
Issue: Distored Images

### ISSUE THREAD

**Issue by NickSatoria** [archetyped/simple-lightbox#543]
## Description of Problem

Some images are distorted. Can't figure out why.

## Details

* URL of Page exhibiting problem: http://www.kutter-galabau.de/pressespiegel/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Every browser I've tested so far.
* Version of SLB Installed: 2.5.3
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it looks like your theme adds CSS that limits the dimensions of images in the lightbox.  Removing these rules should allow SLB to display the images with the proper proportions.

**Comment by NickSatoria** [comment]
Hi, there!

THX for your help and support! Yes, it was a 'max-width_'- and 'max-height_'-attribute, that caused the issue! Looks like it's all fine and dandy right now. ;-)

Cheers!

**Comment by archetyped** [comment]
Awesome!
