### ISSUE TITLE
Issue: Responsive

### ISSUE THREAD

**Issue by jeffrossiter** [archetyped/simple-lightbox#544]
## Description of Problem

Simple Lightbox works perfectly except that it is not responsive.

## Details

* URL of Page exhibiting problem: http://ownprop.com/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Internet Explorer
* Version of SLB Installed: Version 2.5.3
* Other plugins installed: Flexible Map, SG CachePress
* Theme: REHub

**Comment by archetyped** [comment]
Hi, can you please provide more details on how SLB is not responsive for you?  The lightbox was responsive when I tested your site on a variety of devices.

**Comment by jeffrossiter** [comment]
Thanks very much for your quick response - brilliant!

On mobile devices (Android) SLB fits to the screen width, which is fine, but the problem is that on PCs SLB crops the right hand edge when the window width is reduced.

Here are two screenshots:

<img width="947" alt="slb-full-screen" src="https://cloud.githubusercontent.com/assets/4216277/19918851/60f91396-a0d7-11e6-9f13-dd2fb0265053.png">
<img width="398" alt="slb-small-screen" src="https://cloud.githubusercontent.com/assets/4216277/19918852/60fb7064-a0d7-11e6-9f40-b25587399bf6.png">

**Comment by archetyped** [comment]
Glad to hear all is well :)
