### ISSUE TITLE
Issue: Image links refresh page and do not produce a lightbox effect

### ISSUE THREAD

**Issue by bdosono** [archetyped/simple-lightbox#545]
## Description of Problem

Simple Lightbox plugin not working. Image links do not produce a lightbox effect. (See links in the page "Member directory.")

## Details

* URL of Page exhibiting problem: http://uwlambdas.com/brothers/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Firefox
* Version of SLB Installed: 2.5.3
* Other plugins installed: Askimet, AmberPanther Favicon for WordPress, Broken Link Checker, Contact Form 7, Google Analyticator, Huzzaz Video Gallery, kPicasa Gallery, Rich Text Excerpts, Salient Visual Composer, Simple Calendar, Table Press, TablePress Extension: Responsive Tables, Ultimate Tag Cloud Widget, Visualizer: Charts and Graphs Lite, Yoast SEO

**Comment by archetyped** [comment]
Hi, it looks like your site's theme adds some code that intercepts all clicks to add a fade out transition whenever a link is clicked.  This code forces the browser to load the link directly, overriding SLB's behavior (and any other plugin that interacts with links).

SLB should be able to functionality normally once this overriding code is removed.  You can confirm this by activating a different theme (e.g. Twenty-Twelve or other default WordPress theme) and testing an image link.  I would recommend checking the theme's settings to see if the transition can be disabled.  If not, I would recommend contacting the theme's developers for instructions on disabling this behavior to allow other plugins to work with links once again.
