### ISSUE TITLE
default title still showing if linked to a custom image size

### ISSUE THREAD

**Issue by carles-enraona** [archetyped/simple-lightbox#546]
## Description of Problem
It's probably an unusual problem that happens when you have "Enable default title" unchecked: Let's say you upload my-image.jpg and wordpress sets the default title to "my-image". If If you then link to a custom image size in your post, (i.e. 600x600), the default title will still appear, because the url of the image is my-image-600x600

## Details
Seems that in lib.view.js, get_title checks if the title of the image is autogenerated comparing it to the current url of the image:

if ( title === f ) {title = '';}

so when it compares "my-image" to "my-image-600x600" it fails

maybe you should use indexof instead

if (f.indexOf('title')==0){title=='';}

**Comment by archetyped** [comment]
Hi, that option is for media attachments that have the default title created when the image is initially uploaded.  Intermediate image files (e.g. `my-image-600x600.jpg`) are not recognized by WordPress as attachments, so they do not have default titles.

The title you are seeing may be generated in a different way ([more details here](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence)).  If you are unable to track down the source of the title, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
