### ISSUE TITLE
Issue: Can't get lightbox to work

### ISSUE THREAD

**Issue by ByronPSmith** [archetyped/simple-lightbox#547]
## Description of Problem
I have WordPress 4.6.1 installed locally on my PC.
I have enabled the network option to test various themes for my blog.
I am using the wordpress 2016 theme.  (This is the 2nd theme I have tried SLB on)
I installed simple-lightbox and enabled and used all the default settings.
None of my media pictures will open in a lightbox.  When hovering over the image the cursor does not change.
Am I supposed to be doing something else to enable this feature?

## Details

* URL of Page exhibiting problem: http://localhost/wordpress/test1/  (Home page)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Chrome
* Version of SLB Installed: 2.5.3

* Other plugins installed: Increase Upload Max File Size
![capture](https://cloud.githubusercontent.com/assets/23249808/19991373/1caf7ce0-a20b-11e6-8c19-ce35eb4f1508.PNG)

**Comment by archetyped** [comment]
Hi, if the mouse cursor is not changing when you hover over an image, then it sounds like you haven't added links to them.  Without links, they are simply images on the page, not something a visitor can click on to launch the lightbox.

See [WordPress' official documentation on adding links to images](https://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link).

If you are still experiencing the same issue after adding links to the images, please provide a link to a publicly-accessible page (localhost is not accessible to others) and I would be glad to reopen this ticket and take a look.

**Comment by ByronPSmith** [comment]
Thank you.  That was most helpful.
