### ISSUE TITLE
Issue: Can't disable grouping of more than one gallery on a single site

### ISSUE THREAD

**Issue by bullviech** [archetyped/simple-lightbox#548]
## Description of Problem
I have some sliders ("Zur Bildgalerie...") linked on this site. If i go at the first image back i come to the slider before. I want all sliders on their own. How can i acchieve that?

I also do have the problem that the lightbox is aligned to the top on mobile deviced and not centered as on desktops.

pls help!

## Details

* URL of Page exhibiting problem: http://www.entwicklungsumgebung.at/mphoto2016/fotoshootings-salzburg/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All browsers
* Version of SLB Installed: recent
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, you can use the `[slb_group]` shortcode to group links into separate slideshows.  See [SLB's shortcode documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_group) for more details.

See [this existing ticket](https://github.com/archetyped/simple-lightbox/issues/512) for more details on the lightbox's appearance on mobile devices.

If you need further assistance, please provide a link to a page that exhibits the issue you are experiencing (the link you provided returns a "page not found" error) and I would be glad to reopen this ticket and take a closer look.

Thanks.

**Comment by bullviech** [comment]
oh, i'm sorry: https://www.mphoto.at/fotoshootings-salzburg/ this is the link where's the slb integrated

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided a link to.  If I missed them, please let me know where on the page the image links are, otherwise, please provide an alternate link to a page with image links that are displayed in the lightbox.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
