### ISSUE TITLE
Issue: bbPress attachments double photos in lightbox

### ISSUE THREAD

**Issue by per4mance** [archetyped/simple-lightbox#549]
## Description of Problem

jpg files attached to bbPress plugin with GD bbPress Toolbox plugin (for bbPress) doubles the images in lightbox. After clicking one attachment (in my case exists two jpg files) your plugin shows 4 photos from 1 to 4. Photos 1/2 are the same and photos 3/4 too. So a user clicks e.g. the arrow to the right and sees the same photo after one click before change to the next.

## Details

* URL of Page exhibiting problem: https://www.socialmediaschule.org/gruppen/hilfe-support/forum/topic/wie-aktualisiere-ich-mein-profil-und-titelbild/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all browsers
* Version of SLB Installed: 2.6.0
* Other plugins installed: bbPress, GD bbPress Toolbox and many others

**Comment by archetyped** [comment]
Hi, I don't see any image links at the link you provided.  Please let me know when image links have been added to the page (or provide an alternative link) and I would be glad to take another look.

**Comment by per4mance** [comment]
Hi,

 

please take a look to the attached files or try this link:

 

https://www.socialmediaschule.org/gruppen/hilfe-support/forum/topic/wie-aktualisiere-ich-mein-profil-und-titelbild/ 

 

Best Regards,

Thorsten

 

Von: Archetyped [mailto:notifications@github.com] 
Gesendet: Dienstag, 15. November 2016 23:56
An: archetyped/simple-lightbox <simple-lightbox@noreply.github.com>
Cc: Thorsten Wollenhoefer <thorsten.wollenhoefer@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [archetyped/simple-lightbox] Issue: bbPress attachments double photos in lightbox (#549)

 

Hi, I don't see any image links at the link you provided. Please let me know when image links have been added to the page (or provide an alternative link) and I would be glad to take another look.

**Comment by archetyped** [comment]
Thanks for the link.  Both the thumbnail image and the caption text contain a link to the same image, which is why it is being displayed twice in the lightbox.

I would recommend removing the duplicate links on the page for each image (e.g. from the caption).  This will remove the duplicate links from the lightbox.

If you can provide a link to the plugin that is adding the duplicate link to the page, I would be glad to take a look to see if anything can be done from SLB's end.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
