### ISSUE TITLE
Issue: I don't want alt-text to appear in the opened lightbox

### ISSUE THREAD

**Issue by alon737** [archetyped/simple-lightbox#550]
## Description of Problem
Hi, how do I make the alt-text not appear in the opened lightbox? It's perfectly fine that the caption appears, I just want the alt text out of there.

Thanks.

## Details

* URL of Page exhibiting problem: http://harmonicajamz.com/best-beginner-harmonica/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, I could not find any image links at the link you provided that displayed the image's alt text.  Can you please specify which image displays the alt text in the lightbox?

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
