### ISSUE TITLE
SLB with custom post types

### ISSUE THREAD

**Issue by therethere** [archetyped/simple-lightbox#555]
Hello there,

Really love your plugin.
Do SLB supports custom post types? If so, how can i activate it?

Here is a demo link, check multimedia section:
https://goo.gl/0499XW

Many thanks!

**Comment by archetyped** [comment]
Hi, custom post types (CPT) are fully supported and are activated automatically by SLB.  However, theme templates for CPTs must meet the [same requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#theme) as the template for standard post/pages to work properly with SLB.  This is what I would check first if SLB is working fine with standard posts, but not with CPTs.

If you are still experiencing an issue, then [you may want to check for conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) with any plugins you are using to add links to the post (e.g. page builders, gallery plugins, etc.).

Let me know if you find a conflict with a specific plugin and I would be glad to reopen this ticket and take a closer look.

**Comment by therethere** [comment]
Hey, thanks for the feedback. I suppose the problem is that I'm not using the_content on those CPT, only header and footer. The links I want to activate SLB are outside the_content. Is there a way I can activate SLB manually on these links?

Many thanks.

**Comment by archetyped** [comment]
Yep! See [SLB's documentation on manual activation](https://github.com/archetyped/simple-lightbox/wiki/Activation) for full details.
