### ISSUE TITLE
Description not visible on landscape images

### ISSUE THREAD

**Issue by hpthatsme** [archetyped/simple-lightbox#556]
I have checked the html output, the descriptions simply do not appear when the image is wider than it is tall:

**Site:**
http://catalystts.website/portfolio/

**SLV Version:**
SLB Version 2.6.0 

**Plugins:**

- AG Custom Admin
- All-in-One WP Migration
- Autoptimize
- Beaver Builder Plugin (Pro Version)
- Comet Cache
- Contact Form 7
- Current Year and Copyright Shortcodes
- Custom CSS - Whole Site and Per Post
- Disable Comments
- EWWW Image Optimizer
- Meta Slider
- Responsive Gallery Grid
- TinyMCE Advanced
- Wordfence Security
- WP Smush
- WP Testimonials with rotator widget
- Yoast SEO

Tried in Chrome, Opera, Edge

**Comment by archetyped** [comment]
Hi, SLB is not affected by an image's proportions.  However, the issue appears to be that the thumbnails in question are linked to an intermediate image, not the original.  Intermediate images are not recognized by WordPress as part of the media library (where the description is stored), hence no description is found for the image.

Linking to the original images (as is done for the first thumbnail on the page and a few others) will allow WordPress to retrieve the appropriate description for each image.

**Comment by hpthatsme** [comment]
I did not actively choose an intermediate image.  Did that happen because the lightbox was trying to compensate for filling the screen, therefore choosing an intermediate with the appropriate height?

In any case, I changed all of my thumbnails to portrait layout and it worked fine.  It was the only way I found to avoid the intermediate image being displayed.  Please advise if there is a setting I could have used instead.

**Comment by archetyped** [comment]
How are you adding the links to the post?  SLB has no control over the links that are added to the post.  It only displays them in the lightbox.

**Comment by hpthatsme** [comment]
I'm adding them using the standard "Add Media < Create Gallery" method.

**Comment by archetyped** [comment]
Hi, I took another look and it looks like the "Responsive Gallery Grid" plugin you are using modifies links in galleries, replacing original links with intermediate images.  I would recommend contacting the developer of this plugin to see if this can be disabled.

**Comment by hpthatsme** [comment]
thanks for solving it! sorry to bug you.
