### ISSUE TITLE
No functioning after installation

### ISSUE THREAD

**Issue by sushinger** [archetyped/simple-lightbox#557]
## Description of Problem

I have freshly installed the plugin my site, activated and expected it to work on all existing image-posts, such as http://hilfe.macbay.de/mail-probleme-mit-dem-telekom-speedport/

but when clicking the image nothing happens.

## Details

* URL of Page exhibiting problem: 
http://hilfe.macbay.de/mail-probleme-mit-dem-telekom-speedport/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Any Browser

* Version of SLB Installed: 
Version 2.6.0

* Other plugins installed: 
Check the List here -->
https://www.evernote.com/shard/s3/sh/fb49d30f-f5fd-4850-a60e-e523b937760f/5c8be25276f50c84e452b47ac5c09320

**Comment by archetyped** [comment]
Hi, SLB appears to be functioning normally on the page you providing.  The image is displayed in the lightbox when the link is clicked.

I would recommend clearing your browser's cache and refreshing the page to ensure that you are viewing the latest version of the page.
