### ISSUE TITLE
After installing ssl the plugin still showing http images

### ISSUE THREAD

**Issue by tomcruise624** [archetyped/simple-lightbox#558]
## Description of Problem

After I use ssl, the plugin still shows the images with the http version, I added redirect code in .htaccess and makesure that everything is fine, also im forcing ssl in caching plugins & cloudflare, after I flush caches, the images still showing http version.

Regards,
Dev

## Details

* URL of Page exhibiting problem: https://www.decorationy.com/interior-design/bathroom/before-and-after-bathroom-remodel-ideas
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB simply displays the images linked in the post/page.  If the links are HTTP, that is what will be loaded.

If you are still experiencing an issue with SLB, please fully complete the details of your issue above and I would be glad to take a closer look.

**Comment by tomcruise624** [comment]
I`ve redirect everything to https by using htaccess code, the images shows as https, but when i click to display image with lightbot it make a padlock and the images shows http.

Details

ex. url : https://www.decorationy.com/interior-design/bathroom/before-and-after-bathroom-remodel-ideas

Browsers: Firefox, Chrome

Regards,
Dev

**Comment by archetyped** [comment]
Hi, are you using a plugin to update links to https on the fly?  It looks like SLB is seeing the post content with standard http links, then another plugin is changing those links before loading the page in the browser.

To avoid this, fully migrating the site's content (i.e. the content stored in the database) to use https is recommended.
