### ISSUE TITLE
Issue: Creating a theme that excludes some functions and fades out the arrows in Simple Lightbox

### ISSUE THREAD

**Issue by ProductionArtDepartment** [archetyped/simple-lightbox#560]
## Description of Problem
Hello,
Thank you for Simple Lightbox. It is the best lightbox plugin I've found for Wordpress. I have just purchased the video plugin. I have a basic but sound working knowledge of html and css. I require to alter the following things in the lightbox:

* remove the play icon and the close icon in the top right corner (clicking the overlay to close is intuitive, and ensures that no icons interfere with the image)
* remove the "item' text beneath the image (I would just like a short description beneath the image)
* make the arrows completely fade away when you rollout of the image area and onto the overlay

I'm having trouble following your blog post tutorials. I am using the Divi theme, and have made a child theme. I know to put the CSS in the child theme, but I cannot understand where to put the layout html, how to properly mark it up, and where to put the javascript to link the new layout into the plugin.

I would be very grateful for your help.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, when you say that you've made a child theme, are you referring to a child of your site's theme, or a child of one of SLB's existing lightbox themes?  Creating a new lightbox theme, or a light child of an existing lightbox theme is required for full control over the lightbox's appearance and behavior.

Here is [a tutorial on creating a custom lightbox theme](https://archetyped.com/know/slb-theme-anatomy/).  You mentioned that you've looked at a tutorial on the site, but this one basically answers all of the questions you asked (it even includes a downloadable starter theme for you to use), so let's start with that.

Let me know where you're getting stuck in that and we'll go from there.

**Comment by ProductionArtDepartment** [comment]
Thank you very much for getting back to me! I've been caught up with other aspects of the website currently, but I will take a look at the tutorial, and then get back to you. Thanks very much. Will be in contact soon.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
