### ISSUE TITLE
(HELLO. I HAVE A ERROR WITH SLB, WP4.7.1 THE RESET NO WORK.... :-/)

### ISSUE THREAD

**Issue by jesmar1973x** [archetyped/simple-lightbox#562]
HELLO. I HAVE A ERROR WITH SLB, WP4.7.1 THE RESET NO WORK.... :-/
AND NOW, IN MY WORDPRESS, IS WORK TWO LIGHTBOX, SIMPLE AND OTHER, WHAT IS IMPLEMETED IN THE WP GALLERIES... I NEED HELP YOU... I NEED MAKE THE RESET CORRECTLY AND UNINSTALL CORRECTLY. NO NEED THIS PLUGIN... THANK YOU. 

I WAIT A NEW NOTICE, COOMIN SOON... :-)

**Comment by archetyped** [comment]
Hi, uninstalling SLB will definitely stop SLB's lightbox from being loaded.  Resetting SLB's settings is not even required.

Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by jesmar1973x** [comment]
Imposible.... I unistall the plugin, and the interface to lightbox is active... not is normal... and if back to install, the option reset is active. But this no work correctly. My website is www.jesmarmartinez.es

**Comment by archetyped** [comment]
Hi, if you mean that your images are still being opened in a lightbox when they are clicked, then that is not SLB, but rather the lightbox included with your site's theme.

If that is not what you mean, please post a screenshot that shows what "I unistall the plugin, and the interface to lightbox is active" means.  Please also post post a screenshot of your plugins page once SLB has been uninstalled and I will check for possible conflicts.

Thanks.

**Comment by dudlaj** [comment]
I have simillar issue while using Blaszok theme. I wanted to use simple lightbox for simple wordpress galleries in the posts. And now I have simple lightbox all over the site even if it's disabled and deleted.
It is a test site - wine.robocomp.cz.
I'll appreciate any tips. Thank you for response.

**Comment by archetyped** [comment]
@dudlaj the only lightbox I see on the link you provided is from a different plugin (Massive Addons), not SLB.  I would recommend contacting the developer of that plugin for instructions if you cannot find an option to disable their lightbox.

**Comment by jesmar1973x** [comment]
Hello STAFF, and Archetyped... My problem in WP 4.7.2 still the same... 
![no_work_correctly](https://cloud.githubusercontent.com/assets/25262948/22404048/a042826c-e628-11e6-9e05-52a2d9da3539.png)
I install, and unistall, and over again. If allways want make the reset... but the reset no work correctly. And Y want to unistall correctly, because th WP have in the WP gallery, a plugin owner to have the Lightbox. Can you help me?, or make a new actualization to unistall correctly?... Thank you.

**Comment by jesmar1973x** [comment]
The plugin is empty. No is correctly. Please see this: 
![empty_no_work](https://cloud.githubusercontent.com/assets/25262948/22404071/463bc70a-e629-11e6-9f36-1db01488f498.png)
I can be seen?... Empty no work correctly. Thank you... :-) Jesmar from Spain.

**Comment by archetyped** [comment]
Thank you for the screenshots.  It looks like you may have another plugin installed that is affecting SLB's options page.  See here for [instructions for identifying the plugin causing the conflict](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).  Once you've identified the conflicting plugin, post a link to the plugin here and I will take a look at it.

As for uninstalling the plugin, resetting SLB's settings is not required.  You simply need to deactivate it, then uninstall it.  If you are still experiencing an issue after SLB is uninstalled, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by jesmar1973x** [comment]
Hello. My problem has been solved. (I beleive the problem is this plugin - Versión: 1.7
Autor: Web-Settler, Requiere la versión de WordPress: 3.7 o superior, Compatible con: 4.7.2
WHY?.... This plugin is incompatible for example with a countdown counter.

**Comment by jesmar1973x** [comment]
Hello The problem persists.

**Comment by jesmar1973x** [comment]
Hello. I check plugin by plugin. And this have any erro with SLB. When I activate this plugin, de windowborder of SLB aperance but!!! the SLB is unistall... 
--------
Formerly FV WordPress Flowplayer. Embed videos (MP4, WEBM, OGV, FLV) into posts or pages. Uses Flowplayer 6.
Versión 6.0.5.17 | Ver detalles

**Comment by archetyped** [comment]
Hi, as previously requested, please provide a link to a page that exhibits the issue you are experiencing and I will take a closer look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
