### ISSUE TITLE
Suggestion: change order of slides

### ISSUE THREAD

**Issue by matteoraggi** [archetyped/simple-lightbox#563]
I suggest to change order to slides.

**Comment by archetyped** [comment]
Hi, can you please provide a bit more detail regarding your request?  Images in the lightbox are currently ordered based on their order on the page.  How would you like the order to be changed?

**Comment by matteoraggi** [comment]
Just permit to the users to change the order of the slides:
- manually
- by name
- by date

**Comment by archetyped** [comment]
Thanks.  I'll keep this in mind, but as the order of images in the lightbox can fully controlled by changing the order of the image links on the page itself, lightbox-specific sorting is currently not planned.  If you can provide an example of a situation where having the images displayed in a different order than they are on the page itself would be useful, it may help me to more clearly see how adding such a feature could be useful.

**Comment by matteoraggi** [comment]
Ok, great! now I don't exactly remember, maybe I was asking for this first to learn what you tell me now.
For now I just can't use your wonderfull plugin because I still have to find from where the actual lightbox is coming.. it doeasn't looks that Impreza theme is giving a lightbox with it to me and there is no option to disable it too and originally there was no lightbox too. I was just trying many lightboxes and at the end your was the best of the free for my needings, but now I can't use it..
