### ISSUE TITLE
Request: Full size option 

### ISSUE THREAD

**Issue by dimak11** [archetyped/simple-lightbox#564]
## Description of feature/request
Hello, 
It would be great to have a button in the Lightbox to be able to enter in the full image mode, even when
"Resize lightbox to fit in window"  setting is enabled.

## This feature would be used to
I use the Lightbox to creat friend's paintings website http://ninoponditerra.com/index.php/galleries-2/galleries-birds/ 
I think visitors would be interested to study closer the details of the paintings. But I do not want the Lightbox to be opened directly in the image size mode, that's why I want the "Resize lightbox to fit window" setting to be enabled, and only when a user wants to see painting details, he could enter in a full size mode.... Currently this is not possible.

## If you added this feature, I would:
b) :) because I do not have cat and it is still quit cold outside to eat hats =)
I  rate 5 stars your plugin, it is really great - the only one  I could found with the zoom working properly on mobile devices

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, please add your comments and feedback to [the existing ticket for this feature](https://github.com/archetyped/simple-lightbox/issues/288).

Thanks!
