### ISSUE TITLE
Issue: Lightbox not working

### ISSUE THREAD

**Issue by figure2** [archetyped/simple-lightbox#567]
## Description of Problem

Simple Lightbox and the Woocommerce addon aren't working.

## Details
First of all, my apologies for the content. I am not the original developer to work on this website. My client wants the main product image as well as the gallery image views to display as a lightbox images. 

The previous plugin I had used was "Responsive Lightbox" which worked on the main image but not the gallery views. I deactivated that plugin and installed Simple Lightbox and the WooCommerce Activator and now there is no lightbox effect. Can you give me any suggestions to resolve this?

* https://romanticdepotsuperstore.com
* Browser(s) exhibiting problem: Chrome
* Version of SLB Installed: 2.6.0, WooCommerce Activator: 0.21
* Other plugins installed: See attached screenshot
![all_plugins](https://cloud.githubusercontent.com/assets/6961600/22610945/068b8210-ea36-11e6-9540-5c12a4f27280.png)

**Comment by archetyped** [comment]
Hi, here are some things you can do to troubleshoot your issue:

## Confirm SLB is operational

First, let's determine whether SLB is operational on non-product pages.

1. Ensure SLB is enabled in SLB's settings
2. Create a page
3. Add an image link to the page
4. Save page and check to see if image is opened in a lightbox.

Please also provide the link to the page here so that I can take a look for any issues as well.

## Confirm WooCommerce add-on is enabled

The add-on respects WooCommerce's own settings, so ensure that the **Enable Lightbox for product images** setting is enabled in WooCommerce's settings (`Products Tab > Display > Product Image Gallery`).

Once you've confirmed that this setting is enabled, refresh your page (clearing any caching plugins you may be using), and check to see whether the images are being displayed in the lightbox.

Let me know what you find and I would be glad to take another look if necessary.

**Comment by figure2** [comment]
Hello,
    The test page lightbox funtionality works:
      https://romanticdepotsuperstore.com/image-test/
    It just doesn't seem to work on product images. Example:
https://romanticdepotsuperstore.com/product/couples-satin-love-mask-black-red-purple/
      (I'm looking for the least offensive image to use)
    Mark
    
    Mark Hannon
        Art Direction & Design
        Cell: 203-685-5348
        Online Portfolio
      President: Coastal Arts Guild
          of CT
    On 2/4/17 2:07 PM, Archetyped wrote:
    
    
      Hi, here are some things you can do to troubleshoot your issue:
      Confirm SLB is operational
      First, let's determine whether SLB is operational on
        non-product pages.
      
        Ensure SLB is enabled in SLB's settings
        Create a page
        Add an image link to the page
        Save page and check to see if image is opened in a lightbox.
      
      Please also provide the link to the page here so that I can
        take a look for any issues as well.
      Confirm WooCommerce add-on is enabled
      The add-on respects WooCommerce's own settings, so ensure that
        the Enable Lightbox for product images setting
        is enabled in WooCommerce's settings (Products Tab >
          Display > Product Image Gallery).
      Once you've confirmed that this setting is enabled, refresh
        your page (clearing any caching plugins you may be using), and
        check to see whether the images are being displayed in the
        lightbox.
      Let me know what you find and I would be glad to take another
        look if necessary.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/archetyped/simple-lightbox","title":"archetyped/simple-lightbox","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/archetyped/simple-lightbox"}},"updates":{"snippets":[{"icon":"PERSON","message":"@archetyped in #567: Hi, here are some things you can do to troubleshoot your issue:\r\n\r\n## Confirm SLB is operational\r\n\r\nFirst, let's determine whether SLB is operational on non-product pages.\r\n\r\n1. Ensure SLB is enabled in SLB's settings\r\n2. Create a page\r\n3. Add an image link to the page\r\n4. Save page and check to see if image is opened in a lightbox.\r\n\r\nPlease also provide the link to the page here so that I can take a look for any issues as well.\r\n\r\n## Confirm WooCommerce add-on is enabled\r\n\r\nThe add-on respects WooCommerce's own settings, so ensure that the **Enable Lightbox for product images** setting is enabled in WooCommerce's settings (`Products Tab \u003e Display \u003e Product Image Gallery`).\r\n\r\nOnce you've confirmed that this setting is enabled, refresh your page (clearing any caching plugins you may be using), and check to see whether the images are being displayed in the lightbox.\r\n\r\nLet me know what you find and I would be glad to take another look if necessary."}],"action":{"name":"View Issue","url":"https://github.com/archetyped/simple-lightbox/issues/567#issuecomment-277467509"}}}

**Comment by archetyped** [comment]
Hi, glad to hear SLB is working on standard WP pages.  You didn't note whether the lightbox option in WooCommerce's settings was enabled or not, so I would recommend checking there to confirm (see my previous comment for details).

Aside from that, it looks like there may be a conflict with your theme or a plugin.  See here for [instructions on identifying the conflicting theme/plugin](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).  Let me know what you find and I would be glad to take another look if necessary.

**Comment by figure2** [comment]
My apologies, I had meant to attach these screenshots to my
      previous email to show both plugins are active. Since both plugins
      are active but not working on product pages, that leaves the
      potential conflicts.
    The business owner would flip out if I started turning off
      plugins or changing themes so I will likely need to copy the site
      into a local development environment so I can troubleshoot.
    Question: if the problem turns out to be an offending plugin that
      is essential to the operation of the website and can't be
      permanently disabled, what would my next steps be?
    
    --
        Mark Hannon
        Art Direction & Design
        Cell: 203-685-5348
        Online Portfolio
      President: Coastal Arts Guild
          of CT
    On 2/7/17 5:44 PM, Archetyped wrote:
    
    
      Hi, glad to hear SLB is working on standard WP pages. You
        didn't note whether the lightbox option in WooCommerce's
        settings was enabled or not, so I would recommend checking there
        to confirm (see my previous comment for details).
      Aside from that, it looks like there may be a conflict with
        your theme or a plugin. See here for instructions
          on identifying the conflicting theme/plugin. Let me know
        what you find and I would be glad to take another look if
        necessary.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/archetyped/simple-lightbox","title":"archetyped/simple-lightbox","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/archetyped/simple-lightbox"}},"updates":{"snippets":[{"icon":"PERSON","message":"@archetyped in #567: Hi, glad to hear SLB is working on standard WP pages.  You didn't note whether the lightbox option in WooCommerce's settings was enabled or not, so I would recommend checking there to confirm (see my previous comment for details).\r\n\r\nAside from that, it looks like there may be a conflict with your theme or a plugin.  See here for [instructions on identifying the conflicting theme/plugin](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).  Let me know what you find and I would be glad to take another look if necessary."}],"action":{"name":"View Issue","url":"https://github.com/archetyped/simple-lightbox/issues/567#issuecomment-278168109"}}}

**Comment by archetyped** [comment]
Hi, it doesn't appear that emailed images are supported on GitHub.  Please visit this ticket on GitHub's website directly to upload the images.

Testing for conflicts on a development/staging version of the site is recommended.  Once the conflicting plugin is found, it should hopefully be a simple fix for the plugin's developer.  Most conflicts are caused by a bug that is not detected until a more visible plugin like SLB stops working as a result.  Getting the plugin fixed is important as it could be causing other issues on the site that simply aren't as visible at the moment.

**Comment by figure2** [comment]
Images uploaded.

![simple_lightbox_settings_panel](https://cloud.githubusercontent.com/assets/6961600/22752377/46110d3c-ee06-11e6-827f-bbc244b541b1.png)
![simple_lightbox-woocommerce_plugins](https://cloud.githubusercontent.com/assets/6961600/22752376/46104d20-ee06-11e6-949c-5cbf18cb25c8.png)

**Comment by archetyped** [comment]
Thanks.  I don't see a screenshot confirming that the lightbox option in **WooCommerce's settings** is enabled or not, so I would recommend checking there to confirm (see my earlier comment for details on where to find this setting).

**Comment by figure2** [comment]
Thank you and sorry I missed that instruction. I had disabled the built-in lightbox when testing the Responsive Lightbox since they seemed to fight with each other. It's enabled now and the lightbox is working.

Mark

**Comment by archetyped** [comment]
Awesome!  Glad to hear your issue has been resolved :)

**Comment by figure2** [comment]
Hello, my client noticed the main image zooms but the smaller, gallery view images don't: https://romanticdepotsuperstore.com/product/refresh-toy-cleaner/

Anything I can do to get all product images to zoom?

**Comment by archetyped** [comment]
Hi, that may depend on what is being used to generate the tabbed content on the product pages.  Please post a link to the specific theme or plugin that is generating the tabs and I will take a look.

**Comment by figure2** [comment]
Hello, the tabs on the lower portion of the product pages are a standard part of Woocommerce and are mentioned in their documentation: https://docs.woocommerce.com/document/editing-product-data-tabs/

The theme is [AccessPress Lite](https://wordpress.org/themes/accesspress-lite/).

**Comment by archetyped** [comment]
Hi, apologies for not being clear.  The tabs are standard, but the **Photos** tab is not.  I need to know what plugin is being used to add the Photos tab to the product page so that I can see what may be causing an issue.

**Comment by figure2** [comment]
Hello, This was a bit frustrating. I mentioned in an earlier message that I was not the original developer on this website and took over when the original guy abandoned my client. I am still trying to figure out everything the original developer did.

There didn't seem to be any plugins controlling the tabs on the the Woocommerce product page, nor were there any theme options specific to it that I could find.

I finally found this snippet of code in the functions file:
`// Removes tabs from their original locaction 
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_product_data_tabs', 10 );
// Inserts tabs under the main right product content 
add_action( 'woocommerce_single_product_summary', 'woocommerce_output_product_data_tabs', 60 );

// Removes tabs from their original loaction 
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_product_data_tabs', 10 );
// Inserts tabs under the main right product content 
add_action( 'woocommerce_single_product_summary', 'woocommerce_output_product_data_tabs', 60 );
//add extra tabs videos and photos
add_filter( 'woocommerce_product_tabs', 'extra_tabs' );
	
	function extra_tabs( $tabs ) {
	
		//global $post;
		$post_id = get_the_ID();
		$product_video = get_field('video_link',$post_id);
		$product_photos   = $post_id;
			
	 
		if ( $product_video != "" ) {
		
			$tabs['video_tab'] = array(
				'title'    => __( 'Videos', 'woocommerce' ),
				'priority' => 17,
				'callback' => 'video'
			);
			
		}
		
		if ( $product_photos != "" ) {
		
			$tabs['photos_tab'] = array(
				'title'    => __( 'Photos', 'woocommerce' ),
				'priority' => 16,
				'callback' => 'photos'
			);
			
		}
		
				
		return $tabs;
	 
	}`

Does this help you to narrow down the problem?

**Comment by archetyped** [comment]
Great job on tracking that down!  That is indeed the snippet that registers the Photos tab.  Based on that code, there should be a `photos()` function that generates the output for the photos tab.  If you can post that code, I can take a look to see why it isn't working with SLB.

Thanks.

**Comment by figure2** [comment]
Here is the photos() function. But as a backup, I am attaching the full functions.php file in case this is connected to yet another code snippet:
```
	function photos() {
	

		global $product;
		$ids_str = "";
		$product_detail = $product->get_gallery_attachment_ids();
				//echo "<pre>";print_r($product_detail);echo "</pre>";
		foreach($product_detail as $attachment_id){
			echo '<ul class="photo-gallery">';
		  echo '<li><a href="'.$image_link = wp_get_attachment_url($attachment_id).'"><img src="'.$image_link = wp_get_attachment_url($attachment_id).'" class="fancybox" /></a></li>';
		  echo '</ul>';		  
		}
```
[functions-php.pdf](https://github.com/archetyped/simple-lightbox/files/769096/functions-php.pdf)

p

**Comment by archetyped** [comment]
Thanks, that `photos()` function is the problem.  I'm testing out a few things and will update this ticket soon.

**Comment by figure2** [comment]
Hi. My client was wondering why this wasn't getting resolved. I pointed out that you didn't create the problem, yet you are not charging anything to fix it. I suggested that were they to offer to pay you, that you might expedite the solution.

So now he is asking what you would charge to move this closer to the front of the line.

There are some other problems with the site, some I suspect were put there by the original developer and some are beyond my skill level so who knows? You could make a little extra spending money on this website.

Give me a quote for the work and I'll pass it on.

**Comment by archetyped** [comment]
Hi, thanks for your patience.  It seemed strange that the `photos()` function appeared to be duplicating existing Woocommerce functionality, so I did some additional testing just to make sure I wasn't missing something else.

Replace the `photos()` function with this:

```php
function photos() {
	woocommerce_show_product_thumbnails();
}
```

It will then use Woocommerce's own image gallery functionality (which is fully supported by SLB's Woocommerce add-on).  Now the images should be displayed in a lightbox when they are clicked. 

Let me know if you are still experiencing this issue after updating the function with the above code and I would be glad to take another look.

**Comment by figure2** [comment]
Thanks. Unfortunately even after I replaced the photos () function, the lightbox isn't working on the alternate views photos: https://romanticdepotsuperstore.com/product/refresh-toy-cleaner/

**Comment by archetyped** [comment]
Hi, if you look at that page's source, you can see that it is still displaying the output from the original `photos()` function, so I would recommend confirming that the correct `functions.php` file was updated with the new function, and that you've cleared all caches before testing again.
