### ISSUE TITLE
Issue: Links in posts, pages, and widgets are not automatically activated

### ISSUE THREAD

**Issue by k2an** [archetyped/simple-lightbox#569]
## Description of Problem
Links in posts, pages, and widgets are not automatically activated

## Details
I tried to use , is it simple as select an image in post and thats it? Noi its not working like that. Can not click image, if do that its not working as expected.. where did i doing wrong? i tried many plugins all of are same. 
* URL of Page exhibiting problem: on local host
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: latest
* Other plugins installed: no other plugin installed

**Comment by archetyped** [comment]
Hi, see this page in SLB's documentation that has [tips on what to do when the lightbox isn't working](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts).

If you're still experiencing an issue, please upload your site to test server and send me a link and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to reopen the ticket and take a look.
