### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by rosamor333** [archetyped/simple-lightbox#571]
## Description

Sudenly without installing any new plugin, only updating WPRes 7.0 and normal updating the galleries stop working. I´t´s a big problem as I have a lot of galleries with custom fields building with go portfolio and in posts posts!!. It doesn´t work now.

I have simple ligth box in other pages and they work. Maybe is because of any installed plugin when I Update it??
Can you help me please?

## Details

I pass you a link of one of the post where there is a gallery, when you open it, only shows the image static not the gallery with all images including

* URL of Page exhibiting problem: https://www.agaba.net/cursos/taller-elaboracion-de-vermouths-artesanos-noviembre-2016/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 2.6.0
* Other plugins installed: Advanced Custom Fields,Antispam Bee,Duplicate Page,Easy Smooth Scroll Links,Formidable Forms,Go – Responsive Portfolio for WP,	Layers Plus Widgets, Layers Pro, Monarch Plugin,Search Everything,Title Remover,Ultimate Tag Cloud Widget,Uber Login Logo,WP Super Cache,	
Yoast SEO
![captura de pantalla 2017-02-15 14 52 53](https://cloud.githubusercontent.com/assets/22834181/22977524/465c1dd4-f38f-11e6-9e1f-a7335aa95416.png)
![captura de pantalla 2017-02-15 14 52 58](https://cloud.githubusercontent.com/assets/22834181/22977525/46654490-f38f-11e6-85e8-c46d3158b9aa.png)

**Comment by archetyped** [comment]
Hi, it looks like you have a different lightbox plugin activated.  Multiple lightboxes can cause strange behavior, so removing all other lightbox plugins is highly recommended.

If you are still experiencing this issue after removing the other lightbox plugin and activating SLB, please update this ticket, and I would be glad to reopen the ticket and take another look.

Thanks.
