### ISSUE TITLE
Issue: Not working with Converio theme

### ISSUE THREAD

**Issue by fonsito** [archetyped/simple-lightbox#573]
## Description

Not working with theme http://thememotive.com/converio/
It works with a default theme included in WP
Nothing seems to aparently fail using chrome inspector.

## Details

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): None
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, I will contact the theme's developer to review the theme for compatibility issues, but as a paid theme, I cannot guarantee I will be able to access the theme.

You may want to contact the theme's developers directly and ask if the theme meet's [SLB's basic requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements), and to update the theme if it does not.
