### ISSUE TITLE
Issue: Double images showing

### ISSUE THREAD

**Issue by vvolz** [archetyped/simple-lightbox#574]
## Description of Problem

Using Layers Pro. Switched to Twenty Seventeen theme and issue still occurs.
E.g., have four images shows 2 of each in a row when lightbox opens (so 8 in total)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please fully fill in the details of the issue you are experiencing above, and I would be glad to take a closer look.

Thanks.

**Comment by marcperel** [comment]
Hey @vvolz, @archetyped,

The reason this is happening is that Layers adds an <a> around the title as well as the image in a content widget, so Simple Lightbox doubles up.

The way to fix this would be to know how to exclude duplicates @archetyped? By that I mean when the image asset array is built up, how do we make it exclude dups.

Thanks

**Comment by archetyped** [comment]
Thanks for the additional details @marcperel.  You can exclude links from being processed by SLB either by surrounding them with the `[slb_exclude]` shortcode ([documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes)), or by adding `data-slb-active="0"` to the duplicate `<a>` element.  However, in both cases, this will mean that excluded link will not display the image in a lightbox when clicked.

An option to filter duplicates from slideshows is being evaluated, but as this may not always be the desired behavior, the exact implementation is being determined.
