### ISSUE TITLE
Issue: Launching Slideshows from a Single Link

### ISSUE THREAD

**Issue by tkglaze** [archetyped/simple-lightbox#575]
## Description of Problem

I see the workaround you have, and it works for a single gallery text launch on a page, but I need to launch multiple galleries from a page.  It says that you have plans to enhance your plug-in to provide this, but it does not say when this is planned, or even when the workaround was written and documented.  Please advise if this is still in the plan and when it may be available.

## Details

* URL of Page exhibiting problem: http://pctonstage.com/gallery-of-past-shows/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Chrome
* Version of SLB Installed: 2.6.0
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, you can use the `[slb_group]` shortcode ([documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes)) to separate groups of links into separate lightbox slideshows.
