### ISSUE TITLE
Issue: SLB not working on a posts page

### ISSUE THREAD

**Issue by abollmeyer** [archetyped/simple-lightbox#576]
## Description of Problem
On a posts  page, using SLB shortcode only shows [tag] brackets and the lightbox doesn't launch. SLB works fine on single posts and pages, just not the posts page (blogs are linked through my post page).

I've tried disabling all plugins and switching to the Twenty Fifteen theme. Problem still shows up.
![screenshot 88](https://cloud.githubusercontent.com/assets/24943478/23267119/694cf360-f9af-11e6-81d2-18272a14bd79.png)

## Details

* URL of Page exhibiting problem: http://hometechhowto.com/blog/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): MS Edge
* Version of SLB Installed: 2.6.0
* Other plugins installed:

**Comment by archetyped** [comment]
**Reference:** [Original ticket on WP Support forums](https://wordpress.org/support/topic/not-working-on-posts-on-mobile/).

**Comment by abollmeyer** [comment]
Any other suggestions?

**Comment by archetyped** [comment]
Hi, I'm trying to reproduce your issue, but have not yet been able to.  Can you please post a screenshot of your site's SLB settings page so that I can ensure the settings match?  After you've done that, you can also try resetting SLB's settings from your site's **Plugins** admin page by clicking the "**Reset**" link under Simple Lightbox.

**Comment by abollmeyer** [comment]
Hi,

Enabling the Home Screen option under Settings fixed the issue.

On Mar 3, 2017 6:21 PM, Archetyped <notifications@github.com> wrote:

Hi, I'm trying to reproduce your issue, but have not yet been able to. Can you please post a screenshot of your site's SLB settings page so that I can ensure the settings match? After you've done that, you can also try resetting SLB's settings from your site's Plugins admin page by clicking the "Reset" link under Simple Lightbox.
