### ISSUE TITLE
Issue: is not opening properly the pictures

### ISSUE THREAD

**Issue by mihaitza16** [archetyped/simple-lightbox#577]
## Description of Problem
I updated my wordpress installation from 4.6 to 4.7.2, and my theme accesspress basic to 3.0.6.
From that moment the plugin is working randomly.
I observed on IE,  sometimes works, but most of the time on Firefox is not working.
link: http://www.trapafum.ro/cupole-lamilux-f100/
Click on the picture. Is not opening a nice window in the middle as until now.
SLB Version 2.6.0 

Plugins:
All In One SEO Pack	
CMB2
Contact Form 7
Google Analytics Dashboard for WP
Google XML Sitemaps
Postman SMTP
Responsive Tabs
Responsive WordPress Slider - Soliloquy Lite
Tabs Responsive
W3 Total Cache
WP Smush

Thank you.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it looks like there may be a problem with your site's cached code.  I would recommend clearing all caches and deactivating caching plugins to see if the problem persists.

If you are still experiencing an issue, follow these [instructions on identifying plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) to determine if another plugin/theme is conflicting with SLB.  Post a link to the conflicting plugin/theme and I would be glad to take a look.

**Comment by abollmeyer** [comment]
I'm not using any caching plugins. I've tried flushing my DNS cache as well as clearing my browser cache. I've already disabled my theme and plugins. The problem is still there. The problem only shows up on my posts page where the collection of blogs are listed, but not on the blog page itself. If you click any link on the posts page and navigate to the actual blog, SLB behaves like it should.

**Comment by mihaitza16** [comment]
Thanks for your answer.

I think this plugin was causing trouble: W3 Total Cache.

I deactivated and seems that everything is back to normal.

Thank you again, for your prompt reply.

**Comment by archetyped** [comment]
@mihaitza16 glad to hear your issue has been resolved.  W3 Total Cache should not have any lasting conflicts with SLB, but it's a good idea to clear your caches every so often, and especially when you make a change or update something so that stale content does not cause a problem on your site.
