### ISSUE TITLE
Mobile thumbnails

### ISSUE THREAD

**Issue by graffx** [archetyped/simple-lightbox#578]
Script in SLB makes thumbnails of small images (mine are 380px and smaller on one of the measures) - smaller on mobile then bigger one's image thumbnails. On desktop it's fine.

check it here - http://v-zen.com/fantastic-beasts-medieval-manuscripts/ (bug is on mobile version only, so check it on mobile)

**Comment by archetyped** [comment]
Hi, please see my response to [your existing ticket on WordPress' plugin forums](https://wordpress.org/support/topic/mobile-thumbnails-wrong-size/).  Let's keep all further discussion there to avoid confusion.  

Thanks.
