### ISSUE TITLE
Issue: does not work in Local by Flywheel set up

### ISSUE THREAD

**Issue by plaudev** [archetyped/simple-lightbox#579]
## Description of Problem

When an gallery image is clicked, instead of opening up in a modal, it is opened like a post. This problem only happens in my local site hosted via Local by Flywheel. In my cloud hosted site on SiteGround, the SLB plug-in works.

## Details

* URL of Page exhibiting problem: 

![screen shot 2017-03-15 at 04 38 48](https://cloud.githubusercontent.com/assets/17637910/23941063/c1001e32-093d-11e7-85fd-c40af403e2fc.png)
![screen shot 2017-03-15 at 04 39 25](https://cloud.githubusercontent.com/assets/17637910/23941068/c5570bf8-093d-11e7-9525-9b9279363be5.png)
![screen shot 2017-03-15 at 04 40 01](https://cloud.githubusercontent.com/assets/17637910/23941071/c7d265ee-093d-11e7-9cb7-2f4947c60522.png)

Local by Flywheel environ:
wordpress = 4.7.3
php = 7.0.3
web server = apache
mysql = 5.5.49

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 

tested on mac (10.12.3) using chrome 56.0.2924.87 (64-bit) and firefox 52.0 (64-bit).

* Version of SLB Installed: 

2.6.0

* Other plugins installed: 

The same set of plugins are on both the Local by Flywheel site & SiteGround sites (they are mirrored) EXCEPT the SiteGround site also has P3 installed but deactivated.

Activated:
All-in-One WP Migration
Carousel Slider
Child Theme Configurator
Code Snippets
Contact Form 7
Email Address Encoder
Google Analytics for WordPress by MonsterInsights
JetPack by WordPress
Responsive Menu Card
Simple Light Box
WordPress Importer
WP Google Map Plugin

Not activated:
Akismet
Hello Dolly

**Comment by archetyped** [comment]
Hi, it looks like Flywheel lets you share links to the local site, so please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by plaudev** [comment]
Hi, thanks for your response. Here is a [live link to my local by flywheel site](http://57af8313.ngrok.io/). Click the menu item Gallery and then click on any of the images (not including the slider). Appreciate it.

**Comment by archetyped** [comment]
Hi, that link does not appear to be active.  It only displays an `Tunnel 57af8313.ngrok.io not found` message.  Please provide an active link to your site and I would be glad to take a look.

Thanks.

**Comment by plaudev** [comment]
apologies, I had to shutdown my machine for a bit. Please try this link
3fe627b2.ngrok.io. I will keep this one up for at least a week. Thanks

Patrick.

**Comment by archetyped** [comment]
Strange, that one has a similar error message: `Tunnel 3fe627b2.ngrok.io not found`

**Comment by plaudev** [comment]
Sorry again the live link shuts down every time I reboot. It is on again now

**Comment by archetyped** [comment]
Thank you, however, I don't see any image links on that page.  Can you please provide a link to a specific page with image links that I can test?

**Comment by archetyped** [comment]
Hi, it looks like cURL may not be enabled or configured properly on the site.  See SLB's minimum requirements for [more details on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements).

I also found this page regarding enabling cURL in Flywheel, which might help you resolve your issue: [Local by Flywheel Support: Outbound connections via Curl are failing](http://local.getflywheel.com/community/t/outbound-connections-via-curl-are-failing/453 "Outbound connections via Curl are failing - Support - Local by Flywheel").

Let me know if you are still experiencing an issue once cURL has been enabled and configured for PHP requests, and I would be glad to reopen this ticket and take another look.
