### ISSUE TITLE
Why the plugin does not work ?

### ISSUE THREAD

**Issue by flierville** [archetyped/simple-lightbox#580]
Hello, could you tell me why the plugin does not works in my page :

[http://www.copitet-photographe.com/photographie-entreprise/](http://www.copitet-photographe.com/photographie-entreprise/)

Thank you 😉

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled or properly configured for your site.  Please see this page in SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

Please let me know if you are still experiencing an issue after enabling cURL and I would be glad to reopen this ticket and take another look.

Thanks.
