### ISSUE TITLE
Issue: dequeue/remove slb_context js

### ISSUE THREAD

**Issue by chercka** [archetyped/simple-lightbox#581]
## Description of Problem

I need to remove the very stubborn js id="slb_context" being output at the bottom of all pages (for Google AMP to validate). How can I remove this?

## Details

* URL of Page exhibiting problem: 
www.petalatino.com

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
All

* Version of SLB Installed: 
2.6.0

* Other plugins installed:

**Comment by archetyped** [comment]
Hi, the `slb_context` script element is an inline script. Inline scripts are not enqueued like external JavaScript files are in WordPress, so while nothing is being "hijacked" by this or any other inline script, they cannot be dequeued like external JS files.

This particular inline script can be omitted from the page with the following code:

(**Note:** As the context is required for functionality, removing it is not supported and related code may change in future updates.)

```php
add_action('wp_loaded', 'remove_slb_context');
function remove_slb_context() {
	global $slb;
	remove_action('wp_footer', $slb->util->m('set_client_context'), $slb->util->priority('client_footer_output'));
}
```

However, note that SLB outputs other inline scripts as well to minimize multiple connections and optimize page loading speed.  Using a plugin meant to generate an AMP-compatible page is recommended to ensure all inline scripts are removed from the page.

**Comment by chercka** [comment]
Thanks guys!
