### ISSUE TITLE
Miscount on single image or link

### ISSUE THREAD

**Issue by marthaSplatterHead** [archetyped/simple-lightbox#583]
## Description of Problem

When it launches lightbox it counts all -a- tags so if there are 4 and lower on the page there are 2 it says 1 of 6 when in the gallery there are only 4, maybe you could make it filter by class like giving all the images within the related gallery a common class name like "gallerygroup1" this is the solution I was referencing https://archetyped.com/know/slb-single-link-slideshows/

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by marthaSplatterHead** [comment]
Also can't make separate galleries on same page, they mix together

**Comment by archetyped** [comment]
Hi, please edit your original post and fill in the details regarding the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
