### ISSUE TITLE
Issue: SLB not working on a site, but working others on same server

### ISSUE THREAD

**Issue by superian** [archetyped/simple-lightbox#584]
## Description of Problem

When clicking on a picture or gallery image, goes to the file, not the expected Simple Lightbox display.

SLB working fine on other sites on same server.

WordPress 4.7.3
jQuery version: 1.12.4
Theme: Twenty Twelve
Plugins enabled: just SLB and Akismet

I can see the SLB javascript in the page's source code, but clicking on images goes to the relevant image file, not the SLB display.

## Details

* URL of Page exhibiting problem: https://icameisaw.co.uk
* URL of Page on different site on same server NOT exhibiting problem: https://lisageary.co.uk
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chromium, Vivaldi, Opera, Chrome on Android.
* Version of SLB Installed: 2.6.0
* Other plugins installed: Akismet.

**Comment by superian** [comment]
Oh, all SLB settings are the defaults.

**Comment by superian** [comment]
Ah, it may have been an issue with the new SSL cert used on that site, because I can see SLB properly now.

My remaining hair is saved! Hooray! :)

**Comment by archetyped** [comment]
Glad you found the solution :)

**Comment by superian** [comment]
Thank you - it's a great plugin.
