### ISSUE TITLE
How to disable the plugin on mobile devices

### ISSUE THREAD

**Issue by galimbo** [archetyped/simple-lightbox#586]
## Description of Problem
Is it possible to disable the plugin on mobile devices?
Thank you

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, when enabled, SLB is active globally on all device types (desktop, mobile, etc.)
