### ISSUE TITLE
Issue: 

### ISSUE THREAD

**Issue by xabispacebiker** [archetyped/simple-lightbox#588]
## Description of Problem

The lightbox used to work before for any photo inserted in posts but somehow and somewhen it stopped working. 

## Details

* URL of Page exhibiting problem: http://97irratia.info
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  All (Safari, Chrome, Firefox..)
* Version of SLB Installed:  Wordpress 4.7.3, SLB 2.6.0
* Other plugins installed: Yes, too many but it was working with all those plugins. I think it just stopped working on an update (we recently changed the theme)

**Comment by archetyped** [comment]
Hi, it looks like cURL is not properly configured/activated for your site.  This can happen when changing web hosting providers or even when your existing hosting provider makes changes to your server.  See this page in SLB's documentation for [more details on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

Also, your site is using an outdated version of jQuery which may also affect SLB's functionality.  See here for [more details on jQuery support](https://github.com/archetyped/simple-lightbox/wiki/jQuery-Support).

Please let me know if you are still experiencing a problem with SLB once you've resolved the above issues and I would be glad to reopen this ticket and take another look.
