### ISSUE TITLE
Issue: YouTube Embed URL not working with Video Add-on

### ISSUE THREAD

**Issue by portablestaging** [archetyped/simple-lightbox#589]
## Description of Problem
Hi
Ive purchsed the video AddOn-
Lightbox works on images, and text links
But I am unable to get the lightbox to launch on pages, posts etc

## Details
Im using this code
```html
<a href="https://www.youtube.com/embed/x3gUwJ6xROE?rel=0"><img src="https://www.portablestage.co.uk/wp-content/uploads/2017/04/NexGen-Portable-Staging-Videos2.png" alt="" width="125" height="124" class="alignleft size-full wp-image-4339" /></a>
```

* URL of Page exhibiting problem:  https://www.portablestage.co.uk/privacy/ Video link image is at the base.
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Version 2.6.0 
* Other plugins installed: Video Handler Version 0.2.0

**Comment by archetyped** [comment]
Hi, a video's embed URL is intended for displaying a YouTube player widget directly on the page.  Use the video's standard URL (e.g. `https://www.youtube.com/watch?v=x3gUwJ6xROE`) in the link and you should be good to go.

Also, to ensure the best possible support, please use the [Add-ons support forum](https://github.com/archetyped/slb-addons/wiki/Reporting-Issues) for any future questions or feedback.  The readme file included with the Video add-on has direct links for this.

**Comment by portablestaging** [comment]
Great Thanks. Missed that. Added the watch url version and it works great.
Is there a way to avoid the related, using rel=0, the lightbox opens, but video doesnt launch if adding ?rel=0 directly after the youtube link?
Thanks again

**Comment by portablestaging** [comment]
Also tried "youtube link" "rel=0"
Thanks

**Comment by portablestaging** [comment]
Hi, I worked it out.
Here's the code to stop related video's appearing after your video in the lightbox
"https://www.youtube.com/watch?v=SEX7ZJhJu68&rel=0"
Thanks

**Comment by archetyped** [comment]
Perfect!  Here is [Google's documentation on YouTube player parameters](https://developers.google.com/youtube/player_parameters) for future reference.

**Comment by portablestaging** [comment]
Hi
The video lightbox n longer appears to work.
I have a video link In bothe the menu of the site, and lots of other pages in the form of a video image
Theres on in the text area of this product
www.portablestage.co.uk/listing/nexgen-hardboard-fascia-skirt/<http://www.portablestage.co.uk/listing/nexgen-hardboard-fascia-skirt/>
Maybe you could suggest a fix?
Thanks
Nathan

Nathan Griffin Managing Director
[signature]
#RaisingYourPerformance
NexGen Manufactured by Portable Stage, Aizelwoods Mill, Nursery Street, Sheffield  S3 8GG
Tel: 0845 2260 192   Email: enquiries@portablestage.co.uk  Web: https://www.portablestage.co.uk<https://www.portablestage.co.uk/> Twitter: @portablestaging    Facebook: www.facebook.com/nexgenstaging<http://www.facebook.com/nexgenstaging>  App: https://www.portablestage.co.uk/stagingapp/
Google Plus & Reviews: https://goo.gl/zhUJqo
Registered Office: TDL  t/a Portable Stage, Aizelwoods Mill, Nursery Street, Sheffield  S3 8GG
Company Number: 09470041  VAT RegNo. 260 0188 37 - Handmade Portable Staging manufactured in Sheffield under British ISO conditions. CE Certified. GEOTrust Secured.

**Comment by archetyped** [comment]
Hi, it looks like SLB's code is not being loaded properly.  This may be due to recent change in server configuration, caching issues, or a conflict with another plugin.

I would recommend [checking for plugin/theme conflicts](../wiki/Troubleshooting-Plugin-Conflicts), starting with clearing and then disabling any caching plugins your are using.

Please let me know what you find and I would be glad to take another look.
