### ISSUE TITLE
SLB is not working on home page

### ISSUE THREAD

**Issue by u2utech2** [archetyped/simple-lightbox#590]
I have installed the SLB it works on post pages but not on home page. I have checked all the check-boxes in the plugin setting but still not working. when I click on image it goes to the image location link but not open it in lightbox perimeters. Can you please help me to find out the trouble? here is link to my site:
http://pleasantonbootcamp.com

Regards,
Tanweer

**Comment by archetyped** [comment]
Hi, can you please provide some details on how the home page's content is being built?  It does not appear to be a standard WordPress page.  Please provide links to the theme or any plugins that are used to build the home page's content.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
