### ISSUE TITLE
Caption does not display paragraph/line breaks

### ISSUE THREAD

**Issue by iwingfield** [archetyped/simple-lightbox#591]
When entering a caption, Wordpress allows for a hard return in the caption field. These become just spaces in the lightbox.

http://humanizethenumbers.com/fall-2015-photography-workshop/

**Comment by archetyped** [comment]
Hi, line breaks added to the caption field are fully supported by SLB.  WordPress actually converts line breaks to HTML `<br />` tags, so if that's not happening on your site, I would recommend checking to see if your theme or another plugin is causing a conflict with this behavior.

See here for [instructions on identifying theme/plugin conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).  Let me know once you have identified the conflict, and I would be glad to take another look if necessary.
