### ISSUE TITLE
Request: Include feature image in lightbox

### ISSUE THREAD

**Issue by jcooper-korg** [archetyped/simple-lightbox#594]
## Description of feature/request
If you have set a feature image in a post, it would be great if it could show up in the lightbox along with the other post images.

## This feature would be used to
Include the feature image in the lightbox gallery.

## If you added this feature, I would:

Be very thankful :)

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  SLB works with any valid links in your post's content, so adding a link around the featured image should do what you're wanting to do.

Note that if the featured image is added to the page outside the post's content, you may have to edit your theme to add the link to the featured image.  In such cases, using `slb_activate()` ([documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation)) may also be necessary.
