### ISSUE TITLE
Feedback: Visual editor issue after WP 4.7.5

### ISSUE THREAD

**Issue by gezginorman** [archetyped/simple-lightbox#595]
## Description of Problem

Hi,

Hope you're all doing great. Thanks for this wonderful plugin.

After the WP 4.7.5 security update, simple-lightbox causes visual editor mode to not apply any change that might be done. editor loads OK but you cannot make any changes using it. However deactivating, making changes and then reactivating seems to be working fine. This might be a specific issue that I'm experiencing, stil thought you should know.

Best wishes, and thanks again

MH

## Details

* URL of Page exhibiting problem: N/A
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed: 
* Theme:

**Comment by archetyped** [comment]
Hi, thanks for the report.  However, SLB has been tested with WordPress 4.7.5 and no issues were found, including working in the Visual Editor.

The issue may be specific to your configuration.  Please edit your original report to fill in the rest of the details and I would be glad to take a closer look.

Also, please take a look at your browser's developer console when working in the visual editor and let me know if any JavaScript errors are being triggered.

Thanks.

**Comment by gezginorman** [comment]
Hi,

When I open visual editor and make a change while SLB is activated, the change that I made is not appear and the I get the following errors on console:

> Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> load-scripts.php:4 POST http://bilimvesaire.com/wp-admin/admin-ajax.php 500 (Internal Server Error)
> send                               @ load-scripts.php:4
> ajax                                 @ load-scripts.php:4
> n.(anonymous function) @ load-scripts.php:4
> updateWidget                @ load-scripts.php:16
> (anonymous)                  @ load-scripts.php:16
> c                                     @ load-scripts.php:5

However, when SLB's deactivated it behaves normally. This happens both on chrome [Version 58.0.3029.110 (64-bit)] and opera [43.0.2442.1144 (PGO)]. I use ColoMag Pro theme. other plugins are as follows:
- AddQuicktag
- AddToAny Share Buttons
- Antispam Bee
- Disable Comments
- Easy Social Sharing
- Facebook Comments Plugin
- Featured Image Caption
- Head and Footer Scripts Inserter
- Image P tag remover
- Meta Tag Manager
- Ninja Forms
- Polylng
- Post Types Order
- SLB Version 2.6.0
- WP Super Cache
- WP-Optimize
- Yoast SEO

Best regards,
MH

**Comment by gezginorman** [comment]
Hi,

This is gone somehow. I think it was a plugin conflict. I have restored a previous versio of the site that has no WP Super Cache plugin, which did not affect visual editor by itself, but maybe caused some other error that affected SLB, but I cannot be sure.

Anyway, thanks for your concern.

Best regards,
MH
