### ISSUE TITLE
No Title/Caption if src is on subdomain

### ISSUE THREAD

**Issue by hiklot** [archetyped/simple-lightbox#596]
## Description of Problem

There seems to be a problem in loading the image data if the images are located on a subdomain (as set per upload_url_path)

It is strange, because the image is referenced and loading fine, only there is not title displayed.

edit: thanks for looking into this! **additional info:**

I have definitely narrowed it down to the upload_url_path. 
I am loading the image from `https://www.originaltourist.com/mediasrc`
As soon as I set `upload_url_path` back to `https://originaltourist.com/mediasrc` (loading the exact same image from the exact same folder), the title appears.

The folder set by `upload_path` is the same in both cases.

## Details

* URL of Page exhibiting problem: `https://originaltourist.com/hotels/ovolo-hotels-hong-kong/`
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome
* Version of SLB Installed: 2.6.0
* Other plugins installed: Jetpack, Essential Grid (...)

**Comment by archetyped** [comment]
Hi, please edit your original report and add the necessary details as per [the guidelines](https://github.com/archetyped/simple-lightbox/blob/master/CONTRIBUTING.md) and I would be glad to take a closer look into your issue.

Thanks.

**Comment by archetyped** [comment]
Hi, thank you for the additional details.  SLB uses WordPress' built-in functionality to access information from the media library such as title and description.  In order for WordPress to access details from the media library for an image, the URL must match what is stored for the image in the media library.

It looks like the site's home URI does not include the `www`, so links should point to the non-www URI for an image to be recognized as part of WordPress' media library.

**Comment by hiklot** [comment]
Thank you for your reply!

The media library uses the paths set by `upload_url_path` and `upload_path`

The www link is stored in the media library and the database. Wordpress and other plugins such as Essential Grid recognise this. It seems very strange, because Simple Lightbox is displaying the correct image (with the www link) but seems to have trouble getting the attachment information.

Many people are using sub-domains for images for performance reasons. It would be unfortunate if SL would not work under those circumstances.
