### ISSUE TITLE
Slide Duration is not working

### ISSUE THREAD

**Issue by cnymike** [archetyped/simple-lightbox#597]
I am not having any luck trying to change the slide duration. It seems to be stuck on about 6 seconds. Changing the value to more or less time does nothing. I have cleared browser cache after making a change to no effect.

[http://mcgrawhouse.org/site_update/]

WordPress v4.7.5
Divi by Elegant Themes v3.0.47
Simple LIghtbox v2.6.0
jQuery v1.12.4
Chrome Browser Version 58.0.3029.110 (64-bit)

Other Plugins installed and active:
Gravity Forms v2.2.3
Link Manager 0.1-beta

**Comment by archetyped** [comment]
Hi, there don't appear to be any image links on the page you provided.  If there is a different page that exhibits the issue you are experiencing, please post a link to the specific page and I would be glad to take another look.

**Comment by cnymike** [comment]
The page has 2 rotating images at the top of the page. Duration is at 6 second and can't be changed. 
http://mcgrawhouse.org/site_update/

**Comment by archetyped** [comment]
Hi, Simple Lightbox displays a lightbox when image links are clicked.  It sounds like you are describing the slider on that page, which is not added or controlled by Simple Lightbox.

The slider is likely added by your theme or a different plugin.
