### ISSUE TITLE
Any chance to set layout.php instead of html

### ISSUE THREAD

**Issue by hefterbrumi** [archetyped/simple-lightbox#598]
Hi!

It would be awesome to have the layout file in php. On my webpage, I need to put the content title on the slider, however I could not find any solution for this task so far.

Any help appreciated.

**Comment by archetyped** [comment]
Hi, the layout is loaded separately from the current post, so post data would not be accessible even if it were a PHP file.  Data is added to the lightbox using [template tags](https://archetyped.com/know/slb-theme-layout/) (such as `{{item.title}}`).  More template tags are planned and custom template tags can be provided via add-ons.

If you can provide additional details on what you're referring to when you say "content title", I can look into whether it can be supported via template tags.

Thanks.

**Comment by hefterbrumi** [comment]
Oh I see!

I need to show the current content's title and categories to where the images were uploaded to. I wanted to use:
get_the_title and get_the_category().

It would be awesome to have these via template tags.

**Comment by archetyped** [comment]
Got it, I've added them to the list of template tags to consider for future updates.

Thanks.

**Comment by hefterbrumi** [comment]
Any hacky solution for the time being?
