### ISSUE TITLE
Item counter customisation

### ISSUE THREAD

**Issue by hefterbrumi** [archetyped/simple-lightbox#599]

**Comment by hefterbrumi** [comment]
Hi!

Is it possible to change the counter? At the moment it looks like: "item 3 of 12". I would like to do it like: 3//12
Is it customisable?

Thanks

**Comment by hiklot** [comment]
You change it in the lightbox settings.

just edit _Slideshow status format_ to `%current%//%total%`

**Comment by hefterbrumi** [comment]
oh sorry, my bad.
