### ISSUE TITLE
Request: deactivate lightbox for mobile devices

### ISSUE THREAD

**Issue by micheleconunele** [archetyped/simple-lightbox#601]
## Description of feature/request
Hi, I'm using your plug in and loving it. I think it would be handy to have a way to decide whether to activate the lightbox or not in mobile devices.

## This feature would be used to
Give designers more control for responsive themes

## If you added this feature, I would:

d) All of the above and thank you :)

**Comment by archetyped** [comment]
Hi, just so I understand your request, you're saying you would prefer raw images to be loaded in the browser when links on clicked on mobile devices?

**Comment by micheleconunele** [comment]
Hi,
Thanks a lot for your message, and sorry about the late reply, I missed
your message.

No, I would like for the image to not do anything when clicked in mobile
devices, so just the unclickable original image would be visible.


2017-05-31 21:13 GMT-05:00 Archetyped <notifications@github.com>:

**Comment by archetyped** [comment]
Hi, SLB acts upon links that have been added to the post/page, so if the theme doesn't add links to images when displayed on mobile devices, then SLB will not be active on mobile devices by default.

Is this what you are asking?  If not, please provide a bit more detail and I would be glad to reopen the ticket and take another look.

**Comment by micheleconunele** [comment]
yeah, that's what i was asking for, thanks a lot for your reply.

2017-06-07 23:53 GMT-05:00 Archetyped <notifications@github.com>:
