### ISSUE TITLE
Issue: Lightbox not working on pages

### ISSUE THREAD

**Issue by asamson23** [archetyped/simple-lightbox#602]
## Description of Problem
The lightbox is enabled to work on every single page of the website. In an article with a gallery, the lightbox works perfectly fine. When you go to a page, however, the lightbox doesn't appear. Instead, it goes directly to the page or the image directly, according to the settings that were set. Also, pages where the lightbox are show a slb class in the html tag at the top of the page, while the pages where it doesn't work don't show the class tag

## Details

* URL of Page exhibiting problem: https://youtu.be/JjckUZQULk4 (Website is not available to the public)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Google Chrome
* Version of SLB Installed: 2.6.0
* Other plugins installed: Advanced Custom Fields, Akismet Anti-Spam, BackWPup, Black Studio TinyMCE Widget, Contact Form 7, Disable Comments, Google Analytics Dashboard for WP (GADWP), Meta Slider, Page Builder by SiteOrigin, Responsive Menu, Shortcodes Ultimate, SiteOrigin CSS, SiteOrigin Widgets Bundle, Sucuri Security - Auditing, Malware Scanner and Hardening, WordPress Importer, WP-Mail-SMTP

**Comment by asamson23** [comment]
The page where it doesn't work is a custom post type

**Comment by asamson23** [comment]
I found this [https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation](link)

**Comment by archetyped** [comment]
Hi, one of the main reasons why SLB may not work for custom post types is that the theme template for that post type does not meet [SLB's requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements).  This can happen when templates are manually added to a theme, etc.

Ensuring that the template follows standard WordPress theme guidelines will usually allow links in custom post types to be automatically activated by SLB.  If you can post a link to the template for the custom post type, I would be glad to take a look.

**Comment by asamson23** [comment]
I was able to figure it out by looking at the link I posted earlier

**Comment by archetyped** [comment]
Glad to hear it, though manual activation should not be necessary.  Feel free to post the template code here if you are interested in automatic activation and I would be glad to reopen the ticket and take a look.
