### ISSUE TITLE
Is there a way to limit the thumbnails in a gallery

### ISSUE THREAD

**Issue by carsey1990** [archetyped/simple-lightbox#603]
Hi

Ive just got the simple-lightbox and its working great on my site, however, ive got a large album with a lot of pictures and dont want to have a huge amount of thumbnails on my guide as it would just cause un-necessary scrolling for the end user.

Is there a way to limit the amount of thumbnails shown to say 16 but still have the remaining (example 60 images) showing in the lightbox and gallery album in wordpress.

Thanks

Chris

**Comment by archetyped** [comment]
Hi, SLB does not have any control over a gallery's appearance, as it only controls what is displayed in the lightbox.  However, you can manually load a specific selection of images in a gallery (see [this page in WordPress' official documentation](https://codex.wordpress.org/Gallery_Shortcode)), and then insert links to the additional images into the post [using the technique in this tutorial](https://archetyped.com/know/slb-single-link-slideshows/) to display all images as a single slideshow in the lightbox.
