### ISSUE TITLE
Archive Page of CPT ignores slb_activate(..)

### ISSUE THREAD

**Issue by Clickadelic** [archetyped/simple-lightbox#608]
Hi,

I'm creating a plugin to show alloy wheels for cars and I'm using the function slb_activate to enable the lightbox for my images.

**My issue:**
[wheels] shortcode > slb_activate works
https://demo.reifengundlach.de/shortcodes-wheels/

archive page > slb_activate does not work
https://demo.reifengundlach.de/designs/

Please click on the buttons with (+)front or (+)aside to open the lightbox / see the bug.

But both outputs have the same code.

I have already checked my version of jQuery which is 1.12.4

I'm using the function like this (img_aside and img_front are the vars that hold my images):

`if (function_exists('slb_activate')) {
	$img_aside = slb_activate($img_aside);
	$img_front = slb_activate($img_front);
}`

What could be the cause of this issue?

Thanks for any hints to solve this.

Kind regards

Toby

**Comment by archetyped** [comment]
Hi, the first thing to check would be to ensure that the "Enable on Archive Pages" option is enabled in SLB's settings.  With this setting enabled, using `slb_activate()` is unnecessary.

If the above option is enabled and you are still experiencing an issue with SLB, please post the template's full code and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
