### ISSUE TITLE
Enable for Menus

### ISSUE THREAD

**Issue by mangotam** [archetyped/simple-lightbox#610]
hi, may i ask how to use simple lightbox for the wordpress menu item ?

thank and regards  

Mango

**Comment by archetyped** [comment]
Hi, when the "Enable for Menus" option is enabled, any valid link (e.g. a link to an image) in a menu will be opened in a lightbox.

If you need additional support, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take a closer look.

Thanks.
