### ISSUE TITLE
Issue: file name only in the first 30th image

### ISSUE THREAD

**Issue by zerod10** [archetyped/simple-lightbox#613]
All the image are the same settings, the file name is showing only in the fists 30th file.
How can i fix that?

http://www.cristinaeffe.com/lookbook-autunno-inverno-20172018/

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  It looks like all titles are displaying properly in the lightbox at the link you provided. 

Please provide additional details if you are still experiencing an issue and I would be glad to reopen this ticket and take another look.
