### ISSUE TITLE
simple-lightbox-zh_CN.po 

### ISSUE THREAD

**Issue by xkonglong** [archetyped/simple-lightbox#615]
this is Chinese language file.

[Simple-LightBox-zh_CN.zip](https://github.com/archetyped/simple-lightbox/files/1237503/Simple-LightBox-zh_CN.zip)

**Comment by archetyped** [comment]
Translations can be directly integrated using [WordPress' Online Translation site](https://translate.wordpress.org/projects/wp-plugins/simple-lightbox/).
