### ISSUE TITLE
Not working on live environment

### ISSUE THREAD

**Issue by chandra10207** [archetyped/simple-lightbox#617]
It worked perfectly on the local server and test server but when I migrate those files and database into the live site it stops working.
test URL: https://mmdgolive.com/eaglesnest/eagle_gallery/breakfast-entrees/
live URL: https://eaglesnestduluth.com/eagle_gallery/breakfast-entrees/
Please reply asap.
thank you.

**Comment by colingrist** [comment]
I have the same issue of it working fine locally but not on live - anyone?
