### ISSUE TITLE
Issue: Lightbox won't work on gallery 

### ISSUE THREAD

**Issue by RideLikeaGirl** [archetyped/simple-lightbox#619]
## Description of Problem

Hello,
I've just installed Simple Lightbox on my Wordpress but it works only if I click on single image on the article.
If I click on a gallery it doesn't work.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by Beee4life** [comment]
Have you checked the settings ? I think gallery is a separate setting.

**Comment by archetyped** [comment]
Hi, please fill in the details of your issue as per [the submission guidelines](../wiki/Reporting-Issues), and I would be glad to take a closer look.

Thanks.

**Comment by GBWP** [comment]
Hi, I've intstalled the simple-lightbox, but doesnt work.
WordPress 4.8.2 running Sydney Child theme.
Simple Lightbox Version 2.6.0 \| By Archetyped
here is my gallery:
https://mobulez.com/gb-wp-cv/image-gallery/
Thx!

**Comment by Beee4life** [comment]
@GBWP please submit your issue in a new thread. Your situation is different than the OP's issue.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
