### ISSUE TITLE
Play m4v embedded movie in a lightbox

### ISSUE THREAD

**Issue by NewLuckyLuke** [archetyped/simple-lightbox#625]
## Description of Problem

My m4v movie does not open in a lightbox 
The lightbox functionality works for an image that is placed on the same page.

## Details

* URL of Page exhibiting problem: 
https://pxazphp.px.be/2017/10/13/how-to-archive-multiple-assets/?preview_id=383&preview_nonce=4cbf963157&post_format=standard&_thumbnail_id=-1&preview=true

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Chrome, Safari
* Version of SLB Installed: 
Version 2.6.0 + Simple Lightbox: Video Handler Version 0.2.0
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please add your vote for specific video file-type support in [this existing ticket](https://github.com/archetyped/slb-addons/issues/25).

Thank you.
