### ISSUE TITLE
Featured image gets included in slideshow

### ISSUE THREAD

**Issue by Beee4life** [archetyped/simple-lightbox#627]
## Description of Problem
I create public profiles on my site. The featured image is the profile photo. Below it can be 0-10 extra photos for a gallery.

If I click the profile photo and cycle through the rest of the photos, everything works as expected, but the last photo is an unexpected result, because the featured image gets included again, because if I click next, I end up at photo 1 (which is the main profile image).

## Details

* URL of Page exhibiting problem: 
local (but can show it on a htaccess secured server)

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Chrome

* Version of SLB Installed: 
2.6.0

* Other plugins installed: 
ACF City Selector
ACF Counter
Adrotate
Advanced Custom Fields Pro
Debug Bar
Disable comments
Gravity Forms
mobble
Query Monitor
5 custom plugins with a NSWF name :) (contains post types and some custom non-js functions)
Theme My Login
Timber
Timber Debug Bar
User Role Editor
Yoast SEO

**Comment by Beee4life** [comment]
I have to make a correction, the post type on which this happens does not have a featured image.

So apparently the ACF field (which contains the image) gets loaded twice. Once on click and once on the end of the gallery.

**Comment by Beee4life** [comment]
I have 'fixed' the issue. It was caused by the [Timber debug bar](http://github.com/upstatement/debug-bar-timber/) (although I haven't deduced why it was doing it).

Closing the issue and raising it new there :)

**Comment by archetyped** [comment]
Hi, glad to hear you were able to track down the cause of your issue :)
