### ISSUE TITLE
Issue: how to leave a feedback&

### ISSUE THREAD

**Issue by forensi** [archetyped/simple-lightbox#628]
#627 # Description of Problem

![image](https://user-images.githubusercontent.com/22107903/31855471-8b5aeb5c-b6b4-11e7-8a8c-82c4f9cd8f70.png)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Thanks :)
