### ISSUE TITLE
I've intstalled the simple-lightbox, but doesnt work.

### ISSUE THREAD

**Issue by GBWP** [archetyped/simple-lightbox#629]
Hi, I've intstalled the simple-lightbox, but doesnt work.
WordPress 4.8.2 running Sydney Child theme.
Simple Lightbox Version 2.6.0 | By Archetyped
here is my gallery:
https://mobulez.com/gb-wp-cv/image-gallery/
Thx!

**Comment by archetyped** [comment]
Hi, apologies for the long delayed response.  It appears that cURL is not enabled and/or activated for your site.  This is usually resolved with a message to your hosting company.  Please see SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

If you are still experiencing an issue after ensuring that cURL is properly activated and configured, please leave an update with details from your hosting company regarding the cURL setup and I would be glad to reopen this ticket and take another look.

Thanks.
