### ISSUE TITLE
Issues when blog uses an RTL language

### ISSUE THREAD

**Issue by fduraibi** [archetyped/simple-lightbox#631]
Some of my blog posts are in Arabic and the blog direction is set to RTL (Right to Left) for those posts, and that misses up some of the alinements (see picture)

![lighbox](https://user-images.githubusercontent.com/432460/32741890-cc4e8176-c8b8-11e7-87fe-fb2d89a0bd46.jpg)

See this as an example: http://www.fadvisor.net/blog/2015/05/html5-and-h264-for-firefox-on-linux-ar/
English posts (LTR) work fine.

The Previous arrow `<` can be fixed easily by adding `left: 4px` to its style

**Comment by archetyped** [comment]
Thanks for the report, a fix is in development.

Quick question: For RTL sites, should the functionality of the navigation arrows be swapped (e.g. **Left** arrow goes to **next** image and **Right** arrow goes to **previous** image)?

**Comment by earmin** [comment]
Hi. Nice to hear that. 
Yes It is better to be like that, I mean "Left arrow goes to next image and Right arrow goes to previous image". 
An example is here: [https://goo.gl/kPk8Z8](https://goo.gl/kPk8Z8)

**Comment by archetyped** [comment]
v2.7.0 adds RTL support to default lightbox themes.  Please review and let me know if you experience any RTL-related issues.

Thanks :)
