### ISSUE TITLE
image title 

### ISSUE THREAD

**Issue by madelinemoya** [archetyped/simple-lightbox#636]
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Closing due to lack of information.  If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
