### ISSUE TITLE
Issue: Simple Lightbox Stopped Working 

### ISSUE THREAD

**Issue by rachdesire** [archetyped/simple-lightbox#640]
The plugin was working fine before but now the lightbox doesn't seem to work. I recently updated Wordpress to WordPress 4.9.2. I also installed WPML. So I'm not sure if it's the new Wordpress update or the plugin conflicting with the plugin?  I've tried deleting and re-installing SLB but it didn't fix the issue. 

URL of Page exhibiting problem: https://calframax.com/products/household-items/
Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
Version of SLB Installed: 2.6.0
Other plugins installed: WPML, Yoast, Jetpack, Contact 7, Akismet

**Comment by eileengavin** [comment]
I'm also finding it just isn't working.
I'm on WordPress version 4.9.2. 
PHP version 5.6.33.
Plugins running: backupwordpress, contact form 7, jquery vertical accordion menu, redirection, responsive menu, wowslider, wp-table reloaded
including : simple lightbox version 2.6.0

Sample page: https://desmondcollege.ie/history/185-2/

I deactivated Contact 7 as I noticed rachdesire above had that plugin, just to check, but still no joy.
Emptied cache. Restarted laptop.

Running firefox 58.0.1
Running chrome Version 64.0.3282.119 (Official Build) (64-bit)

Any suggestions?

**Comment by eileengavin** [comment]
Update : I forgot to mention I turned off all the Group settings. 
After doing all the above it still wasn't working. 
Then a while later I opened Plugins page, and found the plugin was disabled. 
So I re-enabled it again (honestly, I didn't disable it!) and now it works! 
Maybe it was a caching issue? Thanks.

**Comment by rachdesire** [comment]
After looking into everything I contacted our host and they found out that Simple Light Box uses curl to lookup the self-host dynamically which happens to break when using the external IP address. But the problem is solved now.
Thanks!
