### ISSUE TITLE
use large image not original 

### ISSUE THREAD

**Issue by bearstar** [archetyped/simple-lightbox#641]
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB will display any valid image you link to, so you have full control over what images are displayed in the lightbox.  For example, linking to the "large" version of an image will cause SLB to display that image when the link is clicked.

If you are still experiencing an issue with SLB, please fill out the details of your issue above and I would be glad to reopen the ticket and take another look.

Thanks.
