### ISSUE TITLE
When the_content() is cached SLB does not bind events

### ISSUE THREAD

**Issue by szepeviktor** [archetyped/simple-lightbox#642]
I am a Tiny cache user https://github.com/szepeviktor/tiny-cache/blob/master/tiny-cache.php and the author also.
So hooks/filters during `the_content()` are not fired as it is being cached, actually replaced by `the_content_cached()`

When logged in, everything is OK as Tiny cache is disabled: `is_user_logged_in()`
Please advise.

http://balletsummercoursebudapest.com/accommodation/

v2.6

**Comment by archetyped** [comment]
SLB automatically activates links in content when using `the_content()`.  Links added to a page manually or via third-party template tag can be activated for display in the lightbox using `slb_activate()`.

See [SLB's Activation documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation) for more details on using `slb_activate()`.
