### ISSUE TITLE
Captions Not Displaying

### ISSUE THREAD

**Issue by arshleyd** [archetyped/simple-lightbox#643]
Hello!

I'm having an issue where my captions are not displaying in the lightbox. Any idea what may be causing the issue?

https://ccsbuilds.com/spring-run-corridors/

**Comment by Beee4life** [comment]
AFAIK captions are not displayed in the modal, only descriptions. Copy the caption to the description and re-check.

**Comment by archetyped** [comment]
Hi, how are you inserting this gallery into the post?  For example, if using the `[gallery]` shortcode, please provide the full shortcode used (e.g. with options, etc.).

Are these images uploaded and accessible via the site's media library?  If so, do you see the caption text in the **Caption** field when you click the **Edit** link below one of the images in the media library?

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing this issue, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.

**Comment by purplearth** [comment]
I'm seeing a similar issue: can't get captions to display in the lightbox, only descriptions. Caption text is in the caption field in the Media library. I wish there was an 'item.caption' tag that worked, or better yet, a way to add template tags to handle (for instance) captions and custom fields.
