### ISSUE TITLE
Ignoring wpcontent()

### ISSUE THREAD

**Issue by Curros** [archetyped/simple-lightbox#644]
Hello I´m using the below configuration in my wp-config file, so I can have everything separated. But, this configuration is being ignored, and the plugin use the wordpress url instead.

wp-config:
define('WP_CONTENT_DIR', __DIR__ . '/wp-content');
define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/wp-content');

Result: 
http://localhost/wp/wp-content/plugins/simple-lightbox/themes/baseline/js/prod/client.js?ver=2.6.0

Wanted:
http://localhost/ulmwordpress/wp-content/plugins/simple-lightbox/themes/baseline/js/prod/client.js?ver=2.6.0

**Comment by Beee4life** [comment]
This is not really related to this plugin but more to WP setup.

What if you try this ?

    define( 'WP_HOME',                      'http://' . $_SERVER['HTTP_HOST'] );
    define( 'WP_CONTENT_DIR',               realpath( ABSPATH . '../content/' ) );
    define( 'WP_CONTENT_URL',               WP_HOME . '/content' );

**Comment by archetyped** [comment]
SLB uses WordPress' built-in file loading functionality, so it sounds like @Beee4life's suggestion to rework your configuration may be the right option.

If you are still experiencing this issue once you've confirmed your configuration issues are resolved, please provide a link to a page experiencing the issue and I would be glad to reopen the ticket and take a closer look.

Thanks.
