### ISSUE TITLE
Disable lightbox for certain images/links

### ISSUE THREAD

**Issue by sco2tbold** [archetyped/simple-lightbox#647]
Hi. 

There are similar issues, but not exactly what I was looking for. We're building a knowledge base and have a lot of screenshots in our articles. Some screenshots are so high and narrow that the lightbox shows them in a way that the user cannot see the details. I'd need to disable/bypass the lightbox for certain images or links on a page. 

I though that I could add a text link like "In order to view the image in a seperate tab, please click this link" and in the link I could add class="noLightbox"? 

Thanks for your feedback!

**Comment by archetyped** [comment]
Hi, you can use the `[slb_exclude]` shortcode to exclude links on that page from being displayed by SLB.  See here for [more details on SLB's shortcodes](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes).

You can also disable automatic resizing via SLB's options page to display images at their native dimensions in the lightbox.
