### ISSUE TITLE
Issue: screen_icon() deprecated

### ISSUE THREAD

**Issue by haveboard** [archetyped/simple-lightbox#651]
## Details

"PHP Notice: screen_icon is deprecated since 3.8.0 with no alternative available"

protected function show_icon() uses depreciated screen_icon function

https://wordpress.org/support/topic/php-notice-screen_icon-is-deprecated-since-3-8-0-with-no-alternative-available/

**Comment by icetee** [comment]
Depreciated this functions:
`screen_icon`
`get_screen_icon`
`create_function`
