### ISSUE TITLE
Issue: plugin not working after DNS change

### ISSUE THREAD

**Issue by studiomark** [archetyped/simple-lightbox#652]
## Description of Problem

Hello,
recently I’ve done the migration of the (the test page was www.studiomark.net/off/fondazionecrtrieste) site to another host (95.174.9.185) and set up the DNS pointing to another address (www.fondazionecrtrieste.it), that for now is busy, but it will be the final one. The problem is that after this migration the Simple Lightbox plugin isn’t working. Is a DNS-pointing issue? In the final place with his natural DNS will be ok?
Best regards, Jakob

## Details

* URL of Page exhibiting problem: unfortunately the page isn't visible to public, because it doesn't have a real domain pointing. The address is 95.174.9.185, you can set the final name "www.fondazionecrtrieste.it" to point it (in the end, if all works well, the address will be this) and the page that might have the plugin active may be "www.fondazionecrtrieste.it/gli-artisti/"
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox (we didn't test in other browsers"
* Version of SLB Installed:  2.6.0
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, I'm closing this ticket as SLB appears to working properly at the link you provided.

If you are still experiencing this issue, please post additional details below and I would be glad to reopen the ticket and take another look.
