### ISSUE TITLE
Issue: Lightbox Will Not Display

### ISSUE THREAD

**Issue by jdcarmichael** [archetyped/simple-lightbox#653]
## Description of Problem
Lightbox does not seem to want to work on my site. I've tried deactivating and reactivating but cannot seem to get it to work. Any insights would be much appreciated. If you need log in info or anything that I can do to help, just let me know.

Best regards,

Joshua Carmichael

## Details

* URL of Page exhibiting problem: http://localhost/websites/wordpress
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.6.0
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please update your original post with a valid link (localhost is not accessible outside of your own computer) and I would be glad to take a look.

Thanks.

**Comment by dvdobrovolskiy** [comment]
Does not work.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
