### ISSUE TITLE
Google Fonts and GDPR

### ISSUE THREAD

**Issue by KristofKlein** [archetyped/simple-lightbox#658]
Hi,

I need some help. I try to get my Blog GDPR ready. Means adjust Disclaimer and stuff like that. There is some sort of data protection thing that I would like to resolve. It's about Yanone Kaffeesatz...it's fetched from the google APIs. So therefore no good. Or at least not perfect...

What do I need to do to get rid of it?! A Simple Helvetica font would fits my issue perfectly 😀 
As long as this stupid css from google does not show up in my resources I'm happy 😀

**Comment by wunderlich** [comment]
I'm facing the same issue. I temporary switched to another plugin, because I don't want to manipulate the plugin code (I don't want to change it again after an update). 

But @KristofKlein's workaround worked for me, too.

**Comment by archetyped** [comment]
Theme font is now loaded locally (at least until Google Fonts/GDPR questions are resolved).
