### ISSUE TITLE
Elementor & Simple Lightbox Conflict

### ISSUE THREAD

**Issue by kaleeraisor** [archetyped/simple-lightbox#660]
## Description of Problem

Hey there, thanks for the great plugin. I just wanted to let you in case you weren't already aware that there seems to be a conflict between Elementor and Simple Lightbox (at least in my tests).

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed: Elementor (version?)

**Comment by archetyped** [comment]
Hi, please fill in the rest of the details of your issue above and I would be glad to take a closer look.

Thanks.

**Comment by dkpminus** [comment]
It looks like the issue came into effect since Elementor added the [sitewide lightbox option](https://elementor.com/v160-image-lightbox/), even when the option is disabled SL doesn't work. I've disabled Elementor on that site and it resolved the issue.

**Comment by archetyped** [comment]
Thank you for the additional details.  I will look into this.

**Comment by archetyped** [comment]
Hi, I've tested Elementor v2.0.15 and SLB functions without any issues as long as Elementor's lightbox is disabled (when Elementor's lightbox is also enabled, both lightbox's are displayed, but that is to be expected when multiple lightboxes are activated on a site).

Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing this issue, please provide the previously-requested details and I would be glad to reopen the ticket and take another look.
