### ISSUE TITLE
Issue: Simple Lightbox not working on some sites

### ISSUE THREAD

**Issue by cwittie** [archetyped/simple-lightbox#662]
## Description of Problem
I can’t seem to get Simple Lightbox to work. It was working at one point but now it just opens the image in a new page with a black background. I have 2 sites which I though were identical. It works on one of them but not the other.
http://template1.ipaw2.wpengine.com/products/ This one works fine, this one does not: http://template1.idealprotein.wpengine.com/products/
I can’t figure out what’s wrong. Both sites have the same plugins etc. When I inspect the page, none of the classes or IDs related to the plugin appear around the images int he lightbox.
I just verified with our web host provider that we do meet all of the SLB and WordPress requirements as specified. Do you have any other ideas what could be causing the issue? I tried deleting the plugin and re-installed it.
## Details
* URL of Page exhibiting problem: http://template1.idealprotein.wpengine.com/products/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All browsers Chrome, Firefox, IE, etc.
* Version of SLB Installed: 2.6.0
* Other plugins installed: Adminimize, aspen footer editor, broadcast, broadcast premium, Brute force login protection, Divi, Divi booster, Domain mapping, duplicate post, Erident custom login and dashboard, event tickets, google analytics, gravity forms, monarch, multisite content copier, popup maker, really simple captcha, shortcoder, simple lightbox, the events calendar, events calendar pro, updraft plus, use any font, wordpress importer, WP smush pro, WPMU dev dashboard.

**Comment by cwittie** [comment]
We have over 1000 sites that we use your plugin on so assistance would be greatly appreciated :)

**Comment by archetyped** [comment]
Hi, the main cause of this issue is PHP and/or cURL not being properly configured for handling local requests.  Unfortunately, this sometimes requires asking the hosting company to take a deeper look, as many simply check to see if cURL is enabled the first time around.

Once PHP and cURL have been properly configured, the issue has been resolved 100% of the time for others who have opened tickets regarding this issue, especially where SLB works on one site but not on another site hosted by the same company.

Though unlikely causes of this particular issue, here are some other things you can look into:

* Ensure the theme's layout file exists (for SLB's default themes, the file is `themes/baseline/layout.html` in SLB's folder)
* [Check for plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts "Check for plugin/theme conflicts")

Please let me know what you find, and I would be glad to take another look if necessary.

**Comment by cwittie** [comment]
Hi, I verified multiple times with the host that the PHP and cURL are configured properly. 
The themes layout file exists: themes/baseline/layout.html
I've tried copying to staging and disabling all plugins BUT simple lightbox and I still have the issue.
I also reverted to the Twenty Seventeen theme and still had the issue with all plugins disable BUT the lightbox plugin.
Please take a look when you can, we have 350 sites relying on the plugin and are migrating 650 more sites to WordPress.

**Comment by archetyped** [comment]
You mentioned in your original post that 1 site does not work while another does, but later refer to a number of sites using the plugin.  Are you saying that they all do not work with SLB or just the link provided?

If the former, then it's definitely a host issue, and I would recommend escalating your support request with the host for someone who may better know the ins and outs of configuring cURL for PHP for local requests (it's separate from simply enabling a cURL module).

If the latter, then it sounds like an issue to the specific server the problem site is running on (different sites can run on different servers even though they are both hosted by the same company).  I would recommend checking your error logs for the site experiencing a problem for any details regarding loading the lightbox theme's layout file.

**Comment by archetyped** [comment]
Hi, are you still experiencing this issue?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by cwittie** [comment]
Hello,

Yes I am still experiencing the issue. I have a number of sites in a multi-site instance where the SLB plugin is not working.

**Comment by Similambda** [comment]
The same for me, have 1 site with two versions:
1. developer site
2. official site

On developer site plugin stopped working (can't activate it in wp admin).
On official site plugin is still working as a charm.

So I think problem is server configuration, but what exactly? I don't know.

**Comment by archetyped** [comment]
@Similambda, not being able to activate the plugin is not the same issue.  Please [create a new ticket](https://github.com/archetyped/simple-lightbox/wiki/Reporting-Issues) so that your specific issue can be evaluated.

Thanks.

**Comment by archetyped** [comment]
@cwittie did you find anything in the site's logs where SLB was not working?

Also, if there are multiple sites where SLB is not working, I would recommend evaluating those sites for any similarities that may shed light on why they are not working.  You may need to contact your hosting company for some important information, such as whether the sites in question may be stored on the same physical server, etc.

**Comment by cwittie** [comment]
@archetyped 

The site instances are the same, I confirmed with the web host provider that the sites are stored on the same server.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
