### ISSUE TITLE
Issue: Image compression 

### ISSUE THREAD

**Issue by SannyMedia** [archetyped/simple-lightbox#664]
## Description of Problem

I was wondering of the plugin compresses the images, because no matter how many times I uplaod the best possible quality and eventhough I checked the WP image settings and have not yet installed the EWWW Image Optimizer, my uploaded images are always compress to a low quality? 
Is it possible that the plugin compressed my pictures? 

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, Simple Lightbox does not make any modifications to images.  If you are seeing lower quality images, you may want to check that you are linking to the full-size image you uploaded, as WordPress itself does create compressed versions of uploaded images at different resolutions.

Here is [WordPress' documentation on selecting the image to use when inserting a link](https://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link) to use as a reference.  If you are still experiencing an issue, please update your original post with a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by SannyMedia** [comment]
Thanks a lot, you solved my issue. I had completely forgotten about the media settings of WP and was wondering why the light box would always show a compressed version.

Many thanks
Sanny

**Comment by archetyped** [comment]
Glad to hear your issue was resolved 😃
