### ISSUE TITLE
Event listener not inserted

### ISSUE THREAD

**Issue by christianswanepoel** [archetyped/simple-lightbox#665]
## Description of Problem

Lightbox is working on images placed on pages, but not getting it to work in custom code for a page template. Basically the Lightbox event listener isn't inserted on these pages. Any tips?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it's important that the theme, including custom page templates meets [certain requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#theme) to work properly with Simple Lightbox.  As long as those requirements are met, SLB should work properly.

If you are still experiencing an issue after ensuring the custom template meets the requirements, please fill in the rest of the details of your issue in your original post and copy/paste the template code in a new comment, and I would be glad to reopen this ticket and take a look.

Thanks.
