### ISSUE TITLE
Issue: text not showing in popup after cloning from dev site that was working on another host

### ISSUE THREAD

**Issue by duncanhotston** [archetyped/simple-lightbox#666]
## Description of Problem
Have taken over a site that uses the simple-lightbox plugin for popups. we added title and product codes to popups and all was fine however after putting site live on clients hosts using the managewp clone tool the popups no longer work in the same way. please compare the dev site and live site:

Dev site:
http://skye.agency/MPM/mpm-brands/sperm-keyrings/   -  then click on standard colours tab

Live site (cloned from dev site above)
http://microplasmouldings.com/mpm-brands/sperm-keyrings/   -  then click on standard colours tab

Please can you advise why this might be. I have updated the plugin and tried installing the plugin again on the live site.

Many thanks

## Details

* URL of Page exhibiting problem: http://microplasmouldings.com/mpm-brands/sperm-keyrings/   -  then click on standard colours tab

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All browsers
* Version of SLB Installed: 
* Other plugins installed: /htdocs/MPM/wp-content/plugins/advanced-custom-fields-nav-menu-field
/htdocs/MPM/wp-content/plugins/advanced-custom-fields-pro
/htdocs/MPM/wp-content/plugins/akismet
/htdocs/MPM/wp-content/plugins/all-in-one-wp-migration
/htdocs/MPM/wp-content/plugins/contact-form-7
/htdocs/MPM/wp-content/plugins/custom-post-type-ui
/htdocs/MPM/wp-content/plugins/flamingo
/htdocs/MPM/wp-content/plugins/flow-flow
/htdocs/MPM/wp-content/plugins/gzip-ninja-speed-compression
/htdocs/MPM/wp-content/plugins/minify-html-markup
/htdocs/MPM/wp-content/plugins/post-duplicator
regenerate-thumbnails
search-and-replace_remove
simple-lightbox
wordpress-seo
worker
wp-cli-login-server
wp-file-manager
wp-migrate-db-pro
wp-migrate-db-pro-media-files
wp-nested-pages

**Comment by duncanhotston** [comment]
I have moved hosts and now the popups work however the captions no longer appear:
https://microplas.wpengine.com/mpm-brands/sperm-keyrings/
can you tell me why this is? They should look like this version:
http://skye.agency/MPM/mpm-brands/sperm-keyrings/

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by duncanhotston** [comment]
I did get it working by installing an older version of the plugin but since word press updated it has stopped showing the captions again. I have tried to install the latest plugin version but still does not work.

**Comment by archetyped** [comment]
One suggestion is to upload a new image on a test page on the live (cloned) site with captions and see if that works.  If it does, then it's an indication that the dev site's data was not properly migrated.

Aside from that, there's not I can suggest or look into without the details requested in my earlier comment.  If you can provide those details, I would be glad to take another look.

**Comment by duncanhotston** [comment]
Hi

I have added various new images and added captions but they also do not show.

Can I provide you with the login details so you can investigate in more detail?

Regards 

Duncan

**Comment by archetyped** [comment]
You can send WP user and database login details to support@archetyped.com.  However, that will not provide the previously-requested details such as the migration process, etc., so those details remain essential to properly evaluating your issue.

**Comment by archetyped** [comment]
Hi, posting login information to a public forum is not recommended.  I have removed your previous reply from the thread, but I would recommend updating your login details to be safe.

Once updated, please send WP user and database login details to support@archetyped.com.
