### ISSUE TITLE
Feedback: very nice

### ISSUE THREAD

**Issue by muoe** [archetyped/simple-lightbox#669]
## Description of Problem
congratulations a very nice plugin! It is kept simple and brings the most important functions. nice also that it brings voice files. unfortunately, there is a problem that the title of the image is always displayed even though the display is disabled
(UI > Last step > Title "not selected"

## Details

* URL of Page exhibiting problem:   not public
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  all
* Version of SLB Installed:  current
* Other plugins installed: yes, many

**Comment by archetyped** [comment]
Hi, can you please provide a bit more detail on the issue you are experiencing?  Simple Lightbox does not have an option called "UI > Last step > Title".

Thanks.

**Comment by muoe** [comment]
Please have a look to the screenshot (setting / issue)

Thanks.
![lightbox](https://user-images.githubusercontent.com/41318365/42863842-bec107ae-8a64-11e8-9821-c29635b40682.png)

**Comment by archetyped** [comment]
Thank you for the clarification.  That option is to enable the use of the default title generated by WordPress if no custom title is set.  WordPress uses the image's file name to generate the default title (e.g. `my-photo.jpg` = `my-photo`), which many users do not want so it's use by SLB is disabled by default, but can be enabled via this option.

All elements in the lightbox (title, caption, etc.) are controlled by the selected lightbox theme.  You can create a custom theme (even using an existing theme as a base) to customize the lightbox as desired.  See [SLB's theme documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for more information.
