### ISSUE TITLE
Issue: WooCommerce Add-on not working

### ISSUE THREAD

**Issue by QuailStudio** [archetyped/simple-lightbox#670]
## Description of Problem

 I just bought the Simple Lightbox: WooCommerce Add-on
And I have installed it, but nothing is happening...

"I tried enabling support for the default woocommerce Lighbox,
but it doe not work. it does nothing then. "
could you please help me out.

thanks

## Details

* URL of Page exhibiting problem:  https://www.quailstudio.com/product/kay-red/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all 
* Version of SLB Installed: slb-woocommerce_0.2.1
* Other plugins installed: Akismet Anti-Spam, All-in-One WP Migration, Custom Sidebars, Easy Video Player, Jetpack by WordPress.com, Preserved HTML Editor Markup Plus, Simple Lightbox, Simple Share Buttons Adder, Widget Title Links, WooCommerce PayPal Checkout Gateway, WooCommerce Services.

**Comment by archetyped** [comment]
Hi, what version of WooCommerce do you currently have installed?  Does your site match this and the rest of [the WooCommerce add-on's requirements](https://archetyped.com/lab/slb-woocommerce-beta/)?

**Comment by QuailStudio** [comment]
I have version version 3.4.3 installed at the moment , Oh I see I just realized on your website it says support up to WooCommerce 2.1.6, that's disappointing (>__<) Any plans on an update?

**Comment by archetyped** [comment]
Yes, a lot has changed internally in WooCommerce, but support for the add-on is currently in development.

You will receive an email automatically when the add-on is updated..
