### ISSUE TITLE
Request: Disable comments on elements

### ISSUE THREAD

**Issue by reflectively** [archetyped/simple-lightbox#671]
## Description of feature

Option to disable comments on images or elements in general

## This feature would be used to

Disable comment field for images when lightbox is open

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above <-

**Comment by archetyped** [comment]
Hi, can you provide more details on your request?  Simple Lightbox does not display any comments fields in the lightbox, so a screenshot may be helpful in illustrating what you would like to see changed.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still interested in this feature request for SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
