### ISSUE TITLE
Duplicate imagem with wordpress gallery

### ISSUE THREAD

**Issue by uferes** [archetyped/simple-lightbox#672]
## Description of Problem

Hello! The plugin is wonderful !! I loved. Congratulations on making it available.
The only problem for me when I have a simple wordpress gallery and when I click on the photo the plugin opens the image but behind the wordpress also opens the image preview. That is, I have a duplicate view. How to disable wordpress view and leave only your plugin or vice versa. Tks!

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your original post with the necessary details and I would be glad to take a look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
