### ISSUE TITLE
Request: Remove or change default font

### ISSUE THREAD

**Issue by johnflufin** [archetyped/simple-lightbox#673]
## Description of feature

The default font used with this plugin (Yanone Kaffeesatz) is not what many would consider to be a neutral or generic font that blends with many designs. It has a unique look and clashes with designs 99% of the time. Please consider at least one of the following options

- Remove the default font-family style and allow the theme's css font-family to be used instead.

- Allow the default font-family style to be disabled in the settings so the theme's style can override it.

- Change the default font to something more generic (helvetica, etc).

- Add font choices to the plugin settings page.

## This feature would be used to

This would allow the lightbox this plugin produces to blend in more seamlessly with more themes.

## If you added this feature, I would:

d) All of the above

Thank you for your consideration. Keep up the good work!

**Comment by archetyped** [comment]
Hi, SLB's appearance can be fully customized using a custom theme.  This provides the best option for matching a site's overall theme.

See [SLB's theme documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for details and resources on creating custom themes.

**Comment by johnflufin** [comment]
Hmm, thank you. Good to know. That's certainly a nice option that I wasn't aware of. But considering this plugin is called "Simple" Lightbox and not "Simple Wordpress Developer" Lightbox this isn't what I would describe as a simple solution for changing fonts. 🤔
