### ISSUE TITLE
Issue: Video beta price shows up as $16

### ISSUE THREAD

**Issue by Weeding42** [archetyped/simple-lightbox#674]
## Description of Problem

I am interested in buying the video add-on, but when I click on the link, the pay window shows $16, not the 50% off.  Please help.  Thanks. 

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Thanks for the heads up.  The link has been fixed to reflect the discount.
