### ISSUE TITLE
"Enable default title" disabled but title still displays!

### ISSUE THREAD

**Issue by johnflufin** [archetyped/simple-lightbox#676]
## Description of Problem

The default title of images (file name) is displaying when simple lightbox opens even though "Enable default title" is disabled. If I understand [this page](https://archetyped.com/lab/slb-2-3-0/) correctly, this should not be happening.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Confirmed in latest Chrome, Safari and Firefox
* Version of SLB Installed: 2.7
* Other plugins installed: 

(All latest versions)
Akismet
Classic Editor
Constant Contact Forms for WordPress
Exclude Pages From Menu
Last Modified Timestamp
MetaSlider
Page Links To
Simple Page Ordering
Smush
TinyMCE Advanced
White Label CMS
Wordfence
WP-DBManager
Yoast SEO

**Comment by archetyped** [comment]
Hi, please add a link to a page that exhibits the issue you are experiencing to your post above and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
