### ISSUE TITLE
Issue: Lightbox doesn't work on my site

### ISSUE THREAD

**Issue by netburst** [archetyped/simple-lightbox#677]
## Description of Problem
Hi, I've installed this plugin but it doesn't seem to work on my site... I checked the requirements, tried to deactivate, reactivate and changed my theme but nothing worked. If you need any other info just let me know and I'll happily provide it.
Thank you in advance

## Details

* URL of Page exhibiting problem: https://wordpress-test.site/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome both desktop and mobile
* Version of SLB Installed: 2.7.0
* Other plugins installed: W3 Total cache, Yoast SEO, Defender Pro, Smush

**Comment by archetyped** [comment]
Please provide a working link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by netburst** [comment]
I'm sorry, it went down. Should be working now

**Comment by archetyped** [comment]
Your site appears to be loading 2 separate copies of jQuery, which can cause issues with other code that interacts with jQuery (such as SLB).

Please leave an update if you are still experiencing an issue once the additional jQuery loading is removed.  Also, deactivating any caching plugins during testing is recommended.

**Comment by netburst** [comment]
I've removed the Google jQuery, now there's only the default wordpress one but the lightbox still doesn't work

**Comment by archetyped** [comment]
I looks like some cached JavaScript code is causing an error, which stops other code (such as SLB) from running.  As previously noted, clearing cached files and disabling caching plugins is recommended, at least during testing to avoid issues with stale data.

**Comment by netburst** [comment]
thank you, I disabled caching on the slb scripts and now it works perfectly :)
