### ISSUE TITLE
Creating a custom template with Twig/Timber

### ISSUE THREAD

**Issue by Beee4life** [archetyped/simple-lightbox#678]
After reading [this post](https://archetyped.com/know/slb-theme-anatomy/), I tried to create my own template.

I use this function:
```
function my_custom_lightbox_theme( $themes ) {
    $properties = array (
        'id'     => 'sd8',
        'name'   => 'My customt itle',
        'layout' => 'http://sd8.beee/content/themes/theme-name/templates/lightbox.html',
    );
    $themes->add( 'sd8', $properties );
}
add_action( 'slb_themes_init', 'my_custom_lightbox_theme' );
```

My plan was to use [this layout](https://archetyped.com/know/slb-theme-layout/) and I wanted to replace the title and description. That was not too difficult.

When I then click an image, nothing happens.

I noticed the syntax, which I think causes the problem I have, since my entire theme is written in [Timber](https://www.upstatement.com/timber/) which uses this syntax `{{ value }}`.

Is there a way to make this work with Twig/Timber ?

**Comment by archetyped** [comment]
There shouldn't be any conflict as Timber templates are processed by PHP, while SLB's theme layout is processed by JavaScript.

Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by Beee4life** [comment]
This is how I do some stuff for the image and to prepare twig values (the working version).
```
if ( false == $check_photo ) {
    // take profile offline
    sd_take_profile_offline( $post_id );
} else {
    // images
    $gallery_big    = sd_rewrite_image_location( wp_get_attachment_image_src( $context[ 'image_id' ], 'gallerybig' ) );
    $medium_large   = sd_rewrite_image_location( wp_get_attachment_image_src( $context[ 'image_id' ], 'medium_large' ) );
    $profile        = sd_rewrite_image_location( wp_get_attachment_image_src( $context[ 'image_id' ], 'profile' ) );
    $profile_header = sd_rewrite_image_location( wp_get_attachment_image_src( $context[ 'image_id' ], 'profileheader' ) );

    if ( true == $context[ 'options' ][ 'settings' ][ 'nsfw_filter' ] || ( true == $context[ 'options' ][ 'settings' ][ 'hide_fakes' ] && in_array( $post->post_author, sd_get_fake_users() ) ) ) {
        $fake_image     = $context[ 'options' ][ 'settings' ][ 'fake_image' ];
        $profile        = wp_get_attachment_image_src( $fake_image, 'profile', false );
        $gallery_big    = wp_get_attachment_image_src( $fake_image, 'gallerybig', false );
        $medium_large   = wp_get_attachment_image_src( $fake_image, 'medium_large', false );
        $profile_header = wp_get_attachment_image_src( $fake_image, 'profileheader', false );
    }
    $context[ 'gallery_big' ] = $gallery_big[ 0 ];
    $profile_image            = '<a href="' . $gallery_big[ 0 ] . '"><img src="' . $profile[ 0 ] . '" class="photo" alt="' . get_the_title() . '" /></a>';

    if ( $gallery_big[ 1 ] > $gallery_big[ 2 ] ) {
        $header_image = '<a href="' . $gallery_big[ 0 ] . '"><img src="' . $profile_header[ 0 ] . '" class="photo" alt="' . get_the_title() . '" /></a>';
    } else {
        // TODO: check if this is (still) needed
        $header_image = '<a href="' . $gallery_big[ 0 ] . '"><img src="' . $profile[ 0 ] . '" class="photo" alt="' . get_the_title() . '" /></a>';
    }

    // check if plugin is active
    if ( class_exists( 'SLB_Base' ) ) {
        $processed_profile_image    = slb_activate( $profile_image );
        $context[ 'profile_image' ] = $processed_profile_image;
        if ( $gallery_big[ 1 ] > $gallery_big[ 2 ] ) {
            $processed_header_image    = slb_activate( $header_image );
            $context[ 'header_image' ] = $processed_header_image;
        }
    } else {
        $context[ 'profile_image' ] = $profile_image;
        if ( isset( $header_image ) ) {
            $context[ 'header_image' ] = $header_image;
        }
    }
}
```

This is my output.
```
<figure class="media">
    <div class="enlarge">
        {{ profile_image }}
        {% if post.post_date > site.options.settings.new_date %}
            <div class="new">
                <img src="{{ site.theme.link }}/assets/img/new-ribbon.png" alt="NEW" class="" />
            </div>
        {% endif %}
        {% if 'vip' == function( 'sd_get_user_status', post.post_author ) %}
            <div class="vip">
                <img src="{{ site.theme.link }}/assets/img/vip-crown.png" alt="VIP profile" class="viplogo" />
            </div>
        {% endif %}
    </div>
</figure>
```

**Comment by Beee4life** [comment]
This is my lightbox template.
```
<div class="slb_container">
    <div class="slb_content">
        {{item.content}}
        <div class="slb_nav">
            <span class="slb_prev">
                {{ui.nav_prev}}
            </span>
            <span class="slb_next">
                {{ui.nav_next}}
            </span>
        </div>
        <div class="slb_controls">
            <span class="slb_close">
                {{ui.close}}
            </span>
            <span class="slb_slideshow">
                {{ui.slideshow_control}}
            </span>
        </div>
        <div class="slb_loading">
            {{ui.loading}}
        </div>
    </div>
    <div class="slb_details">
        <div class="slb_inner">
            <div class="slb_data">
                <div class="slb_data_content">
                    <span class="slb_data_title">
                        Example title
                    </span>
                    <span class="slb_group_status">
                        {{ui.group_status}}
                    </span>
                    <div class="slb_data_desc">
                        YYY
                    </div>
                </div>
            </div>
            <div class="slb_nav">
                <span class="slb_prev">
                    {{ui.nav_prev}}
                </span>
                <span class="slb_next">
                    {{ui.nav_next}}
                </span>
            </div>
        </div>
    </div>
</div>
```

**Comment by Beee4life** [comment]
I just found the example theme (as a plugin). Now playing with that. First attempt works... so that's a good thing :)

**Comment by archetyped** [comment]
Glad to hear the starter theme works for you.  This provides a good option to compare with the theme you started building to determine why it was not working.

Depending on the type of changes you want to make to an existing theme, you can either create a child theme or copy and modify an existing theme.

A child theme points to another theme as its parent theme.  This allows you to only included the _changes_ to that theme in your child theme's assets (CSS, JS, etc.).  Another benefit is that updates to the parent theme are automatically reflected in child themes, allowing theme to take advantage of new features, etc. without any additional work.  See [this tutorial on a setting up themes](https://archetyped.com/know/slb-theme-anatomy/) for more details on creating a child theme.

If you are making a lot of changes to an existing theme, then copying it and modifying it may be a good option.  Simply copy the files from the original theme (e.g. default themes are stored in SLB's `themes` directory) to your custom theme's directory and make the desired changes.

**Comment by Beee4life** [comment]
I said it worked, as in functional, but not completely... the css is not loaded because several buttons are shown whereas they should be hidden. 

I tried various options, just loading a template.html file and use the rest from parent, use everything from child etc. nothing seems to change anything....

**Comment by archetyped** [comment]
Thanks for the clarification.  The ticket was closed because you said the starter theme was working and answers to your questions on how to further customize it were provided.  Ticket can always be reopened as necessary.

Please upload your lightbox theme (as a zip file) so that I can test it directly.

**Comment by Beee4life** [comment]
Took a bit of time, sorry for that. I have uploaded it to Github, see it [here](https://github.com/Beee4life/custom-lightbox).

**Comment by archetyped** [comment]
Please post your updated theme with the changes noted above, and I'll take a look at what may be missing.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
