### ISSUE TITLE
Issue: Title and captions not working

### ISSUE THREAD

**Issue by Nooberi** [archetyped/simple-lightbox#679]
I'm using a simple lightbox at my site that has 2 languages. At some images it removes the title and uses caption as title. It shouldn't do that and I haven't figured out where is the problem yet. 

Here is a picture of what it should look like (green) and what it shouldn't (red):
[](http://i1087.photobucket.com/albums/j472/Ultimare/Capture%2002_zpso3imto86.jpg)

This problem displays in all browsers.

**Other pluggins I have installed:**
- Beaver Builder Plugin
- Contact Form 7
- Polylang
- Post Grid
- Smart Slider 3

**Comment by archetyped** [comment]
Hi, it appears that there may have been an issue when uploading your images, as I do not see any images in your post above.  Please try adding the images again and post an update and I will take another look.

Also, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
