### ISSUE TITLE
Issue: lightbox just not working

### ISSUE THREAD

**Issue by nicos222** [archetyped/simple-lightbox#680]
Lightbox not working. Gone through all troubleshooting steps.

New WP installation out of the box (4.9.7 and 4.9.8)
Only your plugin installed and activated
Tested with different WP default templates
Even changed my hosting provider and still have same issue.

So fresh installation without any modifications or content. Other lightbox plugins dont work either.

Example:
http://sv4ahssur.preview.infomaniak.website/2018/09/04/hello-world/

**Comment by archetyped** [comment]
Hi, the problem is that there are no image links on the page, just plain images.  Without links, there is nothing for a user to click, and thus no way for a lightbox to be launched.

See [SLB's Beginner's Guide](https://archetyped.com/know/simple-lightbox-for-noobs/) for more details on adding linked images to your posts.

**Comment by nicos222** [comment]
Thanks for reply. I add images as usual "add media" and from "media library" I select a picture and click "insert into post" it inserts a thumbnail. Are you saying the issue comes from WP?

**Comment by nicos222** [comment]
Thanks for reply. I add images as usual "add media" and from "media
library" I select a picture and click "insert into post" it inserts a
thumbnail. Are you saying the issue comes from WP?

Am Do., 6. Sep. 2018 um 02:00 Uhr schrieb Archetyped <
notifications@github.com>:

**Comment by pvillanueva01** [comment]
Hello all,

I have followed all the recommendations for the having this plugin work, but no luck.
New WP installation 4.9.8
Only your plugin installed and activated
Tested with different WP default templates
Link the image to media and attachment URL

Please see:

http://spvisualmix.com/nva/uncategorized/a-table-for-friends/

I checked with my hosting and cURL is enabled for local requests. Any help would be greatly appreciated it.
