### ISSUE TITLE
Issue: no lightbox opems

### ISSUE THREAD

**Issue by Odido** [archetyped/simple-lightbox#681]
Hello,

on my page the images are not shown as lightbox. Instead the original version is shown. I've checked for jQuery - version 1.12.4 is present and loaded in the head of the page. phpinfo() says, that curl is enabled (7.47.0).

* https://wiki.ad-libitum.info/roaming-profiles (I know about the SSL-problem. This is just a private project not intended for the public and the certificate is not valid for subdomains)
* Chrome, FF, Edge, IE and Opera
* Version of SLB Installed: 2.7.0
* Other plugins installed: All-in-One WP Migration - that's all
* Theme: Twenty Sixteen - untouched.

Thx
Oliver

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled and/or properly configured for your site.  Please see SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

If you are still experiencing an issue once cURL has been set up for your site, please post an update and I will be glad to reopen this ticket and take another look.

**Comment by Odido** [comment]
Hi,

I once again checked for that and can't find a problem with cURL:
![grafik](https://user-images.githubusercontent.com/14124285/45340472-072ed900-b597-11e8-94b1-c80d71d3d2b2.png)

Any further hints?

Thx
Oliver
