### ISSUE TITLE
Safari 12 Compatibility

### ISSUE THREAD

**Issue by jouwstad** [archetyped/simple-lightbox#685]
After an update to Safari 12, the simple lightbox is no longer working properly

**Comment by archetyped** [comment]
Hi, SLB has been tested in Safari 12.  There is [a bug in Safari 12 that affects SLB's slideshow functionality](693), but the lightbox and images should still be displayed.

If you are experiencing a different issue, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
