### ISSUE TITLE
Lightbox not working

### ISSUE THREAD

**Issue by pvillanueva01** [archetyped/simple-lightbox#688]
Hello all,

I have followed all the recommendations for the having this plugin work, but no luck.
New WP installation 4.9.8
Only your plugin installed and activated
Tested with different WP default templates
Link the image to media and attachment URL

Please see:

http://spvisualmix.com/nva/uncategorized/a-table-for-friends/

I checked with my hosting and cURL is enabled for local requests. Any help would be greatly appreciated it.

**Comment by archetyped** [comment]
Hi, that link results in a "Page not found" error.  Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by pvillanueva01** [comment]
Thank you but I ended up using a different plugin.

**Comment by pvillanueva01** [comment]
Thank you but I ended up using a different plugin.
