### ISSUE TITLE
Lightbox open full screen since iframe

### ISSUE THREAD

**Issue by fisgonX** [archetyped/simple-lightbox#689]
I have to use a gallery in a iframe because is in other subdomain.

I want to open the lightbox since that iframe in full screen. How I can do it? It works perfectly, but only inside the iframe

![image](https://user-images.githubusercontent.com/33815647/46345966-c03c7c80-c646-11e8-8a89-cd6afdb53e28.png)

Thanks in advance

**Comment by archetyped** [comment]
SLB generally does not have access to links in an iFrame from the parent document due to the [same origin policy](https://en.wikipedia.org/wiki/Same-origin_policy) browsers implement for security purposes.
