### ISSUE TITLE
problem with plugin very urgent!

### ISSUE THREAD

**Issue by SeoFpc** [archetyped/simple-lightbox#690]
i have install the plugin but in the page there is not this function .. http://test.fpcos.it/hcontinental/hotel/rooms/ in this page, when customer click the slider image, text or room name it will open a lightbox ... now i need the lightbox only here .. please can you check?

**Comment by archetyped** [comment]
Hi, SLB does not appear to be installed and/or activated at the link provided.  Please provide a link to a specific page where SLB is installed and activated, and I would be glad to take another look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
