### ISSUE TITLE
Request: Update to be functional with Gutenberg galleries

### ISSUE THREAD

**Issue by RobertFCda** [archetyped/simple-lightbox#691]
## Description of feature
Updating the plugin to be functional with the new Gutenberg galleries in Wordpress

## This feature would be used to
Add lightbox functionality to Gutenberg

## If you added this feature, I would:
D
a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Added to the list. Thanks.

**Comment by RobertFCda** [comment]
I've discovered the solution.  It's not a plugin issue.  It's an issue with the new Wordpress Blocks architecture.  

In the new Blocks landscape, when inserting an image, or gallery with the desire to have the image clickable to open a larger version, or lightbox, the image/gallery needs to be explicitly set to open the associated media file via the Link to attribute in the block settings.  Once done, Simple Lightbox works as it should with the new Blocks architecture.

**Comment by Grimmwicht** [comment]
I can confirm this behaviour. When inserting a new gallery block, as default the gallery is set to not link images. When changing this, SLB works again as expected. I'm not sure if it's useful to extend SLB functionality to image galleries without links, so this issue could be marked solved, I guess.
