### ISSUE TITLE
Safari 12 Bug affects SLB slideshow functionality

### ISSUE THREAD

**Issue by archetyped** [archetyped/simple-lightbox#693]
Safari v12 (macOS and iOS) includes a WebKit bug that affect's SLB's slideshow functionality.  When navigating to previous/next items in lightbox, navigation is not accessible to subsequent items.

The bug has been fixed in WebKit itself, so hopefully Safari will be updated soon to resolve this issue.

* [WebKit Bug](https://bugs.webkit.org/show_bug.cgi?id=188794)
* [Hacker News Discussion on bug](https://news.ycombinator.com/item?id=18021835)

This ticket will remain open until the issue is resolved.  You can subscribe to this ticket to monitor the status of the Safari bug.

**Comment by geminidreams76** [comment]
Thanks for clearing that up. I suspected something like this, which is why I have 3 browsers on my computer while developing our website, to check for such things, which inevitably happen.

But this is a bug I can live with, as very few of our site visitors use Safari 12. Or I could just turn slideshow off, for now.

**Comment by Deichschaf013** [comment]
Hi, I've read that there is a new iOS version, 12.1. As I have no Apple devices my question: Is the issue solved with iOS 12.1? Thank you in advance for your answer!

**Comment by archetyped** [comment]
The issue appears to be fixed in macOS Safari v12.0.1 and iOS v12.1.

If you are still experiencing this issue, please leave a comment with OS type of version, safari browser version, and a link to a page exhibiting the issue, and I will take a look.

Thanks.
