### ISSUE TITLE
Issue: Plugin is active but doesn't work

### ISSUE THREAD

**Issue by yamanoblu** [archetyped/simple-lightbox#694]
## Description of Problem
 
I activate plugin,  but is not working in the image. I don't know why.. 

Thank you 
Elena

## Details

* URL of Page exhibiting problem: https://stefanodechino.com/index.php/2018/09/11/payment-invoice/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): safari
* Version of SLB Installed: 2.7.0 (I have installed wp 4.9.8)
* Other plugins installed: Akismet Anti-Spam; bbPress; Categories Image; Contact form 7; cookie notice; Facebook widget; fusion builder; fusion core; Grand magazine Theme post options & gallery; mailchimp wp; mash share share button; post views counter; wp review

**Comment by archetyped** [comment]
Hi, there do not appear to be any links in the post, so there is nothing for visitors to click on to display the lightbox.  See [this page in SLB's documentation for more details on ensuring your images are properly linked](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts).

Please leave a comment if you are still experiencing an issue with SLB after adding links to your post, and I would be glad to reopen this ticket and take another look.

Thanks.
