### ISSUE TITLE
Caption not showing on certain images (calling slb_activate() multiple times)

### ISSUE THREAD

**Issue by joerggebauer** [archetyped/simple-lightbox#695]
Hi,

I am experiencing some issues when calling slb_activate() multiple times on one page: the image caption is no longer generated in the lightbox.

The function has to be called multiple times because the page is generated via a custom "page builder" using a lot of flexible ACF fields and several template/module files.

All images generated this way have the same `data-slb-internal="0"` in the surrounding `<a>` tag, so I guess this may be the problem...

Unfortunately I cannot give access to the development site, but plugin and theme conflicts have been tested.

Thanks for any help!

**Comment by archetyped** [comment]
Are you saying the issue you're experiencing only occurs when you call `slb_activate()` multiple times on the same page?  If you removed all but one of the `slb_activate()` calls on the page, the caption would display?

Without being able to evaluate the page directly, I need as much information as possible:

* Are the image's stored in the site's media library?
    * `data-slb-internal="0"` indicates that the image URLs are not stored in the site's media library.
* Are the image URLs relative or absolute?
* Does the hostname of the image URL match the hostname of the site itself?
* What is the output of the `SLB.View.assets` object in the page's source?

**Comment by joerggebauer** [comment]
> Are you saying the issue you're experiencing only occurs when you call slb_activate() multiple times on the same page? If you removed all but one of the slb_activate() calls on the page, the caption would display?

Yes.


> Are the image's stored in the site's media library?

Yes.

> Are the image URLs relative or absolute?

Absolute, since the are coming directly from the media library

> Does the hostname of the image URL match the hostname of the site itself?

Yes.

> What is the output of the SLB.View.assets object in the page's source?

I hope this is the part you are referring to (I ***-ed the actual URL):
`if ( !!window.SLB && SLB.has_child('View.assets') ) { {$.extend(SLB.View.assets, {"694970255":{"id":559,"type":"image","source":"http:\/\/***.***.***\/wp-content\/uploads\/2018\/10\/BUNUN.jpg","internal":true},"1936481979":{"id":null,"type":"image","source":"http:\/\/***.***.***\/wp-content\/uploads\/2018\/10\/20171008_095447.jpg","internal":true}});} }`

**Comment by archetyped** [comment]
Thank you for the additional details.  I've created a test page with multiple calls to `slb_activate()` and all captions were displayed properly.

Can you provide an example of how you're using `slb_activate()` along with the ACF fields?

Thanks.

**Comment by joerggebauer** [comment]
Sure, this is a snippet of one of the content modules, where the user can pick an image via the ACF image field:
`$content = '<a href="'.$module['right_image']['url'].'">';`
`$content .= '<img src="'.$module['right_image']['sizes']['full-width-img'].'" class="wp-image-'.$module['right_image']['ID'].'" alt="'.$module['right_image']['alt'].'" />';`
`$content.= '</a>';`
`if ( function_exists('slb_activate') ){`
`  $content= slb_activate($content);`
`}`
`echo $content;`

**Comment by archetyped** [comment]
This inactive ticket has been closed.  If you are still experiencing this issue with SLB, please provide a link to a page that exhibits the issue and I would be glad to reopen the ticket and take a look.

Thanks.
