### ISSUE TITLE
Issue: SLB doesn't work 

### ISSUE THREAD

**Issue by Deinos23** [archetyped/simple-lightbox#696]
## Description of Problem

Hi,
the Plugin doesn't seem to trigger on the website with the current Theme (Lookbook).
According to the owner it used to work, years ago, but now it only works in a very special case which I have to deactivate anyway to prevent for layout and content safety reasons. ( Enabled Lookbook option ).
So any Post I add Pictures sadly doesn't trigger the SLB Plugin and I'm not sure what to do/check next.

I changed the theme to Twenty-Thirteen, deactivated all Plugins, except SLB ofc, created a new Post with a picture, but no game.

Any idea or help is very much appreciated

## Details
JQ Version: 1.12.4
WP Version: 4.9.8
* URL of Page exhibiting problem:
 ( http://chromaland.com/ ) All posts
 http://chromaland.com/?p=3348
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 69.0.3497.100 Chrome
* Version of SLB Installed: 2.7
* Other plugins installed: 
Normally activated plugins:
Disable Comments
Contact Form by Supsystic
Cleaner Gallery
Categories Images
Archived Post Status
amr shortcode any widget
Akismet
Advanced WP Columns
DWL Preloader
Floating Social Bar
Floating Social Media Icon
LinkWithin
Revolution Slider
WP Hide Post
WP Content Copy Protection

**Comment by Deinos23** [comment]
Ok I found one work-around ( unless I misunderstood the Documentation of "add a picture and it should work"), if I edit the picture and make it a link to itself it triggers your Plugin.

**Comment by archetyped** [comment]
Hi, I'm not sure what documentation page you're referring to, but links are indeed required for visitors to have something to click on to launch the lightbox.

See [SLB's documentation on adding image links to your posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.  If you are still experiencing an issue once you've ensured that image links are added to the post, please provide a link to a specific page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take another look.
