### ISSUE TITLE
Default title displayed in lightbox

### ISSUE THREAD

**Issue by freyke** [archetyped/simple-lightbox#697]
In my simple lightbox it should only show in the left under corner "item x from x"
But it also shows the name of my file which doenst look profesional.
It is weird, because it is not with each picture...

I would like to send you a printscreen but it is not foreseen i think.

my site is still under construction and i cant put it on active for now...

Hope I can send you the printscreen

* URL of Page exhibiting problem:  
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, WordPress generates a default title for uploaded images based on the image's file name.  You can choose not to display this default title in the lightbox by unchecking the "Enable default title" in SLB's admin options.
