### ISSUE TITLE
Lightbox is not working in my site

### ISSUE THREAD

**Issue by BemooreWeb** [archetyped/simple-lightbox#699]
I have installed SLB on my development site and it is not working.
I have already deactivated all other plugins, that did not make any difference. 
I have already looked for javascript conflicts, I have not found any. 
I would really appreciate your help.

## Details

* URL of Page exhibiting problem:  http://corporate.eielectronics.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, chrome, edge, IE
* Version of SLB Installed: 2.7.0
* Other plugins installed: several

**Comment by archetyped** [comment]
Hi, I could not find any image links at the link provided.  Please provide the URL to a specific page on your site that exhibits the issue you are experiencing and I would be glad to take another look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
