### ISSUE TITLE
Plugin does'nt work

### ISSUE THREAD

**Issue by mobydirk** [archetyped/simple-lightbox#701]
## Description of Problem

Hi all, plugin does'nt seem to work. Could you please have look?

## Details

* URL of Page exhibiting problem: https://www.jewi-brocante-vintage-curiosa.nl/dinky-toy-651-en-660/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB appears to be functioning properly at the link you provided.  Please edit your original post to provide all the necessary details regarding your issue and I would be glad to take another look.

Thanks.

**Comment by collizo4sky** [comment]
@archetyped what's the best way to contact you?
