### ISSUE TITLE
Will you be updating for WP version 5 with Gutenberg?

### ISSUE THREAD

**Issue by stevonsky** [archetyped/simple-lightbox#704]
I'm working on upgrading all my clients to the latest WP version 5 with Gutenberg.  I'm going through and finding all the plugins that are not yet compatible before updating. Yours is only good through WP 4.9.9

It has been a nightmare trying to find another plugin that is as simple to add and have it just work with a basic lightbox effect.  I use WP Bakery (Visual Composer) and your plugin does not interfere or conflict with it.  The issue has always been to find a plugin that will apply a lightbox effect to an image inserted into a text box (as in WP Bakery's text box).  Sometimes it's necessary to have text wrap around an image.  
But WP Bakery does not let you apply any lightbox effect to the image.  Well, your plugin does and that is awesome.

So will you be updating for WP version 5 with Gutenberg?

FYI, although I don't normally like running plugins that are not compatible with the current WordPress version out there, I tested your plugin and it still works on WP version 5.0.3

Thanks.

**Comment by archetyped** [comment]
Hi, SLB is compatible with WordPress 5+.  Note that plugins are not necessarily incompatible with a WordPress version just because their "Tested up to" text doesn't list that version.  If you've installed it and it works without any issues, then it's compatible.
