### ISSUE TITLE
Random Captions/Descriptions Work

### ISSUE THREAD

**Issue by richpriordesign** [archetyped/simple-lightbox#705]
## Description of Problem

Hi, I tried using Simple Lightbox but I came across a odd issue. I add a gallery of 6 or more images and it appears that only the first four captions and descriptions show. As it went on they just stopped showing.

When adding more to the gallery to test, the new images also would not display captions and descriptions. One oddly would show the Alt Text even though it had both captions and descriptions.

I created a new post and tested another gallery. The first image only shows the Alt text, and the following 3 showed the caption and description. The remainder of the images only showed the alt text.

I add the images by adding a gallery and creating the gallery like normal through WordPress Gutenberg Editor. I am on WordPress 5.0.3

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your original post to provide the necessary details to evaluate the issue you are experiencing and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.
