### ISSUE TITLE
Issue: Animations and Images Missing in Simple Lightbox

### ISSUE THREAD

**Issue by prodman1** [archetyped/simple-lightbox#706]
## Description of Problem

This site uses the Mineral theme and was updated to 5.03. Mineral has just been updated (it had to be done manually) and the Lightbox settings are intact. All of the images using Simple Lightbox have lost their links. I can restore them but the animations they had are also missing. How can I fix this?

## Details

* URL of Page exhibiting problem: https://barkskin.com/collections/original-barkskin/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by prodman1** [comment]
Here is a sample url https://barkskin.com/collections/original-barkskin/ This site uses the Mineral theme and was updated to 5.03. Mineral has just been updated (it had to be done manually) and the Lightbox settings are intact. All of the images using Simple Lightbox have lost their links. I can restore them but the animations they had are also missing. How can I fix this?

**Comment by archetyped** [comment]
Hi, it appears that the theme is loading its own lightbox.  Disabling the theme's lightbox should allow SLB to function normally.

Please post an update if you are still experiencing an issue after disabling the theme's lightbox, and I would be glad to reopen this ticket and take another look.

Thanks.
