### ISSUE TITLE
Request: CSS Customization

### ISSUE THREAD

**Issue by willemwitteveen** [archetyped/simple-lightbox#708]
I like Simple Lightbox. Is there a css code I could use to change font style and color of the title? That is all I would like to change.
Thanks.
Willem Witteveen
the Netherlands
info@willemwitteveen.com

**Comment by archetyped** [comment]
Hi, please see [SLB's wiki for information on customizing the lightbox's appearance](https://github.com/archetyped/simple-lightbox/wiki/Themes).  The tutorial on **"Customizing Theme Styles"** would likely be the best place to start for what you're looking to do.
