### ISSUE TITLE
Issue: with an empty caption field as well caption as description text of the image are shown

### ISSUE THREAD

**Issue by gjwmvg** [archetyped/simple-lightbox#710]
## Description of Problem
When an image is shown with SLB ( V. 2.7.1 ) i do have 2 problems : 
When adding an image you are able to fill in 3 fields : Caption, Alternative Text and Description
1. when Caption AND Alternative Text are filled ( Description is empty ) SLB only shows Alternative Text ( big like the format of the Caption ).
2. when Alternative Text AND Description are filled ( Caption is empty ) SLB shows Caption AND Alternative Text BIG and Description small. But the Caption, which is empty and should NOT be displayed, shows the same text as Description.

## Details

* URL of Page exhibiting problem: 
1. https://bertvangiersbergen.com/2019/02/overdadig-veel-neerslag/
2. https://bertvangiersbergen.com/foto-albums/2002-zuid-afrika-leshoto-swaziland/10/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Firefox 65.0.1 (64-bit)
* Version of SLB Installed: 
Version 2.7.1
* Other plugins installed: 
Catch IDs
Classic Editor
Contact Form 7
Custom Nextpage
Download Attachments
Enhanced Media Library
External Links
FooGallery
Really Simple SSL
Shortcodes by Angie Makes
Tooltipy
Visualizer
WP Tab Widget
![captionempty-1a](https://user-images.githubusercontent.com/47701255/52905403-fc195c80-324a-11e9-9c83-3f1ca114447a.png)
![captionempty-1b](https://user-images.githubusercontent.com/47701255/52905404-fc195c80-324a-11e9-9c0f-5657472ae123.png)
![descriptionempty-2a](https://user-images.githubusercontent.com/47701255/52905405-fc195c80-324a-11e9-9bb3-9fe2933de03c.png)
![descriptionempty-2b](https://user-images.githubusercontent.com/47701255/52905406-fc195c80-324a-11e9-9ee8-ad92d4bbc86c.png)

**Comment by archetyped** [comment]
Hi, the lightbox is displaying the caption included with the image on the page in the gallery.  SLB prioritizes displaying this caption over an attachment's default metadata as it can be customized by users on a per-use basis.

See SLB's documentation for [more details on title precedence](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence).

**Comment by gjwmvg** [comment]
Dear,

Yes, as describited in the SLB documentation. But in the real world it does not work like that. Since the last update of SLB i the SLB plug-in shows the wrong information !!!
Look at the 4 pictures i added.

The first picture i added is a screencapture from the WP image. NO caption filled in, but when you look in the SLB pop-up ( 2nd picture ) you see the pop-up shows the caption + Altenative text + Description

The third picture the WP image shows a filled caption AND Alternative text but the SLB pop-up ( 4th picture ) only shows the Alternative text.

**Comment by archetyped** [comment]
Reference: @gjwmvg comment from #711 

To show the differences between V2.7.0 & V2.7.1 i have added below images : 
Example 1 : 
- CaptionEmpty-1-WP-image-info.png : contains WP image info ( Caption and/or Alternative text and/or Description field(s) )
- CaptionEmpty-1-V270.png : lightbox with SLB V2.7.0
- CaptionEmpty-1-V271.png : lightbox with SLB V2.7.1

Example 2 : 
- DescriptionEmpty-2-WP-image-info.png : contains WP image info ( Caption and/or Alternative text and/or Description field(s) )
- DescriptionEmpty-2-V270.png : lightbox with SLB V2.7.0
- DescriptionEmpty-2-V271.png : lightbox with SLB V2.7.1

Find the differences ( and that should not be difficult imo )
![captionempty-1-v270](https://user-images.githubusercontent.com/47701255/52975499-d6b95980-33d6-11e9-838c-62eefee4d257.png)
![captionempty-1-v271](https://user-images.githubusercontent.com/47701255/52975500-d6b95980-33d6-11e9-98e5-3337999c296b.png)
![captionempty-1-wp-image-info](https://user-images.githubusercontent.com/47701255/52975501-d751f000-33d6-11e9-9f5b-ce77509295d1.png)
![descriptionempty-2-v270](https://user-images.githubusercontent.com/47701255/52975503-d751f000-33d6-11e9-960d-98038ca30d26.png)
![descriptionempty-2-v271](https://user-images.githubusercontent.com/47701255/52975504-d751f000-33d6-11e9-9e6e-d4683a43d5dd.png)
![descriptionempty-2-wp-image-info](https://user-images.githubusercontent.com/47701255/52975505-d751f000-33d6-11e9-8139-c18c8f14ea13.png)

**Comment by archetyped** [comment]
On both links you provided, v2.7.1 is displaying the caption as described in [SLB's documentation title precedence](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence).

Specifically, the lightbox is displaying #&#x2060;2 in the list of precedence: **the caption accompanying the thumbnail** in the gallery on the page.

As such, the presence or absence of data in specific media library fields is irrelevant, as the custom caption text from the page itself is what is being displayed.  This behavior was made more consistent in SLB 2.7.1, which is why you may be seeing different results compared to v2.7.0.

Please let me know if anything remains unclear and I will do my best to help make things clearer.

Thanks.

**Comment by gjwmvg** [comment]
Dear archtyped,

Lets adopt the fact your documentation is right. What i try to tell is that the textfields in SLB are not displayed well. For our convience i changed the textfields within de WP image settings into the name of the textfield ( see image : 1-WP-imagefield.png ).
When the image is shown in SLB ( see image : 2-SLB-popup.png ) i see 1x 'Alternative Text' and 2x 'Description'. Where is the text 'Caption' ?

I'am running WP 5.0.3 en SLB V2.7.1 ( see image : 3-WP-info.png & 4-Plugin-info.png )

![1-wp-imagefield](https://user-images.githubusercontent.com/47701255/53017859-02355600-3462-11e9-9d9a-d4b7f99885fc.png)
![2-slb-popup](https://user-images.githubusercontent.com/47701255/53017860-02cdec80-3462-11e9-9bf1-bbe56a48ccdc.png)
![3-wp-info](https://user-images.githubusercontent.com/47701255/53017861-02cdec80-3462-11e9-95b6-c79c5d256049.png)
![4-plugin-info](https://user-images.githubusercontent.com/47701255/53017981-49bbe200-3462-11e9-87c6-01ac4a65c9ec.png)

Thanks in advanced

**Comment by archetyped** [comment]
Hi, you didn't provide an example of what the post looks like, so I can only guess that the lightbox title (i.e. the large text) matches the text accompanying the thumbnail in the image/gallery on the page (same as your earlier links, #&#x2060;2 in title precedence).

If this is not the case, please provide a link to a page that exhibits the issue you are experiencing, and I would be glad to take a look.

It also appears that you are using FooGallery, which may use different media library fields for its thumbnail caption text than WordPress' own gallery, so you may want to look at that plugin's settings to customize its output.

Also, if you want to always display the caption from the media library as the lightbox's title, you can create a custom theme layout and replace `{{item.title}}` with `{{item.caption}}`.  See [SLB's documentation on customizing themes/layouts](https://github.com/archetyped/simple-lightbox/wiki/Themes) for more details.

**Comment by gjwmvg** [comment]
Dear archtyped,

I have created in my _local testsite_ a new post and add images. One set of seven, add the images directly in WP, and one set of seven using Foogallery. At every image i made a different combination of filled in text. I have opened all the images, one by one with hand, in both versions of SLB ( V2.7.0 and V2.7.1 ) and put the result of the displayed text in a Excel-sheet ( attached ). I used the last version of Foogallery ( V1.6.15 ) because i don't have a previous version to test. But with the use of Foogallery there are differences between both SLB versions. V2.7.0 shows a **bold** 'Caption text' and NO 'Alternative text', SLB V2.7.1 shows NO 'Caption' but a **bold** 'Alternative Text'.  How should i interpret this ? Is this the result of implementing Gutenberg ?

I know it is really difficult to pinpoint what causes the differences. It might even be a issue with cache, Gutenberg or the setup of the (local)server.
I can create a new post with the images like i did at my local testsite.

BTW : The last changelog of Foogallery was : 
= 1.6.15 =
* Fix : fixed logo path in admin
* Update : changed the paging default output to HTML

Sorry to disturb you.
Bert

[Lightbox-Foogallery-Compared.xlsx](https://github.com/archetyped/simple-lightbox/files/2896840/Lightbox-Foogallery-Compared.xlsx)

**Comment by archetyped** [comment]
> I can create a new post with the images like i did at my local testsite.

Yes, as previously noted, please provide a link to a page that exhibits the issue you are experiencing, and I would be glad to take a look.

Thanks.

**Comment by purplearth** [comment]
re....

> Also, if you want to always display the caption from the media library as the lightbox's title, you can create a custom theme layout and replace {{item.title}} with {{item.caption}}. See SLB's documentation on customizing themes/layouts for more details.

In your documentation, there is no reference to item.caption as a template tag... there's only content (the image), title and description. I really wish there *was* an item.caption tag, since that would simplify my efforts to give my client the capabilities she's looking for (she wants to display the caption and the content of a couple of custom fields for location, photo credit and copyright).

I just tried to replace item.description with item.caption and got nothing.

So a bigger question (maybe outside the context of this issue): is there a way to add template tags to add content to the lightbox?
