### ISSUE TITLE
Dear archtyped,

### ISSUE THREAD

**Issue by gjwmvg** [archetyped/simple-lightbox#712]
Dear archtyped,

Lets adopt the fact your documentation is right. What i try to tell is that the textfields in SLB are not displayed well. For our convience i changed the textfields within de WP image settings into the name of the textfield ( see image : 1-WP-imagefield.png ).
When the image is shown in SLB ( see image : 2-SLB-popup.png ) i see 1x 'Alternative Text' and 2x 'Description'. Where is the text 'Caption' ?

I'am running WP 5.0.3 en SLB V2.7.1 ( see image : 3-WP-info.png & 4-Plugin-info.png )

![1-wp-imagefield](https://user-images.githubusercontent.com/47701255/53017859-02355600-3462-11e9-9d9a-d4b7f99885fc.png)
![2-slb-popup](https://user-images.githubusercontent.com/47701255/53017860-02cdec80-3462-11e9-9bf1-bbe56a48ccdc.png)
![3-wp-info](https://user-images.githubusercontent.com/47701255/53017861-02cdec80-3462-11e9-95b6-c79c5d256049.png)
![4-plugin-info](https://user-images.githubusercontent.com/47701255/53017981-49bbe200-3462-11e9-87c6-01ac4a65c9ec.png)

Thanks in advanced

_Originally posted by @gjwmvg in https://github.com/archetyped/simple-lightbox/issues/710#issuecomment-465125234_

**Comment by gjwmvg** [comment]
Sorry i created a new issue but i don't have rights to (re)open the old issue ( #710). How should i respond ! ! !

**Comment by gjwmvg** [comment]
Dear archtyped,

i did some tests at my local website ( which i use for testing purpose ) and i had some issues with the displayed image info in SLB. I'am not able to find what causes the problems but i have tried many things ( chancing image text, clearing cache, restarting browser ). I will look for another Lightbox solution. It is a pity because i was happy to use SLB.

Thank you for the work you did.
Bert

**Comment by archetyped** [comment]
Hi, comments can be added to closed tickets.

Duplicate of #710
