### ISSUE TITLE
Issue: displaying all sizes

### ISSUE THREAD

**Issue by mossifer** [archetyped/simple-lightbox#715]
## Description of Problem
Issue: It displays "1 of 3" images when there's only one - so I believe it's displaying all 3 sizes? How can I limit that? 

## Details
* URL of Page exhibiting problem: https://yosemitewesternartists.com/member-profile/?pu=moss3web6works9
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  safari
* Version of SLB Installed: 2.7.1

**Comment by archetyped** [comment]
Hi, the number in the lightbox is based on the number of valid links (images, etc. that can be displayed in the lightbox) on the page. The page at the link you provided contains links to the visible images on the page, but also multiple empty links to images as well.  This is why the total in the lightbox appears higher than the number of visible images on the page.

Empty links can sometimes occur when a link is not fully deleted when editing a post.  This can be corrected by either the post's HTML to remove the empty links.

Some plugins may also add empty links on accident, so if you are using a plugin to generate the image gallery on the page, you may want to contact the plugin's developer to inquire about that issue.

If you are still experiencing this issue after clearing the empty links from the post, please provide an updated link to a page that exhibits the issue and I would be glad to reopen this ticket and take another look.

Thanks.
