### ISSUE TITLE
Issue: No looping/grouping on new galleries

### ISSUE THREAD

**Issue by MrPaulin** [archetyped/simple-lightbox#717]
## Description of Problem

Hello,
I may be doing something wrong but I think that the grouping doesn't work on the new "block" galleries. I tried putting the same pictures in a classic gallery and in a new gallery block, and the old ones loop nicely like I want them to, while with the new ones the lightbox just goes on to the next picture when reaching the end of the gallery. 
I have the latest versions of Wordpress and SLB installed and in the SLB settings I have everything ticked in the "grouping" category.

Thank you for your attention and help, and sorry if this is not a real issue but just me missing something.
Pauline

## Details

* URL of Page exhibiting problem: My website is not hosted yet, I work in local
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Only tested in Chrome and Firefox, problem present on both browsers
* Version of SLB Installed: 2.7.1
* Other plugins installed: Akismet, Collapse-O-Matic, Contact Form 7 (no other lightbox)

**Comment by slingshotdesign** [comment]
A visitor to one of my sites has reported the same issue using Safari on a MacBook. However it works fine for me in that browser?

**Comment by archetyped** [comment]
Thanks for  the report.  I am looking into this.

**Comment by MrPaulin** [comment]
Hi, I'm sorry if this is rude but it's been a while since I reported this issue and I was just wondering if there was any news? My professional website kinda heavily depends on this functionality so I'm a bit stuck at the moment. That said I totally understand if you're busy on other stuff! Just making sure this little problem hasn't been forgotten. Thanks!

**Comment by issan74** [comment]
I have the same issue with grouping. Using WP5.4 and SLB 2.8.1. Is the status still evaluating or is the issue dropped?

**Comment by archetyped** [comment]
Update: Support for grouping gallery blocks is planned for an upcoming update.

Please refer to [Ticket #802](802) to track this feature's progress.  You can also show your interest in this feature to prioritize its development by clicking on the thumbs up emoji (👍) in the lower corner of the first post.

Thank you for the reports.
