### ISSUE TITLE
Zoom into a lightbox image?

### ISSUE THREAD

**Issue by newvision2112** [archetyped/simple-lightbox#718]
The lightbox works great, but one question: On desktop, how can we turn on the ability to zoom into an image showing in the lightbox overlay?  Our client posts infographics and it would helpful if there was a way to zoom the lightbox image to see the details.

Thanks,
Dean

**Comment by archetyped** [comment]
Closing this duplicate ticket to keep all discussion in one place.

Please refer to the [original ticket](https://wordpress.org/support/topic/how-to-add-ability-to-zoom-into-a-lightbox-image/) for all future discussion on this topic.

Thanks.

**Comment by newvision2112** [comment]
Thank you. I'll look at your answer and reply if needed.

Best,
Dean
