### ISSUE TITLE
Display images in slideshow in a different order

### ISSUE THREAD

**Issue by TheBoxTheory** [archetyped/simple-lightbox#720]
## Description of Problem

I have created a photo gallery in elementor without using the elementor gallery feature which was too restrictive. The problem is that the photos are arranged in columns and the Lightbox slideshow displays images in column order. I would like it to display accross in row order. Is there some way to make this happen?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB displays slideshows in the order they are arranged in the page's source code, though a plugin's or theme's CSS may modify how this is displayed.

Please update your original post to include the information necessary to evaluate your issue and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
