### ISSUE TITLE
Issue: blank lightbox images & 'next' button not working

### ISSUE THREAD

**Issue by sublimebydesign** [archetyped/simple-lightbox#722]
## Description of Problem

If you select the first image of each gallery section, and attempt to click the 'next' button to view the following images, the lightbox fails to work at some stage and you are presented with a blank box, a screen freeze or the lightbox dropping out and returning to the page. It varies, but sooner or later an error occurs.

## Testing

The issue remains if the theme is changed to Twenty Nineteen and all plugins apart from SLB are deactivated.

## Details
* URL of Page exhibiting problem:  https://www.opticolour.co.uk/glass-manufacturers-gallery/kitchen-glass-splashbacks/mirrored/ 

It also applies to the other galleries in the section.  My localhost environment has the same issues.

* Browser(s) exhibiting problem: Firefox, Chrome, IE, ipad Safari and from Client reports, various mobiles.
* Version of SLB Installed: 2.7.1
* Other plugins installed:  Woocomerce system status info attached below for system and plugin details. 

Woocommerce system status information:
### WordPress Environment ###

Home URL: https://www.opticolour.co.uk
Site URL: https://www.opticolour.co.uk
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0+deb7u1 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.7
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 50.54MB
Database Data Size: 39.39MB
Database Index Size: 11.15MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_ahm_download_stats: Data: 0.08MB + Index: 0.00MB
wp_ahm_emails: Data: 0.02MB + Index: 0.00MB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB
wp_blc_instances: Data: 0.11MB + Index: 0.05MB
wp_blc_links: Data: 0.44MB + Index: 0.16MB
wp_blc_synch: Data: 0.02MB + Index: 0.02MB
wp_bws_fancytree: Data: 0.02MB + Index: 0.00MB
wp_clean_up_optimizer: Data: 0.02MB + Index: 0.00MB
wp_clean_up_optimizer_ip_locations: Data: 0.00MB + Index: 0.00MB
wp_clean_up_optimizer_meta: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_download_log: Data: 0.02MB + Index: 0.02MB
wp_dynamic_widgets: Data: 0.02MB + Index: 0.02MB
wp_exporttopdfrecord: Data: 0.02MB + Index: 0.00MB
wp_ExporttoPDFRecord: Data: 0.02MB + Index: 0.00MB
wp_fb3d_pages: Data: 0.02MB + Index: 0.05MB
wp_fmet_product_dtabs: Data: 0.02MB + Index: 0.00MB
wp_fmet_product_gtabs: Data: 0.02MB + Index: 0.00MB
wp_fmet_product_tabs: Data: 0.02MB + Index: 0.00MB
wp_fmet_temp_dtabs: Data: 0.02MB + Index: 0.00MB
wp_fmet_temp_gtabs: Data: 0.02MB + Index: 0.00MB
wp_fmet_temp_tabs: Data: 0.02MB + Index: 0.00MB
wp_fmet_use_gtabs: Data: 0.02MB + Index: 0.00MB
wp_gdpr_consent: Data: 0.02MB + Index: 0.00MB
wp_image_compression_details: Data: 0.02MB + Index: 0.00MB
wp_image_compression_settings: Data: 0.02MB + Index: 0.00MB
wp_iowd_images: Data: 0.02MB + Index: 0.00MB
wp_layerslider: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mclean_refs: Data: 0.02MB + Index: 0.00MB
wp_mclean_scan: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 16.38MB + Index: 0.16MB
wp_pdfprnt_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 10.52MB + Index: 6.00MB
wp_posts: Data: 4.50MB + Index: 0.58MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB
wp_revslider_slides: Data: 0.13MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.02MB
wp_shortpixel_meta: Data: 1.52MB + Index: 0.34MB
wp_structuring_markup: Data: 0.02MB + Index: 0.02MB
wp_termmeta: Data: 0.06MB + Index: 0.06MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.20MB + Index: 0.17MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpcf7pdf_files: Data: 0.02MB + Index: 0.00MB
wp_wpio_images: Data: 0.23MB + Index: 0.22MB
wp_wpio_listimages: Data: 3.52MB + Index: 2.52MB
wp_wpio_queue: Data: 0.02MB + Index: 0.00MB
wp_wpmcleaner: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.20MB + Index: 0.05MB
wp_yoast_seo_meta: Data: 0.14MB + Index: 0.00MB

### Post Type Counts ###

3d-flip-book: 1
attachment: 1421
condition_group: 17
custom_css: 1
jetpack-testimonial: 9
nav_menu_item: 59
page: 64
post: 20
product: 596
revision: 489
sidebar: 15
slide: 30
testimonial: 15
testimonial_rotator: 1
text-blocks: 2
turbo-sidebar-cpt: 1
vc_grid_item: 1
woo_product_tab: 19
wpb_wtm_tab: 28
wpcf7_contact_form: 2
wpdmpro: 36

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Accelerated Mobile Pages: by Ahmed Kaludi
Mohammed Kaludi – 0.9.97.46

AMPforWP Plugin Manager: by Ahmed Kaludi
Mohammed Kaludi – 1.1

AMP Theme Framework: by AMPforWP Team – 1.0
AMP WooCommerce: by Mohammed Kaludi – 0.4 – Not tested with the active version of WooCommerce
Broken Link Checker: by ManageWP – 1.11.8
Classic Editor: by WordPress Contributors – 1.4
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Content Aware Sidebars: by Joachim Jensen - DEV Institute – 3.8.1
Download Manager: by W3 Eden – 2.9.92
Duplicate Post: by Enrico Battocchi – 3.2.2
3D FlipBook - Light Edition: by iberezansky – 1.9.12
Make Plus: by The Theme Foundry – 1.9.17
Media File Renamer Pro: by Jordy Meow – 4.5.4
Media Library Alt Fields: by Jarret Cade – 1.1
Media Library Assistant: by David Lingren – 2.79
oik fields: by bobbingwide – 1.50.1
oik: by bobbingwide – 3.3.3
Post Thumbnail Editor: by sewpafly – 2.4.8
Resize Image After Upload: by ShortPixel – 1.8.6
Text Blocks: by Hal Gatewood – 1.5.3
Slider Revolution: by ThemePunch – 5.4.8.3
Sassy Social Share: by Team Heateor – 3.2.19
ShortPixel Image Optimizer: by ShortPixel – 4.12.8
Simple 301 Redirects - Addon - Bulk CSV Uploader: by Webcraftic 
Ash Durham  – 1.2.4

Simple 301 Redirects: by Scott Nellé – 1.07
Simple Lightbox: by Archetyped – 2.7.1
Testimonial Rotator: by Hal Gatewood – 2.5.2
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.0.2 – 3.2.3 is available – Not tested with the active version of WooCommerce
WooCommerce Colors: by WooThemes – 1.0.7 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14 – 1.10.21 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.7
Twitter Bootstrap for WordPress: by One Dollar Plugin – 3.4.1-0
Yoast SEO: by Team Yoast – 10.1.3
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.13
WP Migrate DB Pro: by Delicious Brains – 1.9.5
Markup (JSON-LD) structured in schema.org: by Kazuya Takami – 4.6.5
WPB WooCommerce Custom Tab Manager PRO: by wpbean – 1.05 – Not tested with the active version of WooCommerce
WPDM - TinyMce Button: by Shaon – 2.7.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Basket: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page does not contain the shortcode.
Terms and conditions: #549 - /legal/

### Theme ###

Name: Make (child theme)
Version: 1.1.0
Author URL: https://thethemefoundry.com
Child Theme: ✔
Parent Theme Name: Make
Parent Theme Version: 1.9.15 – 1.9.24 is available
Parent Theme Author URL: https://thethemefoundry.com
WooCommerce Support: ✔

### Templates ###

Overrides: make-child-theme/woocommerce/single-product/meta.php
`

**Comment by archetyped** [comment]
Hi, it looks like another plugin is adding data to WordPress' media library that is conflicting with SLB's functionality. 

Each of the images that do not load in the lightbox at the link you provided have non-standard metadata.  This may be caused by the ShortPixel plugin, which does add data to the media library, but this will be resolved on SLB's end in a future update.

Thanks.

**Comment by sublimebydesign** [comment]
Re: [archetyped/simple-lightbox] Issue: blank lightbox images & 'next' button not working (#722)


Hi Archetyped,

I don't doubt there may be an incompatibility with Shortpixel as you say, but there may be something else going on as well? I've disabled Shortpixel on my localhost and live, and both are still experiencing the same issues. I've cleared the browsers caches. Regretfully, I may have to try another lightbox plugin until this is resolved, unless you have any other ideas or workarounds?

Thank you for your time though.

Laura

Saturday, April 13, 2019, 4:25:29 AM, you wrote:





Hi, it looks like another plugin is adding data to WordPress' media library that is conflicting with SLB's functionality.
Each of the images that do not load in the lightbox at the link you provided have non-standard metadata. This may be caused by the ShortPixel plugin, which does add data to the media library, but this will be resolved on SLB's end in a future update.
Thanks.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





Regards,

Laura Somerville
Sublime by Design
9 Belvedere, Lansdown, Bath, Somerset BA1 5ED United Kingdom
Telephone: 01225 329125 
contact@sublimebydesign.co.uk
www.sublimebydesign.co.uk

Sublime by Design Limited. Place of registration: Companies House, Cardiff. Registration number: 5746451.
Registered office address: Anderson Accounting Ltd., Level Two, The Old Malthouse, Clarence St., Bath BA1 5NS

**Comment by archetyped** [comment]
Hi, the modifications by the other plugin are made to your site's Media Library, which means the modifications have been written to your site's database.

Deactivating a plugin does not remove the modifications it has made to the site's database, which is why SLB would need to specifically filter out non-standard modifications when loading data from the Media Library (image captions, descriptions, etc.).

**Comment by sublimebydesign** [comment]
Re: [archetyped/simple-lightbox] Issue: blank lightbox images & 'next' button not working (#722)


Hi Archetyped,

Thank you for the clarification.

Laura

Tuesday, April 30, 2019, 4:54:59 AM, you wrote:





Hi, the modifications by the other plugin are made to your site's Media Library, which means the modifications have been written to your site's database.
Deactivating a plugin does not remove the modifications it has made to the site's database, which is why SLB would need to specifically filter out non-standard modifications when loading data from the Media Library (image captions, descriptions, etc.).
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





Regards,

Laura Somerville
Sublime by Design
9 Belvedere, Lansdown, Bath, Somerset BA1 5ED United Kingdom
Telephone: 01225 329125 
contact@sublimebydesign.co.uk
www.sublimebydesign.co.uk

Sublime by Design Limited. Place of registration: Companies House, Cardiff. Registration number: 5746451.
Registered office address: Anderson Accounting Ltd., Level Two, The Old Malthouse, Clarence St., Bath BA1 5NS
