### ISSUE TITLE
Issue: SLB not working with WP5+

### ISSUE THREAD

**Issue by Hinsonia** [archetyped/simple-lightbox#727]
## Description of Problem
Since new version of WP (with block editor) cannot create new pages with SLB working correctly.

## Details
1. Pages created before upgrade continue to work correctly. 
2. Pages created with Classic Editor show thumbnails correctly but these are unclickable. 
3. Pages created with new Block editor show the image using the full size of the column.
Three examples showing the above below.

* URL of Page exhibiting problem: 
1: https://purenostalgia.org.uk/vehicles/1401-2/30-3-19-barking/
2: https://purenostalgia.org.uk/vehicles/1401-2/28-4-19-bicester/
3: https://purenostalgia.org.uk/vehicles/test-page/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Firefox, Chrome, Internet Explorer, Slimject, Ecosia and probably all others

* Version of SLB Installed: 2.7.1
* Other plugins installed: Classic Editor, Contact Form 7

Current WP version: 5.2
Theme: Twenty Ten

**Comment by McStecca** [comment]
I see that it is working

**Comment by Hinsonia** [comment]
I think you may be mistaken. I can see no change.

Perhaps I didn't explain things well enough.
Example 1 https://purenostalgia.org.uk/vehicles/1401-2/30-3-19-barking/
Works correctly, this was created before the WP upgrade

Example 2 https://purenostalgia.org.uk/vehicles/1401-2/28-4-19-bicester/
This looks correct, but the thumbnails are unclickable. This page was created using the Classic Editor pluginafter the WP ugrade,

Example 3 https://purenostalgia.org.uk/vehicles/test-page/
This shows no signs of SLB at all. This page was created with WP's standard "block" editor.

Hoping you can guide me.

Best regards,

John

**Comment by archetyped** [comment]
Hi, the images in examples 2 and 3 appear to have been inserted without links.  Without links, there is nothing for visitors to click on to launch a lightbox.

* **Classic Editor:** Ensure that the appropriate image link setting is selected when inserting an image.  See [WordPress' official documentation on inserting images with links](https://codex.wordpress.org/Inserting_Images_into_Posts_and_Pages#Image_Link) for full instructions.
* **Block Editor:** Ensure that the image block links to the media file or attachment page.  See [WordPress' official Image Block documentation](https://en.support.wordpress.com/wordpress-editor/blocks/image-block/#link-settings) for full instructions. 

Once links have bee added to the images, SLB should display the links in the lightbox when they are clicked.  If you are still experiencing an issue after adding links, please provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to take another look.

Thanks.
