### ISSUE TITLE
Is it possible to add custom div tags to images when shown?

### ISSUE THREAD

**Issue by GlitzyWorm** [archetyped/simple-lightbox#728]
I need to add a div tag to the image that get's shown, is there a way/feature to do this?

**Comment by archetyped** [comment]
Hi, the lightbox's layout can be fully customized via a custom theme.  See [SLB's documentation on custom themes](https://github.com/archetyped/simple-lightbox/wiki/Themes) for more details on customizing the lightbox's layout with a custom theme.
