### ISSUE TITLE
Lightbox Won't Work, No Errors in Console | Maybe a WPEngine Problem?

### ISSUE THREAD

**Issue by zakkates** [archetyped/simple-lightbox#729]
The plugin is working properly to add attributes to the links to images, however, when I click on an image it simply opens the image in the window instead of opening in the lightbox. 

![Screen Shot 2019-05-22 at 12 24 35 PM](https://user-images.githubusercontent.com/3744142/58195050-ae1e5580-7c8c-11e9-8c94-f1e872f253ae.jpg)

- There are no errors being fired in the console.
- I deactivated all plugins and activated Wordpress's Twenty Nineteen Theme
- I'm running the latest version of the plugin as well as Wordpress

The only thing I can possibly think of is that I'm developing this site on WPEngine.com's hosting platform and the site currently blocks all traffic unless you put in a code to view the page. Could this be causing some issue?

You can see the page here: https://simpleedgewp2.wpengine.com/?page_id=10

The login info is:
- demo
- testing

Here are all of my settings for the plugin:
![screencapture-simpleedgewp2-wpengine-wp-admin-themes-php-2019-05-22-12_25_10](https://user-images.githubusercontent.com/3744142/58195078-bffff880-7c8c-11e9-96c6-a1d3e2686daa.jpg)

**Comment by archetyped** [comment]
Hi, yes HTTP authentication blocks server requests, preventing SLB from loading fully.  See [SLB's documentation on Server Requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#server-environment) for more details.

**Comment by zakkates** [comment]
Thank you, btw! :)
