### ISSUE TITLE
Issue: Not working in WordPress 5.2.1

### ISSUE THREAD

**Issue by aaasoft** [archetyped/simple-lightbox#730]
## Description of Problem
Simple Lightbox not  working in WordPress 5.2.1.

## Details

* URL of Page exhibiting problem: http://xn--fiq63fz0mtuag2fb1bzsv79ebfbg98e.com/pictures/%E8%AE%BE%E8%AE%A1%E8%A7%84%E5%88%92
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome 74.0.3729.169
* Version of SLB Installed: 2.7.1
* Other plugins installed: 

** Absolutely Glamorous Custom Admin version:6.5.2
** Contact Form 7 version:5.1.3
** Meta Tag Manager version:2.1
** Simple Lightbox version:2.7.1
** Smartideo version:2.6.0
** WordPress Importer version:0.6.4
** WP Mail SMTP version:1.4.2
** WP-Optimize version:2.3.3

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.
