### ISSUE TITLE
Changes <area .... > tag to <a .....> 

### ISSUE THREAD

**Issue by jimheck** [archetyped/simple-lightbox#731]
I am using the <area ... > tag to make hotspots in an image. But when the page is served the <area ..> tag is changed to an <a...> tag

## Details
https://www.appletons.org.uk/colours/ (See first entry "purple 101-106" The left two hot spots are changing

Affects IE and Firefox

SLB Ver 2.7.1 installed

Other Plug in:
Akismet Anti-Spam
Select All-in-One WP Migration
Select Better Search Replace
Google Analytics Dashboard for WP (GADWP)
Select Hello Dolly
ManageWP - Worker
Portfolio Slideshow
Redirection
SeedProd Coming Soon Pro
Simple Lightbox
WooDojo
WooSidebars
Wordfence Security
WP Fastest Cache
Select WP Google Maps
WP Google Maps
WP Remote
Yoast SEO 
* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
You found a bug!

Thanks :)

**Comment by jimheck** [comment]
Hi,
Do you think you might be able to fix this bug? If so, what sort of time scales are we looking at? (I am in the middle of a project!)
thanks and rgds Jim Heck
