### ISSUE TITLE
Feedback: lack of clear documentation on how to use your plugin

### ISSUE THREAD

**Issue by gmalone** [archetyped/simple-lightbox#732]
I'm not particularly stupid (usually), but after spending that last 15 minutes with your activated plugin it is absolutely unclear how to use it.  Shortcodes? How to configure?  No screenshots of the plugin actually working.  Sorry, I don't get it.

**Comment by archetyped** [comment]
Hi, I would recommend taking a look at [Simple Lightbox's page in WordPress' Plugin Directory](https://wordpress.org/plugins/simple-lightbox/) for most of your questions.  As the official place where most plugins (including SLB) are downloaded and installed from, the Plugin Directory are a good place to start and become familiar with a plugin.

For example:

* How to use it - From the **Usage** section: "Insert links to images/image attachments into your posts/pages."
    * If you need more detailed guidance (e.g. inserting links into posts in WordPress, etc.), see [SLB Beginner's Guide](https://archetyped.com/know/simple-lightbox-for-noobs/ "SLB Beginner's Guide")
* How to configure - Near the top of the page: "Options for customizing the lightbox behavior are located in the **Appearance > Lightbox** admin menu (or just click the **Settings** link below the plugin’s name when viewing the list of installed plugins)".
* Screenshots - in the **Screenshots** section (standard section for all plugins in the Directory).
* Shortcodes - Unnecessary for standard functionality, but some are available for specific needs.  See [SLB's documentation for more details on shortcodes](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes).

Please let me know if there is anything else you're not finding on [SLB's Plugin Directory page](https://wordpress.org/plugins/simple-lightbox/) or [Documentation](https://github.com/archetyped/simple-lightbox/wiki) and I would be glad to take another look.

Thanks.
