### ISSUE TITLE
Issue: Image not opening in lightbox

### ISSUE THREAD

**Issue by Ayaneko** [archetyped/simple-lightbox#734]
## Description of Problem
Image that is dynamically added to page, with link to image, is not opening in lightbox. I have a feeling it may be something I am missing in my code to display the image, but as I don't know what Simple Lightbox is using as a trigger to know it should display in lightbox, I don't know what to add to my code to cause the trigger. If you have a moment to look at this example page and tell me what I am missing, I would appreciate it. Thank you!

## Details

* URL of Page exhibiting problem: https://ayamenakamura.com/sneaker-freak-air-1985/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox & Chrome. have not checked in others.
* Version of SLB Installed: Latest (2.7.1)
* Other plugins installed: Many, but I am fairly certain it's not a plugin issue. The Simple Lightbox is working for all normally added images, but being a developer, I have customized my theme to display the featured image in the page automagically. :)

**Comment by archetyped** [comment]
Hi, SLB automatically activates links in post/page/widget content.  Links outside of these content areas can be manually activated using `slb_activate()`.  See SLB's documentation for [more details on using `slb_activate()`](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation).

**Comment by Ayaneko** [comment]
Thanks for the info, it led me in the right direction. I was looking for how to make SLB recognize my custom content, but could not find the info. I still had a little trouble with the formatting of the line, but found this code example that worked perfectly for my needs.

https://hotexamples.com/examples/-/-/slb_activate/php-slb_activate-function-examples.html

The first example is exactly what I needed to add the post thumbnail to my posts and have it recognized by SLB. Hope this helps others who may need it.

Thanks!
~Aya
