### ISSUE TITLE
Request: 

### ISSUE THREAD

**Issue by caseyghancock** [archetyped/simple-lightbox#735]
## Description of feature
Ability to turn off or override the custom font used by the plugin.

## This feature would be used to
I'd like the plugin to inherit styles of the theme as much as possible

## If you added this feature, I would:

a) Eat my hat, if I can have some hot sauce with it

**Comment by archetyped** [comment]
Hi, SLB's appearance can be fully customized using a custom theme.  This provides the best option for matching a site's overall theme.

See [SLB's theme documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for details and resources on creating custom themes.
