### ISSUE TITLE
Perfection?

### ISSUE THREAD

**Issue by aaron843** [archetyped/simple-lightbox#736]
Maybe I'm asking too much of a lightbox, but the following would be perfect.
Your lightbox, plus the following:

Ability to display images without the frame/border/glow (maybe I can hide the frame with CSS)
Ability to display larger image screen-sized initially, then let user toggle to 100%

I've seen lightboxes that do these things, but for some reason all seem to lack keyboard support, especially the "esc" key to return from full size, essentially locking the user in a dead end.

**Comment by archetyped** [comment]
Hi,

* **Appearance:** SLB's appearance can be fully customized with themes.  See [SLB's themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for more details.
* **Toggle full-size image:** Follow and add your feedback to [the existing ticket on this functionality](288).

Thanks.
