### ISSUE TITLE
Issue: Lightbox not working after server migration

### ISSUE THREAD

**Issue by dead-famous** [archetyped/simple-lightbox#738]
## Description of Problem
After switching servers, lightbox is no longer working. 
I have checked that cURL is enabled, settings can be found here. 
http://dev.hy-techdrilling.com/phpinfo.php

 Any help in identifying the problem would be great.

Example of new server with affected page:
http://dev.hy-techdrilling.com/our-company/indigenous-people/community/

Example of old server with same working page:
http://hy-tech.deadfamous.ca/our-company/indigenous-people/community/

## Details

* URL of Page exhibiting problem: 
http://dev.hy-techdrilling.com/our-company/indigenous-people/community/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All.
* Version of SLB Installed: 2.7
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it looks like the new site's cURL configuration is the issue.

PHP's info output simply shows whether cURL support is enabled in PHP, but cURL itself must be properly configured at the host/server level.  As noted in [the documentation on SLB's requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support), you may need to contact your host to look into their cURL configuration.

If you are still experiencing this issue after confirming cURL is set up as per the requirements link above, please post an updated link to a page exhibiting the issue and I would be glad to reopen this ticket and take another look.

Thanks.
