### ISSUE TITLE
Request: Simple image enhancements/effects

### ISSUE THREAD

**Issue by ludasmokva** [archetyped/simple-lightbox#742]
I want to say that I am very new to Wordpress, so I may be missing something.
I would suggest some very basic effects for images, like shadow, simple border, or background colour. Nothing overly complex as that defeats the purpose of "simple" lightbox.

I was using Robo Gallery for some of my images but I liked your method of showing a slideshow of selected images (although I am getting an HTML conflict message, it still shows properly). 

Unfortunately, I cannot integrate the two. So I have my first image of the slide show looking different from the other images. I figured it would have been easier to just not use Robo Gallery, but then the images are completely bland. So I figured I would write to you and make a suggestion. :) 

Otherwise congratulations on making a simple and functional plug-in. When I get some videos to display, I will certainly buy the upgrade.

**Comment by archetyped** [comment]
Apologies for the delayed response-- it looks like my original reply did not post for some reason.

The display of the content in the lightbox is fully customizable via themes, allowing you to setup the lightbox exactly as desired (including drop shadows, borders, colors, etc.).  See [SLB's Theme documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for more details and tutorials.

Also, if you can provide a link to a page that shows the differences you describe when using Robo Gallery and SLB, I would be glad to take a look to get a better idea of what you're asking for.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
