### ISSUE TITLE
Redirect not working with Ninja Forms

### ISSUE THREAD

**Issue by ludasmokva** [archetyped/simple-lightbox#743]
This is probably not fixable, but I though I would ask.
I created a Ninja contact form on a separate page. 
Upon submission, I activated a redirect to a new "Success/Thank You" page. 
I would prefer this page opens up in your lightbox so it is easily closed and dismissed, but have no clue how to do it.
The set up for this redirect page simply allows me to insert a link, no other editing.
The button that submits does not allow me to "link" to anything.
Any ideas? 

*EDIT: I did look through the wiki, but I could not find anything that would apply.  Sorry.

**Comment by archetyped** [comment]
Hi, SLB currently displays media (images, etc.), not other posts/pages in the lightbox, though an add-on may provide support for this functionality in the future.

Thanks.

**Comment by ludasmokva** [comment]
Ok, thanks.
I only asked because I though I read somewhere that SLB works with pages and posts. But maybe I misunderstood the note. Thanks for the quick response!

**Comment by archetyped** [comment]
Hi, SLB displays compatible media (e.g. images, etc.) from links in page and post content.  SLB does not display full pages and posts themselves in the lightbox.
