### ISSUE TITLE
Problem with custom module script and Lightbox 

### ISSUE THREAD

**Issue by DimitriDV** [archetyped/simple-lightbox#745]
Hi there

I have written my own, custom module to show some items.
Part of the script has the following code:

```php
<h2>PICTURES</h2>
            <?php
            $images = get_field('gallery');
            if( $images ): ?>
                <ul>
                    <?php foreach( $images as $image ): ?>
                        <li>
                            <a href="<?php echo $image['url']; ?>">
                                <img src="<?php echo $image['sizes']['thumbnail']; ?>" alt="<?php echo $image['alt']; ?>" />
                            </a>
                            <p><?php echo $image['caption']; ?></p>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <div style="clear:both;">&nbsp;</div>
```

*edit: the php code is not shown here, how can I show it?

How can I make the lightbox work with this code please?
I already installed the plugin but it's not working.

**Comment by archetyped** [comment]
Hi, SLB automatically activates links in post/page/widget content.  Links outside of these content areas can be manually activated using `slb_activate()`.  You basically just need to save your generated HTML to a variable and pass that through `slb_activate()` before outputting. 

See SLB's documentation for [more information on using `slb_activate()`](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation).

P.S. I've formatted your post to display the PHP code.  For future reference, you can click on the Markdown icon in the bottom right corner of the forum post editor to display [documentation on formatting content with Markdown](https://guides.github.com/features/mastering-markdown/).
