### ISSUE TITLE
Plugin works in dev but not prod

### ISSUE THREAD

**Issue by pmarxbraun** [archetyped/simple-lightbox#746]
Hey there,

Got 2 environments with exact same theme and plugins
Plugin works on dev but not in Prod 

Exemple when clicking on an image
prod : https://www.aperodujeudi.com/bar/le-cafe-de-lopera/
dev : https://dev2.monsitetranquille.fr/bar/le-cafe-de-lopera/

Tried everything. Any idea ? Thanks

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled and/or properly configured for your site.  Please see SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

Please provide an updated link if you are still experiencing a problem after configuring cURL, and I would be glad to reopen this ticket and take another look.

Thanks.
