### ISSUE TITLE
Issue: Missing File

### ISSUE THREAD

**Issue by kordiks** [archetyped/simple-lightbox#747]
## Description of Problem

After updating WordPress to the latest version, the plugin began to produce a fatal error.
Plugin: Simple Lightbox"

## Details

* URL of Page exhibiting problem:  Warning: require_once(/home/s/student5ru/test/public_html/wp-content/plugins/simple-lightbox/includes/class-requirements-check.php): failed to open stream: No such file or directory in /home/s/student5ru/test/public_html/wp-content/plugins/simple-lightbox/main.php on line 22
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Opera
* Version of SLB Installed: 2.7.1
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it looks like some files were deleted from the plugin (perhaps during the WordPress update).  Deleting the plugin's folder and re-installing Simple Lightbox should resolve the issue and allow SLB to function normally.

Please provide updated details (link, etc.) if you are still experiencing an issue after deleting and re-installing SLB, and I would be glad to reopen this ticket and take another look.
