### ISSUE TITLE
Issue: Lightbox caption showing link text instead of caption

### ISSUE THREAD

**Issue by Netinspire** [archetyped/simple-lightbox#748]
## Description of Problem
When I open a lightbox from a text link, the caption displayed in the lightbox is the link text (e.g. Click here to view image) instead of the caption set in the Media Library.

This is only happening on Chrome on my Windows machine as I am not encountering this issue on my Mac in any browser.

An example is the link on **the accompanying illustration** on the page http://grayspottery.co.uk/exhibitions/exhibitions-1914-1930/ in the 3rd British Industries Fair section.

## Details

* URL of Page exhibiting problem: http://grayspottery.co.uk/exhibitions/exhibitions-1914-1930/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Version 2.7.1
* Other plugins installed: 

Astra Hooks
Astra Pro
Bulk Delete
Custom Hooks
Duplicate Post
Duplicator
Elementor
Elementor Extras
Elementor Pro
FacetWP
FacetWP - Elementor
FacetWP - Flyout menu
FacetWP - Hierarchy Select
Favicon by RealFaviconGenerator
Google Analytics Dashboard for WP (GADWP)
Media Library Categories
Relevanssi
Simple History
Simple Lightbox
TablePress
TablePress Extension: Responsive Tables
The SEO Framework
Toolset Types
Toolset Views
Ultimate Dashboard
Velvet Blues Update URLs
WordPress Backup & Security Plugin - BlogVault
WP All Import - Toolset Types Add-On BETA
WP All Import Pro

**Comment by archetyped** [comment]
Hi, I've tested the example link you mentioned in multiple browsers (including Chrome on Windows), and the lightbox caption shows as "© Pottery Gazette, Lema Publishing Ltd" in all of them.

I would recommend fully clearing the browsers cache and then refreshing the page to ensure you are loading the most current version of the page.  Ensuring that your browser is up to date is also recommended (Chrome Windows v77.0.3865.75 as of today), as there may have been bugs, etc. that affected the browser's functionality.

If you are still experiencing this issue after performing the above steps, please provide a link to a test page that exhibits the issue, and I would be glad to reopen this ticket and take another look.

Thanks.

**Comment by Netinspire** [comment]
Hi,

I am still intermittently experiencing this issue. An exmaple page is http://grayspottery.co.uk/retailers/ and the link is “View Image” on the row which starts T Goode & Co. I have checked the image data in the media library and no meta date is set, iether title or caption but it shows the text “View Image” as a caption.

Kind Regards,
Chris



Chris Platt
Technical Support Manager | Netinspire Ltd
P: 01782524600
E: chris.platt@netinspire.co.uk
How did we do?
Click to rate your experience with Netinspire

**Comment by archetyped** [comment]
Hi, a link's text is used as the final fallback in the lightbox's [title precedence](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence).

The reason why some of the links on the page you provided are blank is because they have the default title generated by WordPress in the media library.  This behavior has been made more consistent in an upcoming update, and the presence of a default title will no longer stop further title precedence fallbacks.
