### ISSUE TITLE
File name displayed instead of caption

### ISSUE THREAD

**Issue by salcan** [archetyped/simple-lightbox#749]
## Description of Problem

> class="slb_template_tag slb_template_tag_item slb_template_tag_item_title"

When I click on an image and activate the lightbox, the filename of the image is being displayed. Is this the intended behavior? I would have expected the caption or Alt text. 

My mistake if this was a conscious decision and not an issue. If this is the case, if this configurable in any way?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please fill in the details of your issue so that it can be fully evaluated.

Thank you.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
