### ISSUE TITLE
How can I speed up show overlay?

### ISSUE THREAD

**Issue by dev4xy** [archetyped/simple-lightbox#750]
Hi,
I want to speed up pop-up overlay opening after click on photo.

In fact I want to run below code at fast speed:
```
// Show overlay
 o.fadeIn({'always': function() {
    // Position lightbox
    l.css(pos);
    dfr.resolve();
}});
```

How can I do it?

Thanks

**Comment by archetyped** [comment]
Hi, here is the documentation of all options available for jQuery's `fadeIn()` function: [`jQuery.fadeIn()` Documentation](https://api.jquery.com/fadein/).

**Comment by foreachthing** [comment]
@dev4xy were you able to set your speed in `o.fadeIn()` and if so, how and where?
