### ISSUE TITLE
Hello! Can i use lightbox on simle images

### ISSUE THREAD

**Issue by wireinet** [archetyped/simple-lightbox#751]
Hello! Can i use lightbox on simle `<img>`, insted `<a>`

**Comment by archetyped** [comment]
Hi, SLB requires links for its functionality.  Without links, there is nothing for visitors to click on and nothing to tell SLB what to display in the lightbox.

**Comment by wireinet** [comment]
hello and Thank you for answer! I solve this problem by adding a link!
