### ISSUE TITLE
'Load More' doesn't work

### ISSUE THREAD

**Issue by Joostdehaas** [archetyped/simple-lightbox#752]
Hi there,
I've encountered a problem.
On my website ( www.joostdehaas.nl ) I'm using a masonry portfolio grid (from a theme called Werkstatt) with your lightbox. It works perfectly BEFORE the 'load more' button. As soon as more items are loaded, the new items are unable to load the lightbox. Is there a way to force reload it or something? My coding skills are not very good, but I know it doesn't work. Do you understand the problem, and think there could be a solution? I very much hope so. Thanks!

**Comment by archetyped** [comment]
Hi, the additional posts appear to be loaded via AJAX, which is not currently supported by SLB by default.

See this [existing ticket on AJAX support](https://github.com/archetyped/simple-lightbox/issues/208) to add your feedback (e.g. submit the specific AJAX theme/plugin you're using) and stay updated on the status of this topic.
