### ISSUE TITLE
Issue: simple-lightbox on top of wp default gallery overlay

### ISSUE THREAD

**Issue by ShawnDK** [archetyped/simple-lightbox#754]
## Description of Problem

When a wp gallery is used simple-lightbox (SLB) is displayed on top of the default ui overlay. This means a user has to close the overlay two times - first click closes SLB, the second closes the wp lightbox.

## Details

* URL of Page exhibiting problem:
    https://shawndesign.dk/danish-design/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
    Chrome, Firefox, Edge
* Version of SLB Installed:
    Version 2.7.1
* Other plugins installed:
    With SLB disabled the problem disappears, since the issue is with SLB overlaying the existing WP 
    gallery ui

**Comment by archetyped** [comment]
Hi, WordPress does not use a lightbox/overlay to display gallery images by default.  This means that the other overlay you're seeing on your site is generated by another plugin (or the active theme).

See [these instructions on identifying plugin conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) to identify and disable the plugin that is displaying the 2nd overlay.
