### ISSUE TITLE
Issue: it always show the ALT

### ISSUE THREAD

**Issue by wuker** [archetyped/simple-lightbox#755]
## Description of Problem
Whenever the alternative text (ALT) is set within the HTML IMAGE TAG, the ALT info will always be shown at the bottom of the lightbox though the image will be rendered correctly also.

## Details

* the blog is setup for internal service, I currently have no link to reproduce the issue. but if you try the following code, it is easier to reproduce it
```
<a href="/wp-content/uploads/2019/11/test.png" style="cursor: default;" data-slb-active="1" data-slb-asset="1994120514" data-slb-internal="0" class="fbx-link fbx-instance">
<img src="/wp-content/uploads/2019/11/test.png" alt="Failed image!" title="" width="400" height="auto" style="cursor: zoom-in;" scale="0"/>
</a>
```
* Chrome, FIrefox & IE
* Version of SLB Installed: don't know
* Other plugins installed: I remove all plugins except for simple-lightbox, same issue

**Comment by archetyped** [comment]
Hi, as per [SLB's title precedence](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence), the `alt` attribute's text is used as a fallback if no other caption values are available for the lightbox.
