### ISSUE TITLE
Issue: Caption line height

### ISSUE THREAD

**Issue by scotteli** [archetyped/simple-lightbox#756]
## Description of Problem
Not an issue, just confusion. I'm trying to restyle the text on the popup caption. I can tweak everything (font family, size, etc.) except the line height. I'm using the following selector which otherwise seems to work for all other parameters:
#slb_viewer_wrap .slb_theme_slb_baseline * {}

 Obviously, this is not a critical issue, but if you could clue me in to what I'm missing, I'd appreciate it.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, that selector affects all elements in the baseline theme.  The baseline theme is a framework/boilerplate for other themes (such as the included Light and Dark themes), so targeting the baseline theme is not recommended.

You can set styles for the lightbox's title/caption with the following selector:
```css
#slb_viewer_wrap .slb_theme_[your-theme] .slb_data_title {}
```
(Where `[your-theme]` is the ID of the theme you're setting styles for.)

See [SLB's Theme's documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for more details on theme customization, including [a guide on customizing theme styles](https://archetyped.com/know/slb-theme-styles/) for more details.

**Comment by scotteli** [comment]
THX!
