### ISSUE TITLE
The plugin doesn't seem to work with multiple galleries on the page. 

### ISSUE THREAD

**Issue by Akidta** [archetyped/simple-lightbox#757]
## Description of Problem

The lightbox works on a single gallery or image. as soon as I add another block - no luck with the added one. What am I missing?

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
I would love to know as well!  Please fill in the full details of your issue above and I would be glad to take a look.

**Comment by Akidta** [comment]
archetyped, thank you! 

here are two pages to compare:
https://uxprofit.blog/test-2/ - working lightbox

But, as soon as I add WP tiled gallery to the page (where I cannot convert the block to HTML), the first block (with lightbox) stops working:
https://uxprofit.blog/test-page/

**Comment by archetyped** [comment]
Hi, it appears that [Jetpack's Carousel](https://jetpack.com/support/carousel/) is intercepting clicks on the gallery images. 

Disabling the Carousel in Jetpack's settings should allow SLB function normally on that page.

Please let me know if you are still experiencing an issue after disabling Jetpack's Carousel and I would be glad to reopen this issue and take another look.
