### ISSUE TITLE
Issue: Not working on new images

### ISSUE THREAD

**Issue by Karditsiwths** [archetyped/simple-lightbox#758]
## Description of Problem
After i installed the plugin all the images inside post-pages etc are working fine but it doesnt happened the same when i upload new images on the site. The new images doesnt open with Lightbox. Any idea why? Thanks in advanced

## Details

* URL of Page exhibiting problem: https://www.romaxorissinora.com/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 
* Other plugins installed: Classic Editor, Contact Form 7, Disable Comments, 
greeklish-permalinks, Loco Translate, Regenerate Thumbnails, Super Socializer, TinyMCE Advanced, TranslatePress - Multilingual

**Comment by archetyped** [comment]
Hi, SLB appears to function properly for all image links on the page you provided.

Please provide more details or a link to a specific page that exhibits the issue you are experiencing, and I would be glad to take another look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
