### ISSUE TITLE
Version 2.8.0 Causing Fatal Error with new WP 5.3 Update

### ISSUE THREAD

**Issue by psasso** [archetyped/simple-lightbox#761]
EMAIL:
Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Simple Lightbox.

...

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3
Current theme: Positive Vibes (version 1.6)
Current plugin: Simple Lightbox (version 2.8.0)
PHP version 5.6.39

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 494 of the file /public_html/WEBSITE-NAME/wp-content/plugins/simple-lightbox/includes/class.field_base.php. Error message: Default value for parameters with a class type hint can only be NULL

**Comment by psasso** [comment]
This is more annoying to me since I've paid for your Simple Lightbox: Video Handler add-on and now it's basically useless.

**Comment by archetyped** [comment]
How did you update SLB?  As noted in the plugin's headers (and changelog, upgrade notices, documentation, etc.), v2.8.0+ requires PHP 7.2+.

WordPress has built-in functionality to prevent the plugin from being updated when requirements (such as the PHP version) are not met by the site, so details on the method you used to update SLB would be very helpful in evaluating this issue.

Thanks.

**Comment by psasso** [comment]
Everything auto updated as far as I know. (The WordPress update happened this weekend.)

I don’t recall working on this site for about a year — so no manual changes other than my client editing content. 

I have deactivated the plugin to get the site working again. 

I should be able to update the PHP over the next day or two. Will that fix it?

Phil Sasso
Sasso Marketing, Inc.
3043 N. 25th Avenue
Franklin Park, IL 60131
tel. 847.451.2246
—
“Strategic thinking is more productive than wishful thinking.”

**Comment by archetyped** [comment]
Plugins and themes are not automatically updated in WordPress by default.  A plugin or theme functionality (or service provide by a web host or third-party) must be used to perform such updates.  Any details you can provide on how your site is configured to perform automatic updates would be very helpful in determining how the update happened.

Yes, updating to a supported version of PHP (7.2+) will resolve this issue.  Please post an update to this ticket if you are still experiencing this issue after updating PHP and I would be glad to take another look.

Thanks.

**Comment by psasso** [comment]
I believe Softaculous may have an plugin auto update function that I enabled during install. 

Does that make sense?

My hosting provider advised me to carefully consider before upgrading to 7.2. They say it might break other plugins. 

Is that accurate?

Thanks!

Phil Sasso
Sasso Marketing, Inc.
3043 N. 25th Avenue
Franklin Park, IL 60131
tel. 847.451.2246
—
“Strategic thinking is more productive than wishful thinking.”

**Comment by archetyped** [comment]
Thank you for the additional details on your auto-update setup.  I'll take a look at Softaculous.

WordPress fully supports PHP 7.2+ (up to 7.4, in fact), but it is possible that some plugins/themes have not been updated to be compatible with WordPress' recommended PHP version (7.3).

The best thing to do is to test any updates on a local or staging site to make sure everything is functioning properly.  Here's [a step-by-step tutorial on upgrading your WordPress site to PHP 7+](https://themeisle.com/blog/upgrade-wordpress-to-php-7/).

You can also perform some tests using a plugin like the [PHP Compatibility Checker](https://wordpress.org/plugins/php-compatibility-checker/), or a site like [PluginTests](https://plugintests.com/).  This allows you to identify issues with specific plugins/themes before performing the PHP upgrade.

**Comment by archetyped** [comment]
This issue has been resolved in [v2.8.1](https://github.com/archetyped/simple-lightbox/releases/tag/2.8.1)
