### ISSUE TITLE
Navigation arrows replaced with text Prev/Next

### ISSUE THREAD

**Issue by smil3y7** [archetyped/simple-lightbox#762]
## Description of feature
Navigation arrows replaced with text Prev/Next, preferably available as an option in settings.

## This feature would be used to
Switch between navigation arrows and text buttons

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above <<< This one, of course!

Thank you very much!

**Comment by archetyped** [comment]
Hi, the lightbox UI (layout, buttons, etc.) is fully control by active lightbox theme, so this is something that you can do right now by building a custom lightbox theme!

See SLB's documentation for [more details and tutorials on creating a custom theme](https://github.com/archetyped/simple-lightbox/wiki/Themes).

I've also added it to the list to keep in mind for future themes for SLB.

Thanks.
