### ISSUE TITLE
HTML in caption

### ISSUE THREAD

**Issue by joostwalter** [archetyped/simple-lightbox#767]
I would like to put a part of the caption of an image in Simple Lightbox on a new line. I've tried `<br>`, but there's no effect: all the words of the caption are written behind each other. So the caption doesn't seem html-sensitive.

Am I right?

**Comment by archetyped** [comment]
Hi, HTML is supported for an image's caption and is displayed in the lightbox.  If you are still experiencing this issue, please provide the following information:

* Link to a page that exhibits the issue you are experiencing.
* Screenshot of caption field with HTML.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
