### ISSUE TITLE
Issue: Fatal error displaying Lightbox Settings, first time after activation

### ISSUE THREAD

**Issue by reine-k** [archetyped/simple-lightbox#768]
## Description of Problem

After activating Simple Lightbox I navigate to the settings and get a message:
Activation
There has been a critical error on your website. Please check your site admin email inbox for instructions.

Activating debug on wordpress I get the following details (I replaced the path to the WP installation on my server by _WP_ROOT_):

Fatal error:
Uncaught Error: Call to undefined function xml_parser_create() in _WP_ROOT_/wp-content/plugins/simple-lightbox/includes/class.field_type.php:293
Stack trace:
#0 _WP_ROOT_/wp-content/plugins/simple-lightbox/includes/class.field_type.php(203): SLB_Field_Type->parse_layout('{field_referenc...', '/{([a-zA-Z0-9]....')
#1 _WP_ROOT_/wp-content/plugins/simple-lightbox/includes/class.field_type.php(385): SLB_Field_Type->get_layout('form')
#2 _WP_ROOT_/wp-content/plugins/simple-lightbox/includes/class.field_type.php(373): SLB_Field_Type->build_layout(NULL, NULL)
#3 _WP_ROOT_/wp-content/plugins/simple-lightbox/includes/class.field_collection.php(392): SLB_Field_Type->build()
#4 _WP_ROOT_/wp-content/plugins/simple-lightbox/includes/class.field_collection.php(695): SLB_Field_Collection->build_items(Object(stdClass))
#5 _WP_ROOT_/wp-content/plugins/simple-lightbox/include in _WP_ROOT_/wp-content/plugins/simple-lightbox/includes/class.field_type.php on line 293

Not sure whether this is relevant, but I had Simple Lightbox activated a long time ago (not sure when/which version, sorry), then I did not use it (deactivated) for a long time, so I thought some obsolete stuff could have persisted in the database and causing the problem.
So I also tried to completely remove Simple Lightbox, then I re-installed it. But the error persists.

## Details

* URL of Page exhibiting problem: https://reinekurth.com/wp-admin/themes.php?page=slb_options
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox 72.0.1 (64-bit) (Desktop)
* Version of SLB Installed: 2.8.0
* Other plugins installed:
    Debug Info (1.3.8)
    Disable Emojis (GDPR friendly) (1.7.2)
    Media from FTP (11.04)
    Nginx Cache (1.0.4)
    SAR Friendly SMTP (1.2.5)
    Sublanguage (2.6)
    WP Crontrol (1.7.1)
    WP Instagram Widget (2.0.3)
I disabled them all and the error was still present.
* Further details:
WordPress Version: 5.3.2
Current WordPress Theme: Twenty Twenty version 1.1
PHP Version: 7.2.26-1
MySQL Version: 10.2.30 (mariaDB)
jQuery version checked with jQuery Check, it is 1.12.4 (on the admin; on the website itself it says "jQuery not loaded").
* cURL info from phpinfo:
(not sure what "cURL must be enabled for local requests" means)
cURL support 	enabled
cURL Information 	7.47.0
Age 	3
Features
AsynchDNS 	Yes
CharConv 	No
Debug 	No
GSS-Negotiate 	No
IDN 	Yes
IPv6 	Yes
krb4 	No
Largefile 	Yes
libz 	Yes
NTLM 	Yes
NTLMWB 	Yes
SPNEGO 	Yes
SSL 	Yes
SSPI 	No
TLS-SRP 	Yes
HTTP2 	No
GSSAPI 	Yes
KERBEROS5 	Yes
UNIX_SOCKETS 	Yes
PSL 	No
Protocols 	dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host 	x86_64-pc-linux-gnu
SSL Version 	OpenSSL/1.0.2g
ZLib Version 	1.2.8

**Comment by archetyped** [comment]
Hi, the error messages indicates that `xml_parser_create()` is not available on your PHP installation.  

PHP's XML functions are included by default, but if you are installing/compiling PHP yourself, you need to make sure that this is not being disabled (e.g. via `--disable-xml`).

If the PHP installation is managed by your web host, I would recommend contacting them to enable PHP's default XML functionality.

See PHP's documentation for [more details on XML setup and requirements](https://www.php.net/manual/en/xml.setup.php).

**Comment by reine-k** [comment]
Thank you!
Sorry for taking your time when my configuration was at fault :/
(I did install php from a - reputable ;) - ppa, have to in ubuntu 16.04 as default is 7.0... Also one has to install/enable the xml extension via a separate package, which I hadn't)

**Comment by archetyped** [comment]
No problem, glad to hear your issue was resolved 🙂
