### ISSUE TITLE
Issue: Lightbox Not Working All The Tim

### ISSUE THREAD

**Issue by ikeaoji** [archetyped/simple-lightbox#769]
## Description of Problem
I got this plugin a while back and it's been working up until recently. Now whenever you click on a gallery item on my website, sometimes it takes you to the attachment page. The plugin will work at times on certain pages and then stop working. I tried to fix it yesterday and I thought it worked but today it's back to doing the same thing.

## Details

* URL of Page exhibiting problem: sidingexpress.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all browswers
* Version of SLB Installed: 2.8.0
* Other plugins installed: akismet anti-spam, backupbuddy, bookly pro, classic editor, elementor, essential addons for elementor, element pack, ithemes security, ithemes sync, make column clickable elementor, redirection, search exclude, simple custom css and js, wp supercache, yoast

**Comment by archetyped** [comment]
Hi, there appears to be an issue with the loading of the lightbox's layout at the link you provided.  This generally occurs when cURL is not enabled and/or properly configured for your site.  Please see SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

You noted that the lightbox is sometimes displayed, so cURL configuration may not be the (only) issue.  Can you please provide a link a specific page where the lightbox is displayed when an image link is clicked?

Thanks.

**Comment by ikeaoji** [comment]
[Here's a page](https://www.sidingexpress.com/doors-gallery/) that I got it to work on. But it's very finnicky and it'll probably stop working after while like it has before.

**Comment by archetyped** [comment]
Hi, SLB does not appear to be activated at the link provided.  Please let me know when SLB has been activated, and I would be glad to take another look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
