### ISSUE TITLE
hi.. how can i..

### ISSUE THREAD

**Issue by aliselvi** [archetyped/simple-lightbox#770]
Hi.. thank you for a very nice plugin.

i just want to know how i can turn off the text at the bottom of the box and totally remove the borders.

thank you again.

**Comment by archetyped** [comment]
Hi, the lightbox's appearance is fully controlled by the active theme.

See [SLB's documentation on themes](https://github.com/archetyped/simple-lightbox/wiki/Themes) for details on creating and customizing themes.
