### ISSUE TITLE
Multiple Galleries on Single Page Merged Into Single Lightbox

### ISSUE THREAD

**Issue by Woolwit** [archetyped/simple-lightbox#772]
Simple Lightbox 2.8
WP 5.3.2 
Twenty Seventeen Theme 
Page: https://svsurrender.com/equipment/
Issue: Though structured as multiple smaller galleries for the purpose of informing particular section of page, once activated, the Simple Lightbox shows photos from all galleries on same page.

**Comment by archetyped** [comment]
Hi, support for separate slideshows for galleries  created using the new block editor is planned for a future update.

Thanks.
