### ISSUE TITLE
Link Not Active Where/When Caption Present

### ISSUE THREAD

**Issue by Woolwit** [archetyped/simple-lightbox#773]
Simple Lightbox 2.8
WP 5.3.2
Twenty Seventeen Theme
Page: https://svsurrender.com/welcome-aboard/
On images that contain captions link to activate Simple Lightbox is not present in vicinity of caption. Depending on size of the thumbnail, this may amount to over 50% of the image. May be beyond the scope of SL but thought worth asking. In this particular case the desired behavior would be that link is active anywhere over image/caption.

**Comment by archetyped** [comment]
Hi, SLB does not make any modifications to the layout of the content on page itself, including gallery thumbnails/captions.  It only controls what is displayed in the lightbox.

As you are using WordPress' block editor, I would recommend submitting a request to link the thumbnail captions of galleries on [the block editor's project page](https://github.com/WordPress/gutenberg).
