### ISSUE TITLE
Latest update breaks lightbox (broken image link)

### ISSUE THREAD

**Issue by chromadesign** [archetyped/simple-lightbox#774]
Hi,

I updated to several Wordpress sites to the latest version of the plugin and the lightbox stopped working on every single site. When an image link is clicked, it says it can't find the image and the console shows that it tries to open sitexyz.com/null instead of the image link (which is correctly linked and works). I also can't close the lightbox anymore. Any idea what might have happend here?

Example page: https://www.axon-electronics.eu/dienstleistungen/produktbeispiele/

Best regards,
Manuela

**Comment by archetyped** [comment]
Hi, SLB does not appear to be installed/activated at the link you provided.

Please let me know when SLB is activated at the link, and I would be glad to take another look.

**Comment by chromadesign** [comment]
Sorry, my bad. There's another plugin with almost the same name which I confused with yours.
