### ISSUE TITLE
Request: display different lightbox images in desktop and mobile views

### ISSUE THREAD

**Issue by gustavo164584** [archetyped/simple-lightbox#776]
## Description of feature
I would like to know how to display different lightbox images in desktop and mobile views

## This feature would be used to
In my website, https://pluuvo.com.br/

## If you added this feature, I would:
d)!!!

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, SLB displays the image that is specified in the link being clicked.  This means that if you want to display different images in different situations, then you just need to update the link on the page to point to the desired image file for each situation (e.g. desktop, mobile, etc.), and SLB will display that image in the lightbox when the link is clicked.
