### ISSUE TITLE
Request: make an option for duration of lightbox slide to be indefinite

### ISSUE THREAD

**Issue by SJT1988** [archetyped/simple-lightbox#777]
## Description of feature

I have a lot of animated gifs in my post. By default, lightbox slides should not change without the user choosing the next slide. Please explicitly indicate an option that makes a slide stay up indefinitely.

## This feature would be used to

Keep the current slide displayed until the user says otherwise.

## If you added this feature, I would:

think the app does what it should already be able to do.

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, you can disable the **Start Slideshow Automatically** option in SLB's settings to make the slideshow advance based on manual controls only.
