### ISSUE TITLE
Simple Lightbox is SIMPLY NOT WORKING AT ALL!?

### ISSUE THREAD

**Issue by Loukadinc** [archetyped/simple-lightbox#779]
I installed this plugin and no matter what I do, it doesnt work for me... I am using siteground cloud server hosting and am able to easily generate staging areas for extensive testing, here is a list of things I have tried : 

- I tried adding images in different ways (inside classic text block, inside image block) and tried linking to media file and attachment page.

-  I tried USING DIFFERENT THEMES **including the default WP themes** (twenty twenty and twenty nineteen)

- I tried **DISABLING ALL PLUGINS** (except Simple Lightbox)

- I tried **changing php versions** (plugin says it requires php 7.2 , i tried lower and higher versions, currently set at 7.3)... 

- I tried **_downgrading_ wordpress from 5.3.2 to 5.3** ( 5.3 is the minimum required version for the plugin) and still no luck. 

- I tried using **different browsers** (chrome / edge)... 

I really dont know what else to try, NOTHING seems to works, the image link send us to the image url instead of opening in a lightbox... When I check the source code the lightbox plugin does seem to be adding some custom classes that should make the lightbox works, but it doesnt.

I could should share access to my staging testing site but I dont think it should be shared publicly here, please let me know if there is a way to get in touch privately.

Thanks

**Comment by archetyped** [comment]
Hi, it looks like you've covered most of the [steps for troubleshooting plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts), so I would recommend also [confirming that your site is properly configured and meets the minimum requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements).

For example, I'm not familiar with how your host handles the configuration of staging sites, so ensuring cURL is properly installed/configured is particularly important.  Also review the notes on the [Requirements page](https://github.com/archetyped/simple-lightbox/wiki/Requirements) if you're using HTTP authentication for your staging site.

Once the site is publicly accessible, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by fhpinotti** [comment]
Hi! 
I am experiencing the same problem discribed above by Loukadinc.
I executed all the sugested actions to solve the problem, but nothing worked for me.
Here are the settings for my web server and site:
PHP 7.4.1
MySql 5.7.28
cURL 7.52.1 OpenSSL/1.0.2u
WordPress 5.3.2 with Twenty Seventeen 2.2
Simple Lightbox Versão 2.8.1

Url to see the problem:
https://sites2.vitoria.es.gov.br/gestaodaorla/area-para-skate-em-camburi/

Can you help me?

**Comment by archetyped** [comment]
@fhpinotti your issue does not appear to be related to the one @Loukadinc is reporting.  Please [create a new ticket](https://github.com/archetyped/simple-lightbox/wiki/Reporting-Issues) so that your specific issue can be fully evaluated.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.

Thanks.
