### ISSUE TITLE
[Support] Don't show media title and caption.

### ISSUE THREAD

**Issue by BirgerKlaus** [archetyped/simple-lightbox#782]
I got only the "figcaption" as title, not the image title and caption provided and stored in the media library. 

## Details
* URL of Page exhibiting problem: www.birgerschwarz.de
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Safari, Chrome (OSX / iOS)
* Version of SLB Installed: 2.81
* Other plugins installed: 

<img width="990" alt="Bildschirmfoto 2020-03-12 um 14 46 19" src="https://user-images.githubusercontent.com/6272313/76529267-5b5b9780-6472-11ea-8778-0154725bb5ff.png">
<img width="1440" alt="Bildschirmfoto 2020-03-12 um 14 48 33" src="https://user-images.githubusercontent.com/6272313/76529282-5f87b500-6472-11ea-8f78-2bc6df958f41.png">

**Comment by archetyped** [comment]
Hi, a manual caption on a specific usage of an image (e.g. in a gallery) is used over the default data in the media library.  See [SLB's title precedence documentation](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence) for more  details.

That said, it does appear that the image links on your page are not being identified as part of the Media Library by WordPress.  This usually occurs when the URL used in a post does not match the image's URL in the media library.

The most common cause for a mismatch is migrating a site to HTTPS without updating the URLs of the items in the media library.  If you have migrated the site to HTTPS (or worse, using a plugin to force the site to load as HTTPS), then I would recommend confirming that the URLs for the items in the media library match the links used throughout the site (i.e. both start with `https://`).

**Comment by BirgerKlaus** [comment]
Thank You!

There was a change from my hosting company and you're hint leads me to the brocken part.
Now everything works well again.
