### ISSUE TITLE
Simple lightbox does not work for my new galleries.

### ISSUE THREAD

**Issue by fhpinotti** [archetyped/simple-lightbox#783]
Hi!
I am experiencing problem with SLB on my most recent website.
The images in the galleries are not shown on the SLB.
When a thumbnail is clicked, the photo appears as a file link or attachment page, with neither lightbox effects nor navigation buttons.

I took all of the suggested actions to resolve the issue:
I tried to USE DIFFERENT THEMES, including the standard WP themes (twenty-twenty and twenty-nineteen)
I tried to DISABLE ALL PLUGINS (except Simple Lightbox)
I tried using different browsers (chrome / edge) ...
Nothing worked for me.

Here are my web server and website settings:
PHP 7.4.1
MySql 5.7.28
cURL 7.52.1 OpenSSL / 1.0.2u
WordPress 5.3.2 with Twenty Seventeen 2.2
Simple Lightbox Version 2.8.1

URL to see the problem:
https://sites2.vitoria.es.gov.br/gestaodaorla/area-para-skate-em-camburi/

Can you help me?

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled and/or properly configured for your site.  Please see SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

Please update this post if you are still experiencing this issue after confirming with your web host that cURL is properly installed and configured and I would be glad to reopen this ticket and take another look.
