### ISSUE TITLE
[Request] Convert an <img> to <a> by adding a class to img tag

### ISSUE THREAD

**Issue by andreascarfo** [archetyped/simple-lightbox#784]
## Description of feature
In my opinion it would be useful to have the possibility to convert in object that become lightboxes not just link but even images without link tag <a>

## This feature would be used to
It would be useful when you want to bulk activate lightbox to alarge amount of items, posts, when you upgrade a site from an old design to a newer one.

## If you added this feature, I would:

a) Eat my hat
X) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, are you saying that you want standalone images to be wrapped with a link to the same image already being displayed on the page?

Can you please provide some details regarding the benefit of displaying an image in the lightbox when the image is already viewable on the page itself?

**Comment by andreascarfo** [comment]
Old websites that can have inline big images can easily transform these img in lightboxes

**Comment by archetyped** [comment]
Hi, I'm still not seeing the benefit for visitors of adding a link to display the **same image** in the lightbox that is already being displayed on the page itself.

That said, bulk modifying post content in this way is outside of SLB's scope, and sounds like it would be better suited as a separate plugin.
