### ISSUE TITLE
[Support] Media/Text Block Appearance

### ISSUE THREAD

**Issue by AndrewMLeonard** [archetyped/simple-lightbox#785]
## Description of Problem

Please have a look at the page (url below)
I was playing wiith the Layout Elements Media & Text block
I have 2014 wirth a a child theme
It looks OK until I link it to get the lightbox effect 

## Details

* URL of Page exhibiting problem: https://ebps.org.uk/adiantum-and-its-colours/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Version 2.8.1 
* Other plugins installed:
Akismet Anti-Spam	Version 4.1.4 by Automattic
Broken Link Checker	Version 1.11.12 by WPMU DEV
CC Child Pages	Version 1.37 by Caterham Computing
Classic Editor	Version 1.5 by WordPress Contributors
Collapse-O-Matic	Version 1.7.11 by twinpictures, baden03
Duplicate Post	Version 3.2.4 by Enrico Battocchi
Email Address Encoder	Version 1.0.19 by Till Krüss
GDPR Cookie Consent Banner	Version 2.3.15 by termly
Image Widget	Version 4.4.7 by Modern Tribe, Inc.
Limit Login Attempts Reloaded	Version 2.11.0 by WPChef
Login Logo Editor	Version 1.3.1 by Scott DeLuzio
MetaSlider	Version 3.16.0 by Team Updraft
oik bwtrace	Version 3.0.0 by bobbingwide
Print, PDF & Email by PrintFriendly	Version 3.14.7 by Print, PDF, & Email by PrintFriendly
Q2W3 Fixed Widget	Version 5.1.9 by Thomas Maier, Max Bond
Real-Time Find and Replace	Version 3.9 by Marios Alexandrou
Schema Glue for Yoast & The Events Calendar by WP Munich	Version 1.1.1 by WP Munich
Simple Lightbox	Version 2.8.1 by Archetyped
Smush	Version 3.6.1 by WPMU DEV
TablePress	Version 1.11 by Tobias Bäthge
TablePress Extension: Responsive Tables	Version 1.7 by Tobias Bäthge
TablePress Extension: Row Filtering	Version 1.3 by Tobias Bäthge
The Events Calendar	Version 5.0.3.1 by Modern Tribe, Inc.
Uber Grid	Version 2.1.2 by Nikolay Karev
Ultimate FAQ	Version 1.8.31 by Etoile Web Design
User Submitted Posts	Version 20200320 by Jeff Starr
VFB Pro	Version 3.4.2 by Matthew Muro
VFB Pro - Payments	Version 2.1.4 by Matthew Muro
What The File	Version 1.5.4 by Never5
Widget Logic	Version 5.10.4 by WPChef
Wordfence Security	Version 7.4.6 by Wordfence
WordPress Importer	Version 0.7 by wordpressdotorg
WP-Optimize - Clean, Compress, Cache	Version 3.0.19 by David Anderson, Ruhani Rabin, Team Updraft
WP Image Zoom	Version 1.40 by SilkyPress
WP Mail SMTP	Version 1.9.0 by WPForms
WP Security Audit Log	Version 4.0.2 by WP White Security
WP Simple Paypal Shopping cart	Version 4.4.9 by Tips and Tricks HQ, Ruhul Amin, mra13
WP Sitemap Page	Version 1.6.2 by Tony Archambeau
WP Theme Tweaks	Version 0.1.0 by Andy Fragen
WP User Avatars	Version 1.4.0 by John James Jacoby
Yoast SEO	Version 13.4.1 by Team Yoast
Yoast SEO: Search index purge	Version 1.1.0 by Team Yoast

**Comment by AndrewMLeonard** [comment]
I forgot to say:
it goes wrong when I use the "Crop image to fill entire column" setting

**Comment by archetyped** [comment]
Hi, please provide a link that shows what the page should look like.  Also, please add a title (following "[Support]") to this ticket that briefly describes your issue.

Thanks.

**Comment by AndrewMLeonard** [comment]
There should be one image and one bit of text
There is a white line which should not be there and the image is sort of split in 2
Also only the left part of the image triggers the lightbox
This is what it looks like in the block editor
![block](https://user-images.githubusercontent.com/61053640/78413019-879bab80-760d-11ea-9309-e6cf18837a0e.jpg)

**Comment by archetyped** [comment]
Thank you for the additional information.  The issue you describe appears to be related to the theme, not SLB (it occurs regardless of whether SLB is activated or not).  The issue also does not appear with other themes.

Contacting the theme's developer to resolve the issue is recommended.

**Comment by AndrewMLeonard** [comment]
I agree with your diagnosis and apologise for troubling you
My theme is 2014
How do I contact the theme developers?

**Comment by archetyped** [comment]
> How do I contact the theme developers?

Click on Support link on [Twenty-Fourteen's official page](https://wordpress.org/themes/twentyfourteen/).

**Comment by AndrewMLeonard** [comment]
I thank you
