### ISSUE TITLE
[Support] PHP count() error

### ISSUE THREAD

**Issue by andreascarfo** [archetyped/simple-lightbox#787]
## Description of Problem
 Warning: count(): Parameter must be an array or an object that implements Countable in /home/___/public_html/wp-content/plugins/simple-lightbox/includes/class.utilities.php on line 1411

## Details

* URL of Page exhibiting problem: 
Some page on the backend

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Firefox, Chrome

* Version of SLB Installed: 
* Other plugins installed:
THIS IS A PROBLEM!

Akismet Anti-Spam
Animate It!
Block Specific Plugin Updates
Classic Editor
Collapse-O-Matic
Contact Form 7
Contact Form 7 Conditional Fields
Cost Calculator Contact Form 7
Featured Video Plus
Galleria
Google Analytics
Google XML Sitemaps
HTML Editor Syntax Highlighter
Jetpack by WordPress.com
Livemesh SiteOrigin Widgets
LoginPress - Customizing the WordPress Login
Manual Image Crop
Open Graphite
Page Builder by SiteOrigin
Permalink Manager Lite
Post Grid by PickPlugins
Post Thumbnail Editor
Redirection
Regenerate Thumbnails
Send PDF for Contact Form 7
SG Optimizer
Simple Lightbox
SiteOrigin Widgets Bundle
Sydney Toolbox
WP Construction Mode
WP Customer Area
Yoast SEO

**Comment by archetyped** [comment]
Hi, you did not include the version of SLB you're using, but it sounds like you are using an old version.

Updating to the latest version of SLB should fix your issue.

Please post an update with all necessary details (including version of SLB you are using) if you are still experiencing this issue after updating SLB and I would be glad to reopen this ticket and take another look.

**Comment by andreascarfo** [comment]
Sorry,
I forgot the version.
It's 2.6.0
