### ISSUE TITLE
[Support] The image #% curr% couldn't be loaded

### ISSUE THREAD

**Issue by Torgut** [archetyped/simple-lightbox#788]
## Description of Problem

When a user closes the slideshow, a layer stays active with a message saying something like "The image #% curr% couldn't be loaded". 

## Details

* URL of Page exhibiting problem: 
http://www.cruzamundos.com/fotoexposicao-cuba/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
Chrome

* Version of SLB Installed: 
Version 2.8.1 

* Other plugins installed:

**Comment by archetyped** [comment]
Hi, that error is coming from an additional lightbox plugin (Magnific Popup) that is active on your site.  Running multiple lightbox plugins simultaneously is not recommended as they generally react to the same triggers (e.g. clicking an image link) and can result in behavior such as this.

Removing or disabling the other lightbox plugin is recommended.  The lightbox is mostly likely added by the current theme, or a different plugin.  You can use [this tutorial on identifying plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) to help you find the specific plugin/theme that is loading the additional lightbox on your site.

**Comment by Torgut** [comment]
Super! Thanks! I will look into it right away :-)
