### ISSUE TITLE
does this not work with Blocks?

### ISSUE THREAD

**Issue by bournedead** [archetyped/simple-lightbox#789]
## Description of Problem

It looks like the plug-in Simple Lightbox is maintained but does it work with Gutenberg? I installed and see the Settings for Lightbox but no way to integrate into Page or Post using blocks, although it does seem to add slideshow effect to default WP galleriess.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB is compatible with posts/pages created with the blocks editor or the classic editor.  If you are still experiencing an issue, please update your original post to include the information necessary to evaluate your issue, and I would be glad to take a look.

Thanks.

**Comment by bournedead** [comment]
Hi. So maybe I don't understand how SLB works. Is there not a way to insert a gallery within a Page, Post, or Widget? If so, I don't mind that but would like to modify styles.

I see Lightbox Settings but the controls I need are not there like fonts, sizes, etc. Should I modify the plug-in's css?

I only see the Advanced CSS field but not sure howto use. I have tried .blocks-gallery-item__caption{display:none;} and figcaption{display:none;} to get rid of captions on top of images but doesn't seem to work. 

http://modifiedarts.org/lightbox-testing/
Using Version 2.8.1
Chrome
using about 8 plugins but nothing related to slideshows or images except "Regenerate Thumbnails" (deactivated)

Thank you!

**Comment by archetyped** [comment]
SLB works with WordPress' native image links and galleries, which means the lightbox is displayed on existing posts/pages without any modification.

SLB's focus is on the lightbox, so it does not make any changes to the appearance of the images/galleries on the page.  Your site's theme is primarily in control of the styling of those elements.

The lightbox's appearance is controlled by the theme set in SLB's settings.  A custom theme gives you full control over the lightbox's appearance.  See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for details on creating a custom theme.

I'm closing this ticket as SLB appears to be functioning properly at the link you provided.  Please post additional details if you are still experiencing an issue, and I would be glad to reopen this ticket and take another look.
