### ISSUE TITLE
[Request] Can the images in lightbox be bigger-fill the screen

### ISSUE THREAD

**Issue by pgb116** [archetyped/simple-lightbox#790]
## Description of feature

Make the images in lightbox bigger - fill the screen

## This feature would be used to

This feature would be used to make the image in lightbox fill the screen

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above
Jump for joy

**Comment by archetyped** [comment]
Hi, SLB will not enlarge images beyond their original size, as that would degrade image quality.

If an image is larger than the screen size, you can control whether it is displayed at full size, or automatically resized to fit in the browser window using the "**Resize lightbox to fit in window**" option in SLB's settings.

If you are requesting something other than described here, please provide additional details, and I would be glad  to reopen this ticket and take another look.

Thanks.

**Comment by pgb116** [comment]
Thank you. I have an image size  2560 × 1916, 658KB in the media files. If I add it to a full width page at full size it fits the whole page. If I click on it, the light box appears with a smaller image, it doesn't fit the page. With apologies, have I missed something? I think I have. I do use the "Resize lightbox to fit window" option.

**Comment by archetyped** [comment]
Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by pgb116** [comment]
Hello, I'm very sorry to have troubled you with this. I've realised I'm viewing on a Macbook Pro 13 inch screen, although the lightbox doesn't fill the screen, it is a good size. I'm happy with it. I am just experimenting with your excellent plugin before publishing my site. I will publish soon.
It won't be necessary to provide a link. 
Thank you once again.

**Comment by archetyped** [comment]
Thanks for the update.  Glad to hear it's working well for you :)
