### ISSUE TITLE
[Support] No support for Wordpress 5.2.5

### ISSUE THREAD

**Issue by SanusiD** [archetyped/simple-lightbox#791]
## Description of Problem

I'm currently trying to use this plugin and it doesn't work on wordpress 5.2.5. Is there a version of this that is compatible with it?

## Details

* URL of Page exhibiting problem: on my localhost
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All browsers
* Version of SLB Installed: 2.8.1
* Other plugins installed: none

**Comment by archetyped** [comment]
Hi, SLB currently requires WordPress v5.3+, but you can check [past releases](https://github.com/archetyped/simple-lightbox/releases) for a version compatible with an old version of WordPress.

However, note that using older versions of WordPress or SLB are not recommended as you will be missing out on updates that may affect functionality, performance, security, etc.
