### ISSUE TITLE
WooCommerce Add-on doesn't work

### ISSUE THREAD

**Issue by luminously7** [archetyped/simple-lightbox#792]
## Description of Problem
Simple Lightbox: WooCommerce Add-on doesn't work!

Woocommerce Version 4.0.1
If this plugin is not set-up to work with Woocommerce 3+ you should not be selling it.
No one is running Woocommerce 2+

I'd like a refund asap.

Thank you

**Comment by archetyped** [comment]
Hi, the requirements are clearly listed on the add-on's page, and while you may not be using a specific version, there are many others who are using this add-on with a compatible version of WooCommerce.

Please send an email to support@archetyped.com from the email used to purchase the add-on to request a refund.

Thank you.
