### ISSUE TITLE
Display image caption in Simple Lightbox 

### ISSUE THREAD

**Issue by annvb53** [archetyped/simple-lightbox#794]
## Description of Problem

Can't get SLB caption to show an image's caption (as manually added to image in media library) instead of image's title.

## Details

I've installed Simple Light Box and it's working correctly - but each image in a slideshow displays the image title *as assigned to the image in the media library), which I don't want. I want to display the image's caption (the caption I've manually added to the image in the media library) - or, if there is no caption, then to display nothing at all. How do I do this? Currently, I've written a bit of css code to prevent the SLB caption from showing at all until this is resolved. Thank you.

* URL of Page exhibiting problem: https://cinergyconstruction.com/acoustic-plasters/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: 2.8.1
* Other plugins installed: Several

**Comment by archetyped** [comment]
Hi, the title area of the lightbox displays content based on title precedence (see [documentation for more details](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence)) to ensure a descriptive title is displayed for all items in the lightbox.

Future updates may introduce additional template tags for more granular control over the content displayed in the lightbox's title area.
