### ISSUE TITLE
[Support] Oh god please help SUPER tight deadline

### ISSUE THREAD

**Issue by pushthepixel** [archetyped/simple-lightbox#796]
## Description of Problem
Hey guys, just straight up can't get it to work no matter what I do. I need this badly to work with a gallery too, any chance of that? If this works Im buying the video version too. 

The site is here: . :  https://pushthepixel.ca/clients/frank
Login with : frank  password is Frankensite 2020

Newest WP, SLB 2.8.1, I've disabled all other plugins, fails on all browsers. 

Please help please please I'm fully panicking :D

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, as per [SLB's Requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements):

> "Basic" HTTP authentication (e.g. requiring a username/password to access the entire site) can block the loading of files and prevent SLB from functioning properly.

Disabling HTTP authentication will allow SLB to function normally.

**Comment by pushthepixel** [comment]
HOLY SHITBALLS IT WORKED. 

I love you man. I'm gonna go buy 3 copies of the video license now, just because.

**Comment by pushthepixel** [comment]
Your site only let me buy 2 copies lol. Thats ok though, you're on my "holy hell these guys are awesome" list and I'll use you for every project I do.

**Comment by archetyped** [comment]
Kind of a long name, but sounds like a cool list to be on nonetheless! 👍
