### ISSUE TITLE
[Support] Lightbox does not work in classic editor

### ISSUE THREAD

**Issue by kudanoff** [archetyped/simple-lightbox#800]
## Description of Problem

In a modern editor, Gutenberg uploading a picture, selecting the "media file" in the link selector, the picture opens on the site in a lightbox, and if you download it in a classic editor, it doesn’t work.

## Details

* URL of Page exhibiting problem: https://mb05.ru/event/antikrizisnyj-intensiv-ot-msp-banka/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: All
* Other plugins installed: Webcraftic Clearfy, Yoast Seo, EventON, EventON - Full cal, Simple Custom Post Order, TinyMCE Advanced, Loco Translate, UpdraftPlus - Backup/Restore, Breadcrumb NavXT, Advanced Custom Fields, 301 Redirects, Contacts Form 7, Classic Editor, TinyPNG.

I tried to disable some of them, it still does not work.

URL on which the lightbox works: https://mb05.ru/gospoderzhka/imushhestvennaja-podderzhka/

**Comment by archetyped** [comment]
Hi, SLB fully supports the classic editor, however the examples you provided were two different post types (an event post and a page), so it is possible that the theme template used for the event post does not meet [SLB's theme requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements#theme).

You can test this by temporarily switching to a default WordPress theme (e.g. [Twenty Twenty](https://wordpress.org/themes/twentytwenty/), etc.).  If SLB functions normally on both pages using a default theme, then the theme template for events needs to be updated to meet SLB's theme requirements.

If SLB does not function on the event post when switching to a default theme, please provide the following:

1. The code for the theme template used for the event post and I will take a look.
2. Screenshot of SLB's admin settings screen showing all options.

Thanks.

**Comment by kudanoff** [comment]
![Настройки лайтбокса](https://user-images.githubusercontent.com/37755184/81732552-57abb780-9499-11ea-8475-487ae5b1873e.png)

The problem persists with the theme twenty twenty.

I don’t know how to show the template code, because it is the EventON plugin which is responsible for the events. I decided to check the lightbox in the news, it also works there, it does not work only in events

**Comment by archetyped** [comment]
Hi, thank you for the additional details.  It appears that there may be an issue with the way the event plugin outputs its content.

Please provide a link to the EventON plugin and I will take a look.

**Comment by kudanoff** [comment]
[EventON link](https://codecanyon.net/item/eventon-wordpress-event-calendar-plugin/1211017)

Thanks for trying to help! I am very happy with such technical support.

True, this plugin is paid and if you suddenly need it, then I can provide a cracked version, they are also on the Internet.

Sorry for the English, I translate the translator from Russian))

**Comment by archetyped** [comment]
EventON's developer has been contacted.  However, note that as a paid plugin, access to the plugin for further investigation is not guaranteed.

**Comment by kudanoff** [comment]
I don’t quite understand you. In general, I’ll say that we have a paid plugin, or rather bought

**Comment by archetyped** [comment]
Unfortunately, the developer of EventON did not respond to any requests, so the issue cannot be investigated further from SLB's end.

I would recommend contacting EventON's developer to see if they can provide any support for your issue.
