### ISSUE TITLE
Images breaking the front page

### ISSUE THREAD

**Issue by neiljames** [archetyped/simple-lightbox#801]
## Description of Problem
An issue with the images breaking the centre block of a 3 block column.
The image gallery is using the simple lightbox plugin to display fullsize when clicked on the front end.
The images in the gallery are set to thumbnail 150×150.
Sometimes but not always the front end is displaying full size images therefore when there is a 4/5 image gallery this completely breaks my site because 400/500 pixel wide images fill the page and the outer blocks display all the text down a thin single character line.

I have given one url but this issuse does not happen all the time you might need to check more than this to find it.
## Details
* URL of Page exhibiting problem: https://mygolfdays.com/golf-courses-in-scotland/midlothian-golf/dalmahoy-golf-and-country-club/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Browsers are Firefoz/Chrome/Chrome incognito
* Version of SLB Installed: SLB 2.8.1
* Other plugins installed: Hummingbird,Sitekit,Yoast,BBQ,Antispambee, WP Cerber

**Comment by archetyped** [comment]
Hi, the issue you describe could not be reproduced despite multiple tests.

However, SLB does not affect the layout of elements on the page.   SLB only controls the display of a lightbox when a valid link is clicked, so your issue may be related to the active theme or another plugin.

If you are still experiencing this issue and have confirmed that SLB is causing it, please provide more details on reproducing it, and I would be glad to reopen this ticket and take another look.

Thanks.
