### ISSUE TITLE
Lightbox plugin is not working on Woocommerce product page

### ISSUE THREAD

**Issue by umairayub151** [archetyped/simple-lightbox#803]
## Description of Problem

I have a E-commerce website where I installed the lightbox plugin. The plugin is working on post or on main navigation of page like Men's Size Chart, but this plugin is not working on product detail page where I put the link below prices Men's Size Chart | Kid's Size Chart. Please guide me how we can resolve this issue.

## Details

* URL of Page exhibiting problem: https://www.fazalsons.com.pk/product/blue-cream-3d-print-waistcoat/ 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): On All Browesers
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, support for WooCommerce content areas is added by SLB's [WooCommerce Extension](https://archetyped.com/lab/slb-woocommerce-beta/).

**Comment by umairayub151** [comment]
> Hi, support for WooCommerce content areas is added by SLB's [WooCommerce Extension](https://archetyped.com/lab/slb-woocommerce-beta/).

Please tell me issue in detail why Lightbox plugin is not working in product details section.

https://www.fazalsons.com.pk/shop/mens-wear/traditional/waist-coat/blue-cream-3d-print-waistcoat/

Men's Size Chart.

**Comment by archetyped** [comment]
Hi, is SLB's WooCommerce Extension installed and activated on your site?  As previously-noted, this extension is necessary to use SLB on WooCommerce-specific content areas such as a product's short description.

If so, please provide the necessary information that was omitted from your original post and I would be glad to take a closer look:

* Version of SLB Installed: 
* WooCommerce Extension version: 
* Other plugins installed:

**Comment by umairayub151** [comment]
Hi, Yes obviously SLB is installed and activated on my website. 

SLB Version - Version 2.8.1
WooCommerce Extension Version - Version 4.1.1

Other Plugins
All-in-One WP Migration
Contact Form 7
KingComposer
LiteSpeed Cache
Redux Framework
Regenerate Thumbnails
Slider Revolution
Variation Swatcher for WooCommerce
WooCommerce
YITH WooCommerce Wishlist

**Comment by archetyped** [comment]
> Hi, Yes obviously SLB is installed and activated on my website.
>
> SLB Version - Version 2.8.1
> WooCommerce Extension Version - Version 4.1.1

Please note that my previous reply asked whether SLB's WooCommerce **Extension** was installed and activated.  It also appears that you have provided the version information for the main WooCommerce plugin you are using, not the version of SLB's WooCommerce **Extension**.

Your list of other plugins does not include SLB's WooCommerce **Extension**.  The extension was linked to in my first reply.  As previously noted, this extension is required to use SLB on WooCommerce product posts.

Please provide the version of SLB's WooCommerce **Extension** that you have installed on your site so that your issue can be fully evaluated.

Thank you.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
