### ISSUE TITLE
Simple lightbox now loading just a white page

### ISSUE THREAD

**Issue by irishkmcd** [archetyped/simple-lightbox#804]
## Simple lightbox now loading just a white page

I am having an issue with the lightbox loading just a white page. I restarted the plugin and checked to make sure that the url that I was opening in the lightbox was the same and it is.
## Details

* URL of Page exhibiting problem: https://www.barstooldesigns.com/product/amisco-aaron-non-swivel-with-cushion/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: Version 2.8.1 
* Other plugins installed: Lots but everything worked fine until yeasterday

**Comment by archetyped** [comment]
Hi, your site appears to be loading multiple lightboxes simultaneously.  Loading multiple lightboxes is not recommended as they can cause unexpected behavior.

Removing/disabling the additional lightbox should allow SLB to function normally.

If you are not sure how the additional lightbox is being added, you can [follow these instructions on identifying plugin/theme conflicts](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) to identify the plugin/theme that is adding the extra lightbox and disable it.

If you are still experiencing an issue after removing the extra lightbox, please provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket take another look.
