### ISSUE TITLE
SLB is not working in new posts

### ISSUE THREAD

**Issue by shak3zz** [archetyped/simple-lightbox#805]
## Description of Problem
In one of my previous posts SLB worked without any problems:
https://besser-lernen.blog/apps-tools/kostenlose-office-tools-mit-google-drive/

But it just won't work in my new post:
https://besser-lernen.blog/apps-tools/4-karteikarten-apps-mit-denen-du-ueberall-lernen-kannst/

I cleared my cache and also tried multiple browsers (latest versions of Edge, Chrome, Firefox) but the problem remains.

## Details

* URL of Page exhibiting problem: 
https://besser-lernen.blog/apps-tools/4-karteikarten-apps-mit-denen-du-ueberall-lernen-kannst/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
latest versions of Edge, Chrome, Firefox

* Version of SLB Installed:
2.8.1
 
* Other plugins installed: 
Accelerated Mobile Pages
Autoptimize
Content Views
Cookie Notice
Custom Twitter Feeds
GA Google Analytics
LuckyWP Table of Contents
Native Lazyload
PWA for WP
Really Simple SSL
Schema & Structured Data for WP & AMP
Shariff Wrapper
Theme Editor
WordPress Popular Posts
WP-Appbox
WPForms Lite
Yoast SEO

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.
