### ISSUE TITLE
More images in any given gallery

### ISSUE THREAD

**Issue by wadesteele** [archetyped/simple-lightbox#806]
Your plugin works great! I am having an issue where I create multiple galleries on a single page and each gallery displays images from the other galleries on the page. When I select the link to open the gallery in Simple Lightbox, the correct images display first. Then the images from the remainder of the other galleries will show. If I select a different gallery, the correct images will display but then at the end of the show it displays the other galleries' images. Here is the code I am using in the Text Editor:

```html
<a href="https://www.kid.org/wp-content/uploads/2020/05/87370310_3106875819357298_5685248016441671680_o.jpg"><img class="aligncenter size-full" src="https://www.kid.org/wp-content/uploads/2020/05/87370310_3106875819357298_5685248016441671680_o.jpg" alt="" width="1189" height="713" /></a>
<div style="display: none;"><a title="Slide 2" href="https://www.kid.org/wp-content/uploads/2020/05/91592784_3203469403031272_2840124472546033664_o.jpg">Slide 2</a>
<a title="Slide 3" href="https://www.kid.org/wp-content/uploads/2020/05/92132170_3203469383031274_5936051987446497280_o.jpg">Slide 3</a>
<a title="Slide 4" href="https://www.kid.org/wp-content/uploads/2020/05/92394311_3203469359697943_9174422487855792128_o.jpg">Slide 4</a>
<a title="Slide 5" href="https://www.kid.org/wp-content/uploads/2020/05/92604841_3203469313031281_4948582381247266816_n.jpg">Slide 5</a>
<a title="Slide 6" href="https://www.kid.org/wp-content/uploads/2020/05/87389632_3106875886023958_1163308028313731072_o.jpg">Slide 5</a>
<a title="Slide 7" href="https://www.kid.org/wp-content/uploads/2020/05/87667599_3106875829357297_916699295464292352_o.jpg">Slide 5</a></div>
```
This gallery had 6 photos but it displays a total of 13 on the page.

Here is the page where they reside:
https://www.kid.org/kid-capital-projects/

I appreciate any help that you are able to offer.

Thank you,
Wade

**Comment by archetyped** [comment]
Hi, SLB has a setting to automatically group native [WordPress galleries](https://wordpress.org/support/article/the-wordpress-gallery/).

However, a list of links as in your example is not technically a "gallery" to WordPress.  For such "manual galleries", you can use the `[slb_group]` shortcode to group links on the page in any way desired.  See [SLB's shortcode documentation](https://wordpress.org/support/article/the-wordpress-gallery/) for more details.
