### ISSUE TITLE
Disable on mobile

### ISSUE THREAD

**Issue by OceanWind** [archetyped/simple-lightbox#809]
## Description of Problem
I would like to disable Simple Lightbox on mobile. What's the easiest way to do that?
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: (not yet public)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): (all)
* Version of SLB Installed: latest
* Other plugins installed: several

Thank you for taking the time to get back to me!

Bill

**Comment by archetyped** [comment]
Hi, SLB works natively on all platforms. Disabling on specific device types is not supported.
