### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SynergyCraft** [archetyped/simple-lightbox#810]
## Plugin Not Working
I just purchased and installed Simple Lightbox: WooCommerce Extension. I changed themes and deactivated plugins the lightbox is not working on my woocommerce products. Please help and can I please get a refund if we cannot get it to work?

Thank you

* URL of Page exhibiting problem: https://synergycraftstudio.com/decal-catalog/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: Simple Lightbox: WooCommerce Extension
* Other plugins installed:

**Comment by archetyped** [comment]
Duplicate of archetyped/simple-lightbox-extensions#82
