### ISSUE TITLE
Problem with metadata in gallery.

### ISSUE THREAD

**Issue by ommoran** [archetyped/simple-lightbox#811]
## Description of Problem

Metadata, specifically photo captions or photo descriptions (both are on each image) not displaying during slideshow.

## Details

* URL of Page exhibiting problem: https://ommoran.ca/2020/06/photo-gallery-running-in-stanely-park/ 
(or any of the galleries on that site)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome, Edge
* Version of SLB Installed: 2.8.1
* Other plugins installed: Advanced iFrame, Askimet, AMP, Bulk remove posts from category, external media, Health Check, Jetpack, Pexels, Social Icons Widget, WP Post Author

**Comment by archetyped** [comment]
Hi, the images at the link provided appear to be stored externally, and thus WordPress is not able to identify these files as part of the site's media library.

This may be related to Jetpack's CDN functionality.  You can check for this with the following steps:

1. Temporarily deactivate Jetpack.
2. Clear your browser's cache.
3. Fully refresh the link provided.
4. Check if captions/descriptions are displayed for images.

Please let me know what you find after testing the site with Jetpack disabled.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide an update and I would be glad to reopen the ticket and take another look.
