### ISSUE TITLE
Simple Lightbox Stopped working

### ISSUE THREAD

**Issue by JSDopefish** [archetyped/simple-lightbox#812]
## Description of Problem

Description of the issue - The problem I'm having is Simple Lighbox stopped working.  When I click on an image it just goes full screen.  I've been using this plugin for years on my blog, and never was a problem until now.  There was one major change to my site - I went from http to https, but I don't believe that alone would cause the problem.  Other than that, I'm unclear what's changed as I haven't added anything new to my WP install of late.

## Details

1) URL of Page exhibiting the issue - https://joesiegler.blog/2020/01/die-hard/ - although any of my pages will, it's not just one of them.  I picked that one randomly.

2) Version of SLB installed - 2.8.1

3) Other plugins installed.  See below, there's several.  However, this same list of plugins has been there all along, nothing's new, unless it's an update to one of them causing a problem.

4) Browser(s) with issue (Firefox, Chrome, etc.) - all of the ones I've tried do the same thing.  Safari, Chrome, Firefox, MS Edge..

Plugin List:

Akismet
Backupbuddy
Classic Editor
Code Embed
Contact Form 7
Display PHP Version
Display Posts
Insert Headers and Footers
iThemes Security Pro
Page Links To
PayPal Donations
Simple Lightbox
Widget Logic
WP Super Cache
WP TFeed
WP Word Count
WP-Optimize
Youtube Embed

**Comment by archetyped** [comment]
Hi, it appears that cURL is not enabled and/or properly configured for your site.  This may or may be related to the HTTP to HTTPS change, depending on how the migration to HTTPS was performed (e.g. updated server configuration may have affected cURL functionality).

Please see SLB's documentation for [more information on cURL support](https://github.com/archetyped/simple-lightbox/wiki/Requirements#curl-support).

**Comment by JSDopefish** [comment]
That's weird because another domain on the same server uses the same plugin, and it doesn't have the problem.  It too was changed to HTTPS on the same day, and it works.  cURL does appear to be installed.   Ah well.

https://www.rangerfans.com/2020/06/my-globe-life-field-tour/

**Comment by archetyped** [comment]
cURL configuration can be site-specific, which is why different sites on the same server can have different behavior.

The cURL error you noted may be related and contacting your host regarding the error is recommended.
