### ISSUE TITLE
duplicate lightboxes when using Simple Lightbox 

### ISSUE THREAD

**Issue by LesWilkins** [archetyped/simple-lightbox#815]
## Description of Problem

I'm using the Wordpress Divi theme. I'm using Simple Lightbox as I want the image 'description' to appear on the lightbox window, which the standard lightbox does not do. Simple Lightbox works as I wanted, but the standard lightbox also opens, overlaid on top of the Simple Lightbox, and both have to be closed independently. How can I use Simple Lightbox and disable the standard lightbox?

I can disable the lightbox with CSS, but I haven't worked out a way to prevent disabling Simple Lightbox as well.

URL dernolvalley.org but the site isn't live yet.
Happening in Firefox and Chrome
SLB 2.8.1
Plug-ins Divi Booster, Enhanced Media Library, Seed Pod 'coming soon'.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Unfortunately SLB does not have any control over other scripts running on your site.

It does look like [Divi has some options for disabling its built-in lightbox](https://divitheme.net/disable-lightbox-gallery/), but contacting the theme's developer is recommended if you want a more global solution for disabling the lightbox that the theme adds.
