### ISSUE TITLE
Not working on Internet Explorer 11

### ISSUE THREAD

**Issue by oncet** [archetyped/simple-lightbox#817]
## Description of Problem

SLB is not working on IE11.

## Details

When clicking a link to an image, the browser navigates to the image URL instead of opening SLB.

The console shows this error:

```
Object doesn't support property or method 'assign'
simple-lightbox.min.js (7,3307)
```

Tried adding a polyfill for [`Object.assign()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) but then I get:

```
Object doesn't support property or method 'from'
simple-lightbox.min.js (7,3373)
```

* URL of Page exhibiting problem: https://gurim.com.ar/product/bitacora-de-cuero/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Internet Explorer
* Version of SLB Installed: 2.1.5
* Other plugins installed: None.

**Comment by archetyped** [comment]
Hi, it appears that you are using a different plugin that may be using a similar name as none of the details in your ticket are applicable to Simple Lightbox (file names, version, etc.).

You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
