### ISSUE TITLE
Gallery in mobile with captions blocks Lightbox

### ISSUE THREAD

**Issue by theallister** [archetyped/simple-lightbox#818]
## Description of Problem

I noticed a problem with using Lightbox on mobile. It works perfectly fine with normal images and galleries where the separate images don't have captions, but when I add a caption to the images in the gallery, the overlay caption blocks the link that opens the Lightbox. This is not a problem in the desktop, and on tablet/iPad, the problem only arises on half of the image (the overlay is a gradient which covers the image completely on mobile but partly on tablet).
When I delete the element for the caption overlay, the problem is gone. Hence, I drew the conclusion that the issue is connected to the caption element.

## Details

* I do not have an URL to share as I am developing locally
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Chrome, Firefox
* Version of SLB Installed: 2.8.1
* Other plugins installed: Categories Images, Yoast SEO

**Comment by archetyped** [comment]
Hi, SLB does not have any control over the display of content (galleries, thumbnails, etc.) on the page itself.  SLB only controls the display of the lightbox.

I would recommend contacting the theme's developer or editing its HTML/CSS to be more accessible on mobile devices.
