### ISSUE TITLE
SLB not working

### ISSUE THREAD

**Issue by francisfustier** [archetyped/simple-lightbox#819]
## Description of Problem

Hi Team,
With WP 5.5 Simple Lightbox V.2.8.1 doesn't work anymore in my blogs:
https://www.navigation-mac.fr/
https://android-marine.fr

Regards
Francis

## Details

* URL of Page exhibiting problem: https://www.navigation-mac.fr/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 2.8.1
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, both sites have multiple JavaScript errors from other scripts on the page.  These errors stop other scripts (including SLB) from loading.

I would recommend opening your browser's developer console and reviewing the JavaScript errors.  You can also follow [these basic steps to identify conflicting plugins](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts) to determine what plugins/scripts are causing the issue.

Once the JS errors from the other scripts, SLB should function normally.  If you are still experiencing an issue after the other JS issues are resolved, please provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take another look.

Thanks.
