### ISSUE TITLE
Unable to "Add Media" to make a gallery

### ISSUE THREAD

**Issue by Pjwilko** [archetyped/simple-lightbox#822]
## Since WP 5.5 unable to add media to make a new gallery on 2 websites.
Click on "Add Media" and nothing happens. Can add new images via Media.

Unable to make a new slideshow of photos of recent events for both car clubs.

https://vvte.com.au/galleries/
New gallery added in July 202 before WP 5.5 update.

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details
https://hetnr-qld.com.au/galleries/
Old galleries OK. Had to fudge new one.

* Version of SLB Installed:  Version 2.8.1
* Other plugins installed: Many - one new one on one website has been disabled with no difference.

**Comment by archetyped** [comment]
Hi, SLB does not add any code to admin pages such as the page/post editors, so it does not appear that SLB is related to the issue you are experiencing.  Nonetheless, SLB has been tested in WP 5.5 and no issues with adding media or galleries were encountered.

You may be experiencing an issue with the current theme, or another plugin.  Here are some [instructions on identifying plugins causing issues](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts).  Once the problematic theme/plugin has been identified, reporting the issue to the developer is recommended.
