### ISSUE TITLE
Out of Square Lightbox Icons

### ISSUE THREAD

**Issue by juanvalerah** [archetyped/simple-lightbox#825]
## Description of Problem

I have a problem that when opening the images it opens the lightbox well but the icons such as full screen, zoom, share are shown as partially cut off. I don't know how to solve it. 

I leave a screenshot as a sample of the problem.

Thanks! hope you can help me

## Details

* URL of Page exhibiting problem: www.valhidesigners.com
* Browser(s) exhibiting problem: Explorer, Chrome, Safari
* Version of SLB Installed: Version 2.8.1

![Captura de pantalla 2020-08-31 a la(s) 17 11 42](https://user-images.githubusercontent.com/70546385/91774049-959a2c00-ebad-11ea-84d0-403c8490ef26.png)

**Comment by archetyped** [comment]
Hi, SLB does not appear to be installed and/or activated at the link you provided.  It appears that you are using a different lightbox script which may be added by the active theme or another plugin.  Running multiple lightbox scripts on the same site is not recommended as they may conflict with each other.

Check your theme and other plugins for lightbox functionality, and disable it to allow SLB to function properly.
