### ISSUE TITLE
Fail to change the fonts size of title

### ISSUE THREAD

**Issue by doggerms** [archetyped/simple-lightbox#826]
What is the right way to change the fonts size of the slide box title?
This is my blog site, please click the photo for opening the light box.
http://block09.net/croatia-2/
i would like to change the fonts size from the original to 18px
I had try to correct the css (themes/default/sass/style.scss)
at the appearance plugin page but it fails to affect the change.

//Title
--
148 | $title-size: 23px; <<<<<<<
149 |  
150 | .slb_data_title, .slb_group_status {
151 | font-family: 'Yanone Kaffeesatz', arial, sans-serif;
152 | font-size: $title-size;
153 | margin-right: .2em;
154 | display: inline-block;

**Comment by archetyped** [comment]
Hi, editing a plugin's files directly is not recommended as any future update to the plugin will overwrite your changes.

Instead, you can add CSS to your theme to modify the lightbox, or even better, you can create a custom lightbox theme with your custom styles.  Lightbox themes can be based off an existing theme, so you only need to add CSS to override specific styles to your custom theme.

See [SLB's Theme documentation for more details on customizing lightbox styles](https://github.com/archetyped/simple-lightbox/wiki/Themes).
