### ISSUE TITLE
[Request]: Add option to the link to the image when clicking on it

### ISSUE THREAD

**Issue by frot-io** [archetyped/simple-lightbox#829]
## Description of feature

I would like to open the link to the image in a new tab when clicking on the image inside the lightbox.

Currently when clicking on the image, either next or prev is clicked (as JS overlays).

## This feature would be used to

Be able to zoom into the image or download it.

## Implementation details

I already tried to implement this inside the plugin editor by adding a `<a href="{{item.src}}" target="_blank">` to `.slb_container > .slb_content` inside `layout.html` but it doesn't seem to work. As I have little to no experience in PHP, any help would be appreciated :)

## If you added this feature, I would:

a) Learn more about PHP *shudder*

**Comment by archetyped** [comment]
This request is functionally the same as #216, so I would recommend adding your vote to that request, as features are developed based on demand.
