### ISSUE TITLE
[Request]: Higher Resolution icons

### ISSUE THREAD

**Issue by ddegner** [archetyped/simple-lightbox#830]
## Description of feature

I love lightbox.  It fits perfectly into my photo portfolio site.

I would like the .png files used in the themes to be higher resolution.  I noticed on my hi-res screen that they appear blurry around the edges.

I was hoping to send you higher resolution icons to make the update easier but when I tried them on my site they just made the icons larger.

Probably the best answer is to use vector SVG icons.  They would be smaller file sizes and sharper.

## This feature would be used to

Polish the look of lightbox and reduce the size.

## If you added this feature, I would:

Continue to support the project with money and feedback.

**Comment by archetyped** [comment]
Updated themes are planned for a future update.  In the meantime, you can use any graphics in the lightbox with a custom theme.  See [SLB's Themes documentation for instructions on creating a custom theme](https://github.com/archetyped/simple-lightbox/wiki/Themes).
