### ISSUE TITLE
Request: Dynamic content in lightbox

### ISSUE THREAD

**Issue by lewtager** [archetyped/simple-lightbox#834]
## I'm looking for: a lightbox popup with ability to vary options by device and time of day:
    > Response options for mobile visitors weekdays during office hours:
         Call Us Now (button dials our office) / Enter Site (lightbox disappears)
    > Response options for mobile off-hours and all other devices all the time:
         Contact Us Now (a contact form) / Enter Site (lightbox disappears)
    Suggestions?

**Comment by archetyped** [comment]
Hi, SLB is primarily designed to display media such as images and videos in a lightbox when a link is clicked.

Buttons that dial phones is not planned for SLB.
