### ISSUE TITLE
Simple Lightbox not animating on my flywheel site

### ISSUE THREAD

**Issue by mhill260** [archetyped/simple-lightbox#836]
## Description of Problem

Simple Lightbox not animating on my flywheel site

## Details

https://hillustration.flywheelsites.com/

All browsers

It's a genesis theme, but I don't have a lot of extra plugins at the moment

**Comment by archetyped** [comment]
Hi, the site does not appear to be accessible and requires a login to view.  Please update this ticket when the site is accessible.

Also note that "Basic" HTTP authentication (currently used at the provided link) can block the loading of files and prevent SLB from functioning properly.  See [SLB's Requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements) for more details.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
