### ISSUE TITLE
Some captions and descriptions not appearing

### ISSUE THREAD

**Issue by tslarkin** [archetyped/simple-lightbox#837]
## Description of Problem

A small number of images do not display their titles or descriptions in the lightbox, even though title, caption, and description are defined for the image in the media library.

## Details

* https://soagannex.art/december-juried-show/
Click on the third image to activate the lightbox containing a group of three items, which are three uploads of the same image file. None of the images show any metadata beyond the group description, even though appropriate metadata are defined. Examination of the HTML produced show empty spans where the metadata should appear. The other two images on the page activate lightbox images that show metadata correctly.
* This happens in Mac Chrome, Safari, and Firefox: 
* Version 2.8.1: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, SLB does not appear to be installed and/or activated at the link you provided.  Please provide an updated link where SLB is activated, and I would be glad to take another look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
