### ISSUE TITLE
[Request]: Lightbox slideshow to be confined to only the selected gallery when there are multiple galleries on a page

### ISSUE THREAD

**Issue by LesWilkins** [archetyped/simple-lightbox#838]
## Description of feature
Lightbox slideshow to be confined to only the selected gallery when there are multiple galleries on a page. Currently if a slideshow is started in one gallery, advancing to the next picture continues into the next gallery when there is more than one gallery on a page. It should be confined to only the gallery in which the starting image was selected.

## This feature would be used to

prevent a user from assuming that the picture being viewed belongs to the category of the initial gallery, when they have unknowingly continued into the next gallery of a different media category.

## If you added this feature, I would:

a) Traddle my thrums

**Comment by archetyped** [comment]
Hi, are you referring to galleries created in the block editor?  If so, please refer to [the existing ticket regarding grouping of gallery blocks](#802).

Grouping is already supported for galleries created using the classic editor by enabling SLB's "Group gallery items separately" option.  If you have enabled this option and classic galleries are not being being grouped, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
