### ISSUE TITLE
Lightbox is not showing at all

### ISSUE THREAD

**Issue by tpuehri** [archetyped/simple-lightbox#842]
## Description of Problem

Lightbox is not showing at all

## Details

www.stempelwunderwelt.at/blog
All browsers
latest
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided that would be opened in the lightbox.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

If you are still experiencing an issue after adding image links to your page, please provide a link to a specific page that contains image links, and I would be glad to reopen this ticket and take another look.

Thanks.
