### ISSUE TITLE
[Request]: similar functionality in plugin

### ISSUE THREAD

**Issue by maddogtvdinners** [archetyped/simple-lightbox#843]
Hi, I'm looking for a gallery plugin that works like the one on this website:
https://www.aliceson.co.uk/photography
with image left and text right and a left/right button to move to the next image with text.
Do you have anything that does that?
Thanks.

**Comment by archetyped** [comment]
Hi, Simple Lightbox displays images on top of the page's content when an image link is clicked on the page.

Once displayed, the lightbox does allow navigation between multiple images (e.g. a gallery).

SLB's flexible theme system also allows full customization of the lightbox, giving you control over its appearance and layout.

For more information, please refer to [Simple Lightbox's home page](https://archetyped.com/tools/simple-lightbox/).

Thanks.
