### ISSUE TITLE
Simple Lightbox not working with „Enable jQuery Migrate Helper 1.2.0“. Help please…

### ISSUE THREAD

**Issue by GroenheitWeigel** [archetyped/simple-lightbox#844]
## Description of Problem

Simple Lightbox not working with „Enable jQuery Migrate Helper 1.2.0“. 
I now have made a Rollback of "Enable jQuery Migrate Helper" to 1.1.0, then SLB is working again....

## Details

* URL of Page exhibiting problem: https://www.groenheit-weigel.de/stausaecke/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, IE, EDGE
* Version of SLB Installed: 2.8.1
* Other plugins installed: Enable jQuery Migrate Helper 1.2.0

**Comment by archetyped** [comment]
Hi, SLB does not use or require the "Enable jQuery Migrate Helper" plugin, but the plugin was tested and SLB functioned normally when "Enable jQuery Migrate Helper" 1.2.0 was installed and activated.

This may indicate that the "Enable jQuery Migrate Helper" plugin is causing a JavaScript error (possibly with another plugin).  JavaScript errors can prevent other scripts (including SLB) from running.

Checking your browser's developer console for errors may indicate what script is triggering an error.  Once the error is resolved, SLB will be able to run again.

If you can provide a link to a page that exhibits the issue you are experiencing, I would be glad to take a look.

**Comment by GroenheitWeigel** [comment]
I have updated now to WP 5.6. 

"Enable jQuery Migrate Helper" don't work anymore and is now .deactivated. 

SLB is still not working. It opens the pictures in a new window: 

https://www.groenheit-weigel.de/stausaecke/

This is a sample link to our page. Same issues on other pages.

**Comment by GroenheitWeigel** [comment]
SOLVED: 
Urgent: WordPress 5.6 change requires Autoptimize settings change

WordPress 5.6 changes the filename of jQuery core. If you’re using Autoptimize and you have jQuery excluded (which is default) you will want to update your JS optimization exclusion list from _**_js/jquery/jquery.js to js/jquery/jquery.min.js.__**

**Comment by archetyped** [comment]
Glad to hear your issue was resolved.
