### ISSUE TITLE
Won't work with my website

### ISSUE THREAD

**Issue by RalphTheCreator** [archetyped/simple-lightbox#845]
## Description of Problem
Hi,

I installed and activated the plugin but it won't work. When I try to click a picture on that page nothing happens. 
I deactivated the functionality on home and posts. Also I deactivated the "Start Slideshow Automatically" & "Loop" functionality.

Hope you can help me with my problem!

Best regards,
Raphael

## Details

* Tested on this page https://bite.guitars/bw/
* Chrome Version 87.0.4280.88 (Offizieller Build) (x86_64)
* Version of SLB Installed: 2.8.1
Theme: Ocean WP 1.0
* Other plugins installed: 

Visual Product Configurator BITE Skin |   | by – 1.0
-- | -- | --
Admin Columns Pro - WooCommerce |   | by Admin Columns – 3.3.7
Admin Columns Pro |   | by AdminColumns.com – 4.7.2
Admin Menu Editor |   | by Janis Elsts – 1.8.8
Advanced Custom Fields PRO |   | by Elliot Condon – 5.7.5
The SEO Framework |   | by The SEO Framework Team – 4.0.7
Beaver Builder Plugin (Pro Version) |   | by The Beaver Builder Team – 2.3.1.1
Beaver Themer |   | by The Beaver Builder Team – 1.2.1.1
Ultimate Addons for Beaver Builder |   | by Brainstorm Force – 1.13.2
PowerPack for Beaver Builder |   | by IdeaBox Creations – 2.6.8.5
Complianz \| GDPR/CCPA Cookie Consent |   | by Really Simple Plugins – 4.7.7
Duplicate Post |   | by Enrico Battocchi – 3.2.2
Email Auto BCC |   | by Toast Code – 1.0
Filenames to latin |   | by webvitaly – 2.6
Fr Custom Payment Gateway Icon for WooCommerce |   | by Fahri Rusliyadi – 1.0.2 – Not tested with the active version of WooCommerce
Health Check & Troubleshooting |   | by The WordPress.org community – 1.4.4
Imsanity |   | by Exactly WWW – 2.4.2
iThemes Security Pro |   | by iThemes – 6.0.2
Kadence WooCommerce Email Designer |   | by Kadence Themes – 1.2.1
Ninja Forms |   | by The WP Ninjas – 3.4.3
Ocean Extra |   | by OceanWP – 1.5.3
Ocean Sticky Header |   | by OceanWP – 1.1.6
Official Facebook Pixel |   | by Facebook – 2.0.1
Password Protected |   | by Ben Huson – 2.2.3
PDF Embedder |   | by Lever Technology LLC – 4.6
PageSpeed Ninja |   | by PageSpeed Ninja – 0.9.38
Really Simple SSL |   | by Rogier Lankhorst, Mark Wolters – 3.1.3
Redirection |   | by John Godley – 3.7.3
Simple Lightbox |   | by Archetyped – 2.8.1
Category Order and Taxonomy Terms Order |   | by Nsp-Code – 1.5.7.3
Compress JPEG & PNG images |   | by TinyPNG – 3.2.0
TinyMCE Advanced |   | by Andrew Ozz – 5.3.0
UpdraftPlus - Backup/Restore |   | by UpdraftPlus.Com, DavidAnderson – 2.16.8.24
User Role Editor |   | by Vladimir Garagulya – 4.50.1
Visual Products Configurator |   | by ORION – 5.6.6
Visual Product Configurator Custom Text Add On |   | by Orion – 2.2.3
MODIFICATED Visual Product Configurator Upload Image |   | by ORION – 9.2.1.2
Visual Products Configuration PDF Download Share Mail Addon |   | by Webartisan – 1.0.0
WebP Express |   | by Bjørn Rosell – 0.14.21
Woo Discount Rules PRO 2.0 |   | by Flycart Technologies LLP – 2.3.2
Woo Discount Rules |   | by Flycart Technologies LLP – 2.3.2
Preview E-mails for WooCommerce |   | by Digamber Pradhan – 1.5.1
WooCommerce Sales Report By Country |   | by zorem – 1.3 – Not tested with the active version of WooCommerce
WooCommerce Variation Swatches |   | by Emran Ahmed – 1.0.53 – Not tested with the active version of WooCommerce
WooCommerce Category Accordion |   | by TechieResource – 2.0 – Not tested with the active version of WooCommerce
WooCommerce Deposits |   | by Webtomizer – 2.5.39
Germanized for WooCommerce Pro |   | by Vendidero – 2.0.15
Germanized for WooCommerce |   | by Vendidero – 3.1.4
heidelpay WooCommerce |   | by heidelpay – 1.6.0 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager |   | by SkyVerge – 1.9.4
WooCommerce PDF Invoices & Packing Slips |   | by Ewout Fernhout – 2.2.14
WooCommerce Table Rate Shipping |   | by WooCommerce – 3.0.14 – Not tested with the active version of WooCommerce
WooCommerce TM Extra Product Options |   | by themeComplete – 4.7.1 – Not tested with the active version of WooCommerce
WooCommerce |   | by Automattic – 3.6.2
WordPress Importer |   | by wordpressdotorg – 0.6.4
WP Disable |   | by optimisation.io - jody nesbitt – 1.5.21
WP Rocket |   | by WP Media – 3.2.6
WP Widget Clipboard |   | by OWL WP PLUGINS – 1.2.11
YoImages |   | by Sirulli – 0.1.8

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

If you are still experiencing an issue after adding image links to the page, please provide an updated link and I would be glad to reopen this ticket and take another look.
