### ISSUE TITLE
picture doesnot work

### ISSUE THREAD

**Issue by denisfromfrance** [archetyped/simple-lightbox#847]
## Description of Problem

hi i just install the plugin and i see when i click that the picture doesnot work, sorry for english. can you help me? thanks 
## Details

* URL of Page exhibiting problem: https://puzzleandco.com/animal-en-costume/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): chrome
* Version of SLB Installed: Version 2.8.1 
* Other plugins installed: woocommerce

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts in WordPress](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.
