### ISSUE TITLE
Перестал работать плагин Simple Lightbox

### ISSUE THREAD

**Issue by pismo66** [archetyped/simple-lightbox#848]
## Description of Problem

После обновления перестал работать плагин Simple Lightbox

## Details

Проверил на конфликт с другими плагинами, конфликтов не обнаружено

* URL of Page exhibiting problem:  https://xn--39-dlclzgfiicbq4ac.xn--p1ai/wp-content/uploads/2017/09/nasos-kotla-daewoo-1.jpg
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Microsoft Edge
* Version of SLB Installed: Версия 2.8.1
* Other plugins installed:

**Comment by pismo66** [comment]
Проблему решили! Она была в конфликте кода меню. Не работало меню сайта и не работал плагин, восстановили работоспособность меню и начал работать плагин.

**Comment by archetyped** [comment]
Glad to hear you found the other plugin causing the issue and resolved your issue :)
