### ISSUE TITLE
Request: Oxygen Builder Support

### ISSUE THREAD

**Issue by guy-leblond** [archetyped/simple-lightbox#849]
## Description of feature/request

To be able to use   SLB plugin with Oxygen builder 

## This feature would be used to

Oxygen is WordPress powerful visual editing plugin but it does not have the a easy way to add a light-box to an image. 
( excepted if all the images are include in the same gallery. 

If you need a built with oxygen with images I'll create one an give you access to it 

## If you added this feature, I would:
d

a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by guy-leblond** [comment]
Same request submitted to oxygen team: https://github.com/soflyy/oxygen-bugs-and-features/issues/1782

**Comment by archetyped** [comment]
Unfortunately, this is not something that can be enabled from SLB's end as Oxygen Builder does not use WordPress' native theme functionality, nor does it provide filters for its own output.

I would be glad to reopen this request in the future once support for Oxygen Builder is possible.
