### ISSUE TITLE
Choosing multiple images to display in the lightbox

### ISSUE THREAD

**Issue by StefRingoot** [archetyped/simple-lightbox#851]
## Description of feature

I am searching a way to display more than one image in the lightbox. It would be great if I could chose which images to display. 

## This feature would be used to

See this page; https://stefringoot.com/poster-cartoons-wenskaarten-en-placemats-als-print/ 
Simple-lightbox is used on the buttons “bekijk voorbeeld”. (View example). However at the moment it is only possible to showcase one image. I can’t find a way to display more than one image. 

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy+++
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, this tutorial show you how to do just that: [Simple Lightbox: Launching Slideshows from a Single Link ](https://archetyped.com/know/slb-single-link-slideshows/)

**Comment by StefRingoot** [comment]
@archetyped hi. I already found that solution and tried it. It’s a workaround if you have not to many images. However there are to many images on my pages so the solution is far to complex. I really hope there wil be an official solution soon.

**Comment by archetyped** [comment]
Perhaps I misunderstood your initial request.  If want to be able to navigate between all images on the page in the lightbox, then all you have to do is enable grouping in SLB's settings.  The previously-referenced tutorial is for setting up a slideshow when only one link is visible on the page, so if all links that you want to display in the lightbox are already visible on the page, then those additional steps are not necessary.

From there, you can split images into separate groups using the `[slb_group]` shortcode ([documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_group)).

**Comment by StefRingoot** [comment]
Thanks for the reply. My English isn’t that good so maybe that is the problem 

What I want is that, after hitting the button “view more” (in Dutch on my page that’s “bekijk meer”) a slide show opens in the light box. (I use “kadance blocks” advanced button for the buttons) displaying 1 image is no problems at all and works great. I can’t add shortcode to the button. (Unless I convert it to html, but I haven’t tried that yet)

I will try your solution.

However it would be great if I could do it without writing code... Maybe an extra page in the preferences of simple lightbox where you can make image groups? If every group has it’s own url it would be possible to attached it to the button
