### ISSUE TITLE
separate slideshows in a page

### ISSUE THREAD

**Issue by cheluvarajhr** [archetyped/simple-lightbox#853]
we need to create multiple slideshows in a page. these slide shows shouldn't not group. right now i have created 4 slide shows and when i run the first slide shows it takes other slides also. i would like to restrict each slide show for its own slides only.  i have tried all possible option in the setting for "Grouping settings"

## Details

* http://vasudevart.com/demo/inner_resonance_bengaluru/  
(grey background area has 4 images which are linked to slideshows) 
Would like to as individual slide shows.

**Comment by archetyped** [comment]
Hi, you can create multiple groups on a page using SLB's `[slb_group]` shortcode.  See [SLB's shortcode documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes#slb_group) for more details.
