### ISSUE TITLE
Divi: Galleries not grouping as expected / Enable default title

### ISSUE THREAD

**Issue by LesWilkins** [archetyped/simple-lightbox#858]
## Description of Problem

Slideshow continues to next gallery / 'enable default title' has no effect.

On pages with several galleries, when scrolling through a sideshow, at the end of one gallery it carries on into the next gallery. As far as I can tell I have configured the settings to prevent this (screenshot attached).

I have several pages with more than one gallery on them, and it happens on all of them. Here's one example: 

https://dernolvalley.org/animals/insects_arthropods/dragonflies_damselflies_mayflies/

Also:
 'enable default title' has no effect. The title shows whether or not this box is ticked.

## Details

It happens in the latest versions of both Firefox and Chrome.
SLB Version 2.8.1

Other plug-ins : 
Divi Booster (I suspect a conflict with this one)
Divi Breadcrumbs Module (from Divi Booster)
Email Subscribers and Newsletters (Icegram)
Enhanced Media Library Pro (wpUXsolutions)
Google XML Sitemaps (Auctollo)
![SLB grouping settings](https://user-images.githubusercontent.com/36489061/104818594-6e708e00-5820-11eb-979f-cdd2de926ea2.jpg)
![SLB grouping settings](https://user-images.githubusercontent.com/36489061/104818605-821bf480-5820-11eb-80cb-190126f3991a.jpg)

**Comment by archetyped** [comment]
## Gallery grouping

Hi, SLB's gallery grouping works with WordPress' native galleries.  It looks like the page you provide is using a non-native gallery.  Please provide a link to the gallery plugin you are using and I would be glad to take a look.

## Default title

It does not appear that any of the links on the page provided are set with the default title generated by WordPress, which would explain why you aren't seeing any change when this option is enabled or disabled.  See SLB's documentation for [more details on the WordPress-generated default title](https://github.com/archetyped/simple-lightbox/wiki/Metadata#notes).

If there is an image with a default title that is not working as expected, please provide:

* Link to page containing image (and location of specific image on page)
* Current "Enable default title" setting (enabled or disabled)
* Details on what should be happening but is not.

**Comment by LesWilkins** [comment]
Thanks for your reply.

I don't use another gallery plug-in as such, but I do use the Divi 
theme, which although it improves a little on the basic Wordpress 
Gallery, its gallery is still not good enough; therefore I also use Divi 
Booster, which adds some useful (essential in my opinion) options to the 
basic Divi gallery. The Divi theme is widely used (their claim "The Most 
Popular WordPress Theme In The World"), and Divi Booster is a popular 
addition to it, so it would be a shame if Simple Lightbox grouping does 
not work as it normally would with them, as it's otherwise ideal for 
what I need.

Divi theme - https://www.elegantthemes.com/gallery/divi/ 
<https://www.elegantthemes.com/gallery/divi/>

Divi Booster - https://divibooster.com/divi-booster-plugin-features/ 
<https://divibooster.com/divi-booster-plugin-features/>


I now understand how the image title works, and can live with that.

Regards,

Les Wilkins

**Comment by archetyped** [comment]
Thanks for the additional information.  Are you saying that the Divi Booster plugin uses WordPress' default gallery shortcode, or that the plugin provides its own gallery block/shortcode in the post editor?

**Comment by LesWilkins** [comment]
As far as I can tell, Divi Booster uses the Elegant Themes 'Divi' theme 
Gallery code, not the default Wordpress code - it just adds extra 
formatting for the number of images in a row, image display sizes and 
title display. I'm not an expert on code, but here's a screenshot of the 
code for a gallery:


I hope this helps, but if there's anything else I can send you, please 
let me know.

Regards,

Les

**Comment by archetyped** [comment]
It doesn't look like the screenshot posted.  If you replied via email, note that attachments are not supported.  Please view this ticket in your browser and upload the screenshot.

Thanks.

**Comment by LesWilkins** [comment]
Screenshot as requested
![sample Divi gallery code for SLB_1](https://user-images.githubusercontent.com/36489061/105835134-52f54800-5fc3-11eb-9279-b95196942b0f.jpg)

**Comment by archetyped** [comment]
Whoops, seems like there was a miscommunication.  I can view the output of the gallery directly via the link you originally provided.

What I would need to know is what you use in the post editor to add a gallery to a post, such as a shortcode, block, etc. so that I can reproduce your issue as closely as possible.

Thanks.

**Comment by LesWilkins** [comment]
I use the Divi 'Gallery' module. I can see this might not be helpful, as 
unless you have Divi, it's not something you can see!

I could set you up as a user and create a dummy page for you to use if 
it would help.

Regards,

Les

**Comment by archetyped** [comment]
Got it, thank you.  I have contacted Divi's developer to evaluate the theme to see if anything can be done from SLB's end to enable grouping for Divi's gallery module.

Please note that as a paid theme, access to the theme for further investigation is not guaranteed.

**Comment by LesWilkins** [comment]
Did anything come of this please?

It was related to there being multiple galleries on a page, and 
scrolling through lightboxed images in a gallery does not restrict 
itself to that gallery, but at the end then proceeds to the next 
gallery.  I would like scrolling through a gallery to be restricted to 
that one gallery.

Regards,

Les Wilkins

**Comment by archetyped** [comment]
Hi, thank you for following up.  Unfortunately, no response was received from the theme's developer.

As a paid theme, access is not guaranteed, but I will reach out to the developer once more.

**Comment by archetyped** [comment]
Hi, I was able to take a closer look at Divi's gallery module. Unfortunately, it looks like there are no options to disable Divi's built-in lightbox, which may conflict with other lightboxes (including SLB).

This likely means that an extension is required for full compatibility with SLB's features.  I've created a ticket for a [Divi Theme extension](https://github.com/archetyped/simple-lightbox-extensions/issues/103), where users can vote for this extension and add feedback.

**Comment by LesWilkins** [comment]
Thanks for your reply, and your help.

I have given the enhancement request on Github a 'thumbs up'.

As you say, there isn't a built-in way to disable Divi's lightbox, but 
Divi did send me this to put into the <HEAD> section, which disables 
their lightbox:

<script type="text/javascript">
     // to disable standard Divi lightbox
jQuery(document).ready(function ($) {var magnificPopupEnabled = 
false;$.extend(true, $.magnificPopup.defaults,
{disableOn: function() {return false;}});});
</script>

It works.

Regards,

Les Wilkins

**Comment by archetyped** [comment]
Unfortunately, that snippet only stops Divi's built-in lightbox from being displayed when a link is clicked.  All of its code is still being loaded, which is what can cause conflicts with other lightboxes.

**Comment by LesWilkins** [comment]
OK, thanks - I understand what you mean, but I don't understand 
javascript, so didn't know this.

Les
