### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by mikejd300** [archetyped/simple-lightbox#861]
I genuinely don't see the point of this, but it is popular so it must be me. It does not follow WP logic at all, and requires either complete automation with no control, or lots of manual intervention, which makes having a plugin pointless.

I think you will also be aware that a lot of Woocommerce users will think this is free an it's not. Doesn't need to be free, but not fair to set it up in that deceptive way, where it arbitrarily isn't connected to Woocommerce

**Comment by archetyped** [comment]
Hi, I'm curious to know specifically how SLB doesn't follow "WP logic" in your opinion, as automatic activation is common for many lightbox plugins, including WordPress' own Jetpack lightbox.

It's also unclear what you mean by "lots of manual intervention" as SLB provides simple settings for further customizing where and when SLB is used.  Some examples would be great.

Finally, I'm not sure what you're referring to regarding WooCommerce, as that plugin is not specifically referenced anywhere on [SLB's home page](https://wordpress.org/plugins/simple-lightbox/), so further clarification on what you mean by things being "set up" in regards to WooCommerce would be appreciated.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.  I would be glad to reopen the ticket once the previously-requested details are provided.

Thanks.
