### ISSUE TITLE
Disable image name

### ISSUE THREAD

**Issue by Mani-Salguero** [archetyped/simple-lightbox#862]
Hello, 
First of all I love your plugin, thank you for all your work.
I'm trying to delete the name description in the bottom part of the image, but I'm not sure how?
Can you help me with this, 
thank you

![image](https://user-images.githubusercontent.com/68559037/106776648-451e7300-6612-11eb-9177-7d6712e317e2.png)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, the layout of the lightbox is controlled by the lightbox theme.  You can create a custom theme to customize all aspects of the lightbox.

See [SLB's theme documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for full details and tutorials on creating and customizing lightbox themes.
