### ISSUE TITLE
Simple Lightbox not running on Simple Non-Profit Theme

### ISSUE THREAD

**Issue by betweendrafts** [archetyped/simple-lightbox#863]
## Description of Problem

Simple Lightbox doesn't work with the "Simple Non-Profit Theme". 
(It works fine with WordPress default themes on the same installation.)

## Details

* WP Installation: https://fda-nrw.de
* Example URL with Gallery: https://fda-nrw.de/2020/10/wandern-in-der-heide/ 
* Version: everything is up-to-date (WordPress 5.6.1, SLB 2.8.1)
* Other plugins installed (active only): Classic Editor

Possibly Aggravating Circumstances:
* The WordPress Installation is German
* The WordPress Installation is in a subfolder (URL/blog/)
* The Simple-Non-Profit Theme seems no longer to be available 
* https://themesinfo.com/simple-non-profit-theme-wordpress-page-template-j3k

**Comment by archetyped** [comment]
Hi, the theme appears to be loading its own very outdated version of jQuery.  Aside from presenting potential security issues, loading an outdated version of jQuery makes it incompatible with WordPress' own functionality and many plugins (including SLB) that use the version of jQuery included with WordPress itself.

Removing the outdated version of jQuery from the theme should resolve the issue with SLB, but there's no way to tell if there are other security or functionality issues that are related to the theme's outdated code.

This is the line that loads the outdated version of jQuery:

```html
<script type="text/javascript" src="https://www.fda-nrw.de/blog/wp-content/themes/simple-non-profit-theme/js/jquery-1.6.1.min.js"></script>
```

This kind of code is generally added to a theme's `header.php` file, though it may be set elsewhere based on how the theme is built.

Also depending on how the theme is built, the full line of code noted above may not be present in the theme, so you may want to broaden the search to `jquery-1.6.1.min.js` when looking through the theme's  files.

**Comment by betweendrafts** [comment]
Wow, thank you so much! I will check that out, and I will mind your advice. Y’all are fantastic, and do fantastic work. Cheers, J.
