### ISSUE TITLE
Lightbox opens, but doesn't display the images

### ISSUE THREAD

**Issue by jens-dots-connect** [archetyped/simple-lightbox#865]
## Description of Problem

Out of sudden, images are not displayed anymore after the lightbox opens

## Details

* URL of Page exhibiting problem: https://www.argoshombeek.be/medische-informatie/chirurgie/kruisbandproblematiek-bij-de-hond/ (3 röntgen photo's above the video.
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: 2.8.1
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, the page you provided is reporting that some of SLB's plugin files are missing.  This may be due an incomplete update (e.g. process canceled before it was completed, network error, etc.).

Reinstalling a fresh copy of SLB.  Make sure to deactivate and delete SLB from your site's Plugin admin page first.  SLB's settings will be retained.

Please provide an updated link if you are still experiencing an issue after reinstalling SLB, and I would be glad to take another look.

**Comment by jens-dots-connect** [comment]
Deleting and downloading again worked. Thanks for the support!

**Comment by archetyped** [comment]
Glad to hear your issue was resolved! 👍
