### ISSUE TITLE
[Request]: PHP 7.4 Compitability

### ISSUE THREAD

**Issue by shaygover** [archetyped/simple-lightbox#867]
## Description of feature

I used PHPCompatibilityWP standard and got this for version 7.4 (the project phpcs file tests against version 5.6):

**simple-lightbox/includes/class.field_collection.php**

> --------------------------------------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
> --------------------------------------------------------------------------------------------------------------------------------
>  146 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as
>      |         | passed to a parameter, but will instead provide the current value. The parameter "$item" was used, and
>      |         | possibly changed (by reference), on line 143.
> -------------------------------------------------------------------------------------------------------------------------------

**simple-lightbox/includes/class.field_base.php**

> --------------------------------------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
> --------------------------------------------------------------------------------------------------------------------------------
>  179 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as
>      |         | passed to a parameter, but will instead provide the current value. The parameter "$path" was used, and
>      |         | possibly changed (by reference), on line 177.
>  914 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as
>      |         | passed to a parameter, but will instead provide the current value. The parameter "$tag" was used, and possibly
>      |         | changed (by reference), on line 904.
> -------------------------------------------------------------------------------------------------------------------------------

**simple-lightbox/includes/class.base_collection.php**

> --------------------------------------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
> --------------------------------------------------------------------------------------------------------------------------------
>  281 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_arg(), no longer report the original value as
>      |         | passed to a parameter, but will instead provide the current value. The parameter "$meta_value" was used, and
>      |         | possibly changed (by reference), on line 278.
> -------------------------------------------------------------------------------------------------------------------------------

**simple-lightbox/includes/class.content_handlers.php**

> --------------------------------------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
> --------------------------------------------------------------------------------------------------------------------------------
>  57 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_arg(), no longer report the original value as
>     |         | passed to a parameter, but will instead provide the current value. The parameter "$id" was used, and possibly
>     |         | changed (by reference), on line 52.
>  59 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_arg(), no longer report the original value as
>     |         | passed to a parameter, but will instead provide the current value. The parameter "$props" was used, and
>     |         | possibly changed (by reference), on line 54.
> -------------------------------------------------------------------------------------------------------------------------------

**simple-lightbox/includes/class.utilities.php**

> -------------------------------------------------------------------------------------------------------------------------------
> FOUND 2 ERRORS AND 1 WARNING AFFECTING 3 LINES
> -------------------------------------------------------------------------------------------------------------------------------
>  666 | ERROR   | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as
>      |         | passed to a parameter, but will instead provide the current value. The parameter "$tag" was changed on line
>      |         | 664.
>  694 | ERROR   | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as
>      |         | passed to a parameter, but will instead provide the current value. The parameter "$tag" was changed on line
>      |         | 692.
>  877 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as
>      |         | passed to a parameter, but will instead provide the current value. The parameter "$key" was used, and possibly
>      |         | changed (by reference), on line 876.
> -------------------------------------------------------------------------------------------------------------------------------

## If you added this feature, I would:

a) Eat my hat
**b) Jump for joy**
c) Shave my cat - I will not shave the cat.
d) All of the above

**Comment by archetyped** [comment]
SLB has its own PHPCS configuration that tests compatibility for PHP 5.6 **and higher** (matching WordPress' own requirements).  

If you do not see the same output when using SLB's own PHPCS configuration then the specific notices have been evaluated and determined to not be relevant to SLB's code.
