### ISSUE TITLE
How to get it to work with post thumbnails?

### ISSUE THREAD

**Issue by radstylix** [archetyped/simple-lightbox#869]
## Description of Problem

I'm trying to add a new post-format (content-image.php) with my current theme. I wanted to use the post's featured image/thumbnail to output an image, but it seems like Simple Lightbox doesn't work with the code I use below. It works perfectly if an image is added to a post using Add Media though, so no complaints about its normal functions. Is there anything I can add to this theme's post-format to make it work? If not or if I have to edit the Simple Lightbox plugin, then please ignore this.

Oh, and thanks for making the plugin!

## Details
The code in content-image.php to output the thumbnail in full size and add a link to the thumbnail's URL:
```
<?php
      $thumbnail   = get_the_post_thumbnail_url($post->ID, 'full');

      if ($thumbnail) { ?>
        <figure class="format-image-container">
          <a href="<?php echo $thumbnail;?>"><?php the_post_thumbnail('full')?></a>
        </figure>
?>
```
* Version of SLB Installed: Version 2.8.1

**Comment by archetyped** [comment]
Hi, please refer to SLB's documentation for details on [activating a post's thumbnail image to be displayed in a lightbox](https://github.com/archetyped/simple-lightbox/wiki/Activation#display-post-thumbnail-in-lightbox).
