### ISSUE TITLE
Simple Lightbox Not Working with Jetpack Infinite Scroll

### ISSUE THREAD

**Issue by rickgordon** [archetyped/simple-lightbox#872]
## Description of Problem

I just upgraded to WP 5.7, and am trying Simple Lightbox, because my previous lightbox plug-in is not being updated any more. How can I make it work through infinitely scrolled Ajax-loaded images, as well as the first page of images?

## Details

* Website: https://www.lloydkahn.com/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 89.0.4389.90 (Official Build) (x86_64) 
* Version of SLB Installed: 2.8.1
* Other plugins installed: Admin Taxonomy Filter
Akismet Anti-Spam
Automatic Featured Images from YouTube / Vimeo
automatic upload images
Better WordPress External Links
Blogger 301 Redirect
Category Posts in Custom Menu
Classic Editor
DoLogin Security
Easy Add Thumbnail
Enable jQuery Migrate Helper
Health Check & Troubleshooting
HTML Special Characters Helper
Intagrate
Jetpack by WordPress.com
LiteSpeed Cache
ManageWP - Worker
Media Cleaner
No Gutenberg - Disable Block Editor - Back to Classic Editor
PHP Compatibility Checker
Post Thumbnail Editor
Regenerate Thumbnails Advanced
Remove Query Strings From Static Resources
Save & Import Image from URL
Search & Filter
Search Regex
Simple Image Sizes
Simple Lightbox
Taxonomy List Widget
Temporary Login Without Password
User Role Editor
WP Crontrol
WP Downgrade | Specific Core Version
WP-Cron Status Checker
WP-Optimize - Clean, Compress, Cache
Yoast SEO
Yoast SEO Premium

**Comment by rickgordon** [comment]
Actually, I reverted back to WordPress 5.5.7 and my old lightbox plugin until I can get things worked out with the upgrade; so Simple Lightbox is not currently installed on the listed website. But I am curious as to whether there is a fixable issue with infinite scroll.

**Comment by archetyped** [comment]
Hi, support for infinite scroll plugins will require an add-on. Please refer to the [existing ticket](208) for more details and to share your feedback.

Thanks.

**Comment by rickgordon** [comment]
Thanks,
 but I'm confused. I went to the referenced "existing ticket" <https://github.com/archetyped/simple-lightbox/issues/208>
 and found a series of comments between 7 and 3 years old complaining of
 the same thing, but no solution offered. 

So what is the add-on required, if you can't offer a function to hook 
into?

Rick Gordon



--------------------
On March 25 [2021] at 5:38PM [-0700],
 Archetyped wrote in an email entitled Re: [archetyped/simple-lightbox] Simple 
Lightbox Not Working with Jetpack Infinite Scroll (#872):

  Hi, support for infinite scroll plugins will require an add-on. 
Please refer to the existing ticket
 for more details and to share your feedback.

  Thanks.


  —You
 are receiving this because you authored the thread.Reply to this 
email directly, view
 it on GitHub, or unsubscribe.

  [
{
***@***.***": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/archetyped/simple-lightbox/issues/872#issuecomment-807828925">"https://github.com/archetyped/simple-lightbox/issues/872#issuecomment-807828925"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/archetyped/simple-lightbox/issues/872#issuecomment-807828925">"https://github.com/archetyped/simple-lightbox/issues/872#issuecomment-807828925"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]

**Comment by archetyped** [comment]
Hi, as noted in the aforementioned add-on proposal: "Add-on development is prioritized by demand".

The proposal ticket exists to receive feedback, provide updates, and determine demand.  Without adequate demand, other higher-priority development will come first.
