### ISSUE TITLE
worst info page ever for slb_activate

### ISSUE THREAD

**Issue by justinblayney** [archetyped/simple-lightbox#873]
## Description of Problem
I want to use slb_activate for advanced custom fields, so I went to your read me page. After reading page, it makes no sense. I still have no idea how to use it. You need a UI person with writing skills to make this page better

## Details
https://archetyped.com/lab/slb-2-3-0/

FYI, I am still unable to use this for ACF

wrapping the image with [slb_activate] or {slb_activate} .. you could blame me, but im a developer with 20 years experience and this page is still nonsense

**Comment by archetyped** [comment]
Hi, the page you provided contains the release notes for a specific release.  Please refer to [SLB's documentation](https://github.com/archetyped/simple-lightbox/wiki) for current details on using SLB.  Specifically, [SLB's Activation documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation) provides details on using `slb_activate()`.

Also, please let me know where you saw any reference to `[slb_activate]` or `{slb_activate}` on the page you provided, as I cannot find it anywhere on that page.  The only reference to activation on that page is the `slb_activate()` template tag, with a code sample provided in the **Usage** section.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
