### ISSUE TITLE
[Request]: Several cool requests

### ISSUE THREAD

**Issue by SteveNeaves** [archetyped/simple-lightbox#875]
## Description of feature

Use theme font for image counter or turn off image counter option

Have a remove glow effect option from all edges/buttons etc

Option to have straight right angles on box corners as opposed to round corners

## This feature would be used to

make this plugin rule!! And fit in with all templates

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, active lightbox theme controls the appearance of the lightbox.

See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for details on customizing lightbox themes.
