### ISSUE TITLE
Simple Lightbox in Divi doesn't work

### ISSUE THREAD

**Issue by graphickraus** [archetyped/simple-lightbox#878]
## Description of Problem

Hello,

I want to use Simple Lightbox by Archetyped in Divi.

Unfortunately, that doesn't work.

Can you help me?

Best regards
Alex

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed: 
* Wordpress 5.7.1
* PHP 7.4.13
* MySQL 8.0
* Divi 4.9.4

**Comment by archetyped** [comment]
Hi, I would love to help.  Please update your original post to provide the necessary details for your issue to be evaluated.

Thanks.

**Comment by graphickraus** [comment]
URL of Page exhibiting problem: Website under construction!

https://architektur.it-kraus.eu
Front- & Backend
username: Eleonora
pw: q%zo5-d8Ccaayw


    Browser(s) exhibiting problem (Firefox, Chrome, etc.): ALL
    Version of SLB Installed: 2.8.1
    Other plugins installed: All-in-One WP Migration (7.41),  Advanced Custom Fields (5.9.5)
    Wordpress 5.7.1
    PHP 7.4.13
    MySQL 8.0
    Divi 4.9.4

**Comment by graphickraus** [comment]
sorry, username & pw = Frontend only

**Comment by archetyped** [comment]
Posting login credentials in a public forum is not recommended.  I have deleted the post, but you should change the login details to avoid any unauthorized logins.

Also, please note that as per [SLB's Requirements](https://github.com/archetyped/simple-lightbox/wiki/Requirements), using HTTP authentication blocks the loading of files SLB needs to function properly.

Removing the HTTP authentication should allow SLB to function properly.  If you are still experiencing an issue after removing the HTTP authentication, please leave an updated link to a specific page that exhibits the issue (i.e. not just the home page), and I would be glad to reopen this ticket and take a look.
