### ISSUE TITLE
SLB has stopped working with Twenty Seventeen

### ISSUE THREAD

**Issue by ray-was** [archetyped/simple-lightbox#882]
Images which were previously opening in SLB just fine, now suddenly are not. 

* Example URL: [https://www.raysume.com/eclat-partefacts/](https://www.raysume.com/eclat-partefacts/)
* Browser(s) exhibiting problem: Chrome, Firefox, Safari
* Version of SLB Installed: latest (2.8.1)
* Other plugins installed: (i deactivated all other plugins, reset SLB, then reactivated one by one): Akismet, Contextual Related Posts, FV top level Categories, Jetpack, Options for Twenty Seventeen, Really Simple SSL, Yoast SEO
* Other plugins installed, but not activated (now or prior to SLB stopping working): Gutenberg, Kirki Customizer Framework, MaxButtons, Meta Box, PDF Embedder, Regenerate Thumbnails, Simple CSS for widgets, WordPress FlippingBook

**Comment by archetyped** [comment]
Hi, SLB is working properly and opening image links at the link you provided.

You may need to clear your browser's cache to ensure that it is loading the latest code.
Also ensure that the page has fully loaded before clicking an image link to ensure that all code (including SLB) has been loaded.

If you are still experiencing this issue, please provide more details of what "SLB has stopped working" means (e.g. what happens instead, etc), and an updated link that exhibits the issue, and I would be glad to reopen this ticket and take another look.
