### ISSUE TITLE
[Request]: Toggle image comments on/off

### ISSUE THREAD

**Issue by zaridan** [archetyped/simple-lightbox#883]
## Description of feature

It would be great if there were a setting that could turn off comments on images.

## This feature would be used to

Turn off comments on images

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Hi, SLB does not display any commenting functionality in the lightbox.  Can you please provide more details on what functionality you are requesting?  A screenshot may also be helpful.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If this request is still valid, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.

Thanks.
