### ISSUE TITLE
Can't get Simple Lightbox to work for Gallery - Coldbox Theme

### ISSUE THREAD

**Issue by jasongows** [archetyped/simple-lightbox#884]
## Description of Problem

I can not for the life of me get the lightbox to come up. I've tried everything, I've disabled all other plugins, I made sure cURL was activated in my php settings, contacted the web hosting service as well, who told me:
"Usually the curl error is related to blocked outgoing connections, so I have gone and whitelisted the problematic ones and now everything should be as intended, if you could please test on your end."

Nothing has worked at all.

## Details

* URL of Page exhibiting problem: http://whittleseahistoricalsociety.org.au/online-image-gallery-people/ ; http://whittleseahistoricalsociety.org.au/online-image-gallery-buildings/ ; http://whittleseahistoricalsociety.org.au/online-image-gallery-locations/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox and Chrome
* Version of SLB Installed: 2.8.1
* Other plugins installed: WPForms Lite, Recent Posts Widget with Thumbnails, Better Search Replace

**Comment by archetyped** [comment]
Hi, SLB does not appear to be installed/activated at the links provided.  Please confirm that SLB is activated on the site and provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to take another look.

Thanks.

**Comment by jasongows** [comment]
Hi there,

Thanks for getting back to me.
SLB is installed and activated as far as I can see, and has been since I
submitted the request.
Here's a screenshot of the plugins page (attached).

Thanks again,
Jason

**Comment by archetyped** [comment]
Hi, I don't see an image. Please note that images and other files must be uploaded to the ticket via a browser; email attachments are not supported.

If you have confirmed that SLB is activated, please also ensure that it is enabled in SLB's settings. A screenshot of SLB's settings page would also be useful. 

Thanks

**Comment by jasongows** [comment]
<img width="1169" alt="Screen Shot 2021-06-10 at 6 36 56 pm" src="https://user-images.githubusercontent.com/85560211/121493291-09117980-ca1b-11eb-9cd4-11b63909ed23.png">
![Screenshot 2021-06-10 111245](https://user-images.githubusercontent.com/85560211/121493329-12024b00-ca1b-11eb-8790-f0759ab97fa3.jpg)


Ok, sorry I sent it via email. Here you go.
Yes - activated in both places, both screenshots are attached.

**Comment by jasongows** [comment]
![Screenshot 2021-06-10 111245](https://user-images.githubusercontent.com/85560211/121493436-2fcfb000-ca1b-11eb-90c3-8bfcc1ee95f7.jpg)

**Comment by archetyped** [comment]
Thank you.  SLB was tested with a default installation of Coldbox theme (v.1.9.3) and no issues were found.  It may be possible that a setting of the theme or a conflict with another plugin is preventing SLB from loading, so checking for theme/plugin conflicts is recommended ([instructions](https://github.com/archetyped/simple-lightbox/wiki/Troubleshooting-Plugin-Conflicts)).

Please provide details of any conflict you've identified, and I'll see what can be done from SLB's end.

Thanks.

**Comment by jasongows** [comment]
Hi, thanks again.
So I've tested both plugins and themes. Even with all other plugins deactivated, SLB still didn't work. Then, with TwentyTwenyOne theme activated, it also didn't work.
I also tried removing all custom css, it hasn't worked either.
I'm very confused, not sure what I'm missing!

For the record (if this helps), I've also tried a few other lightbox plugins that operate in a similar way (automatically applied to gallery images when set to link to > media file) but none of them have worked, either. SLB is my preference, I hope we can figure out what's going on.

Thank you again for your help so far, hope we can find a fix.

**Comment by archetyped** [comment]
SLB not working with all other plugins disabled and a default theme, as well as no other lightbox plugins working either may indicate that the issue is related to configuration of the site by your web host.

I would recommend contacting the web host for your site to inquire about any non-standard configuration settings used on the site itself or globally by the hosting company.  For example, do they block certain PHP functions, etc. Some setting could be preventing essential WordPress functionality, as it appears that SLB is not being loaded at all at the links provided (different than a cURL-specific configuration issue you mentioned contacting them about).

**Comment by archetyped** [comment]
Hi, did you receive any further details from your web hosting provider regarding how they configure sites hosted by them?  Let me know if you have any further details, as it may shed some light on what is preventing SLB from being loaded.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
