### ISSUE TITLE
Issue with Generate Press - and Lightbox

### ISSUE THREAD

**Issue by madislander** [archetyped/simple-lightbox#885]
## Using Generate Press Theme - created a "thumbnail gallery" but the images, when shown large on the side will not open in lightbox

Also, Lightbox opening in fullsize window, yeah - but there is no closing "X" for users to see and visitors must use back button in browser, bummer (is this a theme issue?). I used Simple Lightbox in our current theme and it worked perfectly. So need to figure out how to fix in the new theme - Generate Press.

Current website simple lightbox works beautifully - https://psemc.com/products/expanding-tube-assembly/

## Details

* Page is in development site, can give access if requested
* Testing in all browsers - Chrome, Firefox, Edge, Safari
* Version of SLB Installed: 2.8.1
* Multitude

In Generate Press:
![Simple Lightbox image 1](https://user-images.githubusercontent.com/8197291/122257306-c0c3e280-ce84-11eb-8dfb-0816f99fbb76.PNG)

Generate Press Product Image Area
![Generate Press Product Image Area](https://user-images.githubusercontent.com/8197291/122257858-434ca200-ce85-11eb-8f83-e0ea7e2aa9dc.PNG)

In Current live theme:
![Simpe Lightbox in current Theme](https://user-images.githubusercontent.com/8197291/122257819-38920d00-ce85-11eb-9184-cb6f8e4ade31.PNG)

**Comment by madislander** [comment]
Trying a different lightbox - sorry.

**Comment by archetyped** [comment]
Hi, SLB was tested with GeneratePress and no issues were encountered.

However, note that if you are using HTTP Authentication to control access to the in-development site, WordPress is blocked from loading certain files that can prevent SLB's normal functionality. See [SLB's requirements documentation](https://github.com/archetyped/simple-lightbox/wiki/Requirements#http-authentication) for more details.

Thanks.
