### ISSUE TITLE
[Request]: Add URL field 

### ISSUE THREAD

**Issue by stathimexas** [archetyped/simple-lightbox#887]
## Description of feature

Add a URL field in each image to be clickable to direct you there during sliding
Example:
```html
<a href="image_1.png" title="Slide 1" url='https://www.my.com/image1.html">Slide 1</a>
```

## This feature would be used to
To direct you where the picture points to

## If you added this feature, I would: DDDD
a) Eat my hat
b) Jump for joy
c) Shave my cat
d) All of the above

**Comment by archetyped** [comment]
Hi, can you please clarify your request?  Is this link a link that would be added to the lightbox?  What does clicking the link do (e.g. load the image file directly in the browser, display the image in the lightbox, etc.)?

Thanks.

**Comment by stathimexas** [comment]
Thank you for your response. 
That link would be just like any other regular ‘<a html=‘ url tag and take you anywhere you want. I need it to take me to a url related to the image. 
Also, I have noticed that even though the plug-in reads and has code for n images, it thinks it has many more. Perhaps you can help me with that. 
Thank you so much. How can I donate a few dollars?

-

**Comment by archetyped** [comment]
Thank you for the additional details.  The key issue is _where_ the URL and link text would be set for a specific image link, as WordPress' media library does not support such a field at this time.

A better fit may be **Description** field in WordPress' media library, as supports HTML including links.  SLB displays the content from this field (including links) in the lightbox.

As for the "n images" issue, please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

P.S. A donate button is available on [SLB's page in the WordPress Plugin Directory](https://wordpress.org/plugins/simple-lightbox/). Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
