### ISSUE TITLE
[Request]: Hide Titles on Images

### ISSUE THREAD

**Issue by CFB-Caleb** [archetyped/simple-lightbox#889]
## Description of Problem

Currently, enable default title doesn't seem to remove a title when it is disabled. We would like to be able to hide titles completely, we do not purposely use them on our images.

It would stop me from having to delete each default title when uploaded, things are usually in messy shape, bunch of letters and numbers, would be great not to have to delete it so it didn't show up. If I'm not using this correctly, please advise. I have checked and unchecked the "Enable default title" option and each way it did not stop 
![Untitled](https://user-images.githubusercontent.com/86625440/123688633-dedffa00-d817-11eb-94ab-b6d912ba65cc.png)
the title from showing up.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
This ticket has been changed to a support ticket, which is better suited to evaluating a feature not working as expected.  Please update your original post and provide the necessary details to fully evaluate your issue.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
