### ISSUE TITLE
Does it work with links?

### ISSUE THREAD

**Issue by aanders77** [archetyped/simple-lightbox#890]
Hi. I haven't installed your plugin yet, just wanted to know if it will work with links ("a" tags) which does not contain an img tag inside?

Explanation: I have a table with many rows. One of the columns says "Show image" inside an "a" tag. I want the images to load into your lightbox when the links are clicked.

**Comment by archetyped** [comment]
Yes, as per the first feature listed on [SLB's home page](https://wordpress.org/plugins/simple-lightbox/), SLB automatically activates links (which are created by "a" tags) for display in the lightbox when clicked.  The presence of images within the link is not a factor in SLB's functionality.

In fact, as images within links are often smaller thumbnail versions of images, the browser has no way of knowing what full-size image should be displayed when an image is clicked.  That's what links are necessary for.
