### ISSUE TITLE
[Question]: Can you target only specific images/links?

### ISSUE THREAD

**Issue by aanders77** [archetyped/simple-lightbox#891]
I have FooGallery installed from before, but I want to use Simple Lightbox for the images that are not part of a gallery. When both are installed, they are in conflict (images are opened in both lightboxes, on top of each other). I can't find a way to exclude/include by css class or similar?

**Comment by archetyped** [comment]
Hi, running multiple lightboxes on the same site is not recommended as they all act upon the same things (i.e. image links).

To resolve this, setting FooGallery's galleries "Lightbox" setting to "None" is recommended.  This will stop FooGallery from loading an additional lightbox on pages, resulting in faster page loads and allowing SLB to display images in the lightbox without any conflicts when the gallery links are clicked.

Alternatively, you can use SLB's `[slb_exclude]` shortcode to exclude gallery links from being displayed by SLB. See [SLB Shortcodes documentation](https://github.com/archetyped/simple-lightbox/wiki/Shortcodes) for more details.

**Comment by aanders77** [comment]
Hi,

Thanks, that did the trick!

One more question. On this page
https://www.saltdalselva.no/statistikk-fangster/ I have included an alt
attribute on the "Vis foto" links on the far right. Still the lightbox only
shows the link title. Why?

Regards,
Anders

tor. 22. jul. 2021 kl. 22:26 skrev Archetyped ***@***.***>:

**Comment by archetyped** [comment]
Hi, `alt` is not a valid attribute for links in HTML (it is an image element attribute).

Using an attribute specified in [SLB's Title Precedence documentation](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence) is recommended for manually setting the title in the lightbox.
