### ISSUE TITLE
VK links are not working

### ISSUE THREAD

**Issue by Arskrigitsioniets** [archetyped/simple-lightbox#892]
## Description of Problem

If I try to paste images through the VK link, like [this](https://sun9-38.userapi.com/impg/tRF_WKLg1xh9xKRzyQHM2YPeA89UUJstWFy6wg/eqc2Rz0Ljvg.jpg?size=1914x1200&quality=96&sign=185472b66f6711ceef4d0dd2dce3dabd&type=album), it doesn't work on the lightbox, I get endless load.

**Comment by archetyped** [comment]
Hi, it looks like WordPress cleans up link URLs to properly use character entities (e.g. `&` to `&amp;`).  Additionally, it appears that VK does not handle URLs when proper entities are used for some reason, returning a 403 Forbidden error code instead.

This is more of a server configuration issue on VK's end, but I will look into whether anything can be done on SLB's end without introducing compatibility issues with servers that are configured correctly.  As this entails a fair amount of testing to ensure there are no compatibility issues, it may take a while.  I would recommend contacting VK and informing them of their issue with URLs with proper character entities, as that may resolve the issue more quickly without requiring any workarounds.

Let me know what you hear back from VK.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a another look.

Thanks.
