### ISSUE TITLE
WEBP Files Problem

### ISSUE THREAD

**Issue by JustMeAlone** [archetyped/simple-lightbox#896]
## Description of Problem

There appears to be a problem with Simple Lightbox working with WEBP graphic files. The lightbox opens and displays the image but none of the control seem to work, the image just fills the screen and can't be closed or advanced to another image. The only exit is to go back to the last page shown.

## Details

* URL of Page exhibiting problem: https://e-olio.com/simple-lightbox-test.html
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  Firefox 90.0.2 (64-bit)
* Version of SLB Installed: 2.8.1
* Other plugins installed: Genesis Blocks, iThemes Sync, Wordfence Security, WP Last Modified Info, Yoast SEO -- but the number or type don't seem to be a factor as the same thing happens on my other sites with variable numbers of different plug-ins. I set up the test page on the simplest of my sites, one set aside for testing only.

**Comment by JustMeAlone** [comment]
Same problem using Microsoft Edge Version 92.0.902.67 (Official build) (64-bit).
Ditto Google Chrome Version 92.0.4515.131 (Official Build) (64-bit).

**Comment by archetyped** [comment]
Hi, WEBP files are loaded directly by the browser, they are not loaded into the lightbox.

WordPress 5.8 just added support for WEBP images, so support will be added to SLB in an upcoming update.

**Comment by JustMeAlone** [comment]
Thank you. That's what I was hoping would happen. Best.

**Comment by fxaviers** [comment]
Is there any news on this case?
Is there an ETA for implementing WebP support?

**Comment by JustMeAlone** [comment]
Sorry, I would not know. Got tired of waiting and switched to Easy Fancybox
and not looked back.
