### ISSUE TITLE
Simple Lightbox not support image .webp

### ISSUE THREAD

**Issue by langtuhodo** [archetyped/simple-lightbox#900]
## Description of Problem
Simple Lightbox not support image .webp , please help me.
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Duplicate of #896

Please [search for existing tickets](https://github.com/archetyped/simple-lightbox/wiki/Feedback-&-Support) before creating new ones.

Thank you.
