### ISSUE TITLE
Watermark in Simple Lightbox 

### ISSUE THREAD

**Issue by Kar120c** [archetyped/simple-lightbox#905]
Hello
How can I add a watermark in the images shown in my galleries ?
Thanks in advance for an answer easy to understand for a (french) beginner on wordpress. 😀

**Comment by archetyped** [comment]
Hi, SLB's primary focus is displaying media in a lightbox.  It does not modify your images in any way.

Ideally, a watermark would be added before you upload the images (e.g. with photo editing software) to give you the most control over the placement of the watermark.  However, you may also find a suitable plugin in [WordPress' Plugin Directory](https://wordpress.org/plugins/search/watermark/) that can add a watermark to images as they are uploaded.
