### ISSUE TITLE
Lightbox’s layout is not being loaded

### ISSUE THREAD

**Issue by yanou333** [archetyped/simple-lightbox#913]
it appears that the lightbox’s layout is not being loaded, which may be due to an expired certificate in your WordPress installation
How i can solve?
Url:
https://www.eco-ce.fr/test1/

**Comment by archetyped** [comment]
Hi, please refer to [the ticket provided in reply to your post on WordPress' support forums](906) for further details and resources on resolving the issue.

Thank you.
