### ISSUE TITLE
next and previous button enabled but not visible.  

### ISSUE THREAD

**Issue by saskiac70** [archetyped/simple-lightbox#914]
## Description of Problem

next and previous button enabled but not visible. Only close x is visible. Both in dark as in light theme. Am I doing something wrong? 
Gr, Saskia

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox
* Version of SLB Installed: latest
* Other plugins installed: just started so just some basics

**Comment by archetyped** [comment]
Hi, please update your post to include the details necessary to fully evaluate your issue.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
