### ISSUE TITLE
SLIDER GALLEY ISSUE Browser 

### ISSUE THREAD

**Issue by dary89** [archetyped/simple-lightbox#915]
## Description of Problem

Hi Guy, I installed this plugin on the WordPress website but I got an issue. When I'm opening the slider gallery in the article pages, it's redirecting to me at the homepage but if I'll clean the cache on incognito view it's working properly.

So I think it could be a cache issue but I don't know because I've WP ROCKET and CLOUDFLARE.

Let me know any suggestions!

Cheers to everyone.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your post to include the requested details to fully evaluate your issue.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
