### ISSUE TITLE
The image opens in a new page without the icons for swiping and closing images

### ISSUE THREAD

**Issue by neoline14** [archetyped/simple-lightbox#916]
Hello, I'm Vitaliy.
I am using your SIMPLE LIGHTBOX plugin. And I have a problem. The plugin worked correctly at first. The images were enlargable, there were icons to turn and close the lightbox. But some time before the plugin began to work incorrectly: the image opens in a new page without the icons for swiping and closing images. An example on this page:
 https://oniks-master.ru/reklamnie-viveski -> https://oniks-master.ru/wp-content/uploads/2021/03/rv14.jpg
What is the reason of this incorrect behaviour? And how to fix it to restore the plugin to work correctly?

* URL of Page exhibiting problem:  https://oniks-master.ru/reklamnie-viveski -> https://oniks-master.ru/wp-content/uploads/2021/03/rv14.jpg
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Firefox, Chrome
* Version of SLB Installed: 
* Other plugins installed: Popup Maker, Contact Form 7, All in One SEO

**Comment by archetyped** [comment]
Hi, SLB appears to be properly displaying the images in a lightbox at the link you provided.

If you are still experiencing this issue, please make sure you have cleared your browser's cache before testing.  Once you have confirmed that the issue persists, please provide an updated link to a page that exhibits the issue and I would be glad to take another look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
