### ISSUE TITLE
Centering wpb_wrapper div

### ISSUE THREAD

**Issue by JuanjoBaeza** [archetyped/simple-lightbox#919]
Hello, first of all thank you very much for this great plugin. I want to ask if it´s possible any way to get an absolute centering, i know the wpb_wrapper div itself is centered, but the free space into it makes as if it´s uncentered. I send an screenshot.

![screen](https://user-images.githubusercontent.com/40768784/142853169-19e54a79-8c1b-4794-bcf9-cdbdd64f206f.jpg)

Thanks! in advance.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, there appears to be a different lightbox active on your site, as `.wpb_wrapper` is not an element created by SLB.

Please ensure that SLB is installed/activated and all other lightbox plugins/scripts are removed from the site.  If you are still experiencing this issue, please provide the details necessary to fully evaluate your issue missing from your original post (link, browser, etc.), and I would be glad to take another look.

Thanks.

**Comment by JuanjoBaeza** [comment]
mmmh... i think i´m in the right site. 

![plugin-detail](https://user-images.githubusercontent.com/40768784/143193747-2c450878-9d79-4c7d-82b6-7fe553bd2c81.PNG)

**Comment by archetyped** [comment]
Hi, even if SLB is activated, there appears to be another lightbox being loaded on your site based on the screenshots you have provided.  This other lightbox may come from the site's theme, or another plugin (such as the Bakery plugin you mentioned).

As previously1
