### ISSUE TITLE
Lightbox feature not working.

### ISSUE THREAD

**Issue by garydumbleton** [archetyped/simple-lightbox#923]
## Description of Problem

When I am doing a blog the lightbox feature is not applied to the page pictures that I am working on.
It always seemed to work fine in the past.
past posts all still work.

## Details

* URL of Page exhibiting problem:   https://smallsensorphotography.com/everything-has-a-cost
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  All browsers
* Version of SLB Installed:  2.8.1
* Other plugins installed: 

![image](https://user-images.githubusercontent.com/8402934/146269326-43844aa9-97cd-47c7-b655-1bd97259387e.png)

Thanks for anything that you can do to get this going again.

Gary

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

Please provide an updated link if you are still experiencing an issue once image links are added to the page, and I would be glad to reopen this ticket and take another look.
