### ISSUE TITLE
hyperlink in caption

### ISSUE THREAD

**Issue by gilnamur** [archetyped/simple-lightbox#924]
A hyperlink that would appear below the caption when viewing images. 

(Describe your feature or idea here)

For example: If you are interested in purchasing this image, _click here_ to contact us.

(Describe usage here)

## If you added this feature, I would:

a) Eat my hat
b) Jump for joy
c) Shave my cat
**d) All of the above**

**Comment by archetyped** [comment]
Hi, adding the desired link to the image's description field in the media library is recommended as this field supports HTML (including links).

An image's description is displayed below the caption in SLB's default themes.
