### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by stevinoz** [archetyped/simple-lightbox#925]
## Description of Problem

just couldn't get it to do anything to image display using vw hair salon theme, didn't work  :(

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your original post to provide the details necessary to fully evaluate your issue, and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.
