### ISSUE TITLE
Lightbox not working

### ISSUE THREAD

**Issue by basnet45** [archetyped/simple-lightbox#927]
## Description of Problem
Lightbox not working for gallery image, instead while opening gallery image it opens attachment url.

## Details
I have added gallery from WordPress default gallery. And on viewing, instead of opening in lightbox, it opens attachment URL.

I have tried for Google Chrome, Mozilla Firefox (Newly installed Browser) and also in Chrome on Mobile. But nothing works.

Installed today, so it must be latest version.

None of other plugins (comes with WordPress) are activated, just, Lightbox is activated.

Link for page: https://www.anwanepal.org/our_gallery/first-gallery/

**Comment by archetyped** [comment]
Hi, I do not see a default Wordpress gallery at the link provided.  Can please provide an updated link to a page containing a gallery for evaluation and a screenshot of the gallery on the page?

Thank you.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
