### ISSUE TITLE
Use with shortcode

### ISSUE THREAD

**Issue by stacef** [archetyped/simple-lightbox#929]
## Description of Problem
Hi there. I really like your plugin and it works flawlessly when I add a gallery to a post (custom post type). But I would like to include the gallery within the php template using do_shortcode. However, when I do, the plugin no longer works.

In the post, I use [gallery columns="6" ids="56,74,55,54,53,52,51,50"]. In the page template, I use do_shortcode( '[gallery columns="6" ids="56,74,55,54,53,52,51,50"]' ). In both cases, the gallery displays without issue, html seems to be identical, but the do_shortcode version goes to an attachment page instead of using displaying with Simple Lightbox.

Any thoughts or ideas welcomed!
Thanks

## Details

* URL of Page exhibiting problem: 
* https://familyfeld.net/tree/people/louis-eustace-felder-jr/. 
*login required: use simplelightbox/simplelightbox
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Using Chrome
* Version of SLB Installed: 2.8.1
* Other plugins installed: Only a couple of simple ones built by me. I don't think it's a plugin conflict because SLB works as expected in all other contexts beside do_shortcode.

**Comment by archetyped** [comment]
Hi, you can use `slb_activate()` to enable the lightbox for content outside of the standard content areas.

Please see [SLB's Activation documentation](https://github.com/archetyped/simple-lightbox/wiki/Activation#manual-activation) for full details and examples.
