### ISSUE TITLE
<figcaption> is not in <a> attribute

### ISSUE THREAD

**Issue by noha7** [archetyped/simple-lightbox#931]
## Description of Problem

Currently generated code containing figcaption looks like this:
```
<figure>
  <a href="3.jpg" data-slb-active="1" data-slb-asset="339193813" data-slb-internal="0" data-slb-group="14">
    <img loading="lazy" width="300" height="225" src="3-300x225.jpg" alt="" data-id="54" data-full-url="3.jpg" data-link="3" class="wp-image-54" srcset="3-300x225.jpg 300w, 3-768x576.jpg 768w, 3.jpg 1024w" sizes="(max-width: 300px) 100vw, 300px" />
  </a>
  <figcaption class="blocks-gallery-item__caption">
    Some caption
  </figcaption>
</figure>
```
![Non-linkable-part](https://user-images.githubusercontent.com/9210391/153726762-e76ed9dc-36b4-48a7-b139-e363e553e7c6.png)

Even figcaption is over image - it is not linkable. I would except whole image (so even figcaption) would work to open lightbox.

## Details

* URL of Page exhibiting problem: locally
* Browser(s) exhibiting problem: Firefox, Chrome
* Version of SLB Installed: 2.8.1
* WordPress version: 5.8.3
* Other plugins installed: Smart Slider 3

**Comment by archetyped** [comment]
Hi, SLB has no control over the code generated on the page.  It only controls the display of the lightbox.

As you note, the `figcaption` element is not linkable, and as SLB works with links, clicking non-link elements cannot display the lightbox.

If you are saying that the `figcaption` element is blocking portions of the linked thumbnail from being clicked, this may be something you can address via the site's theme and/or custom CSS styles.
