### ISSUE TITLE
Gallery sequence

### ISSUE THREAD

**Issue by corvandongen** [archetyped/simple-lightbox#933]
**Change the sequence of pictures in the gallery**
I can no longer change the sequence of the selected pictures in my gallery.
Only the option to reverse last/first works but I cannot change manually.
This issue occurs on all my pages

## Details

* URL of Page exhibiting problem: http://www.riakeemink.nl/home-page/galerie-bloemen/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of SLB Installed: ?
* Other plugins installed: no other gallery plug ins installed

**Comment by archetyped** [comment]
Hi, can you please provide more details on the issue you're experiencing?  SLB does not control any aspect of galleries in posts-- it only controls the lightbox.  Links (whether in galleries or otherwise) are displayed in the lightbox in the order that they appear on the page.

**Comment by corvandongen** [comment]
Thanks for your feedback, it appeared that my website-space at the webhosting was almost used completely by many stored backups. 
After deleting several older backups the gallery functions fine.
thanks again

**Comment by corvandongen** [comment]
after deleting older backups everything works fine again
case closed
