### ISSUE TITLE
Customizing metadata displayed in lightbox

### ISSUE THREAD

**Issue by ernst-weinzettl** [archetyped/simple-lightbox#935]
## Description of feature
I would like to set the informations displayed with the images. For example: At the moment I would like to define image title & image description to be displayed.

## This feature would be used to
To avoid double display as now appears. There are more than 8.000 images on my website (most in a not public area) that I would have to edit if I use your lightbox without the possibility to check and uncheck what to display.

## If you added this feature, I would:
a) Eat my hat
**b) Jump for joy**
c) Shave my cat
d) All of the above

My website is https://www.weinzettl.info but I have to deactivate the lightbox at the moment. Special problems would be at https://www.weinzettl.info/fotografie/geometrie-der-farben/ and similar pages. See my screenshot.

![image](https://user-images.githubusercontent.com/100420778/155721296-57b2ae63-4d04-4b31-9f02-2fcbafddfb62.png)

Kind regards
Ernst Weinzettl

**Comment by archetyped** [comment]
Hi, SLB displays title and description metadata from your site's media library in the lightbox.

> I would like to define image title & image description to be displayed.

This is what SLB's default lightbox themes display.  If this is not what you are experiencing, please provide more details on the issue you are experiencing as well as a link that exhibits the issue (the link you provided displays title and description for images in the lightbox).

**Comment by ernst-weinzettl** [comment]
Hi and thanks for prompt reply!

Sorry that my request was unclear. What I would like: The possibility to set what I want to see: title and/or description or none. This I meant with "define".

And finf would be to an option for used font. This because the used font should fit to the rest of the homepage (for example equal with font od titles).

I hope this is clear now. Thank you for patience.

Kind regards
Ernst

**Comment by ernst-weinzettl** [comment]
Oh! Just controlled what you told me: In my case there are two lines with description, not title and description. How could this happen?

![20140921-1216-EW21500-01](https://user-images.githubusercontent.com/100420778/155837076-7fd18758-0a86-4660-b85a-dd955be18ceb.jpg)

![20140921-1216-EW21500-02](https://user-images.githubusercontent.com/100420778/155837075-47fa049b-85a4-43a2-b00d-c3031786664b.jpg)

Website is www.weinzettl.info. The screenshots are from menu "Bilder", item "Landschaften", click on the first image to see the lightbox. I'll keep Simple Lightbox activated till you could check it.

Tell me, if you need more details and which you need.

Kind regards
Ernst

**Comment by archetyped** [comment]
Thank you for the additional details.  Lightbox characteristics such as the metadata displayed (title, description, etc.) and font are handled by the lightbox theme.  See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for full details on creating a custom theme.

---

The default themes display a caption that uses different metadata values depending on their availability.  In the example you provided, the lightbox is displaying the image's Beschriftung (Caption), which has a higher precedence than the Titel (Title) field.

See [SLB's documentation on title precedence](https://github.com/archetyped/simple-lightbox/wiki/Metadata#title-precedence) for more details.
