### ISSUE TITLE
Does your plugin work with text or only images?

### ISSUE THREAD

**Issue by flybetty** [archetyped/simple-lightbox#937]
Does your plugin work with text or only images?

I need a light box for text. I am open to paying if I need to!

**Comment by archetyped** [comment]
Hi, SLB works with any valid link, regardless of what the link wraps around (text, image, etc.).

By default, the SLB displays images in the lightbox, but additional content types are supported via extensions.  See [SLB's Home Page](https://archetyped.com/tools/simple-lightbox/) for more details.
