### ISSUE TITLE
Files missing ?

### ISSUE THREAD

**Issue by Aquaa22** [archetyped/simple-lightbox#938]
## Description of Problem

Hi, sorry cause I'm a bit noob and talking bad english.

I hope you'll undestrand my issue.

Simple-lightbox works fine, but my web host tells me **files are missing** : 
/wp-content/plugins/simple-lightbox/Gruntfile.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/jshint.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/phplint.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/sass.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/uglify.js : File is missing
/wp-content/plugins/simple-lightbox/grunt/watch.js : File is missing
/wp-content/plugins/simple-lightbox/package-lock.json : File is missing

I got an alert from their virus / malware scan. I updates Simple Lightbox but still those files are missing.

Do I have to dowload those files ? Or is it OK without them ?

Thank you very much for your reply. 

## Details

* URL of Page exhibiting problem: 
ex : https://www.clairejourner.com/8-octobre-2016/

* Other plugins installed: 
Advanced Custom Fields
Contact Form 7
Yoast SEO

**Comment by archetyped** [comment]
Hi, I'm not sure why your getting that message from your web host, as the files you listed are not included in official SLB releases.

Those files are used in development versions of SLB only.
