### ISSUE TITLE
Lag when using multiple lightbox plugins on mobile

### ISSUE THREAD

**Issue by juliencordier369** [archetyped/simple-lightbox#940]
Hello,
Simple lightbox works fine on desktop devices, but lags on mobile devices.
Could you tell me a way to solve the problem please
best regards,
Julien

**Comment by juliencordier369** [comment]
here is a sample page
https://www.juliencordier.fr/illustration/affiches/

**Comment by juliencordier369** [comment]
Hello, 
I found the solution to the slideshow lag issue: I disabled the Responsive Lightbox and Visual Portfolio plugins which were visibly conflicting with simple lightbox.

I'm looking for a way to swipe images with simple light box on mobile devices.

greetings,
Julian

**Comment by archetyped** [comment]
Yes, running multiple lightboxes simultaneously is not recommended as they can cause conflicts and unexpected behavior.

Features are prioritized based on demand. You can [vote for touch gesture support here](https://github.com/archetyped/simple-lightbox/issues/302).
