### ISSUE TITLE
Simple Lightbox Wordpress plugin by "Archetyped" with Envira Gallery

### ISSUE THREAD

**Issue by Nour238** [archetyped/simple-lightbox#941]
Simple Lightbox Wordpress plugin by "Archetyped"

Hello, I am using Simple lightbox plugin, it was showing the image caption as I need, after I downloaded a plugin called "Envira Gallery" the caption are not showing anymore, it just showing the image title, could you help me with that. 

Envira Gallery plugin has lightbox option but I need the lightbox on because it can be customized as I need

## Details

* URL of Page exhibiting problem:

 https://sy-revo-archive.com/أطفال-سوريا/

* before I use Envira Gallery:
![before](https://user-images.githubusercontent.com/62910482/160275646-583e1ca7-8ee3-422d-bec6-64d26672f2a2.jpg)
* after I used Envira Gallery:
![after](https://user-images.githubusercontent.com/62910482/160275654-2803f2f6-85a5-481b-9b12-72e9c18a1fe9.jpg)

**Comment by archetyped** [comment]
Can you please clarify, are both screenshots of an image being displayed in the lightbox?  (only the 2nd image appears to be SLB's lightbox)

If not, please provide more details on your issue so that it can be fully evaluated.

Thanks.

**Comment by Nour238** [comment]
Hello, thank you very much for your respond, I really appreciate it.

I actually moved to another plugin and now my problem is fixed with new plugin.

Thanks & Regards
