### ISSUE TITLE
Default WP image viewer is loading on top of lightbox page

### ISSUE THREAD

**Issue by dsl25** [archetyped/simple-lightbox#943]
## Description of Problem

When using WP galleries linking to Media Files, and when clicking on an image, WP opens the original image file in a new page and Lightbox only loads over the Gallery's page only when closing the page with the original image.

## Details

URL:---
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): any
* Version of SLB Installed: latest
* Other plugins installed:

**Comment by dsl25** [comment]
UPDATE;

After testing by disabling several plugins, it appears there is a conflict with WP Fastest Cache.
When disabling it, Lightbox works fine again!
Very strange because I'm running the same installation (with both plugins) on another site, on same server, where this issue is not happening...

**Comment by dsl25** [comment]
SOLVED!
The culprit is this plugin that was installed by mistake because RanMath has the same setting enabled:
https://wordpress.org/plugins/open-external-links-in-a-new-window/

**Comment by VanWebDev** [comment]
Hmm I have the same issue, and don't have that plugin. I also disabled WP Fastest Cache and it hasn't been fixed. It's working perfectly on the development site with all the same plugins and settings, but randomly started this behaviour on the production site.

**Comment by archetyped** [comment]
@dsl25 glad to hear you found the plugin causing the issue.

@VanWebDev please [create a new ticket](https://github.com/archetyped/simple-lightbox/issues/new/choose) so that your specific issue can be fully evaluated.
