### ISSUE TITLE
Simple Lightbox Captions

### ISSUE THREAD

**Issue by mjsdiaz** [archetyped/simple-lightbox#946]
## Description of Problem
Image Captions used to appear on the images in the lightbox.
But I'm not seeing them now.
I'm also not sure when the captions stopped appearing.

Thank you.

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: https://dtcox.com/dave-cox-in-costa-rica-tirimbina-rainforest-organization-lodge-along-sarapiqui-river-apr-8-2022/

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
- Chrome Version 100.0.4896.75 (Official Build) (x86_64)
- Firefox 99.0 (64-bit)

* Version of SLB Installed: Version 2.8.1
* Other plugins installed: 

### wp-mu-plugins (1) ###

System Plugin: author: (undefined), version: 4.22.2

### wp-plugins-active (19) ###

Akismet Anti-Spam: version: 4.2.2, author: Automattic, Auto-updates disabled
All-in-One WP Migration: version: 7.57, author: ServMask, Auto-updates disabled
All-in-One WP Migration S3 Extension: version: 3.71, author: ServMask, Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Classic Widgets: version: 0.3, author: WordPress Contributors, Auto-updates disabled
Contact Form 7: version: 5.5.6, author: Takayuki Miyoshi, Auto-updates disabled
Descriptions as Captions in Galleries: version: 9.0.0, author: Milan Dinić, Auto-updates disabled
Disable Comments: version: 2.3.4, author: WPDeveloper, Auto-updates disabled
Exclude Pages from Navigation: version: 1.92, author: Simon Wheatley, Auto-updates disabled
Google Doc Embedder: version: 2.6.4, author: Kevin Davis, Auto-updates disabled
Growmap Anti Spambot Plugin: version: 1.5.6, author: Andy Bailey, Auto-updates disabled
Login LockDown: version: v1.8.1, author: Michael VanDeMar, Auto-updates disabled
Really Simple CAPTCHA: version: 2.1, author: Takayuki Miyoshi, Auto-updates disabled
Simple Lightbox: version: 2.8.1, author: Archetyped, Auto-updates disabled
Simple Page Ordering: version: 2.3.4, author: Jake Goldman, 10up, Auto-updates disabled
TW Recent Posts Widget: version: 1.0.5, author: Igor Vučković, Auto-updates disabled
Welcome to WordPress: version: 1.0, author: Starfield Technologies, Auto-updates disabled
WP Help: version: 1.7.1, author: Mark Jaquith, Auto-updates disabled
Yoast SEO: version: 18.5.1, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (9) ###

Comprehensive Google Map Plugin: version: 9.1.3, author: Alex Zagniotov, Auto-updates disabled
Go Daddy Quick Setup: version: 1.06, author: GoDaddy.com, LLC, Auto-updates disabled
Gravity Forms: version: 2.4.24, author: Gravity Forms, Auto-updates disabled
ShareThis Dashboard for Google Analytics: version: 2.5.4, author: ShareThis, Auto-updates disabled
Sidekick: version: 2.6.8, author: Sidekick.pro, Auto-updates disabled
Sucuri Security - Auditing, Malware Scanner and Hardening: version: 1.8.30, author: Sucuri Inc., Auto-updates disabled
Universal Post Manager: version: 1.5.0, author: gVectors Team, Auto-updates disabled
WP101 Video Tutorials: version: 0.3, author: WP101Plugin.com, Auto-updates disabled
WP Publication Archive: version: 3.0.1, author: Eric Mann, Auto-updates disabled

**Comment by archetyped** [comment]
Hi, it appears that all images are being served from an external CDN (`https://secureservercdn.net`).  Depending on how the CDN plugin handles offloading media to the CDN, WordPress may be prevented from connecting the CDN-based image URLs with your site's media library metadata (title, caption, description, etc.).

To confirm this, temporarily disabling the CDN functionality is recommended (usually by deactivating a WordPress plugin, but sometimes also via a setting in your web host's control panel).

Once the CDN is confirmed as the cause of the issue, reporting the issue to the CDN provider to request that the CDN functionality does not break the connection between the media and your site's media library is recommended.

If you are still experiencing an issue, please provide an updated link with the CDN functionality disabled, and I would be glad to reopen this ticket and take another look.

**Comment by mjsdiaz** [comment]
Thank you so very much for pointing out the CDN.

The CDN was Managed GoDaddy (client's choice, not mine)
I did get the CDN turned off though, so all is well.

I really appreciate your help with this!

Marcy Díaz
*Amethyst Website Design*
Website: amethystwebsitedesign.com
Email: ***@***.***
Phone: 602.759.0501

**Comment by archetyped** [comment]
Glad to hear the issue was resolved :)
