### ISSUE TITLE
Question about Reset

### ISSUE THREAD

**Issue by AnneEllis11** [archetyped/simple-lightbox#948]
##  
Question about Reset option

## Details

Hello. Just a question - what does the "reset" option do on the plugin page?

Thanks!
![Screenshot 2022-05-11 090927](https://user-images.githubusercontent.com/105366688/167857651-76f0e64c-27bf-4b45-b607-422f0428e39a.jpg)

**Comment by archetyped** [comment]
"Reset" resets the plugin to its default settings.
