### ISSUE TITLE
SimpleLightbox not working on new server

### ISSUE THREAD

**Issue by tdlewis77** [archetyped/simple-lightbox#952]
## Description of Problem

I am the process of migrating several websites to a new server. Simple Lightbox works on the old server, but not on the new one. The page content and the SLB configuration are identical on the two sites. SLB version is 2.8.1. I have reviewed the requirements for SLB and written a script to output the relevant information to wit:

Having checked everything on the Requirements page I'm not sure what else to look for. Note: I have root access to the new server so I am the "host support staff".

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 2.8.1
* Other plugins installed: 
* WordPress version: 6.0
* PHP version: 7.4.30
* jQuery version: 3.6.0
* MySQL version: 8.0.29-0ubuntu0.20.04.3
* cURL: version 7.68.0
* cURL: localhost connection successful (1453 byte(s) returned)

**Comment by archetyped** [comment]
Hi, the support ticket template has been applied to your original post.  Please update the post to include the details necessary to fully evaluate your issue.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
