### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by bnovak99** [archetyped/simple-lightbox#956]
## Description of Problem
I am no longer getting a lightbox when adding images and linking to the media file. I have not added new plugins. I've tried disabling other plugins. This started after update the WP Core to 6.01
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details
https://nenehbiffinger.com/land-for-duplex-redevelopment-in-wheat-ridge/

**Comment by bnovak99** [comment]
I figured out the problem. The plugin does not work with webp image files.

**Comment by archetyped** [comment]
Hi, yes webp support is planned for a future update.
