### ISSUE TITLE
SLB causing error with wp-cli

### ISSUE THREAD

**Issue by ktuli** [archetyped/simple-lightbox#957]
## Description of Problem

When trying to use the wp-cli utility to manage my Wordpress instance, if I have SLB activated, it causes wp-clii to throw an error and does not work.  The error is:

PHP Fatal error:  Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in [....]/wp-content/plugins/simple-lightbox/includes/class.utilities.php:1319

Looking at the code, I do see a line at 1301 that makes the following call:
  $dir = @opendir($this->get_path_base());
But the opendir function returns false on failure.  I am not sure why the routine is failing to get the base path in my instance.  So either there is a bug in the code or something is broken when my installation - though it appears to be working properly.  If I comment the closedir call on line 1319, wp-cli works again and the plugin appears to work ok on my website.

Any ideas?

## Details

* URL of Page exhibiting problem: No URL - this is related to the wp-cli utility
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): wp-cli
* Version of SLB Installed: 2.8.1
* Other plugins installed: 
+------------------------------+--------+--------+---------+
| name                         | status | update | version |
+------------------------------+--------+--------+---------+
| advanced-random-posts-widget | active | none   | 2.2.0   |
| akismet                      | active | none   | 5.0     |
| exif-caption                 | active | none   | 3.06    |
| random_quote                 | active | none   | 0.3     |
| simple-lightbox              | active | none   | 2.8.1   |
| editorial-calendar           | active | none   | 3.7.12  |
| twitter-auto-publish         | active | none   | 1.4.2   |
+------------------------------+--------+--------+---------+

**Comment by archetyped** [comment]
Hi, what version of PHP are you using?

**Comment by ktuli** [comment]
PHP 8.1.8 (cli) (built: Jul 12 2022 06:22:24) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies

**Comment by archetyped** [comment]
Thanks.  It sounds like it's probably due to the way handling of error control operators changed in PHP 8+.

The good news is that this code has changed completely in the upcoming update, so this issue should be resolved upon release.  You can test out [SLB's `develop` branch](https://github.com/archetyped/simple-lightbox/tree/develop) if you're curious, but keep in mind that it may be less stable than the official release.
