### ISSUE TITLE
[Request]: Lightbox for Featured Image

### ISSUE THREAD

**Issue by stephentalla** [archetyped/simple-lightbox#959]
## Description of feature

If it is fine if the Featured Image every post could be zoomed out to a lightbox like an ordinary image on a post.

## This feature would be used to

Featured Images could be fine art that needed to be zoomed out and appreciated.

## If you added this feature, I would:

b) Jump for joy

**Comment by archetyped** [comment]
Duplicate of #950 

Please remember to search before creating new tickets.

Thanks.
