### ISSUE TITLE
HTML question

### ISSUE THREAD

**Issue by atomikdog** [archetyped/simple-lightbox#960]
I'm using WP All Import to maintain 3000 separate posts. The template is HTML-based. I've found that the Simple Lightbox plugin works if I set up my template html like so:

`<a href="https://sitename.com/wp-content/uploads/{imagefilename[1]}" data-slb-active="1" data-slb-internal="0" data-slb-group="36"><img src="https://sitename.com/wp-content/uploads/{imagefilename[1]}" alt="" /></a>`

I know I'm missing at least one bit of code, though. The not-unique asset number (?)...

`data-slb-asset="842492188"`

1. Can I get away with not including it?
2. Am I missing anything else important?

**Comment by archetyped** [comment]
Hi, SLB automatically displays valid links in the lightbox without any manual coding.  The `data-slb-...` attributes you reference are only used internally and may change at any time, so manually adding them is not recommended.

**Comment by atomikdog** [comment]
So do you have a recommendation for a purely html-based wordpress site? I may not be describing the scenario accurately here.

**Comment by archetyped** [comment]
Yes, more details would be helpful.  For example:

* Please provide a link to a page that does not include the manually-set `data-slb-...` attributes that exhibits an issue with SLB.
* What do you mean by "purely html-based wordpress site"?  Are you saying a WP theme is not being used on the site?
* Any other details that may be helpful in fully evaluating your issue.

Thanks.

**Comment by archetyped** [comment]
Hmmm, did you test to see if SLB worked before adding the hard-coded `data-slb` attributes to the import template?

Based on the information you provided, there shouldn't be anything preventing SLB from working normally on your imported posts.  SLB does not depend on any particular post editor-- as long as there are valid image links in the post content, they will be automatically displayed in a lightbox when clicked.  It does not matter how the link is added, whether directly added in HTML or via a WYSIWYG editor (which generates an HTML link).

As previously-noted, removing the hard-coded `data-slb` attributes is recommended, as that can lead to unexpected behavior (example: `data-slb-group` controls slideshow grouping, so hard-coding that attribute conflicts with the refined slideshow grouping controls in SLB's options).

If you are experiencing an issue after removing the hard-coded attributes from the import template, please provide a link that exhibits the issue, and I would be glad to reopen this ticket and take another look.

**Comment by atomikdog** [comment]
Gotcha. When I initially installed SL, it didn't immediately work on the existing images. That's when I added the hard-coded attributes. But I just deleted the attributes from one post and the lightbox still worked. So maybe this was a non-issue all along. Thank you.
