### ISSUE TITLE
Simple Lightbox doesn't work anymore with linked images

### ISSUE THREAD

**Issue by Prazzone** [archetyped/simple-lightbox#962]
## Description of Problem

Hi

Somehow Wordpress changed the way to embedd images in posts.
SLB works fine in older posts where images are embedded like:

`<a href="https://paparazzo.one/wp-content/uploads/2022/02/Luzern-ante-001.jpg"><img class="aligncenter size-full wp-image-25879" src="https://paparazzo.one/wp-content/uploads/2022/02/Luzern-ante-001.jpg" alt="" width="1600" height="1042" /></a>
`

In newer posts images are embedded like:

`<img class="alignnone size-full wp-image-27536" src="https://paparazzo.one/wp-content/uploads/2022/08/IMG_20220806_090240.jpg" alt="" width="1600" height="1200" />
`
SLB obviously doesn't recognize these image links.

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: 
paparazzo.one
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
any
* Version of SLB Installed:
newest 2.8.1 
* Other plugins installed: 
many, but it worked before see above

Thx for fixing that or extend your plugin.

Prazzone

(didn't like i had to create a for me totally useless github account to get support!)

**Comment by archetyped** [comment]
Hi, your second example is the answer: an image is inserted, but **there are no links**.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.
