### ISSUE TITLE
Display description in lightbox

### ISSUE THREAD

**Issue by TerraDiLavero** [archetyped/simple-lightbox#963]
## Description of Problem

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, please update your original post to include the details of the issue you are experiencing so that it can be fully evaluated.

This ticket will be closed in 24 hours due to inactivity.

**Comment by TerraDiLavero** [comment]
The description field  entry (where it exists) appears in some cases in the lightbox but not in others. In the first photo the description does not appear but appear but it does in the 11th photo (Giacinto De Marco) The problem seems to occur when new media items are added.
The Browser is Edge latest version and Lightbox latest version
URL of page - https://picinisco.uk/?page_id=11693
Plugins used ;-
Autoptimiise
Block Visibility
Enable media replace
Folders
Insert Pages
Kadence Blocks
Litespeed Cache
Password Procted
Post Type Switcher
Qubely Advanced gutenberg blocks
Shiftnav
Simple Lightbox
Sorry for the late reply, I am new to GitHub #

**Comment by archetyped** [comment]
Hi, the link you provided appears to require a password to view.  Please provide a link to a publicly-accessible page that exhibits the issue you are experiencing, and I would be glad to take a look.

Note: As this is public forum, posting passwords is not recommended.

**Comment by archetyped** [comment]
Hi, the link you provided appears to require a password to view.  Please provide a link to a publicly-accessible page that exhibits the issue you are experiencing, and I would be glad to take a look.

Note: As this is public forum, posting passwords is not recommended.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
