### ISSUE TITLE
Upgrading to 2.9.0 breaks all functionality

### ISSUE THREAD

**Issue by kaiyoma** [archetyped/simple-lightbox#964]
## Description of Problem

I've used Simple Lightbox for years without any issues, but 2.9.0 seems problematic. After upgrading, the lightbox functionality stopped working entirely. Clicking on images in my blog posts would navigate to the full image instead of displaying the JS modal. I was also seeing some subtle artifacts (a red horizontal line) when hovering over images.

I tried clearing the browser cache and that didn't help. I used a rollback plugin to roll back to version 2.8.1 and now everything is working correctly again, so 2.9.0 is definitely the problem. I'm happy to help you debug this, if you let me know what you need.

## Details

* URL of Page exhibiting problem: https://www.kylegetz.me/2021/10/10/fleet-week-air-show/ (not visible currently as the plugin has been rolled back)
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Edge, Firefox
* Version of SLB Installed: 2.9.0
* WordPress Version: 6.0.1
* PHP Version: 7.4.3
* Other plugins installed: Classic Editor, Favicon by RealFaviconGenerator, Jetpack, Open External Links in a New Window, WP Rollback

**Comment by archetyped** [comment]
Hi, the standard [Support Ticket](https://github.com/archetyped/simple-lightbox/issues/new?assignees=&labels=support&template=0_support-ticket.md&title=) template contains all the fields necessary to evaluate issues, so I've updated your post with that template.  Please edit your original post and fill in the fields, and I would be glad to take a look.

Thanks.

**Comment by archetyped** [comment]
Thank you for the details, however I need to be able to see the actual issue in order to evaluate it.  SLB 2.9.0 has been tested on several sites without issue prior to release, so the issue may be specific to your site.

Please provide a link to a page that exhibits the issue you are experiencing (and all caching plugins disabled), and I would be glad to take a look.

Thanks.

**Comment by kaiyoma** [comment]
@archetyped I just upgraded the plugin again, so you can see it live on the URL above.

**Comment by archetyped** [comment]
Thanks.  Can you temporarily disable Jetpack to see if that resolves the issue?

**Comment by kaiyoma** [comment]
Disabled Jetpack and your plugin is working again (yay! ... kind of). I've left the plugins in that state so you can look for yourself.

**Comment by archetyped** [comment]
Thanks.  Looks like this is due to Jetpack's "Image Accelerator" feature, which modifies image URLs to serve them from Jetpack's own servers.

This will be looked into, but in the meantime, you can disable Jetpack's "Image Accelerator" feature to keep SLB working.

**Comment by kaiyoma** [comment]
@archetyped I disabled the image accelerator, and I'm still seeing the same problem. I don't think it's that setting: I think it's actually the lazy loading. Toggling that setting and refreshing the page changes the behavior.

**Comment by paroj** [comment]
>  I think it's actually the lazy loading.

I can confirm that

**Comment by OldGrumpy-de** [comment]
I observed the same issues as @kaiyoma but I don't run any caching plugin. Disabling the built-in lazy load of WordPress did not help either. By disabling plugins systematically I found out that Nextgen Gallery (https://wordpress.org/plugins/nextgen-gallery/) seems to clash with Simple Lightbox 2.9.0. Simple Lightbox 2.9.0 works properly when Nextgen Gallery is disabled, so maybe there is some overlapping with internal shortcodes? Rolling back to Simple Lightbox 2.8.1 resolves the issue too. Nextgen Gallery is at the most recent version (3.28) for all tests. Did shortcode handling change between 2.8.1 and 2.9.0? Were new shortcodes introduced? I'm quite busy with other projects at the moment (including water in the basement after recent heavy rain, sigh...), but I'll gladly test or help debug, just let me know.

**Comment by archetyped** [comment]
> I can see the shortcode [slb_group][/slb_group] around the gallery images, so it apparently doesn't get processed properly. Might be a valuable hint.

@OldGrumpy-de Can you please clarify what "gallery images" you're referring to?  Standard WordPress galleries, Nextgen-created galleries, a different plugin?

Thanks.

**Comment by OldGrumpy-de** [comment]
> > I can see the shortcode [slb_group][/slb_group] around the gallery images, so it apparently doesn't get processed properly. Might be a valuable hint.
> 
> @OldGrumpy-de Can you please clarify what "gallery images" you're referring to? Standard WordPress galleries, Nextgen-created galleries, a different plugin?
> 
Oh, my bad. Sorry, it's a standard WordPress gallery, using the [gallery][/gallery] shortcode. I'll also add that to my previous post.

**Comment by archetyped** [comment]
[v2.9.1](https://github.com/archetyped/simple-lightbox/releases/tag/2.9.1) contains the fix for this issue.  Please clear WordPress and browser cache after updating plugin to ensure your site is loading the updated code.

@OldGrumpy-de the issues you reported (NextGen gallery, shortcodes displaying) could not be reproduced. If you are still experiencing this issue after updating to 2.9.1, please create a new ticket for each issue so that they can be fully evaluated.

Thanks all.

**Comment by kaiyoma** [comment]
Just upgraded and the problem is fixed for me. Thanks @archetyped

**Comment by OldGrumpy-de** [comment]
@archetyped Just did some testing and the issue is fixed with the update to 2.9.1 for me as well. Thank you very much!
