### ISSUE TITLE
the plugin does not support the webp image format?

### ISSUE THREAD

**Issue by FoxitHero** [archetyped/simple-lightbox#966]
## Description of Problem

Why the plugin does not work If I only change the jpg/png image to webp? Can someone help with this? Thank you.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, the standard [Support Ticket](https://github.com/archetyped/simple-lightbox/issues/new?assignees=&labels=support&template=0_support-ticket.md&title=) template contains all the fields necessary to evaluate issues, so I've updated your post to restore that template.  Please edit your original post to provide the necessary details, and I would be glad to take a look.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
