### ISSUE TITLE
Simple Lightbox slideshow is repeating slides 

### ISSUE THREAD

**Issue by jennbryant** [archetyped/simple-lightbox#967]
## Description of Problem

When you click on View Slideshow, it opens the first image. Clicking the arrow to the right brings the same image. Clicking it again brings the next image. Clicking it again brings the first image, then the second, then the third, repeat ad nauseum. 
We have deactivated all plugins except for Simple Lightbox and the problem persists. 
Changing themes simply deactivates the lightbox no matter what theme we choose. 

## Details

* URL of Page exhibiting problem: https://research.uga.edu/news/costa-rica-trip-is-a-summer-immersion-into-onehealth/ (This is just one of the many, as all pages using this gallery are exhibiting the same behavior) 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Firefox, Safari
* Version of SLB Installed: 2.9.0
* Other plugins installed: 

404page
Admin Menu Tree
Advanced Custom Fields PRO
Advanced Custom Fields: Font Awesome
Advanced Editor Tools (previously TinyMCE Advanced)
All-in-One WP Migration
Better Search Replace
Classic Editor
Classic Widgets
Code Snippets
Cool Timeline Pro
Custom Menu
Custom Post Type UI
Duplicate Page
Enhanced Text Widget
Font Awesome
Fonts Plugin \| Google Fonts Typography
Formidable Forms
Formidable Forms Pro
Formidable Locations
Formidable Registration
Icegram - Popups, Optins, CTAs & lot more...
IconPress Lite
Intuitive Custom Post Order
LayerSlider
Maintenance Mode
Max Mega Menu
Network Plugin Auditor
NS Cloner - Site Copier
NS Cloner Pro
Page Links To
Plugin Activation Status
PublishPress Future
Real3D Flipbook
reBusted!
Related Posts for WordPress Premium
Sassy Social Share
Shortcodes Ultimate
Simple Lightbox
Site Kit by Google
Smash Balloon Instagram Feed
Smush
SSL Insecure Content Fixer
SVG Icons for Visual Compose
TablePress
The Grid
Ultimate Addons for WPBakery Page Builder
Ultimate Posts Widget
Unconfirmed
Video Thumbnails
Visualizer: Tables and Charts for WordPress
What The File
Widget Shortcode
WordPress Importer
WordPress Popular Posts
WP Extended Search
WP Gallery Custom Links
WP Theme Update
WPBakery Page Builder
WPCode - Insert Headers, Footers, and Code Snippets
WPFront Scroll Top
Yoast SEO Premium
Yoast Test Helper

**Comment by archetyped** [comment]
Hi, I am not seeing any duplicate images in the slideshow at the link you provided.

Confirming the following is recommended:

1. Latest version of SLB is installed ([releases](https://github.com/archetyped/simple-lightbox/releases/)).
2. Site cache has been cleared.
3. Browser cache has been cleared.

If you are still experiencing this issue, please provide an updated link that exhibits the issue you are experiencing, and I would be glad to reopen this ticket and take another look.

Thanks.
