### ISSUE TITLE
Update failed: Unable to create folder.

### ISSUE THREAD

**Issue by titanicboyke** [archetyped/simple-lightbox#968]
## Description of Problem

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Closed as empty ticket.

If you are experiencing an issue with SLB, please update your original post to include the requested details and I would be glad to reopen this ticket and take another look.
