### ISSUE TITLE
[Request]: Social Sharing

### ISSUE THREAD

**Issue by herrseiler** [archetyped/simple-lightbox#978]
## Description of feature
A social sharing feature would be helpful.

## This feature would be used to
A user watching a WP gallery within the lighbox can share the actual shown image to the following social media networks (FB, Instagram, Linkedin, Mail, Whatsapp, …)

## If you added this feature, I would:
Use this lightbox on every customer project and spread the name!

**Comment by archetyped** [comment]
Duplicate of #206.

Please add your feedback to the existing post to keep all discussion on this functionality in one place.

Thanks.
