### ISSUE TITLE
Current gallery images not opened by Simple Lightbox 

### ISSUE THREAD

**Issue by bsllcp** [archetyped/simple-lightbox#979]
## Description of Problem

SLB will not open the images on a new gallery which I have created.  It had opened images on all 160 previous galleries which average about 70-80 images each.

## Details

The galleries are on a subscription website.  I could provide you with an account if you need to see the issue for yourself.

It is not browser specific.  Behavior is consistent with different browsers.

Current version of SLB (2.9.3) running on Wordpress 6.1.1.

SLB was working fine for several months.  Primarily picked SLB because it supports the use of an Attachment Page.

I have a custom theme running on the site.  The galleries are 8 to a page and I currently have 20 pages.  The problem of SLB not opening the images on a page began on the 161 gallery.  I tried rolling everything back on the site to a version that worked several weeks ago.  The problem was the same once I created the 161 gallery.  It seems like the various versions do not effect anything.  It seems more like the volume of pages, galleries or photos is creating the problem.   Is that a possibility?

**Comment by archetyped** [comment]
Hi, there is no limit within SLB based on the number of pages or galleries on a site.

Please send an email to support@archetyped.com containing the following details:

* Test account login
* Link to page where SLB is working as expected.
* Link to page where SLB is not working as expected.

**Comment by archetyped** [comment]
Closed ticket to keep all discussion in one place.  Please provide the previously-requested details via email.
