### ISSUE TITLE
Feedback: How do you use Simple-lighbox

### ISSUE THREAD

**Issue by vicaz1** [archetyped/simple-lightbox#985]
You have no documentation on how to use your plugin. I install it and how do I use it. Your website doesn't have ANY information, no tutorial, no video, no written instructions. The settings show it's enabled, but how do I add a lightbox to a WP webpage??????

**Comment by archetyped** [comment]
Hi, I'm not sure where you've looked, but [SLB's page in WordPress' Plugin Directory](https://wordpress.org/plugins/simple-lightbox/) has a **Usage** section with instructions on how to use SLB and links to additional resources.  I'll include those steps here as well for your reference:

### Usage

1. Insert links to images/image attachments into your posts/pages

**That’s it! The image will be displayed in a lightbox automatically.**

For more usage tips, go to [Simple Lightbox’s official page](http://archetyped.com/tools/simple-lightbox/)
See [Simple Lightbox’s documentation](https://github.com/archetyped/simple-lightbox/wiki) for in-depth information on using and customizing SLB.

---

There's really not much more required than that, but be sure to check out the **Resources** section on [SLB's home page](http://archetyped.com/tools/simple-lightbox/) for quick tutorials or the aforementioned documentation to go even deeper.

If you are still experiencing an issue, please provide more details on your specific issue, as well as a link that exhibits the issue you are experiencing, and I would be glad to reopen this ticket and take a look.
