### ISSUE TITLE
Simple Lightbox stoped working on edge browser

### ISSUE THREAD

**Issue by daliab** [archetyped/simple-lightbox#986]
## Description of Problem

Simple Lightbox stoped working on edge browser
## Details
it works on chrom and firefox
* URL of Page exhibiting problem:  daniel-zahavi.co.il/אמנות/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.):  edge
* Version of SLB Installed: 
* Other plugins installed: Advanced Custom Fields, List category posts, MailPoet, Mammoth .docx converter, Members,

**Comment by daliab** [comment]
It just beginning to work.... very strange....  I hope it will continue to work .....

**Comment by archetyped** [comment]
SLB is working at the URL provided when tested in Edge.  Different browsers handle caching differently, so clearing your site's cache and your browser's cache to avoid loading stale data is recommended if something is not working as expected.
