### ISSUE TITLE
Relative Paths to Non-Standard Port Not Working

### ISSUE THREAD

**Issue by OptrixAU** [archetyped/simple-lightbox#989]
## Description of Problem

My server is running on a non-standard port during development, and when using a relative path to an image the light-box doesn't work, as the port is not present in the final URL used when loading the image in the lightbox.

I can click the lightbox and it appears, but the image never finishes loading due to a 404 error (as its tried to load the image from the incorrect server port).

## Details

* URL of Page exhibiting problem: N/A
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All Tested Browsers (Firefox, Chrome)
* Version of SLB Installed: 2.9.3
* Other plugins installed: Yoast SEO

**Comment by OptrixAU** [comment]
Note that the port number is present in the configuration for Wordpress and all other wordpress relative links work fine.

**Comment by archetyped** [comment]
Please provide a link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by OptrixAU** [comment]
Unfortunately, I've switched to using a different plugin that doesn't have the issue. So I don't have an example link at the moment.

**Comment by archetyped** [comment]
No problem.  If you provide a link in the future, I would be glad to reopen this ticket and take a look.
