### ISSUE TITLE
Previous/Next buttons without play button

### ISSUE THREAD

**Issue by henry88g** [archetyped/simple-lightbox#990]
Just a question -  Is it possible to have the lightbox images have right and left arrows, but no 'play' triangle?
That is, a manual-only slideshow.
And, just a note - it would be a good option to have the 'X' outside the lightbox image - either above or below.  When displaying artwork, it would be cool if the control 'buttons' didn't overlay the artwork.

**Comment by archetyped** [comment]
The slideshow play/pause button is always displayed  in the default themes when grouping is enabled.

However, all visual aspects of the lightbox are fully customizable by themes (including the other UI preferences you noted).  See [SLB's Themes documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for more details on create a custom lightbox theme that fits your needs exactly.
