### ISSUE TITLE
Probleme avec le theme divi d'elegantheme

### ISSUE THREAD

**Issue by cabrio2b** [archetyped/simple-lightbox#991]
## Description

l'extention ne fonctionne pas du tout

## Details

* URL of Page exhibiting problem: https://inoxprestige.com/galerie-photos/garde-corps/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): chrome et firefox
* Version of SLB Installed: Version 2.9.3
* Other plugins installed: Divi Supreme Pro, Enhanced Media Library, Complianz | GDPR/CCPA Cookie Consent

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

If you are still experiencing an issue after adding links, please provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to reopen this ticket and take another look.
