### ISSUE TITLE
Nothing seems to happen with this plugin?

### ISSUE THREAD

**Issue by freekvh** [archetyped/simple-lightbox#992]
## Description of Problem

I have version 6.1.1 of Wordpress with the default theme (twenty twenty-three).

I activate this plugin and add an image (via upload). Nothing seems different than without this plugin.

I distill the url to the image from the html (so now I paste https://domain.com/wp-content/uploads/2023/01/image.png [fake url] into a new paragraph). I can now click the url and the image opens full screen, no buttons, I can just only back to the previous page with the browser back button.

So, what am I missing? Maybe I don't understand what this plugin does. I was hoping to provide a "click to zoom in" functionality for images that contain text that is too small to read for example.

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, image links should be displayed in a lightbox, so I've changed your post to a support ticket.

Please update your original post to include the details necessary to fully evaluate your issue and I would be glad to take a closer look.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB?  If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by freekvh** [comment]
Apologies for the in activity, I will include the requested details today. Thank you.

**Comment by freekvh** [comment]
Hi, I had a look, there is not much to show, I have the plugin enabled:

![Screenshot from 2023-02-15 20-08-40](https://user-images.githubusercontent.com/12241293/219128617-ee8b1359-1547-4a16-b5d8-d3b654b00414.png)

But when I upload an image, I simply see nothing different than without the plugin:

![Screenshot from 2023-02-15 20-06-00](https://user-images.githubusercontent.com/12241293/219128731-0c69c408-5ce7-4bef-a5c6-820953ed0bfc.png)

I don't really know what to expect? I was expecting that I could click images to make them bigger.

**Comment by archetyped** [comment]
Hi, this is the support forum for [Simple Lightbox](https://wordpress.org/plugins/simple-lightbox/).  Based on your screenshot, you are using a different plugin called "FooBox Image Lightbox".

Checking that plugin's plugin listing or home page for contact information is recommended to get further support from its developers.

Thanks.

**Comment by freekvh** [comment]
I apologize, I screenshotted the wrong plugin indeed, this is the correct one:

![image](https://user-images.githubusercontent.com/12241293/220383967-7ccae0bb-4d04-4a49-88ca-dbd677094ec6.png)

**Comment by archetyped** [comment]
Hi, the first thing to do is to deactivate any other lightbox plugins, as they can create conflicts since they all are designed to do a similar thing (display image in lightbox when a link is clicked).

After that, please update your original post to include the previously-requested details necessary to fully evaluate your issue (URL, plugins, etc.) and I would be glad to take a closer look.

Thanks.

**Comment by archetyped** [comment]
Hi, are you still experiencing an issue with SLB? If so, please provide the requested details and I would be glad to take a look.

This ticket will be closed in 24 hours due to inactivity.

**Comment by freekvh** [comment]
Hi, I'm still experiencing it indeed. But, feel free to close this issue, I'll try setting up a clean system, find out what is wrong. But I have (take?) little time to work on this, apologies. For now: Thank you for your kind and helpful attitude.

**Comment by archetyped** [comment]
No problem.  When you are ready, just post a link that exhibits the issue you are experiencing and the other details needed to evaluate your issue further (listed in the first post), and I would be glad to reopen this ticket and take a look.

**Comment by freekvh** [comment]
Hi, I read that it could be that it does not work because I had http basic auth blocking access, so I turned that off.

I use [this docker image](https://github.com/docker-library/wordpress/blob/7abee5418f61c0247efab5f736f1ecbf7486cb59/latest/php8.0/fpm/Dockerfile) for Wordpress. And I put Caddy in front.

Still nothing, this is the page with the visual: https://dcdc-tx.com/our-science/  are you able to see what is wrong?

Thanx!

**Comment by archetyped** [comment]
Hi, there do not appear to be any image links on the page you provided.  Without links, there is nothing for visitors to click on and launch the lightbox.

See [SLB's documentation on adding image links to posts](https://github.com/archetyped/simple-lightbox/wiki/Lightbox-not-working-on-New-Posts) for more details.

If you are still experiencing an issue after adding image links to the page, please provided an updated link to a page that exhibits the issue you are experiencing, as well as the previously-requested details (listed in the first post), and I would be glad to take another look.

Thanks.

**Comment by freekvh** [comment]
Yes, that was it! Apologies for not reading everything. It looks very nice, thanx!!!

**Comment by archetyped** [comment]
Glad to hear your issue was resolved 👍
