### ISSUE TITLE
Can you advise me on where to alter the code to center the caption on the lightbox pop up?

### ISSUE THREAD

**Issue by tplowe56** [archetyped/simple-lightbox#994]
Can you advise me on where to alter the code to center the caption on the lightbox pop up?

**Comment by archetyped** [comment]
Hi, the lightbox's appearance is fully controlled by the lightbox theme.  See [SLB's Themes Documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes) for details on creating a custom theme using simple HTML and CSS.

Once created, simply select the custom lightbox theme in SLB's options to use it.
