### ISSUE TITLE
Deactivate IPTC Data

### ISSUE THREAD

**Issue by stefangregor** [archetyped/simple-lightbox#995]
## Description of Problem
I would like to deactivate the IPTC data such as description/caption so that they are not visible in my Photogallery in the web. How can this be done?
(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details
The site is not online yet, I am creating it.
I use Safari (Mac OS Ventura 13.2.1
Version of Simple Lightbox is 2.9.3

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by archetyped** [comment]
HI, SLB uses caption/description fields from WordPress' media library.  It does not directly use an image's IPTC metadata.  

However, WordPress itself may use an image's metadata to populate the fields in the media library during upload.  I would recommend looking into WordPress' settings or other plugins if you don't want the metadata to be used at all.

If you only want to omit those elements in the lightbox, then you can use a custom lightbox theme ([documentation](https://github.com/archetyped/simple-lightbox/wiki/Themes)) to fully control the lightbox's appearance and behavior.

Note that the media library's fields (caption, description, etc.) will still be used by WordPress in other ways (link attributes, media library pages, etc.) if the fields are still populated during upload.

**Comment by stefangregor** [comment]
Thank you for your quick response. I will try your suggestions.
Stefan
