### ISSUE TITLE
The title does not appear under the photo

### ISSUE THREAD

**Issue by Vaness33** [archetyped/simple-lightbox#997]
Good morning,

I installed the simple-lightbox plugin on my site, it works very well, my photos open as they should.
However, I have a problem with the title of the photos, I can't make it appear under the photos. I checked the box in the settings to make it appear but it does not work. I only have the legend of the number of photos (1 out of 5 for example).
I can't figure out where the problem is, if you can help me.

Thanks in advance.
Vanessa

## Details

* URL of Page exhibiting problem: https://acteurs-du-fleuve.fr/quest-ce-que-le-fluvial
See below title in french "LE TRANSPORT FLUVIAL C'EST ÇA !"

* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of SLB Installed: i don't know
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, it appears that all images are being served from an external CDN, such as [Jetpack's "Site Accelerator"](https://jetpack.com/support/site-accelerator/). Depending on how the CDN plugin handles offloading media to the CDN, WordPress may be prevented from connecting the CDN-based image URLs with your site's media library metadata (title, caption, description, etc.).

To confirm this, temporarily disabling the CDN functionality is recommended (usually by deactivating a WordPress plugin, but sometimes also via a setting in your web host's control panel).

After disabling the CDN and clearing your site's cache, test to see if WordPress is now able to access the media library metadata (title, etc.) when opening the gallery links in the lightbox.

Once the CDN is confirmed as the cause of the issue, reporting the issue to the CDN provider to request that the CDN functionality does not break the connection between the media and your site's media library is recommended.  You can also [request an extension](https://github.com/archetyped/simple-lightbox-extensions/discussions/categories/extension-requests) to support your desired CDN.

If you are still experiencing an issue after the CDN has been disabled, please provide an updated link with the CDN functionality disabled, and I would be glad to reopen this ticket and take another look.
