### ISSUE TITLE
Intermittent functionality

### ISSUE THREAD

**Issue by NapaArtist** [archetyped/simple-lightbox#998]
## Description of Problem

There's something I don't quite understand with Simple Lightbox.  I get it working fine, and then when I return to my website after some time has passed, the lightbox is no longer active.  Poking around, refreshing, or logging in and just touching it seems to get it going again.  Does anyone understand what is happening?
Thanks, @NapaArtist

## Details

* URL of Page exhibiting problem: https://anomalyengineering.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 
* Other plugins installed:

**Comment by NapaArtist** [comment]
FYI- SLB currently working, [https://anomalyengineering.com](url)

**Comment by archetyped** [comment]
Hi, I've changed your post to a support ticket.  Please update your original post to include the requested details so that your issue can be fully evaluated.

Also, being able to view the site when SLB is not working would be ideal.  Please provide an updated link when that occurs (before you do any remediation) so that it can be tested.

Thanks.

**Comment by NapaArtist** [comment]
As you noted, this intermttent functionality is very difficult to track down.  Currently it is functioning on this configuation:
URL noted above.
Browser Safari was just updated to 16.3.1
SLB version is 2.9.3
Other plugins installed are Askimet Anti-Spam 5.0.2, Jetpack 11.8.4, Official StatCounter PlugIn 2.0.9, SiteGround Optimizer 7.3.1 UpdraftPlus 1/22/24, and Wordfence Security (Free Version) 7.9.0. 
MacOS 11.7.4
WordPress 6.1.1. running Business Child theme

**Comment by archetyped** [comment]
Thank you for the additional details.

SLB currently appears to be working normally at the URL provided, so please provide an updated link when SLB stops working for you, and I would be glad to take another look.

Please also ensure that the page is fully loaded when testing SLB's functionality, as that may affect the page's behavior.

**Comment by archetyped** [comment]
Closing this ticket as SLB still appears to be working properly at the link provided.

Please provide an updated link if you experience the same issue in the future, and I would be glad to reopen this ticket and take another look.

Thanks.
