### ISSUE TITLE
Pictures in single posts not showing

### ISSUE THREAD

**Issue by Adamdawg** [archetyped/simple-lightbox#999]
## Description of Problem

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)
The pictures that I've added to the post are not clickable and do not open up lightbox.
I've enabled everything under activation. Still, the issue persists.

## Details

* URL of Page exhibiting problem:  https://www.innovaengineering.avgroup.se/test-5-3-23/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome, Edge
* Version of SLB Installed:  6.1.1
* Other plugins installed: None

**Comment by archetyped** [comment]
Hi, the link you provided returns a "404" error.  Please provide an updated link to a page that exhibits the issue you are experiencing and I would be glad to take a closer look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with SLB, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
